DROP TABLE SPTYT.AUDI_REPO_GENE CASCADE CONSTRAINTS;

CREATE TABLE SPTYT.AUDI_REPO_GENE
(
  NU_ID_GEN_REP           NUMBER(10)            NOT NULL,
  NU_AUTO_GEN_HIST        NUMBER(10),
  AU_AUD_REP              VARCHAR2(4000)        NOT NULL,
  FE_FEC_REP              DATE                  NOT NULL,
  VA_VAL_TOT_FAC_REP      VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_AUD_REP          NUMBER(10)            NOT NULL,
  VA_VAL_TOT_GLO_REP      VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_FOR_GLO_REP      NUMBER(10)            NOT NULL,
  VA_VAL_RET_REP          VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_FOR_GLO_PAG_REP  NUMBER(10)            NOT NULL,
  VA_VAL_PAG_REP          VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_FOR_FOR_PAG_REP  NUMBER(10)            NOT NULL,
  VA_VAL_CON_REP          VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_FAC_CON_REP      NUMBER(10)            NOT NULL,
  VA_VAL_MED_NUM_REP      VARCHAR2(20 CHAR)     NOT NULL,
  VA_VAL_DEM_CTC_REP      VARCHAR2(20 CHAR)     NOT NULL,
  VAL_VAL_MED_TUT_REP     VARCHAR2(20 CHAR)     NOT NULL,
  AN_ANA_REP              VARCHAR2(1400 CHAR),
  VA_VAL_MED_CAN_TUT_REP  VARCHAR2(20 CHAR)     NOT NULL,
  NU_NUM_FOR_EJE_REP      NUMBER(10)            NOT NULL,
  NU_NUM_FOR_ARM_REP      NUMBER(10)            NOT NULL,
  NUM_NUM_FOR_FAC_REP     NUMBER(10)            NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;