CREATE OR REPLACE PROCEDURE H3i_AUDIT_CONS_ITMS_AUDITADOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIDOC IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)

AS
BEGIN
	OPEN CV_1 FOR
		SELECT DISTINCT
			ATI.CD_CODI_ATDI,
			ATI.CD_CODI_ATD_ATDI,
			ATI.DE_DESC_ATDI,
			AGI.BT_ESTADO_AGSI,
			AGI.COD_CAUSA_TIPO_AGSI,
			ATI.ES_GLOSADO_COMPLETO
		FROM AUDITAR_REGISTRO_GLOSADO ARG
			INNER JOIN AUDITAR_GLOSADO_SEGUIM_ITEMS AGI 
				ON ARG.AUTO_REG_GLOSA = AGI.AUTO_REG_GLOSA_AGSI
			INNER JOIN AUDITAR_TIPO_DOCU_ITEM ATI 
				ON AGI.CD_CODI_ATDI_AGSI = ATI.CD_CODI_ATDI
		WHERE ARG.COD_AUDI_DOCUM_ARG = V_CODIDOC;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);			
END;