CREATE OR REPLACE PROCEDURE H3i_SP_AUDI_VAL_NUMRADICADO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_RADICA_ALSD IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT NU_NUME_RADICA_ALSD 
		FROM AUDITAR_LOG_SINCRO_DOCU 
		WHERE  NU_NUME_RADICA_ALSD = v_NU_NUME_RADICA_ALSD ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;