CREATE OR REPLACE PROCEDURE H3i_SP_AUDI_CONS_TIPDOCXCONSEC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_DOCUMENTO_TIPO IN VARCHAR2,
	V_DOCUMENTO_CONSECUTIVO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)

AS
	V_EXISTE NUMBER;
BEGIN

	SELECT COUNT(*)
	INTO V_EXISTE
	FROM AUDITAR_DOCUMENTO 
	INNER JOIN AUDITAR_REGISTRO_GLOSADO 
	ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_ARG 
	WHERE DOCUMENTO_TIPO = V_DOCUMENTO_TIPO 
		AND DOCUMENTO_CONSECUTIVO = V_DOCUMENTO_CONSECUTIVO;

	IF(V_EXISTE >= 1) THEN

		BEGIN
			OPEN CV_1 FOR
				SELECT CD_ASIG_DOCU,
					COD_AUDI_DOCUM_AAD,
					IDEN_USUARIO_AAD,
					(	SELECT NO_NOMB_USUA 
						FROM USUARIOS 
						WHERE ID_IDEN_USUA = IDEN_USUARIO_AAD
							AND ROWNUM <= 1
					) NOM_AUDIT_ASIG,
					NVL(FE_FECHA_ARG, FECHA_ASIG_AAD) FE_FECHA_ARG,
					COD_AUDI_DOCUM,
					DOCUMENTO_TIPO,
					DOCUMENTO_CONSECUTIVO,
					ESTADO_ARG,
					NVL((	select MAX(NU_NUM_RESPUESTA) 
							FROM AUDITAR_RESPUESTA_DOCU_OBJET 
							WHERE CODIGO_DOC_OBJETADO = COD_AUDI_DOCUM),0) CANT_RESPUESTA,		
					REPLACE(DOCUMENTO_TIPO_CONSEC,'-','') ID_DOCUM_INTERFAZ,
					DOCUMENTO_TIPO_CONSEC IDENTIFICADOR_ADJUNTOS,
					ATD.NU_DATO_INTER_ATD,
					ATD.CD_CODI_ATD,
					ATD.NO_NOMB_ATD,
					AUTO_REG_GLOSA,
					COD_REG_GLO_PADRE,
					FUERZA_NOMBRE
		 		FROM (	SELECT COD_AUDI_DOCUM,
							DOCUMENTO_TIPO,
							DOCUMENTO_CONSECUTIVO,
							DOCUMENTO_TIPO_CONSEC,
							FUERZA_NOMBRE,
							BODEGA_CODIGO 
						FROM AUDITAR_DOCUMENTO 
					 	WHERE DOCUMENTO_TIPO = V_DOCUMENTO_TIPO
							AND DOCUMENTO_CONSECUTIVO = V_DOCUMENTO_CONSECUTIVO) AD 
				INNER JOIN AUDITAR_ASIGNACION_DOCUM AAD 
					ON AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
				INNER JOIN AUDITAR_TIPO_DOCU ATD 
					ON ATD.NU_DATO_INTER_ATD = REPLACE(DOCUMENTO_TIPO, TO_NUMBER(BODEGA_CODIGO), '') --Valores R, P, H, A
				INNER JOIN AUDITAR_REGISTRO_GLOSADO ARG 
					ON ARG.COD_AUDI_DOCUM_ARG = AD.COD_AUDI_DOCUM
				ORDER BY COD_AUDI_DOCUM DESC;
		END;

	ELSE

		BEGIN
			OPEN CV_1 FOR
				SELECT CD_ASIG_DOCU,
					COD_AUDI_DOCUM_AAD,
					IDEN_USUARIO_AAD,
					(	SELECT NO_NOMB_USUA 
						FROM USUARIOS 
						WHERE ID_IDEN_USUA = IDEN_USUARIO_AAD
							AND ROWNUM <= 1
					) NOM_AUDIT_ASIG,
					NVL(FE_FECHA_ARG, FECHA_ASIG_AAD) FE_FECHA_ARG,
					COD_AUDI_DOCUM,
					DOCUMENTO_TIPO,
					DOCUMENTO_CONSECUTIVO,
					ESTADO_ARG,
					NVL((	SELECT MAX(NU_NUM_RESPUESTA) 
							FROM AUDITAR_RESPUESTA_DOCU_OBJET 
							WHERE CODIGO_DOC_OBJETADO = COD_AUDI_DOCUM),0) CANT_RESPUESTA,		
					REPLACE(DOCUMENTO_TIPO_CONSEC,'-','') ID_DOCUM_INTERFAZ,
					DOCUMENTO_TIPO_CONSEC IDENTIFICADOR_ADJUNTOS,
					ATD.NU_DATO_INTER_ATD,
					ATD.CD_CODI_ATD,
					ATD.NO_NOMB_ATD,
					AUTO_REG_GLOSA,
					COD_REG_GLO_PADRE,
					FUERZA_NOMBRE
		 		FROM (SELECT COD_AUDI_DOCUM,
							DOCUMENTO_TIPO,
							DOCUMENTO_CONSECUTIVO,
							DOCUMENTO_TIPO_CONSEC,
							FUERZA_NOMBRE,
							BODEGA_CODIGO 
					FROM AUDITAR_DOCUMENTO 
					WHERE DOCUMENTO_TIPO = V_DOCUMENTO_TIPO
						AND DOCUMENTO_CONSECUTIVO = V_DOCUMENTO_CONSECUTIVO) AD 
		 		INNER JOIN AUDITAR_ASIGNACION_DOCUM AAD 
		 			ON AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
				INNER JOIN AUDITAR_TIPO_DOCU ATD 
					ON ATD.NU_DATO_INTER_ATD = REPLACE(DOCUMENTO_TIPO, TO_NUMBER(BODEGA_CODIGO), '') --Valores R, P, H, A
				LEFT JOIN AUDITAR_REGISTRO_GLOSADO ARG 
					ON ARG.COD_AUDI_DOCUM_ARG = AD.COD_AUDI_DOCUM
				ORDER BY COD_AUDI_DOCUM DESC;
		END;

	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;