CREATE OR REPLACE PROCEDURE H3i_SP_AUDI_GUARDA_LOG_ERROR
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	v_FECHA_SINCRO IN DATE,
	v_MENSAJE_ERROR IN VARCHAR2,
	v_ITEMS_ERROR IN VARCHAR2,
	v_NUMERO_RADICADO IN NUMBER
)
AS

BEGIN

	INSERT INTO AUDITAR_LOG_SINCRO_ERROR(
		FE_FECHA_SINCR_ALSE, NU_NUME_RADICA_ALSE, DE_MENSAJE_ERR_ALSE, ITEMS_ERROR_ALSE )
	VALUES ( 
		v_FECHA_SINCRO, v_NUMERO_RADICADO, v_MENSAJE_ERROR, v_ITEMS_ERROR );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;