CREATE OR REPLACE PROCEDURE H3i_SP_AUDIT_OBT_FILTROS_SES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================

(
	V_ID_IDEN_USUA IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)

AS
BEGIN
	OPEN CV_1 FOR
		SELECT COD_GLOSA_ARFS,
			FILTRAR_FECHA_ARFS,
			FECHA_DESDE_ARFS,
			FECHA_HASTA_ARFS,
			ESM_DISPENSA_ARFS,
			ESM_NOMBRE_ARFS,
			OPCION_ORDEN_ARFS,
			TIPO_ORDEN_ARFS,
			TIPO_DOCUMENTO
		FROM AUDITAR_REG_FILTRO_SESION
		WHERE ID_IDEN_USA_SESION = V_ID_IDEN_USUA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;