CREATE OR REPLACE PROCEDURE H3i_SP_AUDI_PRECIO_ANIO_MDICA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_COD_CATAL_MEDICAM_CPAM IN NUMBER
)

AS
BEGIN
	DELETE FROM 
		AUDITAR_PRECIO_ANIO_MEDICAM
	WHERE 
		COD_CATAL_MEDICAM_CPAM = V_COD_CATAL_MEDICAM_CPAM;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;