CREATE OR REPLACE PROCEDURE H3i_SP_AUDIT_OBT_FE_TRANSA_DOC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_DOCU_TIPO IN VARCHAR2,
  v_CONSECUTIVO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT DISTINCT DOCUMENTO_FECHA_TRANSACCION 
		FROM AUDITAR_DOCUMENTO 
		WHERE  DOCUMENTO_TIPO = v_DOCU_TIPO
		AND DOCUMENTO_CONSECUTIVO = v_CONSECUTIVO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;