CREATE PROCEDURE H3i_REP_TRAB_AUDI_FECH_REGAUDI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHA_INICIO IN DATE,
	V_FECHA_FIN IN DATE,
	CV_1 OUT SYS_REFCURSOR
)

AS
	V_FECHA_INICIO_N DATE := V_FECHA_INICIO;
	V_FECHA_FIN_N DATE := V_FECHA_FIN;
BEGIN
	OPEN CV_1 FOR
		--seleccionamos los ultimos documentos con operaciones 
		SELECT COD_AUDI_DOCUM,
			   FECHA_ASIG_AAD,
			   IDEN_USUARIO_AAD,
			   DOCUMENTO_VALOR_TOTAL,
			   ESTADO_ARG,
			   FE_FECHA_ARG
		INTO #DOCUMENTOS_GLOSADOS 
		FROM AUDITAR_REGISTRO_GLOSADO ARG 
		INNER JOIN AUDITAR_DOCUMENTO 
			ON ARG.COD_AUDI_DOCUM_ARG = COD_AUDI_DOCUM
		INNER JOIN AUDITAR_ASIGNACION_DOCUM 
			ON COD_AUDI_DOCUM_AAD = COD_AUDI_DOCUM
		WHERE (FECHA_ASIG_AAD BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
			OR (FE_FECHA_ARG BETWEEN @FECHA_INICIO_N AND V_FECHA_FIN_N)
		
		SELECT U.ID_IDEN_USUA, 
			U.NO_NOMB_USUA, 
			U.NU_TRABAJO_AUDI,
			(	SELECT COUNT(COD_AUDI_DOCUM_AAD) 
				FROM AUDITAR_ASIGNACION_DOCUM
				WHERE (FECHA_ASIG_AAD BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
				AND	IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_TOTAL,
			(	SELECT ISNULL(SUM(DOCUMENTO_VALOR_TOTAL), 0) 
				FROM AUDITAR_DOCUMENTO 
				INNER JOIN AUDITAR_ASIGNACION_DOCUM 
					ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
				WHERE (FECHA_ASIG_AAD BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_TOTAL,
			(	SELECT COUNT(DG.COD_AUDI_DOCUM) 
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_AUDITADOS,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_AUDITADOS,
			(	SELECT COUNT(AAD2.COD_AUDI_DOCUM_AAD)
				FROM AUDITAR_DOCUMENTO AD2 
				INNER JOIN AUDITAR_ASIGNACION_DOCUM AAD2 
					ON AD2.COD_AUDI_DOCUM = AAD2.COD_AUDI_DOCUM_AAD
				LEFT JOIN AUDITAR_REGISTRO_GLOSADO ARG2 
					ON AD2.COD_AUDI_DOCUM = COD_AUDI_DOCUM_ARG
					AND (FECHA_ASIG_AAD BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND AAD2.IDEN_USUARIO_AAD = U.ID_IDEN_USUA 
					AND ARG2.AUTO_REG_GLOSA IS NULL
			) AS CANTIDAD_SIN_AUDITAR,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM AUDITAR_DOCUMENTO 
				INNER JOIN AUDITAR_ASIGNACION_DOCUM AAD2 
					ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
			   	LEFT JOIN AUDITAR_REGISTRO_GLOSADO ARG2 
			   		ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_ARG
				WHERE (FECHA_ASIG_AAD BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND AAD2.IDEN_USUARIO_AAD = U.ID_IDEN_USUA 
					AND ARG2.AUTO_REG_GLOSA IS NULL
			) AS VALOR_SIN_AUDITAR,
			(	SELECT COUNT(DG.COD_AUDI_DOCUM) 
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
				AND ESTADO_ARG = 0 
				AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_GLOSADOS,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND ESTADO_ARG = 0 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_GLOSADOS,
			(	SELECT COUNT(DG.COD_AUDI_DOCUM) 
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND ESTADO_ARG = 1 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_CERRADOS,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND ESTADO_ARG = 1 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_CERRADOS,
			(	SELECT COUNT(DG.COD_AUDI_DOCUM) 
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) 
					AND ESTADO_ARG = 2 
					AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_CON_RESPUESTA,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) AND 
						ESTADO_ARG = 2 AND 
						IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_CON_RESPUESTA,
			(	SELECT COUNT(DG.COD_AUDI_DOCUM) 
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) AND 
						ESTADO_ARG = 3 AND 
						IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS CANTIDAD_CONCILIADOS,
			(	SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL), 0)  
				FROM #DOCUMENTOS_GLOSADOS AS DG
				WHERE (DG.FE_FECHA_ARG BETWEEN V_FECHA_INICIO_N AND V_FECHA_FIN_N) AND 
						ESTADO_ARG = 3 AND 
					   IDEN_USUARIO_AAD = U.ID_IDEN_USUA
			) AS VALOR_CONCILIADOS
		FROM USUARIOS U 
		INNER JOIN USUARIO_PERFIL UP 
			ON U.ID_IDEN_USUA = UP.ID_IDEN_USUA
		WHERE UP.CD_CODI_PERF = 33
		ORDER BY U.ID_IDEN_USUA;

	DROP TABLE #DOCUMENTOS_GLOSADOS;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;