CREATE OR REPLACE PROCEDURE H3i_SP_REP_DOC_SINC_NOSINC 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINI IN DATE DEFAULT NULL,
	V_FECHAFIN IN DATE DEFAULT NULL,
	V_ES_SINC IN NUMBER DEFAULT 1,
	V_INICIO IN NUMBER DEFAULT 0,
	V_LIMITE IN NUMBER DEFAULT 500,
	CV_1 OUT SYS_REFCURSOR
)

AS
BEGIN
	IF(V_ES_SINC = 1) THEN
		BEGIN
			OPEN CV_1 FOR
				SELECT DOCUMENTO_TIPO,
					DOCUMENTO_CONSECUTIVO,
					DOCUMENTO_FECHA_TRANSACCION,
					BODEGA_NOMBRE,
					ESM_ADSCRITO_CODIGO,
					ESM_ADSCRITO_NOMBRE,
					ESM_ATENCION_CODIGO,
					ESM_ATENCION_NOMBRE,
					DOCUMENTO_VALOR_TOTAL,
					CANTIDAD_MEDICAMENTOS,
					'SINCRONIZADO' AS ESTADO
				FROM (	SELECT DOCUMENTO_TIPO,
							DOCUMENTO_CONSECUTIVO,
							DOCUMENTO_FECHA_TRANSACCION,
							BODEGA_NOMBRE,
							ESM_ADSCRITO_CODIGO,
							ESM_ADSCRITO_NOMBRE,
							ESM_ATENCION_CODIGO,
							ESM_ATENCION_NOMBRE,
							DOCUMENTO_VALOR_TOTAL,
							CANTIDAD_MEDICAMENTOS,
							'SINCRONIZADO' AS ESTADO,
							ROWNUM AS RNUM
						FROM( 	SELECT DOCUMENTO_TIPO,
									DOCUMENTO_CONSECUTIVO,
									DOCUMENTO_FECHA_TRANSACCION,
									BODEGA_NOMBRE,
									ESM_ADSCRITO_CODIGO,
									ESM_ADSCRITO_NOMBRE,
									ESM_ATENCION_CODIGO,
									ESM_ATENCION_NOMBRE,
									DOCUMENTO_VALOR_TOTAL,
									(	SELECT COUNT(*) 
										FROM AUDITAR_DOCU_MEDICAMENTO ADM 
										WHERE ADM.COD_AUDI_DOCUM_ADM = COD_AUDI_DOCUM 
									) AS CANTIDAD_MEDICAMENTOS,
									'SINCRONIZADO' AS ESTADO
								FROM AUDITAR_ASIGNACION_DOCUM 
								INNER JOIN AUDITAR_DOCUMENTO 
									ON COD_AUDI_DOCUM_AAD = COD_AUDI_DOCUM
								WHERE FECHA_ASIG_AAD  BETWEEN TO_DATE(TO_CHAR(V_FECHAINI,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
														  AND TO_DATE(TO_CHAR(V_FECHAFIN,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
								ORDER BY DOCUMENTO_FECHA_TRANSACCION ASC)
						WHERE ROWNUM <= V_LIMITE)
				WHERE RNUM > V_INICIO;
		END;

	ELSE

		BEGIN
			OPEN CV_1 FOR
				SELECT DOCUMENTO_TIPO,
					DOCUMENTO_CONSECUTIVO,
					DOCUMENTO_FECHA_TRANSACCION,
					BODEGA_NOMBRE,
					'' AS ESM_ADSCRITO_CODIGO,
					'' AS ESM_ADSCRITO_NOMBRE,
					ESM_ATENCION_CODIGO,
					ESM_ATENCION_NOMBRE,
					DOCUMENTO_VALOR_TOTAL,
					CANTIDAD_MEDICAMENTOS,
					'RECHAZADO POR FTP' AS ESTADO
				FROM (	SELECT DOCUMENTO_TIPO,
							DOCUMENTO_CONSECUTIVO,
							DOCUMENTO_FECHA_TRANSACCION,
							BODEGA_NOMBRE,
							'' AS ESM_ADSCRITO_CODIGO,
							'' AS ESM_ADSCRITO_NOMBRE,
							ESM_ATENCION_CODIGO,
							ESM_ATENCION_NOMBRE,
							DOCUMENTO_VALOR_TOTAL,
							CANTIDAD_MEDICAMENTOS,
							'RECHAZADO POR FTP' AS ESTADO,
							ROWNUM AS RNUM
						FROM( 	SELECT DOCUMENTO_TIPO,
									DOCUMENTO_CONSECUTIVO,
									DOCUMENTO_FECHA_TRANSACCION,
									BODEGA_NOMBRE,
									'' AS ESM_ADSCRITO_CODIGO,
									'' AS ESM_ADSCRITO_NOMBRE,
									ESM_ATENCION_CODIGO,
									ESM_ATENCION_NOMBRE,
									DOCUMENTO_VALOR_TOTAL,
									CANTIDAD_MEDICAMENTOS,
									'RECHAZADO POR FTP' AS ESTADO
								FROM AUDITAR_DOCU_SINCRO_SIN_FTP
								WHERE FECHA_SINCRONIZA_DOC BETWEEN TO_DATE(TO_CHAR(V_FECHAINI,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
															   AND TO_DATE(TO_CHAR(V_FECHAFIN,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
								ORDER BY DOCUMENTO_FECHA_TRANSACCION ASC)
						WHERE ROWNUM <= V_LIMITE)
				WHERE RNUM > V_INICIO;		
		END;
	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;