CREATE PROCEDURE H3i_AUDIT_CONS_DOC_COD_ESTADO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(

	V_COD_AUDI_DOCUM IN NUMBER,
	V_ESTADO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR 
		SELECT COD_AUDI_DOCUM_ARG
		FROM AUDITAR_REGISTRO_GLOSADO
		WHERE ESTADO_ARG = V_ESTADO 
			AND COD_AUDI_DOCUM_ARG = V_COD_AUDI_DOCUM;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;