CREATE OR REPLACE PROCEDURE H3i_SP_DOCU_ESM_DISPENSA_X_FEC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINI IN DATE ,
	V_FECHAFIN IN DATE ,
	V_POR_SINCRON IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)


AS
BEGIN
	IF V_POR_SINCRON = 0 THEN
		BEGIN
			OPEN CV_1 FOR		
				SELECT --BODEGA_CODIGO, 
					BODEGA_NOMBRE, 
					COUNT(DOCUMENTO_CONSECUTIVO) AS CANTIDAD,
					SUM(DOCUMENTO_VALOR_TOTAL) AS VALOR_TOTAL_DOCUMENTOS
				FROM AUDITAR_DOCUMENTO
				WHERE DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(TO_CHAR(V_FECHAINI,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
												  AND TO_DATE(TO_CHAR(V_FECHAFIN,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
				GROUP BY BODEGA_NOMBRE;
		END;

	ELSE

		BEGIN
			OPEN CV_1 FOR
				SELECT --BODEGA_CODIGO, 
					BODEGA_NOMBRE, 
					COUNT(DOCUMENTO_CONSECUTIVO) AS CANTIDAD,
					SUM(DOCUMENTO_VALOR_TOTAL) AS VALOR_TOTAL_DOCUMENTOS
				FROM AUDITAR_DOCUMENTO 
				INNER JOIN AUDITAR_ASIGNACION_DOCUM 
					ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
				WHERE FECHA_ASIG_AAD BETWEEN TO_DATE(TO_DATE(V_FECHAINI,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
									 AND TO_DATE(TO_CHAR(V_FECHAFIN,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
				GROUP BY BODEGA_NOMBRE;
		END;

	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;