CREATE OR REPLACE PROCEDURE H3i_SP_DOCU_AUDITOR_POR_FECHA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_USUARIO IN VARCHAR2,
	V_FECHAINI IN DATE ,
	V_FECHAFIN IN DATE,
	V_POR_SINCRON IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)

AS
	V_USUARIO_LOCAL VARCHAR2(30) := V_USUARIO;
	V_FECHAINI_LOCAL DATE := V_FECHAINI;
	V_FECHAFIN_LOCAL DATE := V_FECHAFIN;
	V_POR_SINCRON_LOCAL NUMBER := V_POR_SINCRON;
BEGIN
	
	IF V_POR_SINCRON_LOCAL = 0 THEN
		BEGIN
			OPEN CV_1 FOR
				-- CANTIDAD DE DOCUMENTOS ASIGNADOS POR AUDITOR PARA FECHA ESPECÍFICA
				SELECT DISTINCT USR.ID_IDEN_USUA, 
					USR.NO_NOMB_USUA, 
					USR.NU_TRABAJO_AUDI, 
					(	SELECT COUNT(AD.COD_AUDI_DOCUM) 
						FROM AUDITAR_ASIGNACION_DOCUM AAD 
						INNER JOIN AUDITAR_DOCUMENTO AD 
							ON AAD.COD_AUDI_DOCUM_AAD = AD.COD_AUDI_DOCUM
						WHERE AAD.IDEN_USUARIO_AAD = USR.ID_IDEN_USUA 
							AND (AD.DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(TO_CHAR(V_FECHAINI_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
																AND TO_DATE(TO_DATE(V_FECHAFIN_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss'))
					) AS CANTI_DOCU_ASIG,
					(	SELECT SUM(AD.DOCUMENTO_VALOR_TOTAL) 
						FROM AUDITAR_ASIGNACION_DOCUM AAD 
						INNER JOIN AUDITAR_DOCUMENTO AD 
							ON AAD.COD_AUDI_DOCUM_AAD = AD.COD_AUDI_DOCUM
						WHERE AAD.IDEN_USUARIO_AAD = USR.ID_IDEN_USUA 
							AND (AD.DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(TO_CHAR(V_FECHAINI_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
																AND TO_DATE(TO_CHAR(V_FECHAFIN_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss'))
					) AS VALOR_TOTAL_DOCUMENTOS
				FROM USUARIOS USR 
				INNER JOIN USUARIO_PERFIL 
					ON USR.ID_IDEN_USUA = USUARIO_PERFIL.ID_IDEN_USUA
				WHERE USUARIO_PERFIL.CD_CODI_PERF = V_USUARIO_LOCAL
				ORDER BY CANTI_DOCU_ASIG DESC;
		END;

	ELSE

		BEGIN
			OPEN CV_1 FOR
				SELECT DISTINCT USR.ID_IDEN_USUA, 
					USR.NO_NOMB_USUA, 
					USR.NU_TRABAJO_AUDI, 
					(	SELECT COUNT(AD.COD_AUDI_DOCUM) 
						FROM AUDITAR_ASIGNACION_DOCUM AAD 
						INNER JOIN AUDITAR_DOCUMENTO AD 
							ON AAD.COD_AUDI_DOCUM_AAD = AD.COD_AUDI_DOCUM
						WHERE AAD.IDEN_USUARIO_AAD = USR.ID_IDEN_USUA 
							AND (AAD.FECHA_ASIG_AAD BETWEEN TO_DATE(TO_CHAR(V_FECHAINI_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss')
													AND TO_DATE(TO_CHAR(V_FECHAFIN_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss'))
					) CANTI_DOCU_ASIG,
					(	SELECT SUM(AD.DOCUMENTO_VALOR_TOTAL) 
						FROM AUDITAR_ASIGNACION_DOCUM AAD 
							INNER JOIN AUDITAR_DOCUMENTO AD 
								ON AAD.COD_AUDI_DOCUM_AAD = AD.COD_AUDI_DOCUM
						WHERE AAD.IDEN_USUARIO_AAD = USR.ID_IDEN_USUA 
							AND (AAD.FECHA_ASIG_AAD BETWEEN TO_DATE(TO_CHAR(V_FECHAINI_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss') 
													AND TO_DATE(TO_CHAR(V_FECHAFIN_LOCAL,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd hh24:mi:ss'))
					) VALOR_TOTAL_DOCUMENTOS
				FROM USUARIOS USR 
				INNER JOIN USUARIO_PERFIL 
					ON USR.ID_IDEN_USUA = USUARIO_PERFIL.ID_IDEN_USUA
				WHERE USUARIO_PERFIL.CD_CODI_PERF = V_USUARIO_LOCAL
				ORDER BY CANTI_DOCU_ASIG DESC;
		END;

	END IF;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;