CREATE OR REPLACE PROCEDURE H3i_SP_ELIM_TOPE_DATEXAM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_AUTO_DAEX IN NUMBER
)
AS

BEGIN

   DELETE TOPE_DATOEXAMEN
   WHERE  NU_AUTO_DAEX_TPDA = v_NU_AUTO_DAEX;
   DBMS_OUTPUT.PUT_LINE('SE HA CREADO EL PROCEDIMIENTO ALMACENADO H3i_SP_ELIM_TOPE_DATEXAM');

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;