CREATE OR REPLACE PROCEDURE H3i_SP_OBTENER_PERSFAMILGRAMA -- PROCEDIMIENTO ALMACENADO PARA RECUPERACION DE PERSONAFAMILIOGRAMA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_NU_HCLI IN VARCHAR2,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT PER.NU_NUME_PER ,
             PER.NO_NOMB_PER ,
             PER.NO_SGNO_PER ,
             PER.NO_PRAP_PER ,
             PER.NO_SGAP_PER ,
             PER.NU_HIST_PAC ,
             PER.NU_NUME_PER_PADRE ,
             PER.NU_NUME_PER_MADRE ,
             PER.GEN_SEX ,
             PER.FEC_NACIM ,
             PER.FEC_MUERTE ,
             PER.NACIDO_VIVO ,
             PER.ES_BIOLOGICO ,
             PER.TIPO_EMBARAZO ,
             PER.ES_GEMELO ,
             PADRE.NO_NOMB_PER NO_NOMB_PER_PADRE  ,
             PADRE.NO_SGNO_PER NO_SGNO_PER_PADRE  ,
             PADRE.NO_PRAP_PER NO_PRAP_PER_PADRE  ,
             PADRE.NO_SGAP_PER NO_SGAP_PER_PADRE  ,
             PADRE.NU_HIST_PAC NU_HIST_PAC_PADRE  ,
             PADRE.NU_NUME_PER_PADRE NU_NUME_PER_PADRE_PADRE  ,
             PADRE.NU_NUME_PER_MADRE NU_NUME_PER_MADRE_PADRE  ,
             PADRE.GEN_SEX GEN_SEX_PADRE  ,
             PADRE.FEC_NACIM FEC_NACIM_PADRE  ,
             PADRE.FEC_MUERTE FEC_MUERTE_PADRE  ,
             PADRE.NACIDO_VIVO NACIDO_VIVO_PADRE  ,
             PADRE.ES_BIOLOGICO ES_BIOLOGICO_PADRE  ,
             PADRE.TIPO_EMBARAZO TIPO_EMBARAZO_PADRE  ,
             PADRE.ES_GEMELO ES_GEMELO_PADRE  ,
             MADRE.NO_NOMB_PER NO_NOMB_PER_MADRE  ,
             MADRE.NO_SGNO_PER NO_SGNO_PER_MADRE  ,
             MADRE.NO_PRAP_PER NO_PRAP_PER_MADRE  ,
             MADRE.NO_SGAP_PER NO_SGAP_PER_MADRE  ,
             MADRE.NU_HIST_PAC NU_HIST_PAC_MADRE  ,
             MADRE.NU_NUME_PER_PADRE NU_NUME_PER_PADRE_MADRE  ,
             MADRE.NU_NUME_PER_MADRE NU_NUME_PER_MADRE_MADRE  ,
             MADRE.GEN_SEX GEN_SEX_MADRE  ,
             MADRE.FEC_NACIM FEC_NACIM_MADRE  ,
             MADRE.FEC_MUERTE FEC_MUERTE_MADRE  ,
             MADRE.NACIDO_VIVO NACIDO_VIVO_MADRE  ,
             MADRE.ES_BIOLOGICO ES_BIOLOGICO_MADRE  ,
             MADRE.TIPO_EMBARAZO TIPO_EMBARAZO_MADRE  ,
             MADRE.ES_GEMELO ES_GEMELO_MADRE  
        FROM HIST_GENO_PERSONA PER
               LEFT JOIN HIST_GENO_PERSONA PADRE   ON PADRE.NU_NUME_PER = PER.NU_NUME_PER_PADRE
               LEFT JOIN HIST_GENO_PERSONA MADRE   ON MADRE.NU_NUME_PER = PER.NU_NUME_PER_MADRE
       WHERE  PER.NU_HIST_PAC = v_CD_NU_HCLI ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;