CREATE OR REPLACE PROCEDURE H3i_SP_RESULTADOLABO_INS /*PROCEDIMIENTO ALMACENADO QUE PERMITE CONSULTAR LOS RESULTADOS DE LABORATORIO OBTENIDOS MEDIANTE INTERFACE PARA SER MOSTRADOS EN HC*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HPRO_RELA IN NUMBER,
  v_FE_PROCESA_RELA IN DATE,
  v_FE_REGISTRA_RELA IN DATE,
  v_TX_SECCION_RELA IN VARCHAR2,
  v_TX_PARAMETRO_RELA IN VARCHAR2,
  v_TX_VALOR_RELA IN VARCHAR2,
  v_TX_RANGO_RELA IN VARCHAR2
)
AS

BEGIN

    INSERT INTO RESULTADO_LABCLI( 
        NU_NUME_HPRO_RELA, FE_PROCESA_RELA, 
        FE_REGISTRA_RELA, TX_SECCION_RELA, 
        TX_PARAMETRO_RELA, TX_VALOR_RELA, 
        TX_RANGO_RELA )
    VALUES ( 
        v_NU_NUME_HPRO_RELA, v_FE_PROCESA_RELA, 
        v_FE_REGISTRA_RELA, v_TX_SECCION_RELA, 
        v_TX_PARAMETRO_RELA, v_TX_VALOR_RELA, 
        v_TX_RANGO_RELA );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;