CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_ALT_NPOSM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_AUTO_NOPM_ALTN IN NUMBER DEFAULT NULL ,
  v_NU_ORDEN_ALTN IN NUMBER DEFAULT NULL ,
  v_TX_PRINCIP_ALTN IN VARCHAR2 DEFAULT NULL ,
  v_TX_TIEMUTI_ALTN IN VARCHAR2 DEFAULT NULL ,
  v_TX_DOSIS_ALTN IN VARCHAR2 DEFAULT NULL ,
  v_NU_NOMEJOR_ALTN IN NUMBER DEFAULT NULL ,
  v_NU_REACADV_ALTN IN NUMBER DEFAULT NULL ,
  v_NU_INTOLER_ALTN IN NUMBER DEFAULT NULL 
)
AS

BEGIN

    INSERT INTO ALT_NPOSM (
      NU_AUTO_NOPM_ALTN, NU_ORDEN_ALTN, 
      TX_PRINCIP_ALTN, TX_TIEMUTI_ALTN, 
      TX_DOSIS_ALTN, NU_NOMEJOR_ALTN, 
      NU_REACADV_ALTN, NU_INTOLER_ALTN)
    VALUES (
      v_NU_AUTO_NOPM_ALTN, v_NU_ORDEN_ALTN, 
      v_TX_PRINCIP_ALTN, v_TX_TIEMUTI_ALTN, 
      v_TX_DOSIS_ALTN, v_NU_NOMEJOR_ALTN, 
      v_NU_REACADV_ALTN, v_NU_INTOLER_ALTN );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;