CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_ODONTO_RELA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
(
  v_ID IN NUMBER,
  v_TIPO IN VARCHAR2,
  v_DIAGNOSTICO IN VARCHAR2,
  v_PARAMETRO IN NUMBER,
  v_SERVICIO IN VARCHAR2,
  v_ESCARIES IN NUMBER,
  v_CARIESCAV IN NUMBER,
  v_CARNOCAV IN NUMBER,
  v_OPTURADOS IN NUMBER,
  v_PERDIDOS IN NUMBER,
  v_ENDODONCIA IN NUMBER,
  v_EXODONCIA IN NUMBER,
  v_CATEGORIA IN NUMBER
)
AS

BEGIN

   UPDATE ODONTO_RELA
      SET ID_TIPO_PARA_ODRE = v_TIPO,
          CD_CODI_DIAG_ODRE = v_DIAGNOSTICO,
          CD_CODI_PARA_ODRE = v_PARAMETRO,
          CD_CODI_SER_ODRE = v_SERVICIO,
          NU_ESCARIES_ODRE = v_ESCARIES,
          NU_CARIESCAV_ODRE = v_CARIESCAV,
          NU_CARNOCAV_ODRE = v_CARNOCAV,
          NU_OPTURADOS_ODRE = v_OPTURADOS,
          NU_PERDIDOS_ODRE = v_PERDIDOS,
          NU_ENDODONCIA_ODRE = v_ENDODONCIA,
          NU_EXODONCIA_ODRE = v_EXODONCIA,
          NU_AUTO_CAOD_ODRE = v_CATEGORIA
    WHERE  NU_AUTO_RELA = v_ID;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;