CREATE OR REPLACE FUNCTION CUENTACONTABLExSERVICIO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_NU_NUME_LABO IN NUMBER,
    v_CECOMOVI IN VARCHAR2,
    v_CENTRO IN VARCHAR2,
    v_SUBCENTRO IN VARCHAR2,
    v_TIPOCUENTA IN VARCHAR2
)
RETURN VARCHAR2
AS
    v_RTA NVARCHAR2(20);

BEGIN
    SELECT CD_CODI_CUEN_RDES 
    INTO v_RTA
    FROM LABORATORIO,
        R_DEP_ESP_SER 
    WHERE  CD_CODI_CECO_RDES = v_CECOMOVI
        AND LABORATORIO.CD_CODI_ESP_LABO = R_DEP_ESP_SER.CD_CODI_ESP_RDES
        AND LABORATORIO.CD_CODI_SER_LABO = R_DEP_ESP_SER.CD_CODI_SER_RDES
        AND TX_TIPCUE_RDES = v_TIPOCUENTA
        AND NU_NUME_LABO = v_NU_NUME_LABO
        AND CD_CODI_CC_RLD_RDES = v_CENTRO
        AND CD_CODI_SUBCC_RDES = v_SUBCENTRO;
        
   RETURN v_RTA;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;