CREATE OR REPLACE FUNCTION F_FILTRA_TIPOSERVICIOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_TIPOSERV IN VARCHAR2
)
RETURN TYPE_TAB_FILTRA_TIPOSERVICIOS
IS
    V_TABLA TYPE_TAB_FILTRA_TIPOSERVICIOS := TYPE_TAB_FILTRA_TIPOSERVICIOS();
    ---------------------------------------
    V_TIPO NUMBER;
    V_COMPARACION NUMBER;
    ---------------------------------------
    CURSOR CV_1 IS
        SELECT DISTINCT NU_OPCI_SER  
        FROM SERVICIOS
        ORDER BY NU_OPCI_SER;
    ---------------------------------------

BEGIN
    OPEN CV_1;
    FETCH CV_1 INTO V_TIPO;
        
    WHILE CV_1%FOUND
    LOOP
        V_COMPARACION := INSTR(TO_CHAR(V_TIPO),V_TIPOSERV);

        IF(V_COMPARACION <> 0 ) THEN
            V_TABLA.EXTEND;
            V_TABLA(V_TABLA.LAST) := TYPE_F_FILTRA_TIPOSERVICIOS(
                V_TIPO
              );
        END IF; 
    END LOOP;

    CLOSE CV_1;

    RETURN V_TABLA;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;



--CREACION DEL TYPO COMO OBJECTO QUE SERA LA TABLA
CREATE TYPE TYPE_F_FILTRA_TIPOSERVICIOS AS OBJECT (
    NU_OPCI_SER NUMBER(3)
);

--CREACION DEL TYPE COMO UNA TBLA DE ESE TIPOP
CREATE TYPE TYPE_TAB_FILTRA_TIPOSERVICIOS IS TABLE OF TYPE_F_FILTRA_TIPOSERVICIOS;