CREATE OR REPLACE FUNCTION FN_LISTACARGOSCONFIRMADOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_CodMed IN VARCHAR2,
    V_FechaIni IN DATE,
    V_FechaFin IN DATE
)
RETURN TYPE_TAB_LISTACARGOSCONFIRMADO
AS
    V_TABLA  TYPE_TAB_LISTACARGOSCONFIRMADO := TYPE_TAB_LISTACARGOSCONFIRMADO();
    -------------------------------------
    TYPE RECORDTYPE IS RECORD (
        COL1 VARCHAR2(30), COL2 VARCHAR2(20), 
        COL3 VARCHAR2(405), COL4 NUMBER(3),
        COL5 VARCHAR2(20), COL6 NUMBER(3),
        COL7 DATE, COL8 VARCHAR2(30),
        COL9 NUMBER, COL10 VARCHAR2(100),
        COL11 VARCHAR2(255), COL12 VARCHAR2(70), 
        COL13 VARCHAR2(170), COL14 VARCHAR2(5), 
        COL15 NUMBER, COL16 NUMBER(10), 
        COL17 VARCHAR2(5), COL18 NUMBER , 
        COL19 NUMBER(10), COL20 DATE
    );
    -------------------------------------  
    CURSOR CV_1 IS
          SELECT  TO_CHAR(FE_HORA_CCAR) FE_HORA_CARG, 
              NU_HIST_PAC, 
              SUBSTR(DE_PRAP_PAC || ' ' || DE_SGAP_PAC || ' ' || NO_NOMB_PAC || ' ' || NO_SGNO_PAC,1,150) AS NOMB_PAC,
              NU_TIPD_PAC, NU_DOCU_PAC,
              NU_SEXO_PAC, FE_NACI_PAC,
              SUBSTR(DE_TELE_PAC,1,20) DETELEPAC,
              0 NU_ESTA_CIT, NO_NOMB_EPS, 
              SUBSTR(NO_NOMB_SER,1,150), 
              SUBSTR(MED_ORDE.NO_NOMB_MED,1,100), 
              NO_NOMB_USUA,'' DE_DESC_CIT, 
              3 NU_TIPO_CIT, NU_NUME_LABO, 
              '' TX_OBSFIN_CIT, 1 NU_CONFIR_CIT, 
              NU_NUME_MOVI, 
              FE_HORA_CCAR FE_FECH_CIT
          FROM CONFIRMA_CARG 
          INNER JOIN MOVI_CARGOS 
              ON NU_NUME_MOVI = NU_NUME_MOVI_CCAR
          INNER JOIN LABORATORIO 
              ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
          INNER JOIN SERVICIOS 
              ON CD_CODI_SER =CD_CODI_SER_LABO
          INNER JOIN PACIENTES 
              ON NU_HIST_PAC = NU_HIST_PAC_MOVI
          INNER JOIN MEDICOS 
              ON CD_CODI_MED  = CD_CODI_MEDI_LABO
          INNER JOIN CONVENIOS 
              ON NU_NUME_CONV = NU_NUME_CONV_MOVI
          INNER JOIN EPS 
              ON CD_NIT_EPS= CD_NIT_EPS_CONV
          INNER JOIN CONEXIONES 
              ON  NU_NUME_CONE_MOVI = NU_NUME_CONE
          INNER JOIN USUARIOS 
              ON USUARIO = ID_IDEN_USUA 
          LEFT JOIN MEDICOS MED_ORDE 
              ON CD_MEDI_ORDE_MOVI = MED_ORDE.CD_CODI_MED 
          WHERE NU_ESTA_MOVI <> 2
              AND NU_ESTA_LABO <> 2
              AND MEDICOS.CD_CODI_MED = V_CodMed
              AND FE_HORA_CCAR BETWEEN V_FechaIni AND V_FechaFin 
              AND NU_NUME_MOVI NOT IN (SELECT NU_NUME_MOVI_CIT FROM CITAS_MEDICAS WHERE CD_CODI_MED_CIT =  V_CodMed)      
            
        UNION ALL
          
          SELECT  TO_CHAR(CONEXIONES.FECHA) FE_HORA_CARG,
              NU_HIST_PAC, 
              SUBSTR(DE_PRAP_PAC + ' ' + DE_SGAP_PAC + ' ' + NO_NOMB_PAC + ' ' + NO_SGNO_PAC,1,150) AS NOMB_PAC,
              NU_TIPD_PAC, NU_DOCU_PAC,
              NU_SEXO_PAC,FE_NACI_PAC,
              SUBSTR(DE_TELE_PAC,1,20) DETELEPAC,
              0 NU_ESTA_CIT, NO_NOMB_EPS, 
              SUBSTR(NO_NOMB_SER,1,150), 
              SUBSTR(MED_ORDE.NO_NOMB_MED,1,100), 
              NO_NOMB_USUA, '' DE_DESC_CIT,
              3 NU_TIPO_CIT, NU_NUME_LABO, 
              '' TX_OBSFIN_CIT, 1 NU_CONFIR_CIT, 
              NU_NUME_MOVI,  
              CONEXIONES.FECHA FE_FECH_CIT
          FROM MOVI_CARGOS 
          INNER JOIN LABORATORIO 
              ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
          INNER JOIN SERVICIOS  
              ON CD_CODI_SER =CD_CODI_SER_LABO
          INNER JOIN PACIENTES 
              ON NU_HIST_PAC = NU_HIST_PAC_MOVI
          INNER JOIN MEDICOS 
              ON CD_CODI_MED  = CD_CODI_MEDI_LABO
          INNER JOIN CONVENIOS 
              ON NU_NUME_CONV = NU_NUME_CONV_MOVI
          INNER JOIN EPS 
              ON CD_NIT_EPS= CD_NIT_EPS_CONV
          INNER JOIN CONEXIONES 
              ON  NU_NUME_CONE_MOVI = NU_NUME_CONE
          INNER JOIN USUARIOS 
              ON USUARIO = ID_IDEN_USUA 
          LEFT JOIN MEDICOS MED_ORDE 
              ON CD_MEDI_ORDE_MOVI = MED_ORDE.CD_CODI_MED 
          WHERE NU_ESTA_MOVI<>2
              AND NU_ESTA_LABO<>2
              AND MEDICOS.CD_CODI_MED = V_CodMed
              AND SERVICIOS.NU_NOFACT_SER = 1
              AND FECHA BETWEEN V_FechaIni AND V_FechaFin
              AND NU_NUME_MOVI NOT IN (SELECT NU_NUME_MOVI_CIT FROM CITAS_MEDICAS WHERE CD_CODI_MED_CIT =  V_CodMed); 
    -------------------------------------   
    OUTTABLE RECORDTYPE;

BEGIN

    OPEN CV_1;
    FETCH CV_1 INTO OUTTABLE;

    WHILE CV_1%FOUND
    LOOP
      V_TABLA.EXTEND;
      V_TABLA(V_TABLA.LAST) := TYPE_FN_LISTACARGOSCONFIRMADOS(
          OUTTABLE.COL1, OUTTABLE.COL2,
          OUTTABLE.COL3, OUTTABLE.COL4,
          OUTTABLE.COL5, OUTTABLE.COL6,
          OUTTABLE.COL7, OUTTABLE.COL8,
          OUTTABLE.COL9, OUTTABLE.COL10,
          OUTTABLE.COL11, OUTTABLE.COL12,
          OUTTABLE.COL13, OUTTABLE.COL14, 
          OUTTABLE.COL15, OUTTABLE.COL16, 
          OUTTABLE.COL17, OUTTABLE.COL18, 
          OUTTABLE.COL19, OUTTABLE.COL20
        );
      FETCH CV_1 INTO OUTTABLE;
    END LOOP;

    CLOSE CV_1;

    RETURN V_TABLA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

--CREACION DEL TYPO COMO OBJECTO QUE SERA LA TABLA
CREATE TYPE TYPE_FN_LISTACARGOSCONFIRMADOS AS OBJECT (
    FE_HORA_CCAR VARCHAR2(30),
    NU_HIST_PAC VARCHAR2(20), 
    NOMB_PAC VARCHAR2(405),
    NU_TIPD_PAC NUMBER(3),
    NU_DOCU_PAC VARCHAR2(20),
    NU_SEXO_PAC NUMBER(3),
    FE_NACI_PAC DATE,
    DE_TELE_PAC VARCHAR2(30),
    NU_ESTA_CIT NUMBER,
    NO_NOMB_EPS VARCHAR2(100),
    NO_NOMB_SER VARCHAR2(255),
    NO_NOMB_MED VARCHAR2(70), 
    NO_NOMB_USUA VARCHAR2(170),
    DE_DESC_CIT VARCHAR2(5), 
    NU_TIPO_CIT NUMBER, 
    NU_NUME_LABO NUMBER(10), 
    TX_OBSFIN_CIT VARCHAR2(5), 
    NU_CONFIR_CIT NUMBER , 
    NU_NUME_MOVI NUMBER(10),
    FE_FECH_CIT DATE
);

--CREACION DEL TYPE COMO UNA TBLA DE ESE TIPOP
CREATE TYPE TYPE_TAB_LISTACARGOSCONFIRMADO IS TABLE OF TYPE_FN_LISTACARGOSCONFIRMADOS;
