CREATE OR REPLACE FUNCTION FN_MEDICAMENTO_NoPOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_NumNoPOS IN NUMBER,
    V_Orden IN NUMBER
)
RETURN TYPE_TAB_MEDICAMENTO_NoPOS
AS
    V_TABLA  TYPE_TAB_MEDICAMENTO_NoPOS := TYPE_TAB_MEDICAMENTO_NoPOS();
    -------------------------------------
    TYPE RECORDTYPE IS RECORD (
        COL1 VARCHAR2(20), COL2 VARCHAR2(100),
        COL3 VARCHAR2(100), COL4 VARCHAR2(100), 
        COL5 NUMBER(10), COL6 NUMBER(10), 
        COL7 NUMBER(10), COL8 VARCHAR2(50),
        COL9 VARCHAR2(40), COL10 NUMBER
    );
    ------------------------------------- 
    CURSOR CV_1 IS
        SELECT TX_CODI_MED_DNOP, TX_PRINCIP_DNOP, 
            TX_GRUPOT_DNOP, TX_FORMA_DNOP, 
            NU_DIASTRAT_DNOP, NU_DOSISD_DNOP, 
            NU_CANTMES_DNOP, TX_VIAADM_DNOP, 
            TX_INVIMA_DNOP, V_NumNoPOS
        FROM DET_NPOSM 
        WHERE NU_AUTO_NOPM_DNOP = V_NumNoPOS  
            AND NU_TIPO_DNOP = V_Orden;
    -------------------------------------   
    OUTTABLE RECORDTYPE;
BEGIN
    OPEN CV_1;
    FETCH CV_1 INTO OUTTABLE;

    WHILE CV_1%FOUND
    LOOP
      V_TABLA.EXTEND;
      V_TABLA(V_TABLA.LAST) := TYPE_FN_MEDICAMENTO_NoPOS(
          OUTTABLE.COL1, OUTTABLE.COL2,
          OUTTABLE.COL3, OUTTABLE.COL4,
          OUTTABLE.COL5, OUTTABLE.COL6,
          OUTTABLE.COL7, OUTTABLE.COL8,
          OUTTABLE.COL9, OUTTABLE.COL10
        );
      FETCH CV_1 INTO OUTTABLE;
    END LOOP;

    CLOSE CV_1;

    RETURN V_TABLA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;


--CREACION DEL TYPO COMO OBJECTO QUE SERA LA TABLA
CREATE TYPE TYPE_FN_MEDICAMENTO_NoPOS AS OBJECT (
    TX_CODI_MED_DNOP VARCHAR2(20),
    TX_PRINCIP_DNOP VARCHAR2(100),
    TX_GRUPOT_DNOP VARCHAR2(100),
    TX_FORMA_DNOP VARCHAR2(100),
    NU_DIASTRAT_DNOP NUMBER(10),
    NU_DOSISD_DNOP NUMBER(10),
    NU_CANTMES_DNOP NUMBER(10), 
    TX_VIAADM_DNOP VARCHAR2(50),
    TX_INVIMA_DNOP VARCHAR2(40),
    NUMNOPOS NUMBER 
);

--CREACION DEL TYPE COMO UNA TBLA DE ESE TIPOP
CREATE TYPE TYPE_TAB_MEDICAMENTO_NoPOS IS TABLE OF TYPE_FN_MEDICAMENTO_NoPOS;

      