CREATE OR REPLACE FUNCTION FN_TablaDocumentosGlosados2
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_IDEN_USR_OPL IN VARCHAR2,
    V_FILTROFECHA IN NUMBER,
    V_FECHAINI IN DATE,
    V_FECHAFIN IN DATE,
    V_CODGLOSA IN VARCHAR2,
    V_COD_BODEGA IN NUMBER,
    V_OPCIONORDEN IN NUMBER,
    V_TIPOORDEN IN NUMBER
)
RETURN TYPE_TAB_TablaDocumenGlosados2
AS
    V_TABLA  TYPE_TAB_TablaDocumenGlosados2 := TYPE_TAB_TablaDocumenGlosados2();
    -------------------------------------
    TYPE RECORDTYPE IS RECORD (
        COL1 NUMBER(19), COL2 VARCHAR2(4000),
        COL3 NUMBER(19), COL4 NUMBER(19),
        COL5 NUMBER(38), COL6 NUMBER(38),
        COL7 NUMBER(38), COL8 NUMBER(10),
        COL9 DATE, COL10 VARCHAR2(30),
        COL11 VARCHAR2(20), COL12 VARCHAR2(20)
    );
    ------------------------------------- 
    CURSOR CV_1 IS
        SELECT COD_AUDI_DOCUM_TB, DE_OBSERVACION_ARG, 
            AUTO_REG_GLOSA, COD_AUDI_DOCUM_ARG, 
            VALOR_FACTURADO_ARG, VALOR_GLOSADO_ARG, 
            VALOR_PAGAR_ARG, ESTADO_ARG,
            FE_FECHA_ARG, IDEN_USUARIO_FARM_ARG, 
            CAUSA_CODIGO_CONCIL_ARG, COD_CAUSA_TIPO_AGSI
        FROM (SELECT COD_AUDI_DOCUM_ARG COD_AUDI_DOCUM_TB,
                  DE_OBSERVACION_ARG, AUTO_REG_GLOSA,
                  COD_AUDI_DOCUM_ARG, VALOR_FACTURADO_ARG,
                  VALOR_GLOSADO_ARG, VALOR_PAGAR_ARG,
                  ESTADO_ARG, FE_FECHA_ARG,
                  IDEN_USUARIO_FARM_ARG, CAUSA_CODIGO_CONCIL_ARG,
                  AGSI.COD_CAUSA_TIPO_AGSI
              FROM AUDITAR_REGISTRO_GLOSADO ARG 
              INNER JOIN AUDITAR_DOCUMENTO 
                  ON ARG.COD_AUDI_DOCUM_ARG = COD_AUDI_DOCUM
              INNER JOIN AUDITAR_ASIGNACION_DOCUM 
                  ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
              LEFT JOIN AUDITAR_GLOSADO_SEGUIM_ITEMS AGSI 
                  ON (AUTO_REG_GLOSA = AGSI.AUTO_REG_GLOSA_AGSI 
                      AND AGSI.COD_CAUSA_TIPO_AGSI IS NOT NULL 
                      AND AGSI.COD_CAUSA_TIPO_AGSI <> '')
              WHERE ESTADO_ARG = 0
                  AND FECHA_ASIG_AAD > TO_DATE('2015-09-26 00:00:00','YYYY-MM-DD HH24:MI:SS') -- SE PONE DE MOMENTO ESTA RESTRICCIÓN HASTA QUE SOLUCIONEN QUE SE HARÁ CON TODO LO OBJETADO O CONCILIEN.
                  AND (DOC_FUE_REPORTADO IS NULL 
                      OR DOC_FUE_REPORTADO = 0)
                  AND AGSI.COD_CAUSA_TIPO_AGSI = NVL(V_CODGLOSA, AGSI.COD_CAUSA_TIPO_AGSI)
                  AND BODEGA_CODIGO = CASE 
                                          WHEN V_COD_BODEGA = 0 THEN BODEGA_CODIGO 
                                          ELSE V_COD_BODEGA 
                                      END
                  AND IDEN_USUARIO_FARM_ARG = V_IDEN_USR_OPL
                  AND DOCUMENTO_FECHA_TRANSACCION >=CASE 
                                                        WHEN V_FILTROFECHA = 1 THEN V_FECHAINI 
                                                        ELSE DOCUMENTO_FECHA_TRANSACCION 
                                                    END
                  AND DOCUMENTO_FECHA_TRANSACCION <=CASE 
                                                        WHEN V_FILTROFECHA = 1 THEN V_FECHAFIN 
                                                        ELSE DOCUMENTO_FECHA_TRANSACCION 
                                                     END
              ORDER BY 
                  CASE WHEN V_OPCIONORDEN = 1 AND V_TIPOORDEN = 2 THEN VALOR_FACTURADO_ARG END ASC,
                  CASE WHEN V_OPCIONORDEN = 1 AND V_TIPOORDEN = 1 THEN VALOR_FACTURADO_ARG END DESC,
                  CASE WHEN V_OPCIONORDEN = 2 AND V_TIPOORDEN = 2 THEN DOCUMENTO_FECHA_TRANSACCION END ASC,
                  CASE WHEN V_OPCIONORDEN = 2 AND V_TIPOORDEN = 1 THEN DOCUMENTO_FECHA_TRANSACCION END DESC)
        WHERE ROWNUM <= 20;
    -------------------------------------   
    OUTTABLE RECORDTYPE;
BEGIN
    OPEN CV_1;
    FETCH CV_1 INTO OUTTABLE;

    WHILE CV_1%FOUND
    LOOP
      V_TABLA.EXTEND;
      V_TABLA(V_TABLA.LAST) := TYPE_FN_TablaDocumentGlosados2(
          OUTTABLE.COL1, OUTTABLE.COL2,
          OUTTABLE.COL3, OUTTABLE.COL4,
          OUTTABLE.COL5, OUTTABLE.COL6,
          OUTTABLE.COL7, OUTTABLE.COL8,
          OUTTABLE.COL9, OUTTABLE.COL10,
          OUTTABLE.COL11, OUTTABLE.COL12
        );
      FETCH CV_1 INTO OUTTABLE;
    END LOOP;

    CLOSE CV_1;

    RETURN V_TABLA;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;



--CREACION DEL TYPO COMO OBJECTO QUE SERA LA TABLA
CREATE TYPE TYPE_FN_TablaDocumentGlosados2 AS OBJECT (
    COD_AUDI_DOCUM_TB NUMBER(19),
    DE_OBSERVACION_ARG VARCHAR2(4000),
    AUTO_REG_GLOSA NUMBER(19),
    COD_AUDI_DOCUM_ARG NUMBER(19),
    VALOR_FACTURADO_ARG NUMBER(38),
    VALOR_GLOSADO_ARG NUMBER(38),
    VALOR_PAGAR_ARG NUMBER(38),
    ESTADO_ARG NUMBER(10),
    FE_FECHA_ARG DATE,
    IDEN_USUARIO_FARM_ARG VARCHAR2(30),
    CAUSA_CODIGO_CONCIL_ARG VARCHAR2(20),
    COD_CAUSA_TIPO_AGSI VARCHAR2(20)
);

--CREACION DEL TYPE COMO UNA TBLA DE ESE TIPOP
CREATE TYPE TYPE_TAB_TablaDocumenGlosados2 IS TABLE OF TYPE_FN_TablaDocumentGlosados2;
