CREATE OR REPLACE VIEW FACPAQU
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
	SELECT MOVI_CARGOS.NU_NUME_PAQU_MOVI,
		MOVI_CARGOS.NU_NUME_FACO_MOVI,
		CD_CODI_LUAT_MOVI 
	FROM MOVI_CARGOS 
	INNER JOIN LABORATORIO    
		ON MOVI_CARGOS.NU_NUME_MOVI = LABORATORIO.NU_NUME_MOVI_LABO
	WHERE  ( MOVI_CARGOS.NU_NUME_PAQU_MOVI <> 0 )
		AND ( MOVI_CARGOS.NU_NUME_FACO_MOVI <> 0 )
		AND NU_ESTA_MOVI <> 2;