CREATE OR REPLACE VIEW SERVICIOS_SECCIONES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
	SELECT SECCIONES.CD_CODI_SEC ,
		SECCIONES.NO_NOMB_SEC ,
		SERVICIOS.CD_CODI_SER ,
		SERVICIOS.NO_NOMB_SER 
	FROM R_SERV_SEC 
	INNER JOIN SECCIONES    
		ON R_SERV_SEC.CD_CODI_SEC = SECCIONES.CD_CODI_SEC
	INNER JOIN SERVICIOS    
		ON R_SERV_SEC.CD_CODI_SER = SERVICIOS.CD_CODI_SER;