CREATE OR REPLACE VIEW V_CARGO_ADSCRITO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
    SELECT PACIENTES.NU_DOCU_PAC, PACIENTES.NU_HIST_PAC ,
        PACIENTES.NU_TIPD_PAC, PACIENTES.DE_PRAP_PAC,
        PACIENTES.DE_SGAP_PAC, PACIENTES.NO_NOMB_PAC,
        PACIENTES.NO_SGNO_PAC, PACIENTES.FE_NACI_PAC,
        PACIENTES.DE_DIRE_PAC, PACIENTES.DE_TELE_PAC,
        PACIENTES.NU_SEXO_PAC, MOVI_CARGOS.NU_NUME_MOVI ,
        MOVI_CARGOS.NU_ESTA_MOVI, MOVI_CARGOS.FE_FECH_MOVI,
        LABORATORIO.CD_CODI_SER_LABO , LABORATORIO.CT_CANT_LABO,
        LABORATORIO.VL_UNID_LABO, LABORATORIO.VL_COPA_LABO,
        SERVICIOS.NO_NOMB_SER, SERVICIOS.NU_OPCI_SER,
        ORDENES.NU_NUME_ORDE, ORDENES.FE_FECH_ORDE,
        ORDENES.NU_HIST_PAC_ORDE, ORDENES.NU_ESTA_ORDE,
        AUTORIZACION.NU_CONSE_AUTOR, AUTORIZACION.CD_CODI_MOTI_AUTOR,
        ADSCRITOS.NU_CONSE_ADSC, ADSCRITOS.DE_NOMB_ADSC,
        ADSCRITOS.DE_DIREC_ADSC, MEDICOS.CD_CODI_MED,
        MEDICOS.NO_NOMB_MED, MEDICOS.NU_DOCU_MED,
        MEDICOS.NU_INDI_MED, EPS.CD_NIT_EPS,
        EPS.NO_NOMB_EPS, DETAUT.CD_CODI_DETAUT,
        DETAUT.NU_CANT_DETAUT, DETAUT.VL_VALORXP_DETAUT,
        CONEXIONES.USUARIO, CONEXIONES.NOMBRE_PC,
        REGIMEN.NO_NOMB_REG, USUARIOS.NO_NOMB_USUA 
    FROM MOVI_CARGOS 
    INNER JOIN LABORATORIO    
        ON MOVI_CARGOS.NU_NUME_MOVI = LABORATORIO.NU_NUME_MOVI_LABO
    INNER JOIN ORDENES    
        ON MOVI_CARGOS.NU_NUME_ORDE_MOVI = ORDENES.NU_NUME_ORDE
        AND MOVI_CARGOS.NU_HIST_PAC_MOVI = ORDENES.NU_HIST_PAC_ORDE
    INNER JOIN CONVENIOS    
        ON MOVI_CARGOS.NU_NUME_CONV_MOVI = CONVENIOS.NU_NUME_CONV
    INNER JOIN EPS    
        ON CONVENIOS.CD_NIT_EPS_CONV = EPS.CD_NIT_EPS
    INNER JOIN AUTORIZACION    
        ON CONVENIOS.NU_NUME_CONV = AUTORIZACION.NU_NUME_CONV_AUTOR
        AND ORDENES.NU_NUME_ORDE = AUTORIZACION.NU_NUME_ORDE_AUTOR
        AND ORDENES.NU_HIST_PAC_ORDE = AUTORIZACION.NU_HIST_PAC_AUTOR
    INNER JOIN CONEXIONES    
        ON AUTORIZACION.NU_NUME_CONE_AUTOR = CONEXIONES.NU_NUME_CONE
    INNER JOIN MEDICOS    
        ON AUTORIZACION.CD_CODI_MED_AUTOR = MEDICOS.CD_CODI_MED
    INNER JOIN DETAUT    
        ON AUTORIZACION.NU_CONSE_AUTOR = DETAUT.NU_CONSE_AUTOR_DETAUT
    INNER JOIN ADSCRITOS    
        ON MEDICOS.NU_CONSE_ADSC_MED = ADSCRITOS.NU_CONSE_ADSC
    INNER JOIN PACIENTES    
        ON MOVI_CARGOS.NU_HIST_PAC_MOVI = PACIENTES.NU_HIST_PAC
    INNER JOIN SERVICIOS    
        ON LABORATORIO.CD_CODI_SER_LABO = SERVICIOS.CD_CODI_SER
    INNER JOIN REGIMEN    
        ON MOVI_CARGOS.CD_REGIMEN_MOVI = REGIMEN.CD_CODI_REG
    INNER JOIN USUARIOS    
        ON CONEXIONES.USUARIO = USUARIOS.ID_IDEN_USUA;