CREATE OR REPLACE VIEW V_IMPUESTOS_PAC_COMPROBANTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
    SELECT TB6.CD_CODI_COMPROBANTE_ZETA,
        TB7.DE_DESC_CAJA,
        TB5.DE_NOMB_IMPU IMPUESTO,
        TB5.CD_CUEN_IMPU CUENTA,
        SUM(((TB2.VL_UNID_LABO * TB2.CT_CANT_LABO) - TB2.VL_COPA_LABO)) BASE,
        CASE TB5.NU_TCOBRO_IMPU
            WHEN 1 THEN TB5.PR_PORC_IMPU
            ELSE 0
        END PORCENTAJE  ,
        SUM(TB1.VL_IMPUESTO_RLI)  VALOR  
    FROM R_LABO_IMPU TB1
    INNER JOIN LABORATORIO TB2   
        ON TB2.NU_NUME_LABO = TB1.NU_NUME_LABO_RLI
    INNER JOIN MOVI_CARGOS TB3   
        ON TB3.NU_NUME_MOVI = TB2.NU_NUME_MOVI_LABO
    INNER JOIN FACTURAS_CONTADO TB4   
        ON TB4.NU_NUME_FACO = TB3.NU_NUME_FACO_MOVI
    INNER JOIN TC_IMPUESTOS TB5   
        ON TB5.CD_CODI_IMPU = TB1.CD_CODI_IMPU_RLI
    INNER JOIN ZETAS TB6   
        ON TB6.NU_NUME_ZETA = TB4.NU_NUME_ZETA_FACO
    INNER JOIN CAJAS TB7   
        ON TB7.DE_IPDIR_CAJA = TB6.DE_IPDIR_CAJA_ZETA
        AND TB7.CD_CODI_CAJA = TB4.NU_NUME_CAJA_FACO
    WHERE  TB4.NU_NUME_FACO <> 0
        AND TB3.NU_ESTA_MOVI <> 2
        AND TB4.NU_CONSE_FACCAJA_FACO <> 0
        AND TB1.ID_PAGADOPOR_RLI = 0
    GROUP BY TB6.CD_CODI_COMPROBANTE_ZETA,
        TB7.DE_DESC_CAJA, TB5.DE_NOMB_IMPU,
        TB5.CD_CUEN_IMPU, TB5.NU_TCOBRO_IMPU,
        TB5.PR_PORC_IMPU;