CREATE OR REPLACE VIEW V_PLANTILLAS_HISTORIAS
AS 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
    SELECT R_PLANTILLA_HIST.NU_NUME_PLHI_R ,
      FINALIDAD_HIST.CD_NOMB_FIN ,
      GRUPO_HIST.CD_CODI_GRHI ,
      GRUPO_HIST.NU_NUME_GRHI ,
      CONCEPTO_HIST.CD_CODI_COHI ,
      CONCEPTO_HIST.NU_NUME_COHI ,
      CONCEPTO_HIST.NU_TIPO_COHI ,
      R_PLAN_CONC.NU_INDI_RPC 
    FROM R_PLANTILLA_HIST 
    INNER JOIN FINALIDAD_HIST    
        ON R_PLANTILLA_HIST.NU_FINA_PLHI = FINALIDAD_HIST.CD_CODI_FIN
    INNER JOIN CONCEPTO_HIST 
    INNER JOIN R_PLAN_CONC    
        ON CONCEPTO_HIST.NU_NUME_COHI = R_PLAN_CONC.NU_NUME_COHI_RPC
    INNER JOIN GRUPO_HIST    
        ON R_PLAN_CONC.NU_NUME_GRHI_RPC = GRUPO_HIST.NU_NUME_GRHI
        ON R_PLANTILLA_HIST.NU_NUME_PLHI_R = R_PLAN_CONC.NU_NUME_PLHI_RPC;