CREATE OR REPLACE VIEW V_SERV_NOPOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
    SELECT TB5.DE_PRAP_PAC || ' ' || 
          TB5.DE_SGAP_PAC || ' ' || 
          TB5.NO_NOMB_PAC || ' ' || 
          TB5.NO_SGNO_PAC PACIENTE  ,
        MOSTRARTIPODOCUMENTO(TB5.NU_TIPD_PAC) TIPODOC  ,
        TB5.NU_HIST_PAC NRODOC,
        TB6.NO_NOMB_REG REGIMEN,
        TB1.NU_NUME_HICL_NPSE NROHC,
        TB1.NU_NUME_HEVO_NPSE NROEV,
        TB1.NU_NUME_HPRO_NPSE NROORD  ,
        TB1.TX_RESHC_NPSE RESUMEN  ,
        TB1.CD_CODI_SER_NPSE CODSER  ,
        ( SELECT NO_NOMB_MED 
          FROM SERVICIOS 
          WHERE  CD_CODI_SER = TB1.CD_CODI_SER_NPSE ) NOMSER  ,
        TB1.NU_AGOTADO_NPSE AGOTADO  ,
        TB1.NU_RIESGO_NPSE RIESGO  ,
        TB1.NU_PYP_NPSE PYP  ,
        TB1.NU_DIAG_NPSE DIAG  ,
        TB1.NU_REHABI_NPSE REHABI  ,
        TB1.NU_REPITE_NPSE REPITE  ,
        TB1.TX_FREC_NPSE FRECUENCIA  ,
        TB1.NU_CANTI_NPSE CANT  ,
        TB1.TX_TIEMPO_NPSE ,
        TB1.TX_INDICA_NPSE ,
        TB7.NO_NOMB_MED NOMMED  ,
        TB7.NU_DOCU_MED DOCMED  ,
        TB7.DE_REGI_MED REGISTROMED  ,
        TB1.NU_AUTO_NPSE 
    FROM NOPOS_SERV TB1
    INNER JOIN HISTORIACLINICA TB2   
        ON TB2.NU_NUME_HICL = TB1.NU_NUME_HICL_NPSE
    INNER JOIN LABORATORIO TB3   
        ON TB3.NU_NUME_LABO = TB2.NU_NUME_LABO_HICL
    INNER JOIN MOVI_CARGOS TB4   
        ON TB4.NU_NUME_MOVI = TB3.NU_NUME_MOVI_LABO
    INNER JOIN PACIENTES TB5   
        ON TB5.NU_HIST_PAC = TB4.NU_HIST_PAC_MOVI
    INNER JOIN REGIMEN TB6   
        ON TB6.CD_CODI_REG = TB4.CD_REGIMEN_MOVI
    INNER JOIN MEDICOS TB7   
        ON TB7.CD_CODI_MED = TB1.CD_CODI_MEDI_NPSE;