CREATE OR REPLACE VIEW VISTA_ARTICULOS_POR_ACTIVIDAD_
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
	SELECT DISTINCT ACTIVIDAD_PYP.CD_CODI_ACTI ,
		ARTICULO.CD_CODI_ARTI ,
		ARTICULO.NO_NOMB_ARTI 
	FROM ARTICULO 
	INNER JOIN R_ARTI_ACTI    
		ON ARTICULO.CD_CODI_ARTI = R_ARTI_ACTI.CD_CODI_ARTI_RARA
	INNER JOIN ACTIVIDAD_PYP   
		ON R_ARTI_ACTI.CD_CODI_ACTI_RARA = ACTIVIDAD_PYP.CD_CODI_ACTI;