CREATE OR REPLACE VIEW VISTA_CONV_TIUS_RSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
	SELECT 
		TO_CHAR(CONVENIOS.ID_CODI_TIUS_CONV) || '-' || 
			TO_CHAR(R_RSA_TIUS.NU_CONS_RSA_RRT) R_TIUS_RSA  ,
		CONVENIOS.ID_CODI_TIUS_CONV,
		CONVENIOS.NU_NUME_CONV,
		CONVENIOS.CD_CODI_CONV,
		R_RSA_TIUS.NU_CONS_RSA_RRT,
		R_RSA_TIUS.NU_META_RRT,
		CONVENIOS.CD_NIT_EPS_CONV 
	FROM R_RSA_TIUS 
	INNER JOIN R_TIUS_TIUSF    
		ON R_RSA_TIUS.ID_CODI_TIUS_RRT = R_TIUS_TIUSF.TX_CODI_RTT
	INNER JOIN CONVENIOS    
		ON R_TIUS_TIUSF.TX_CODI_RTT = CONVENIOS.ID_CODI_TIUS_CONV;