CREATE OR REPLACE VIEW VISTA_SERVICIOS_POR_ACTIVIDAD_
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
	SELECT DISTINCT ACTIVIDAD_PYP.CD_CODI_ACTI ,
		SERVICIOS.CD_CODI_SER ,
		SERVICIOS.NO_NOMB_SER ,
		R_SER_ACTI.NU_CONS_RSA ,
		ACTIVIDAD_PYP.NO_NOMB_ACTI 
	FROM ACTIVIDAD_PYP 
	INNER JOIN R_SER_ACTI    
		ON ACTIVIDAD_PYP.CD_CODI_ACTI = R_SER_ACTI.CD_CODI_ACTI_RSA
	INNER JOIN SERVICIOS    
		ON R_SER_ACTI.CD_CODI_SER_RSA = SERVICIOS.CD_CODI_SER;
