CREATE OR REPLACE VIEW VISTA_MOVI_CARGOS_ELE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
    SELECT MOVI_CARGOS.NU_ESTA_MOVI,
        MOVI_CARGOS.NU_NUME_MOVI,
        MOVI_CARGOS.CD_CODI_LUAT_MOVI || '-' || 
          FORMULAS.CD_CODI_ESP_FORM || '-' || 
          TO_CHAR(MOVI_CARGOS.NU_TIAT_MOVI) || '-' || 
          '1' LUAT_ESP_TIAT_ESELE_MC,
        FORMULAS.VL_UNID_FORM * FORMULAS.CT_CANT_FORM VL_TOTAL_CONTA  ,
        FORMULAS.VL_UNID_FORM * FORMULAS.CT_CANT_FORM - FORMULAS.VL_COPA_FORM VL_RADI_CREDITO  ,
        MOVI_CARGOS.NU_NUME_CONV_MOVI,
        MOVI_CARGOS.FE_FECH_MOVI,
        ESPECIALIDADES.NO_NOMB_ESP 
    FROM MOVI_CARGOS 
    INNER JOIN FORMULAS    
        ON MOVI_CARGOS.NU_NUME_MOVI = FORMULAS.NU_NUME_MOVI_FORM
    INNER JOIN ESPECIALIDADES    
        ON FORMULAS.CD_CODI_ESP_FORM = ESPECIALIDADES.CD_CODI_ESP
    WHERE (MOVI_CARGOS.NU_ESTA_MOVI <> 2 );