CREATE OR REPLACE VIEW VISTA_FRECUENCIA_POR_ELEMENTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
      SELECT DISTINCT R_ARTI_GRPOB.NU_VALOR_RAG ,
            GRUPO_POBLA.DE_DESCRIP_GP ,
            R_ARTI_ACTI.CD_CODI_ARTI_RARA ,
            R_ARTI_ACTI.CD_CODI_ACTI_RARA ,
            CONDICION_POBLA.NU_EDAD_INI_CP ,
            CONDICION_POBLA.NU_EDAD_FIN_CP ,
            CONDICION_POBLA.CD_CODI_GP_CP ,
            CONDICION_POBLA.NU_SEXO_CP 
      FROM CONDICION_POBLA 
      INNER JOIN GRUPO_POBLA    
            ON CONDICION_POBLA.CD_CODI_GP_CP = GRUPO_POBLA.CD_CODI_GP
      INNER JOIN R_ARTI_GRPOB    
            ON GRUPO_POBLA.CD_CODI_GP = R_ARTI_GRPOB.CD_CODI_GP_RAG
      INNER JOIN R_ARTI_ACTI    
            ON R_ARTI_GRPOB.NU_AUTO_RARA_RAG = R_ARTI_ACTI.NU_AUTO_RARA;