CREATE OR REPLACE VIEW VREINGRESOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS 
    SELECT DISTINCT TO_CHAR(MOVI_CARGOS.FE_FECH_MOVI,'MM') Mes,
        PACIENTES.NU_TIPD_PAC,
        PACIENTES.NU_DOCU_PAC Documento ,
        REGISTRO.NU_NUME_REG 
    FROM MOVI_CARGOS 
    INNER JOIN REGISTRO    
        ON MOVI_CARGOS.NU_NUME_REG_MOVI = REGISTRO.NU_NUME_REG
    INNER JOIN PACIENTES    
        ON MOVI_CARGOS.NU_HIST_PAC_MOVI = PACIENTES.NU_HIST_PAC
    INNER JOIN CONVENIOS    
        ON CONVENIOS.NU_NUME_CONV = MOVI_CARGOS.NU_NUME_CONV_MOVI
    INNER JOIN EPS    
        ON CONVENIOS.CD_NIT_EPS_CONV = EPS.CD_NIT_EPS
    INNER JOIN LUGAR_ATENCION    
        ON LUGAR_ATENCION.CD_CODI_LUAT = MOVI_CARGOS.CD_CODI_LUAT_MOVI
    WHERE (MOVI_CARGOS.NU_ESTA_MOVI <> 2 )
        AND (MOVI_CARGOS.NU_NUME_FACO_MOVI <> 0 )
        AND (REGISTRO.NU_TIAT_REG = 2 )
        AND TO_CHAR(FE_FECH_MOVI,'MM') = 5
    GROUP BY TO_CHAR(MOVI_CARGOS.FE_FECH_MOVI,'MM'),
        PACIENTES.NU_TIPD_PAC,PACIENTES.NU_DOCU_PAC,
        REGISTRO.NU_NUME_REG;