CREATE OR REPLACE VIEW VW_ACTIVIDADESGRUPALESDETALLE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
AS 
    SELECT DISTINCT CONCEPTO_HIST.CD_CODI_COHI Actividad  ,
        PAU.NU_DOCU_PAC_PAU Documento_paciente  ,
        P.TX_NOMBRECOMPLETO_PAC Nombre_paciente  ,
        D.DE_DESC_DEPE Facultad  ,
        PA.TX_NOMB_PA Programa  ,
        HC.FE_FECH_HICL Fecha  
    FROM PLANTILLA_HIST 
    INNER JOIN R_PLAN_CONC    
        ON PLANTILLA_HIST.NU_NUME_PLHI = R_PLAN_CONC.NU_NUME_PLHI_RPC
    INNER JOIN CONCEPTO_HIST    
        ON R_PLAN_CONC.NU_NUME_COHI_RPC = CONCEPTO_HIST.NU_NUME_COHI
    INNER JOIN R_PLAN_GRUP    
        ON PLANTILLA_HIST.NU_NUME_PLHI = R_PLAN_GRUP.NU_NUME_PLHI_RPG
        AND R_PLAN_CONC.NU_NUME_GRHI_RPC = R_PLAN_GRUP.NU_NUME_GRHI_RPG
    INNER JOIN GRUPO_HIST    
        ON R_PLAN_GRUP.NU_NUME_GRHI_RPG = GRUPO_HIST.NU_NUME_GRHI
    INNER JOIN HISTORIACLINICA HC   
        ON PLANTILLA_HIST.NU_NUME_PLHI = HC.NU_NUME_PLHI_HICL
    INNER JOIN VALCONC_HIST1    
        ON CONCEPTO_HIST.NU_NUME_COHI = VALCONC_HIST1.NU_NUME_COHI_VAHI1
    INNER JOIN HIST_NUME HN   
        ON HC.NU_NUME_HICL = HN.NU_NUME_HICL_HINU
        AND HN.NU_INDI_HINU = R_PLAN_CONC.NU_INDI_RPC
    INNER JOIN PACIENTES_ANEXO_UNAL PAU   
        ON HN.NU_CD_PAC_HCNUM = PAU.NU_HIST_PAC_PAU
    INNER JOIN PACIENTES P   
        ON PAU.NU_DOCU_PAC_PAU = P.NU_DOCU_PAC
    INNER JOIN PROGRAMA_ACADEMICO PA   
        ON PAU.CD_CODI_PA_PAU = PA.CD_CODI_PA
    LEFT JOIN DEPENDENCIA D   
        ON PAU.CD_CODI_DEPE_PAU = D.CD_CODI_DEPE
    WHERE (HC.NU_NUME_PLHI_HICL IN (3041,3051))
        AND (CONCEPTO_HIST.NU_NUME_COHI IN ( 22920,22707,22701,22703,22704,22918,22700,22708,22699,22706,22702,22705 ))
        AND ( HN.NU_DESC_HINU = '1' )
    ORDER BY Actividad, Documento_paciente;