CREATE OR REPLACE VIEW ZETA_CAJEROS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
AS 
    SELECT USUARIOS.NO_NOMB_USUA,
        SUM(MOVI_CARGOS.VL_UNID_MOVI)  VALOR,
        FC.NU_NUME_ZETA_FACO,
        FC.NU_NUME_CAJA_FACO,
        ObtieneCantFac_CajaZ(FC.NU_NUME_ZETA_FACO, FC.NU_NUME_CAJA_FACO, FC.CAJERO, 1) CANT_FACOS ,
        ObtieneCantFac_CajaZ(FC.NU_NUME_ZETA_FACO, FC.NU_NUME_CAJA_FACO, FC.CAJERO, 0) CANT_ANULADAS  
    FROM FACTURAS_CONTADO FC
    JOIN MOVI_CARGOS    
        ON FC.NU_NUME_FACO = MOVI_CARGOS.NU_NUME_FACO_MOVI
    LEFT JOIN USUARIOS    
        ON USUARIOS.ID_IDEN_USUA = FC.CAJERO
    WHERE (FC.NU_NUME_FACO <> 0)
        AND (MOVI_CARGOS.NU_ESTA_MOVI <> 2)
        AND (FC.NU_CONSE_FACCAJA_FACO <> 0)
    GROUP BY USUARIOS.NO_NOMB_USUA,FC.NU_NUME_ZETA_FACO,
        FC.NU_NUME_CAJA_FACO,FC.CAJERO,
        FC.NU_CONE_ANUL_FACO;