CREATE OR REPLACE FUNCTION CalcularEdad
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	FECHA_NACIMIENTO DATE, 
	FECHA_COMPARA DATE, 
	ESUME VARCHAR2
)
RETURN NUMBER
IS
	DIFD NUMBER(10);
	DFIM NUMBER;
	EDAD NUMBER;
	UME NUMBER(10);

	DIA_NACIMIENTO VARCHAR2(10);
	MES_NACIMEINTO VARCHAR2(10);
	ANO_NACIMEINTO VARCHAR2(10);

	DIA_COMPARA VARCHAR2(10);
	MES_COMPARA VARCHAR2(10);
	ANO_COMPARA VARCHAR2(10);
	 
BEGIN
	DIFD := 0;
	DFIM := 0;

	SELECT  TO_CHAR(FECHA_NACIMIENTO,'DD') into DIA_NACIMIENTO FROM DUAL;
	SELECT  TO_CHAR(FECHA_NACIMIENTO,'MM') into MES_NACIMEINTO FROM DUAL;
	SELECT  TO_CHAR(FECHA_NACIMIENTO,'YYYY') into ANO_NACIMEINTO FROM DUAL;

	SELECT  TO_CHAR(FECHA_COMPARA,'DD') into DIA_COMPARA FROM DUAL;
	SELECT  TO_CHAR(FECHA_COMPARA,'MM') into MES_COMPARA FROM DUAL;
	SELECT  TO_CHAR(FECHA_COMPARA,'YYYY') into ANO_COMPARA FROM DUAL;

	IF(TO_NUMBER(DIA_COMPARA) < TO_NUMBER(DIA_NACIMIENTO)) THEN
		BEGIN
			DIFD := 1;
		END;
	END IF;

	IF(TO_NUMBER(MES_COMPARA) < TO_NUMBER(MES_NACIMEINTO)) THEN
		BEGIN
			DFIM := 1;
		END;
	END IF;

	IF(TO_NUMBER(ANO_COMPARA) = TO_NUMBER(ANO_NACIMEINTO)) THEN
		BEGIN
			IF(TO_NUMBER(MES_COMPARA) - TO_NUMBER(MES_NACIMEINTO) - DIFD > 0) THEN
				BEGIN
					EDAD := TO_NUMBER(MES_COMPARA) - TO_NUMBER(MES_NACIMEINTO) - DIFD;
					UME := 2;
				END;
			ELSE
				BEGIN
					EDAD := FECHA_COMPARA - FECHA_NACIMIENTO;
					UME := 3;
				END;
			END IF;
		END;
	ELSE
		BEGIN
			IF(TO_NUMBER(ANO_COMPARA) - TO_NUMBER(ANO_NACIMEINTO) - DFIM <= 0) THEN
				BEGIN
					EDAD:= (12 - TO_NUMBER(MES_NACIMEINTO)) + TO_NUMBER(MES_COMPARA) -1;
					UME := 2;
				END;
			ELSIF (TO_NUMBER(MES_COMPARA) = TO_NUMBER(MES_NACIMEINTO)) THEN
				BEGIN
					EDAD := ANO_COMPARA - ANO_NACIMEINTO - DIFD;
					UME := 1;

					IF(EDAD = 0) THEN
						BEGIN
							EDAD := (12 - TO_NUMBER(MES_NACIMEINTO)) + TO_NUMBER(MES_COMPARA) -1;
							UME := 2;
						END;
					END IF;
				END;
			ELSE
				BEGIN
					EDAD := TO_NUMBER(ANO_COMPARA) - TO_NUMBER(ANO_NACIMEINTO) - DFIM;
					UME := 1;
				END;
			END IF;
		END;
	END IF;

	IF(ESUME = 1) THEN
		RETURN UME;
	ELSE
		RETURN EDAD;
	END IF;
END;