CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_PLAN
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO_PLAN IN VARCHAR2 DEFAULT NULL ,
  v_DESCRIPCION_PLAN IN VARCHAR2 DEFAULT NULL 
)
AS

BEGIN

   UPDATE PLANES
      SET DE_DESC_PLAN = v_DESCRIPCION_PLAN
    WHERE  CD_CODI_PLAN = v_CODIGO_PLAN;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_EDITAR_PLAN;