CREATE OR REPLACE PROCEDURE H3i_SP_REPORTE_PROGRAMAS_SALUD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_FECHAINICIO IN DATE,
  v_FECHAFIN IN DATE,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT p.NU_HIST_PAC ,
             p.TX_NOMBRECOMPLETO_PAC ,
             pr.DE_NOMB_PRSA ,
             S.TX_NOMB_SUBP ,
             a.DE_NOMB_ACSA ,
             H.FE_MATRICULA_HIPR ,
             u.NO_NOMB_USUA 
        FROM HIST_PROG h
               JOIN PACIENTES p   ON h.NU_HIST_PAC_HIPR = p.NU_HIST_PAC
               JOIN ACTIVIDAD_SALUD_UNAL a   ON h.NU_CODI_ACSA_HIPR = a.NU_CODI_ACSA
               JOIN SUBPROGRAMAS_SALUD_UNAL S   ON h.NU_CODI_SUBP_HIPR = S.NU_CODI_SUBP
               JOIN PROGRAMA_SALUD_UNAL pr   ON h.NU_CODI_PRSA_HIPR = pr.NU_CODI_PRSA
               JOIN CONEXIONES c   ON h.NU_NUME_CONE_HIPR = c.NU_NUME_CONE
               JOIN USUARIOS U   ON c.USUARIO = u.ID_IDEN_USUA
       WHERE  TO_DATE(FE_MATRICULA_HIPR,TO_CHAR(200)) BETWEEN TO_DATE(v_FECHAINICIO,TO_CHAR(200)) AND TO_DATE(v_FECHAFIN,TO_CHAR(200))
        ORDER BY FE_MATRICULA_HIPR ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;