CREATE OR REPLACE PROCEDURE H3i_SP_LIST_OPC_PER_ENUM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_DE_DESC_OPC_ENUM_OPCI IN VARCHAR2,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT CD_CODI_OPCI ,
             DE_DESC_OPC_ENUM_OPCI 
        FROM OPCIONES 
       WHERE  DE_DESC_NOM_ENUM_OPCI = v_DE_DESC_OPC_ENUM_OPCI ;
   DBMS_OUTPUT.PUT_LINE('PROCESO H3i_SP_LIST_OPC_PER_ENUM CREADO');

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_LIST_OPC_PER_ENUM;