CREATE OR REPLACE PROCEDURE H3i_SP_INSCRIBIR_ESTS_GRUPO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_GRUP_EST_DOC_ESP_RGE IN NUMBER,
  v_CD_CODI_MED_DOC_RGE IN VARCHAR2
)
AS

BEGIN

   INSERT INTO R_GEDE_ESTD
     ( NU_GRUP_EST_DOC_ESP_RGE, CD_CODI_MED_DOC_RGE )
     VALUES ( v_NU_GRUP_EST_DOC_ESP_RGE, v_CD_CODI_MED_DOC_RGE );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_INSCRIBIR_ESTS_GRUPO;