CREATE OR REPLACE PROCEDURE H3i_SP_GUAR_PREPA_SERV_CITA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_PREP_SER IN NUMBER,
  v_CD_CODI_SER IN VARCHAR2,
  v_NU_HIST_PAC_CIT IN NUMBER,
  v_FE_FECH_CIT IN DATE,
  v_NU_NUME_MOVI_CIT IN NUMBER,
  v_NU_NUME_CONE_CIT IN NUMBER,
  v_NU_NUME_CONV_CIT IN NUMBER,
  v_CD_MEDI_ORDE_CIT IN VARCHAR2,
  v_NU_DURA_CIT IN NUMBER
)
AS
   v_NU_NUME_CIT NUMBER(10,0);

BEGIN

   SELECT *
     INTO v_NU_NUME_CIT
     FROM ( SELECT NU_NUME_CIT 
     FROM CITAS_MEDICAS 
    WHERE  CD_CODI_SER_CIT = v_CD_CODI_SER
             AND FE_FECH_CIT = v_FE_FECH_CIT
             AND NU_HIST_PAC_CIT = v_NU_HIST_PAC_CIT
             AND NU_NUME_MOVI_CIT = v_NU_NUME_MOVI_CIT
             AND NU_NUME_CONE_CIT = v_NU_NUME_CONE_CIT
             AND CD_MEDI_ORDE_CIT = v_CD_MEDI_ORDE_CIT
             AND NU_NUME_CONV_CIT = v_NU_NUME_CONV_CIT
             AND NU_DURA_CIT = v_NU_DURA_CIT
     ORDER BY NU_NUME_CIT DESC )
     WHERE ROWNUM <= 1;
   INSERT INTO SERVICIOS_PREPARACIONES_CITA
     ( CD_CODI_SER, CD_CODI_PREP_SER, NU_NUME_CIT )
     VALUES ( v_CD_CODI_SER, v_CD_CODI_PREP_SER, v_NU_NUME_CIT );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUAR_PREPA_SERV_CITA;