CREATE OR REPLACE PROCEDURE H3i_SP_LISTAR_ESTUDI_GRUPO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_AUTO_GRAP IN NUMBER,
  v_NU_AUTO_HOGR_RGE IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT GRUPO_ASIGNATURA_PERIODO.NU_AUTO_GRAP ,
             GRUPO_ASIGNATURA_PERIODO.NU_CODIGO_GRAP ,
             R_GRU_EST_2.CD_CODI_MED_RGE ,
             MEDICOS.NU_DOCU_MED ,
             MEDICOS.NO_NOMB_MED ,
             MEDICOS.NU_TIPO_MEDI 
        FROM ( GRUPO_ASIGNATURA_PERIODO GRUPO_ASIGNATURA_PERIODO
               JOIN R_GRU_EST_2 R_GRU_EST_2   ON ( GRUPO_ASIGNATURA_PERIODO.NU_AUTO_GRAP = R_GRU_EST_2.NU_AUTO_GRAP_RGE )
                ) 
               JOIN MEDICOS MEDICOS   ON ( MEDICOS.CD_CODI_MED = R_GRU_EST_2.CD_CODI_MED_RGE )
       WHERE  GRUPO_ASIGNATURA_PERIODO.NU_AUTO_GRAP = v_NU_AUTO_GRAP
                AND NU_AUTO_HOGR_RGE = v_NU_AUTO_HOGR_RGE ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_LISTAR_ESTUDI_GRUPO;