CREATE OR REPLACE PROCEDURE H3i_SP_OBTENR_ART_DEPENDENCIAS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_DEPE_DEAR VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 for
		SELECT CD_CODI_ARTI ,NO_NOMB_ARTI , DE_DESC_ARTI  
		FROM ARTICULO
		INNER JOIN  R_DEPE_ARTI 
		ON CD_ARTI_DEAR = CD_CODI_ARTI
		WHERE CD_DEPE_DEAR = V_CD_DEPE_DEAR;
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_OBTENR_ART_DEPENDENCIAS;