CREATE OR REPLACE PROCEDURE H3i_SP_CONSUL_CIERRE_REQUISITO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_COD_ESTUDIANTE IN PROCEDIMIENTO_ACADEMICO.CD_CODI_MED_PRA%TYPE,
	V_REQUISITO IN PROCEDIMIENTO_ACADEMICO.ID_IDEN_REQ_PRA%TYPE,
	V_RESULTADO OUT PROCEDIMIENTO_ACADEMICO.CERRADO%TYPE
)
AS 
BEGIN 
	SELECT CERRADO
	INTO V_RESULTADO
	FROM PROCEDIMIENTO_ACADEMICO
	WHERE CD_CODI_MED_PRA = V_COD_ESTUDIANTE AND ID_IDEN_REQ_PRA = V_REQUISITO;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CONSUL_CIERRE_REQUISITO;