CREATE OR REPLACE PROCEDURE H3i_SP_LIM_ESPECIALIDAD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_ID_ESP_LIM IN NUMBER,
  v_ESPECIALIDAD IN VARCHAR2,
  v_LIMITE IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT CD_CODI_ESP_ESPL 
        FROM ESPECIALIDAD_LIMITE 
       WHERE  CD_CODI_ESP_ESPL = v_ESPECIALIDAD ;
   IF SQL%ROWCOUNT <> 1 THEN
    INSERT INTO ESPECIALIDAD_LIMITE
     ( CD_CODI_ESP_ESPL, NU_NUME_MIN_ESPL )
     VALUES ( v_ESPECIALIDAD, v_LIMITE );
   ELSE
      UPDATE ESPECIALIDAD_LIMITE
         SET CD_CODI_ESP_ESPL = v_ESPECIALIDAD,
             NU_NUME_MIN_ESPL = v_LIMITE
       WHERE  CD_CODI_ESP_ESPL = v_ESPECIALIDAD;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_LIM_ESPECIALIDAD;