CREATE OR REPLACE PROCEDURE H3i_SP_CONSUL_BARRIOS_X_PAIS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_COD_PAIS IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR 
		SELECT * FROM BARRIO WHERE CD_CODI_PAIS_BAR = V_COD_PAIS;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CONSUL_BARRIOS_X_PAIS;