CREATE OR REPLACE PROCEDURE H3i_SP_CONSUL_ESPECIALIDADES2
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR
		SELECT CD_CODI_ESP, NO_NOMB_ESP, NU_INTCIT_ESP, TX_CODI_EQUI_ESP, NU_TIENE_ABONOS
		FROM ESPECIALIDADES
		ORDER BY NO_NOMB_ESP;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
        
END H3i_SP_CONSUL_ESPECIALIDADES2;