CREATE OR REPLACE PROCEDURE H3i_SP_ELIMI_ARTICULO_DEPE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO_PLAN IN VARCHAR2 DEFAULT NULL ,
  v_CODIGO_DEPE IN VARCHAR2 DEFAULT NULL ,
  v_CODIGO_ARTI IN VARCHAR2 DEFAULT NULL 
)
AS

BEGIN

   	DELETE R_ELE_PLAN
    WHERE  ABS(CD_CODI_PLAN_REP) = v_CODIGO_PLAN
             AND ABS(CD_CODI_CECO_REP) = v_CODIGO_DEPE
             AND CD_CODI_ELE_REP = v_CODIGO_ARTI;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_ELIMI_ARTICULO_DEPE;