CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_TIPO_DEPORTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN v_1 FOR
		SELECT NU_AUTO_NUME_TIPDEP, TX_DESC_TIPDEP, ESTADO_DEP
		FROM TIPO_DEPORTES;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CONSULTA_TIPO_DEPORTE;


