CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_VAR_INDIC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_INS_UP_VARINDIC OUT NUMBER,
  v_NU_COD_VAIN IN NUMBER,
  v_NO_SIGLA_VAIN IN VARCHAR2,
  v_NO_NOMBRE_VAIN IN VARCHAR2,
  v_NU_VALOR_VAIN IN NUMBER,
  v_BO_ESTADO_VAIN IN NUMBER
)
AS

BEGIN

   IF ( v_NU_COD_VAIN = 0 ) THEN
    
   BEGIN
      INSERT INTO VARIABLE_INDICADOR
        ( TX_CODIGO_VAIN, TX_DESCRIBE_VAIN, NU_OPERACION_VAIN, NU_ESTA_VAIN )
        VALUES ( v_NO_SIGLA_VAIN, v_NO_NOMBRE_VAIN, v_NU_VALOR_VAIN, v_BO_ESTADO_VAIN );

        SELECT NU_AUTO_VAIN 
        INTO v_CD_INS_UP_VARINDIC 
        FROM VARIABLE_INDICADOR
        WHERE NU_AUTO_VAIN = (SELECT MAX(NU_AUTO_VAIN) FROM VARIABLE_INDICADOR);
   
   END;
   ELSE
   
   BEGIN
      UPDATE VARIABLE_INDICADOR
         SET TX_CODIGO_VAIN = v_NO_SIGLA_VAIN,
             TX_DESCRIBE_VAIN = v_NO_NOMBRE_VAIN,
             NU_OPERACION_VAIN = v_NU_VALOR_VAIN,
             NU_ESTA_VAIN = v_BO_ESTADO_VAIN
       WHERE  NU_AUTO_VAIN = v_NU_COD_VAIN;
      v_CD_INS_UP_VARINDIC := v_NU_COD_VAIN ;
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUARDAR_VAR_INDIC;