CREATE OR REPLACE PROCEDURE H3i_SP_GUAR_PREPARAC_SERVI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_SER IN VARCHAR2,
  v_TX_DESC_PREPARACION IN VARCHAR2
)
AS

BEGIN

   INSERT INTO SERVICIOS_PREPARACION
     ( CD_CODI_SER, TX_DESC_PREPARACION )
     VALUES ( v_CD_CODI_SER, v_TX_DESC_PREPARACION );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUAR_PREPARAC_SERVI;