CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_SERVICIO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_ID_SERVICIO IN VARCHAR2,
  v_NOMBRE IN VARCHAR2,
  v_CODIGO IN VARCHAR2,
  v_TIPO_SERVICIO IN NUMBER,
  v_NIVEL IN NUMBER,
  v_GENERO IN NUMBER,
  v_EDAD_INICIAL IN NUMBER,
  v_EDAD_FINAL IN NUMBER,
  v_ESTADO IN NUMBER,
  v_TIPO_CODIGO IN NUMBER,
  v_OBSERVACION IN VARCHAR2,
  v_CODIGO_CONCEPTO IN VARCHAR2,
  v_CODIGO_TIPO_SERVICIO IN VARCHAR2,
  v_CITA IN VARCHAR2,
  v_DURACION IN NUMBER,
  v_GENERA_CITA IN VARCHAR2,
  v_PYP IN NUMBER,
  v_VACUNA IN NUMBER,
  v_CLASE IN NUMBER,
  v_EVOLUCION IN NUMBER,
  v_DIAGNOSTICO IN VARCHAR2,
  v_FINALIDAD IN VARCHAR2,
  v_SIN_COPAGO IN NUMBER,
  v_HONORARIO IN NUMBER,
  v_GRUPAL IN NUMBER,
  v_MAXIMO IN NUMBER,
  v_RIPS IN NUMBER,
  v_NOPOS IN NUMBER,
  v_NOFAC IN NUMBER,
  v_NORIPS IN NUMBER,
  v_REQUIERE IN NUMBER,
  v_ES_SERV_WEB_SER IN NUMBER,
  v_SERVODONT IN NUMBER DEFAULT 0 ,
  v_MEDIDA_TIEMPO IN NUMBER DEFAULT 1 ,
  v_MENSAJE_SERVICIO IN VARCHAR2
)
AS

BEGIN

   INSERT INTO SERVICIOS
     ( CD_CODI_SER, NO_NOMB_SER, CD_CODI_CUEN_SER, NU_OPCI_SER, NU_NIVE_SER, NU_APLI_SER, NU_EDIN_SER, NU_EDFI_SER, NU_ESTA_SER, NU_TITA_SER, DE_OBSE_SER, CD_CODI_COSE_SER, CD_CODI_TISE_SER, ID_CITA_SER, NU_MICO_SER, ID_GCIT_SER, NU_NUME_IND_SER, NU_VACU_SER, NU_CLAS_SER, NU_EVOL_SER, DX_PREDET, FINALIDAD, SIN_COPAGO, NU_HOME_SER, NU_ESGRUPAL_SER, NU_MAXPACGRU_SER, NU_AUTRIPS_SER, NU_NOPOS_SER, NU_NOFACT_SER, NU_NORIPS_SER, NU_REQAUT_SER, ES_SERV_WEB_SER, MEDIDA_TIEMPO, MENSAJE_SERVICIO )
     VALUES ( v_ID_SERVICIO, v_NOMBRE, v_CODIGO, v_TIPO_SERVICIO, v_NIVEL, v_GENERO, v_EDAD_INICIAL, v_EDAD_FINAL, v_ESTADO, v_TIPO_CODIGO, v_OBSERVACION, v_CODIGO_CONCEPTO, v_CODIGO_TIPO_SERVICIO, v_CITA, v_DURACION, v_GENERA_CITA, v_PYP, v_VACUNA, v_CLASE, v_EVOLUCION, v_DIAGNOSTICO, v_FINALIDAD, v_SIN_COPAGO, v_HONORARIO, v_GRUPAL, v_MAXIMO, v_RIPS, v_NOPOS, v_NOFAC, v_NORIPS, v_REQUIERE, v_ES_SERV_WEB_SER, v_MEDIDA_TIEMPO, v_MENSAJE_SERVICIO );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CREAR_SERVICIO;