CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_PERSONAL_APOYO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIGO EVENTO_PERSONAL_APOYO.CD_EVT_PERSONAL_APOYO%TYPE,
	V_DESCRIPCION EVENTO_PERSONAL_APOYO.DE_DESCRIP_PERSONAL_APOYO%TYPE,
	V_ESTADO EVENTO_PERSONAL_APOYO.ESTADO_PERSONAL_APOYO%TYPE
)
AS
BEGIN
	
	IF(V_CODIGO = 0) THEN
		BEGIN
			INSERT INTO EVENTO_PERSONAL_APOYO (DE_DESCRIP_PERSONAL_APOYO, ESTADO_PERSONAL_APOYO)
			VALUES (V_DESCRIPCION, V_ESTADO);
		END;
	ELSE
		BEGIN
			UPDATE EVENTO_PERSONAL_APOYO
			SET DE_DESCRIP_PERSONAL_APOYO = V_DESCRIPCION, 
				ESTADO_PERSONAL_APOYO = V_ESTADO
			WHERE CD_EVT_PERSONAL_APOYO = V_CODIGO;
		END;
	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUARDA_PERSONAL_APOYO;