CREATE OR REPLACE PROCEDURE H3i_GUARDA_SEGUIMIENTOGESTION
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_GESA_SEGE IN NUMBER,
  v_TX_DETA_SEGE IN VARCHAR2,
  v_NU_NUME_CONE_SEGE IN NUMBER
)
AS

BEGIN

   INSERT INTO SEGUIMIENTO_GESTION_SALUD
     ( NU_NUME_GESA_SEGE, TX_DETA_SEGE, NU_NUME_CONE_SEGE )
     VALUES ( v_NU_NUME_GESA_SEGE, v_TX_DETA_SEGE, v_NU_NUME_CONE_SEGE );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_GUARDA_SEGUIMIENTOGESTION;