CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_LUGAR_OCURRENCIA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  v_DESCRIPCION IN VARCHAR2,
  v_ESTADO IN NUMBER
)
AS

BEGIN

   IF ( v_CODIGO = 0 ) THEN
    
   BEGIN
      INSERT INTO EVENTO_LUGAR_OCURRENCIA
        ( DE_DESCRIP_LUGAR_OCURR, ESTADO_LUGAR_OCURR )
        VALUES ( v_DESCRIPCION, v_ESTADO );
   
   END;
   ELSE
   
   BEGIN
      UPDATE EVENTO_LUGAR_OCURRENCIA
         SET DE_DESCRIP_LUGAR_OCURR = v_DESCRIPCION,
             ESTADO_LUGAR_OCURR = v_ESTADO
       WHERE  CD_EVT_LUGAR_OCURR = v_CODIGO;
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUARDA_LUGAR_OCURRENCIA;