CREATE OR REPLACE PROCEDURE H3i_SP_CREA_PLAN_SERV_ESPEC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO_PLAN IN VARCHAR2 DEFAULT NULL ,
  v_CODIGO_ESPECIALIDAD IN VARCHAR2 DEFAULT NULL ,
  v_CODIGO_SERVICIO IN VARCHAR2 DEFAULT NULL 
)
AS

BEGIN

   INSERT INTO R_SER_PLAN
     ( CD_CODI_PLAN_RSP, CD_CODI_SER_RSP, CD_CODI_ESP_RSP )
     VALUES ( v_CODIGO_PLAN, v_CODIGO_SERVICIO, v_CODIGO_ESPECIALIDAD );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CREA_PLAN_SERV_ESPEC;