CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_ELEMENTOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_DEPE_DEAR IN VARCHAR2, 
    V_NU_NUME_CONV IN NUMBER, 
    V_INCLUIR_PAQUETE IN NUMBER, 
    V_NU_NUME_PAQU IN NUMBER, 
    V_FILTRAR_POR_NOMBRE IN NUMBER, 
    V_FILTRO IN VARCHAR2,
    V_NU_REGIMEN IN VARCHAR2,
    V_AMBITO_ATENCION IN NUMBER,
    CV_1 OUT SYS_REFCURSOR
)
AS
	TIPO_INTERFAZ VARCHAR2(32767);
BEGIN
	-- TABLA TEMPORAL 
	
	-- DETERMINAR EL TIPO DE INTERFAZ DE INVENTARIO QUE SE ESTA USANDO
	SELECT NVL(VL_VALO_CONT, 'HIMS')
	INTO TIPO_INTERFAZ
	FROM   CONTROL CON
	WHERE  CON.CD_CONC_CONT = 'TIPO_INTERFAZ_INVENTARIO';

	-- INVOCAR EL PROCEDIMIENTO ALMACENADO DE ACUERDO AL TIPO DE INTERFAZ DE 
	-- INVENTARIO
	IF TIPO_INTERFAZ = 'HIMS' THEN
	    BEGIN
	       H3i_SP_HIMS_CONSULTA_ELEMENTOS(V_CD_DEPE_DEAR, V_NU_NUME_CONV, V_INCLUIR_PAQUETE, V_NU_NUME_PAQU, V_FILTRAR_POR_NOMBRE,
	        					V_FILTRO, V_NU_REGIMEN, V_AMBITO_ATENCION);
	    END;
	END IF;


	OPEN CV_1 
		FOR SELECT * FROM RESULTADO; --	RESULTADO ES UNA TABLA TEMPORAL 

	COMMIT;	



EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);

END H3i_SP_CONSULTA_ELEMENTOS;
