CREATE OR REPLACE PROCEDURE H3i_SP_OBTENER_DEPENDEN_PLAN
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
		V_CODIGO_PLAN IN VARCHAR2,
		V_CODI_CECO OUT CENTRO_COSTO.CD_CODI_CECO%TYPE,
		V_NOMB_CECO OUT CENTRO_COSTO.NO_NOMB_CECO%TYPE,
		V_ESTADO_CEC OUT CENTRO_COSTO.ESTADO_CEC%TYPE
)
AS
BEGIN

	SELECT DISTINCT CD_CODI_CECO , NO_NOMB_CECO, ESTADO_CEC
	INTO V_CODI_CECO, V_NOMB_CECO, V_ESTADO_CEC
	FROM R_DEPE_ARTI 
	INNER JOIN CENTRO_COSTO 
	ON CD_CODI_CECO = ABS(CD_DEPE_DEAR);
	
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_OBTENER_DEPENDEN_PLAN;
