CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_ACTI_SALUD_UNAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_DE_NOMB_ACSA IN VARCHAR,
	V_DE_DESC_ACSA IN VARCHAR,
	V_NU_ESTA_ACSA IN NUMBER
)
AS
BEGIN
 
	INSERT INTO ACTIVIDAD_SALUD_UNAL (DE_NOMB_ACSA, DE_DESC_ACSA, NU_ESTA_ACSA)
	VALUES(V_DE_NOMB_ACSA, V_DE_DESC_ACSA, V_NU_ESTA_ACSA);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CREAR_ACTI_SALUD_UNAL; 