CREATE TABLE PUESTOS(
    CODPUESTO NUMBER NOT NULL,
    CODMES NUMBER,
    PRIMARY KEY(CODPUESTO)
);

ALTER TABLE PUESTOS
ADD CONSTRAINT FK_PUESTOS_INV00018 
FOREIGN KEY (CODMES)
REFERENCES INV00018(MESCOD);