CREATE TABLE SUBPEDIDO(
    SUBPEDNRO NUMBER NOT NULL,
    PEDNRO NUMBER,
   	CODPUESTO NUMBER,
    LINCODCATE CHAR(8),
    PRIMARY KEY(SUBPEDNRO)
);

ALTER TABLE SUBPEDIDO
ADD CONSTRAINT FK_SUBPEDIDO_IN00018 
FOREIGN KEY (PEDNRO)
REFERENCES VEN0104(PEDNRO);

ALTER TABLE SUBPEDIDO
ADD CONSTRAINT FK_SUBPEDIDO_IN00018 
FOREIGN KEY (CODPUESTO)
REFERENCES PUESTO(PEDNRO);

ALTER TABLE SUBPEDIDO
ADD CONSTRAINT FK_SUBPEDIDO_IN00018 
FOREIGN KEY (LINCODCATE)
REFERENCES INV0015(LINCODCATE);
