CREATE OR REPLACE FUNCTION FN_TIEMPO_TRASCURRIDO_PEDIDO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
(
	IN_MESA NUMBER,			  -- CODIGO DE LA MESA
	IN_HORA_PEDIDO VARCHAR2,  -- HORA EN LA QUE EL PEDIDO FUE REALIZADO
 	IN_TIEMPO_DEMORA NUMBER   -- NUMERO DE MINUTOS QUE DEMORA EL PEDIDO EN SER ENTREGADO A LA MESA
)
RETURN VARCHAR2
AS
	V_FECHA_PEDIDO VARCHAR2(10); -- FECHA CUANDO EL PEDIDO SE HIZO 
	V_FECHA_PEDIDO_COMPLETA VARCHAR2(30);
	V_FECHA_ENTREGAR VARCHAR2(30);	
	V_FECHA_ACTUAL VARCHAR2(30);
	V_MINUTOS_PASADOS NUMBER;
BEGIN
	-- CONSULTA LA FECHA DEL PEDIDO
	SELECT DISTINCT TO_CHAR(PEDFECE, 'DD/MM/YYYY')
	INTO V_FECHA_PEDIDO
	FROM VEN0104 A
	INNER JOIN INV00018 B
		ON A.MESCOD = B.MESCOD
		AND B.MESNUMREQ  = PEDNUMDOC
		OR B.MESNUMREQ2 = PEDNUMDOC
		OR B.MESNUMREQ3 = PEDNUMDOC
		OR B.MESNUMREQ4 = PEDNUMDOC
	WHERE A.MESCOD = IN_MESA;		

	-- FECHA Y HORA DEL PEDIDO
	V_FECHA_PEDIDO_COMPLETA := V_FECHA_PEDIDO||' '||IN_HORA_PEDIDO;
	-- FECHA Y HORA QUE SE DEBERIA ENTREGAR EL PEDIDO EN MESA
	V_FECHA_ENTREGAR := TO_CHAR(TO_DATE(V_FECHA_PEDIDO_COMPLETA, 'DD/MM/YYYY HH24:MI:SS') + IN_TIEMPO_DEMORA / 1440,'DD/MM/YYYY HH24:MI:SS');
	-- FECHA DEL SISTEMA
	V_FECHA_ACTUAL := TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS');

	-- SI LA FECHA DE ENTREGA ES MENOR A LA ACTUAL NO ESTA RETRASADA
	IF(TO_DATE(V_FECHA_ACTUAL,'DD/MM/YYYY HH24:MI:SS') < TO_DATE(V_FECHA_ENTREGAR,'DD/MM/YYYY HH24:MI:SS')) THEN 
		BEGIN
			RETURN 'SIN_RETRASO';
		END;
	ELSE
		BEGIN
			-- SE CALCULAS LOS MINUTOS DE RETRASO QUE TIENE EL PEDIDO
			SELECT (DIFERENCIA_HORAS * 60) + (DIFERENCIA_MINUTOS)
		    INTO V_MINUTOS_PASADOS
		    FROM (
			    SELECT FECHA_UNO,
			        FECHA_DOS,		        
			        TRUNC(MOD((FECHA_DOS - FECHA_UNO) * 24, 24)) DIFERENCIA_HORAS,
			        TRUNC(MOD((FECHA_DOS - FECHA_UNO) * (60 * 24), 60)) DIFERENCIA_MINUTOS,
			        TRUNC(MOD((FECHA_DOS - FECHA_UNO) * (60 * 60 * 24), 60)) DIFERENCIA_SEGUNDOS
			    FROM (
			        SELECT 
			            TO_DATE(V_FECHA_ENTREGAR, 'DD.MM.YYYY HH24:MI:SS') FECHA_UNO,
			            TO_DATE(V_FECHA_ACTUAL, 'DD.MM.YYYY HH24:MI:SS') FECHA_DOS
			        FROM DUAL
			        )
		    );

		    RETURN TO_CHAR(V_MINUTOS_PASADOS);
		END;
	END IF;


END;