CREATE OR REPLACE PROCEDURE H3i_SP_AUDI_INS_ADJUNT_DOCUM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_DOC_TIPO_CONSEC VARCHAR2,
	V_NOMBRE_ADJUNTO VARCHAR2
)
AS
	V_EXISTE NUMBER;
BEGIN
	SELECT COUNT(*) 
	INTO V_EXISTE
	FROM AUDITAR_DOCUS_ADJUNTOS 
	WHERE DOCUMENTO_TIPO_CONSEC_ADA = V_DOC_TIPO_CONSEC 
		AND NOMBRE_ADJUNTO = V_NOMBRE_ADJUNTO;

	IF (V_EXISTE <= 0) THEN

		BEGIN
			INSERT INTO AUDITAR_DOCUS_ADJUNTOS (
				DOCUMENTO_TIPO_CONSEC_ADA, NOMBRE_ADJUNTO)
			VALUES (
				V_DOC_TIPO_CONSEC, V_NOMBRE_ADJUNTO);
		END;

	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;