CREATE OR REPLACE PROCEDURE H3i_SP_ACT_ESTADO_RESULTADOS1
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_RESU IN VARCHAR2,
  v_NU_ESTA_RESU IN NUMBER
)
AS

BEGIN

	UPDATE RESULTADOS1
	SET NU_ESTA_RESU = v_NU_ESTA_RESU
	WHERE  NU_NUME_RESU = v_NU_NUME_RESU;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;