CREATE OR REPLACE PROCEDURE H3i_SP_CREA_RIPS_PROCED
(
    v_NU_FACTURA IN VARCHAR2,
    v_PRESTADOR IN VARCHAR2,
    v_TIPO_IDEN IN VARCHAR2,
    v_NU_IDEN IN VARCHAR2,
    v_FECHA_PROCED IN DATE,
    v_AUTORIZACION IN VARCHAR2,
    v_PROCEDIMIENTO IN VARCHAR2,
    v_AMBITO IN VARCHAR2,
    v_FINALIDAD IN VARCHAR2,
    v_PERSONAL IN VARCHAR2,
    v_DX IN VARCHAR2,
    v_DX_RELACIONADO IN VARCHAR2,
    v_COMPLEJIDAD IN VARCHAR2,
    v_FORMULARIO IN VARCHAR2,
    v_VALOR_PROCED IN NUMBER
)
AS

BEGIN

    INSERT INTO RIPS_PROCEDIMIENTO( 
        NU_FACT_AP, CD_PRES_AP, 
        TI_IDEN_US_AP, NU_IDEN_US_AP, 
        FE_PROC_AP, NU_AUTO_AP, 
        CD_PROC_AP, CD_AMBI_AP, 
        CD_FINA_AP, CD_PERS_AP, 
        CD_DIAG_AP, CD_DIAG_REL_AP, 
        CD_COMPL_AP, CD_FORM_AP, 
        VL_PROC_AP )
    VALUES ( v_NU_FACTURA, v_PRESTADOR, 
        v_TIPO_IDEN, v_NU_IDEN, 
        v_FECHA_PROCED, v_AUTORIZACION, 
        v_PROCEDIMIENTO, v_AMBITO, 
        v_FINALIDAD, v_PERSONAL, 
        v_DX, v_DX_RELACIONADO, 
        v_COMPLEJIDAD, v_FORMULARIO, 
        v_VALOR_PROCED );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;