CREATE OR REPLACE PROCEDURE H3i_SP_AUDIT_INS_CATAL_MEDICA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_CODIGO_GENERICO_CCM IN VARCHAR2,
    v_NOMBRE_GENERICO_CCM IN VARCHAR2,
    v_CODIGO_LABORATORIO_CCM IN FLOAT,
    v_NOMBRE_LABORATORIO_CCM IN VARCHAR2,
    v_CODIGO_REFERENCIA_CCM IN VARCHAR2,
    v_NOMBRE_REFERENCIA_CCM IN VARCHAR2,
    v_REFERENCIA_CUM_CCM IN VARCHAR2,
    v_REFERENCIA_INVIMA_CCM IN VARCHAR2,
    v_REFERENCIA_CONTROLADA_CCM IN VARCHAR2,
    v_REFERENCIA_REGULADA_CCM IN VARCHAR2,
    v_REFERENCIA_ALTO_COSTO_CCM IN VARCHAR2,
    v_REFERENCIA_CADENA_FRIO_CCM IN VARCHAR2,
    v_REFERENCIA_CODIGO_BARRAS_CCM IN VARCHAR2,
    v_REFERENCIA_CONCENTRACION_CCM IN VARCHAR2,
    v_REFERENCIA_LINEA_CODIGO_CCM IN VARCHAR2,
    v_REFERENCIA_LINEA_NOMBRE_CCM IN VARCHAR2,
    v_REFERENC_PORCENTAJE_IVA IN VARCHAR2,
    v_PRESENTACION IN VARCHAR2,
    v_CODIGO_INTERNO IN VARCHAR2,
    v_CODIGO_HOMIC IN VARCHAR2,
    v_VIA_ADMINISTRA IN VARCHAR2,
    v_UNIDAD_MEDIDA IN VARCHAR2,
    v_ES_CTC_TUTELA IN NUMBER,
    v_TIENE_IVA IN NUMBER,
    v_PRECIO_DRO_SERV IN NUMBER,
    v_PRECIO_INFLACION IN NUMBER
)
AS
    v_temp NUMBER(1, 0) := 0;

BEGIN

    BEGIN
        SELECT 1 
        INTO v_temp
        FROM DUAL
        WHERE EXISTS( SELECT COD_CATAL_MEDICAM 
                      FROM AUDITAR_CATALOGO_MEDICAMENTO 
                      WHERE  CODIGO_INTERNO_CCM = v_CODIGO_INTERNO );
    EXCEPTION
      WHEN OTHERS THEN
         NULL;
    END;
      
    IF v_temp = 1 THEN
    
        BEGIN
            UPDATE AUDITAR_CATALOGO_MEDICAMENTO
            SET NOMBRE_GENERICO_CCM = v_NOMBRE_GENERICO_CCM,
                CODIGO_LABORATORIO_CCM = v_CODIGO_LABORATORIO_CCM,
                NOMBRE_LABORATORIO_CCM = v_NOMBRE_LABORATORIO_CCM,
                NOMBRE_REFERENCIA_CCM = v_NOMBRE_REFERENCIA_CCM,
                REFERENCIA_CUM_CCM = v_REFERENCIA_CUM_CCM,
                REFERENCIA_INVIMA_CCM = v_REFERENCIA_INVIMA_CCM,
                REFERENCIA_CONTROLADA_CCM = v_REFERENCIA_CONTROLADA_CCM,
                REFERENCIA_REGULADA_CCM = v_REFERENCIA_REGULADA_CCM,
                REFERENCIA_ALTO_COSTO_CCM = v_REFERENCIA_ALTO_COSTO_CCM,
                REFERENCIA_CADENA_FRIO_CCM = v_REFERENCIA_CADENA_FRIO_CCM,
                REFERENCIA_CODIGO_BARRAS_CCM = v_REFERENCIA_CODIGO_BARRAS_CCM,
                REFERENCIA_CONCENTRACION_CCM = v_REFERENCIA_CONCENTRACION_CCM,
                REFERENCIA_LINEA_CODIGO_CCM = v_REFERENCIA_LINEA_CODIGO_CCM,
                REFERENCIA_LINEA_NOMBRE_CCM = v_REFERENCIA_LINEA_NOMBRE_CCM,
                REFERENC_PORCENTAJE_IVA = v_REFERENC_PORCENTAJE_IVA,
                PRESENTACION_CCM = v_PRESENTACION,
                CODIGO_INTERNO_CCM = v_CODIGO_INTERNO,
                CODIGO_HOMIC_CCM = v_CODIGO_HOMIC,
                VIA_ADMINISTRACION_CCM = v_VIA_ADMINISTRA,
                UNIDAD_MEDIDA_CCM = v_UNIDAD_MEDIDA,
                ES_CTC_TUTELA_CCM = v_ES_CTC_TUTELA,
                TIENE_IVA_CCM = v_TIENE_IVA
            WHERE  CODIGO_INTERNO_CCM = v_CODIGO_INTERNO;
        END;

    ELSE
   
        BEGIN
            INSERT INTO AUDITAR_CATALOGO_MEDICAMENTO( 
                CODIGO_GENERICO_CCM, NOMBRE_GENERICO_CCM, 
                CODIGO_LABORATORIO_CCM, NOMBRE_LABORATORIO_CCM, 
                CODIGO_REFERENCIA_CCM, NOMBRE_REFERENCIA_CCM, 
                REFERENCIA_CUM_CCM, REFERENCIA_INVIMA_CCM, 
                REFERENCIA_CONTROLADA_CCM, REFERENCIA_REGULADA_CCM, 
                REFERENCIA_ALTO_COSTO_CCM, REFERENCIA_CADENA_FRIO_CCM, 
                REFERENCIA_CODIGO_BARRAS_CCM, REFERENCIA_CONCENTRACION_CCM, 
                REFERENCIA_LINEA_CODIGO_CCM, REFERENCIA_LINEA_NOMBRE_CCM, 
                REFERENC_PORCENTAJE_IVA, PRESENTACION_CCM, 
                CODIGO_INTERNO_CCM, CODIGO_HOMIC_CCM, 
                VIA_ADMINISTRACION_CCM, UNIDAD_MEDIDA_CCM, 
                ES_CTC_TUTELA_CCM, TIENE_IVA_CCM )
            VALUES ( 
                v_CODIGO_GENERICO_CCM, v_NOMBRE_GENERICO_CCM, 
                v_CODIGO_LABORATORIO_CCM, v_NOMBRE_LABORATORIO_CCM, 
                v_CODIGO_REFERENCIA_CCM, v_NOMBRE_REFERENCIA_CCM, 
                v_REFERENCIA_CUM_CCM, v_REFERENCIA_INVIMA_CCM, 
                v_REFERENCIA_CONTROLADA_CCM, v_REFERENCIA_REGULADA_CCM, 
                v_REFERENCIA_ALTO_COSTO_CCM, v_REFERENCIA_CADENA_FRIO_CCM, 
                v_REFERENCIA_CODIGO_BARRAS_CCM, v_REFERENCIA_CONCENTRACION_CCM, 
                v_REFERENCIA_LINEA_CODIGO_CCM, v_REFERENCIA_LINEA_NOMBRE_CCM, 
                v_REFERENC_PORCENTAJE_IVA, v_PRESENTACION, 
                v_CODIGO_INTERNO, v_CODIGO_HOMIC, 
                v_VIA_ADMINISTRA, v_UNIDAD_MEDIDA, 
                v_ES_CTC_TUTELA, v_TIENE_IVA );   
        END;
    END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;