CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_CONVENIO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_IDCONVENIO IN NUMBER DEFAULT NULL ,
  v_NIT_EPS IN VARCHAR2,
  v_CD_NOMB_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_CODI_CONV IN VARCHAR2 DEFAULT NULL ,
  v_FE_INIC_CONV IN DATE DEFAULT NULL ,
  v_FE_FINA_CONV IN DATE DEFAULT NULL ,
  v_CD_CODI_TARB_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_CODI_TARI_CONV IN VARCHAR2 DEFAULT NULL ,
  v_VL_CUPO_CONV IN FLOAT DEFAULT 0 ,
  v_VL_SALD_CONV IN FLOAT DEFAULT 0 ,
  v_NU_COBR_CONV IN NUMBER DEFAULT NULL ,
  v_NU_FORM_CONV IN NUMBER DEFAULT NULL ,
  v_PR_COBR_CONV IN FLOAT DEFAULT 0 ,
  v_VL_CUIN_CONV IN FLOAT DEFAULT 0 ,
  v_CD_CODI_PLAN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_NU_VIGE_CONV IN NUMBER DEFAULT NULL ,
  v_NU_CAPI_CONV IN NUMBER DEFAULT NULL ,
  v_CD_CXC_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_COPA_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_PR_LABO_CONV IN FLOAT DEFAULT 0 ,
  v_NU_ALTE_CONV IN NUMBER DEFAULT NULL ,
  v_PR_LABHOS_CONV IN FLOAT DEFAULT 0 ,
  v_CT_LABPAQ_CONV IN NUMBER DEFAULT NULL ,
  v_CT_ELEPAQ_CONV IN NUMBER DEFAULT NULL ,
  v_NU_FOPA_CONV IN NUMBER DEFAULT NULL ,
  v_CD_RECA_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_SUBS_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_DESC_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_GANA_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_PERD_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_NU_COBR_ELE_CONV IN NUMBER DEFAULT NULL ,
  v_NU_FORM_ELE_CONV IN NUMBER DEFAULT NULL ,
  v_PR_COBR_ELE_CONV IN FLOAT DEFAULT 0 ,
  v_NU_COPRICONS_CONV IN NUMBER DEFAULT NULL ,
  v_NU_REG_CONV IN NUMBER DEFAULT NULL ,
  v_NU_INDPYP_CONV IN NUMBER DEFAULT NULL ,
  v_CD_CXCP_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_ID_CODI_TIUS_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_ANTI_CUEN_CONV IN VARCHAR2 DEFAULT NULL ,
  v_VL_MULT_CONV IN FLOAT DEFAULT 0 ,
  v_NU_COGN_CONV IN NUMBER DEFAULT NULL ,
  v_NU_SOAT_CONV IN NUMBER DEFAULT NULL ,
  v_NU_TIEM_VENC_CONV IN NUMBER DEFAULT NULL ,
  v_NU_RC_CONV IN NUMBER DEFAULT NULL ,
  v_NU_PORC_COPA IN NUMBER DEFAULT 0 ,
  v_NU_ABS_CONV IN NUMBER DEFAULT NULL ,
  v_NU_FORMLST_CONV IN NUMBER DEFAULT NULL ,
  v_NU_AUTO_MEDNOPOS_CONV IN NUMBER DEFAULT NULL ,
  v_NU_AUTO_MEDPOS_CONV IN NUMBER DEFAULT NULL ,
  v_NU_PORADS_CONV IN VARCHAR2 DEFAULT NULL ,
  v_CD_PORADS_CONV IN VARCHAR2 DEFAULT NULL 
)
AS
    v_temp NUMBER(1, 0) := 0;

BEGIN

    BEGIN
        SELECT 1 INTO v_temp
        FROM DUAL
        WHERE ( SELECT COUNT(CD_CODI_CONV)  
                FROM CONVENIOS 
                WHERE  NU_NUME_CONV = v_IDCONVENIO ) = 0;
    EXCEPTION
        WHEN OTHERS THEN
          NULL;
    END;
      
    IF v_temp = 1 THEN
    
        BEGIN
            INSERT INTO CONVENIOS( 
                CD_CODI_CONV, CD_NIT_EPS_CONV, 
                VL_CUPO_CONV, VL_SALD_CONV, 
                NU_COBR_CONV, NU_FORM_CONV, 
                PR_COBR_CONV, CD_CODI_TARB_CONV, 
                FE_INIC_CONV, FE_FINA_CONV, 
                VL_CUIN_CONV, CD_CODI_PLAN_CONV, 
                NU_VIGE_CONV, NU_CAPI_CONV, 
                CD_CXC_CUEN_CONV, CD_COPA_CUEN_CONV, 
                PR_LABO_CONV, CD_CODI_TARI_CONV, 
                NU_ALTE_CONV, PR_LABHOS_CONV, 
                CT_LABPAQ_CONV, CT_ELEPAQ_CONV, 
                NU_FOPA_CONV, CD_RECA_CUEN_CONV, 
                CD_SUBS_CUEN_CONV, CD_DESC_CUEN_CONV, 
                CD_GANA_CUEN_CONV, CD_PERD_CUEN_CONV, 
                NU_COBR_ELE_CONV, NU_FORM_ELE_CONV, 
                PR_COBR_ELE_CONV, NU_COPRICONS_CONV, 
                NU_REG_CONV, NU_INDPYP_CONV, 
                CD_CXCP_CUEN_CONV, ID_CODI_TIUS_CONV, 
                CD_ANTI_CUEN_CONV, VL_MULT_CONV, 
                NU_COGN_CONV, NU_SOAT_CONV, 
                NU_TIEM_VENC_CONV, NU_RC_CONV, 
                NU_PORC_COPA, CD_NOMB_CONV, 
                NU_ABS_CONV, NU_FORMLST_CONV, 
                NU_AUTO_MEDPOS_CONV, NU_AUTO_MEDNOPOS_CONV, 
                NU_PORADS_CONV, CD_PORADS_CONV)
            VALUES ( 
                v_CD_CODI_CONV, v_NIT_EPS, 
                v_VL_CUPO_CONV, v_VL_SALD_CONV, 
                v_NU_COBR_CONV, v_NU_FORM_CONV, 
                v_PR_COBR_CONV, v_CD_CODI_TARB_CONV, 
                TO_DATE(v_FE_INIC_CONV,'dd/mm/yyyy'), 
                TO_DATE(v_FE_FINA_CONV,'dd/mm/yyyy'), 
                v_VL_CUIN_CONV, v_CD_CODI_PLAN_CONV, 
                v_NU_VIGE_CONV, v_NU_CAPI_CONV, 
                v_CD_CXC_CUEN_CONV, v_CD_COPA_CUEN_CONV, 
                v_PR_LABO_CONV, v_CD_CODI_TARI_CONV, 
                v_NU_ALTE_CONV, v_PR_LABHOS_CONV, 
                v_CT_LABPAQ_CONV, v_CT_ELEPAQ_CONV, 
                v_NU_FOPA_CONV, v_CD_RECA_CUEN_CONV, 
                v_CD_SUBS_CUEN_CONV, v_CD_DESC_CUEN_CONV,
                v_CD_GANA_CUEN_CONV, v_CD_PERD_CUEN_CONV, 
                v_NU_COBR_ELE_CONV, v_NU_FORM_ELE_CONV, 
                v_PR_COBR_ELE_CONV, v_NU_COPRICONS_CONV, 
                v_NU_REG_CONV, v_NU_INDPYP_CONV, 
                v_CD_CXCP_CUEN_CONV, v_ID_CODI_TIUS_CONV, 
                v_CD_ANTI_CUEN_CONV, v_VL_MULT_CONV, 
                v_NU_COGN_CONV, v_NU_SOAT_CONV, 
                v_NU_TIEM_VENC_CONV, v_NU_RC_CONV, 
                v_NU_PORC_COPA, v_CD_NOMB_CONV, 
                v_NU_ABS_CONV, v_NU_FORMLST_CONV, 
                v_NU_AUTO_MEDNOPOS_CONV, v_NU_AUTO_MEDPOS_CONV, 
                v_NU_PORADS_CONV, v_CD_PORADS_CONV);   
        END;

    ELSE
   
        BEGIN
            UPDATE CONVENIOS
            SET CD_CODI_CONV = v_CD_CODI_CONV,
                CD_NIT_EPS_CONV = v_NIT_EPS,
                VL_CUPO_CONV = v_VL_CUPO_CONV,
                VL_SALD_CONV = v_VL_SALD_CONV,
                NU_COBR_CONV = v_NU_COBR_CONV,
                NU_FORM_CONV = v_NU_FORM_CONV,
                PR_COBR_CONV = v_PR_COBR_CONV,
                CD_CODI_TARB_CONV = v_CD_CODI_TARB_CONV,
                FE_INIC_CONV = v_FE_INIC_CONV,
                FE_FINA_CONV = v_FE_FINA_CONV,
                VL_CUIN_CONV = v_VL_CUIN_CONV,
                CD_CODI_PLAN_CONV = v_CD_CODI_PLAN_CONV,
                NU_VIGE_CONV = v_NU_VIGE_CONV,
                NU_CAPI_CONV = v_NU_CAPI_CONV,
                CD_CXC_CUEN_CONV = v_CD_CXC_CUEN_CONV,
                CD_COPA_CUEN_CONV = v_CD_COPA_CUEN_CONV,
                PR_LABO_CONV = v_PR_LABO_CONV,
                CD_CODI_TARI_CONV = v_CD_CODI_TARI_CONV,
                NU_ALTE_CONV = v_NU_ALTE_CONV,
                PR_LABHOS_CONV = v_PR_LABHOS_CONV,
                CT_LABPAQ_CONV = v_CT_LABPAQ_CONV,
                CT_ELEPAQ_CONV = v_CT_ELEPAQ_CONV,
                NU_FOPA_CONV = v_NU_FOPA_CONV,
                CD_RECA_CUEN_CONV = v_CD_RECA_CUEN_CONV,
                CD_SUBS_CUEN_CONV = v_CD_SUBS_CUEN_CONV,
                CD_DESC_CUEN_CONV = v_CD_DESC_CUEN_CONV,
                CD_GANA_CUEN_CONV = v_CD_GANA_CUEN_CONV,
                CD_PERD_CUEN_CONV = v_CD_PERD_CUEN_CONV,
                NU_COBR_ELE_CONV = v_NU_COBR_ELE_CONV,
                NU_FORM_ELE_CONV = v_NU_FORM_ELE_CONV,
                PR_COBR_ELE_CONV = v_PR_COBR_ELE_CONV,
                NU_COPRICONS_CONV = v_NU_COPRICONS_CONV,
                NU_REG_CONV = v_NU_REG_CONV,
                NU_INDPYP_CONV = v_NU_INDPYP_CONV,
                CD_CXCP_CUEN_CONV = v_CD_CXCP_CUEN_CONV,
                ID_CODI_TIUS_CONV = v_ID_CODI_TIUS_CONV,
                CD_ANTI_CUEN_CONV = v_CD_ANTI_CUEN_CONV,
                VL_MULT_CONV = v_VL_MULT_CONV,
                NU_COGN_CONV = v_NU_COGN_CONV,
                NU_SOAT_CONV = v_NU_SOAT_CONV,
                NU_TIEM_VENC_CONV = v_NU_TIEM_VENC_CONV,
                NU_RC_CONV = v_NU_RC_CONV,
                NU_PORC_COPA = v_NU_PORC_COPA,
                CD_NOMB_CONV = v_CD_NOMB_CONV,
                NU_ABS_CONV = v_NU_ABS_CONV,
                NU_FORMLST_CONV = v_NU_FORMLST_CONV,
                NU_AUTO_MEDPOS_CONV = v_NU_AUTO_MEDNOPOS_CONV,
                NU_AUTO_MEDNOPOS_CONV = v_NU_AUTO_MEDPOS_CONV,
                NU_PORADS_CONV = v_NU_PORADS_CONV,
                CD_PORADS_CONV = v_CD_PORADS_CONV
            WHERE  NU_NUME_CONV = v_IDCONVENIO;   
        END;
        
    END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;