CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_SOL_CIR -- PROCEDIMIENTO ALMACENADO QUE PERMITE GUARDAR UN REGISTRO PARA SOLICITUD 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_DUR_CIR IN DATE,
  v_DES_CIR IN VARCHAR2,
  v_PRIO_CIR IN NUMBER,
  v_CD_CODI_MED IN VARCHAR2,
  v_FECH_REG IN DATE,
  v_ESTA_REG IN NUMBER,
  v_NU_HIST_PAC IN VARCHAR2,
  v_CD_CODI_CONV IN NUMBER,
  v_CD_NIT_AFI IN VARCHAR2,
  v_CD_TIP_ATEN IN NUMBER,
  v_ID_REGISTRO OUT NUMBER
)
AS

BEGIN

    INSERT INTO SOLI_CIR( 
        DUR_CIR, DES_CIR, 
        PRIO_CIR, CD_CODI_MED, 
        FECH_REG, ESTA_REG, 
        NU_HIST_PAC, CD_CODI_CONV, 
        CD_NIT_AFI, CD_TIP_ATEN )
    VALUES ( 
        v_DUR_CIR, v_DES_CIR, 
        v_PRIO_CIR, v_CD_CODI_MED, 
        v_FECH_REG, v_ESTA_REG, 
        v_NU_HIST_PAC, v_CD_CODI_CONV, 
        v_CD_NIT_AFI, v_CD_TIP_ATEN );

    SELECT NU_NUME_SOL_CIR 
    INTO v_ID_REGISTRO 
    fROM SOLI_CIR
    WHERE NU_NUME_SOL_CIR = (SELECT MAX(NU_NUME_SOL_CIR) FROM SOLI_CIR);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;