CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_ADSCRITO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_ID IN NUMBER,
    v_CODIGO IN VARCHAR2,
    v_NOMBRE IN VARCHAR2,
    v_DIRECCION IN VARCHAR2,
    v_TELEFONO IN VARCHAR2,
    v_ESTADO IN NUMBER,
    v_DEPARTAMENTO IN VARCHAR2,
    v_MUNICIPIO IN VARCHAR2,
    v_TIPO IN NUMBER,
    v_CALI IN NUMBER,
    v_TIPD IN NUMBER,
    v_DOCUMENTO IN VARCHAR2,
    v_LABO_DENTAL IN NUMBER
)
AS

BEGIN

    UPDATE ADSCRITOS
    SET CD_CODI_ADSC = v_CODIGO,
        DE_NOMB_ADSC = v_NOMBRE,
        DE_DIREC_ADSC = v_DIRECCION,
        NU_TELE_ADSC = v_TELEFONO,
        NU_ESTA_ADSC = v_ESTADO,
        CD_CODI_DPTO_ADSC = v_DEPARTAMENTO,
        CD_CODI_MUNI_ADSC = v_MUNICIPIO,
        NU_TIPCONT_ADSC = v_TIPO,
        NU_CALI_ADSC = v_CALI,
        NU_TIPD_ADSC = v_TIPD,
        CD_CODIGO_ADSC = v_DOCUMENTO,
        NU_LABO_DENTAL = v_LABO_DENTAL
    WHERE  NU_CONSE_ADSC = v_ID;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;