CREATE OR REPLACE PROCEDURE H3i_SP_OBTNR_CONS_ODONTOBASICO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_CD_NU_LABO IN NUMBER,
	V_CD_NU_HCLI IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
 )
	
AS
BEGIN
	OPEN CV_1 FOR 
		SELECT CD_CONS_ODO,
			NU_HCLI_PAC_ODO,
			FE_CONS_ODO,
			CD_NUM_LABO,
			VAL_PRESEN_COP,
			VAL_SANOS_COP,
			VAL_CARIAD_COP,
			VAL_OBTUR_COP,
			VAL_PERDID_COP,
			VAL_COP,
			VAL_PRESEN_CEO,
			VAL_SANOS_CEO,
			VAL_CARIAD_CEO,
			VAL_OBTUR_CEO,
			VAL_PERDID_CEO,
			VAL_CEO
		FROM HIST_ODO_CONSULTAS
		WHERE NU_HCLI_PAC_ODO = V_CD_NU_HCLI 
			AND CD_NUM_LABO = V_CD_NU_LABO;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;