CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_REL_CIR_PROC -- PROCEDIMIENTO ALMACENADO QUE PERMITE GUARDAR UN REGISTRO DE RELACION DE CIRUGIAS Y PROCEDIMIENTOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_CIR IN NUMBER,
  v_CD_CODI_PRO IN VARCHAR2,
  v_CD_CODI_ESP IN VARCHAR2,
  v_NU_REALIZA_RSC IN NUMBER
)
AS

BEGIN

  	INSERT INTO R_SER_CIR( 
  		CD_CODI_CIR, CD_CODI_PRO, CD_CODI_ESP, NU_REALIZA_RSC )
    VALUES( 
    	v_CD_CODI_CIR, v_CD_CODI_PRO, v_CD_CODI_ESP, v_NU_REALIZA_RSC );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;