CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_R_ART_SER
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_ARTI_RAS IN VARCHAR2,
  v_CD_CODI_SER_RAS IN VARCHAR2,
  v_NU_CANTIDAD_RAS IN NUMBER,
  v_TX_OB_R_ART_SER IN VARCHAR2
)
AS

BEGIN

   	INSERT INTO R_ART_SER(
   		CD_CODI_ARTI_RAS, CD_CODI_SER_RAS, CD_CODI_MED_RAS, NU_CANTIDAD_RAS, TX_OB_R_ART_SER )
    VALUES( 
    	v_CD_CODI_ARTI_RAS, v_CD_CODI_SER_RAS, '<<SINESPECIFICAR>>', v_NU_CANTIDAD_RAS, v_TX_OB_R_ART_SER);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;