CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_SERVICIO_RESTRIC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  v_EPS IN VARCHAR2,
  v_CONVENIO IN NUMBER,
  v_SERVICIO IN VARCHAR2,
  v_SERVICIO_REQUISITO IN VARCHAR2,
  v_MEDIDA IN NUMBER,
  v_PERIODO IN NUMBER,
  v_ESTADO IN NUMBER
)
AS

BEGIN

    UPDATE SERVICIOS_RESTRICCION
    SET CD_NIT_EPS_SR = v_EPS,
        NU_NUME_CONV_SR = v_CONVENIO,
        CD_CODI_SER_SR = v_SERVICIO,
        CD_CODI_SER_REQ_SR = v_SERVICIO_REQUISITO,
        NU_NUME_UNI_SR = v_MEDIDA,
        NU_NUME_PER_SR = v_PERIODO,
        NU_NUME_EST_SR = v_ESTADO
    WHERE  ID_IDEN_SR = v_CODIGO;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;