CREATE OR REPLACE PROCEDURE H3i_SP_LISTA_ORDCONC_CONSULTA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_NU_HIST_PAC IN VARCHAR2,
    cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN  cv_1 FOR
        SELECT HP.NU_NUME_HPRO ,
            HP.FE_FECH_HPRO ,
            HP.NU_NUME_HICL_HPRO NU_HIST_PAC  ,
            CS.CD_CODI_COSE ,
            CS.NO_NOMB_COSE ,
            HP.NU_CANT_HPRO ,
            S.CD_CODI_SER CD_CODI_SER  ,
            UPPER(S.NO_NOMB_SER) NO_NOMB_SER  ,
            M.CD_MEDI_ORDE_MOVI ,
            ( SELECT NO_NOMB_MED 
              FROM MEDICOS 
              WHERE  CD_CODI_MED = M.CD_MEDI_ORDE_MOVI ) MEDIORDEN  ,
            L.CD_CODI_ESP_LABO ,-- CODIGO LABORATORIO  SELECT * FROM MOVI_CARGOS
            ( SELECT NO_NOMB_ESP 
              FROM ESPECIALIDADES 
              WHERE  CD_CODI_ESP = L.CD_CODI_ESP_LABO ) ESPEORDEN  ,
            M.CD_CODI_MED_MOVI ,
            ( SELECT ESPECIALIDADES.CD_CODI_ESP 
              FROM( R_MEDI_ESPE R_MEDI_ESPE
                    INNER JOIN MEDICOS MEDICOS   
                        ON (R_MEDI_ESPE.CD_CODI_MED_RMP = MEDICOS.CD_CODI_MED)) 
              INNER JOIN ESPECIALIDADES ESPECIALIDADES   
                  ON (R_MEDI_ESPE.CD_CODI_ESP_RMP = ESPECIALIDADES.CD_CODI_ESP)
              WHERE  MEDICOS.CD_CODI_MED = M.CD_CODI_MED_MOVI AND ROWNUM <= 1) CODESPEREALI  
        FROM HIST_PROC HP
        INNER JOIN HISTORIACLINICA H   
            ON HP.NU_NUME_HICL_HPRO = H.NU_NUME_HICL
        INNER JOIN LABORATORIO L   
            ON L.NU_NUME_LABO = H.NU_NUME_LABO_HICL
        INNER JOIN MOVI_CARGOS M   
            ON M.NU_NUME_MOVI = L.NU_NUME_MOVI_LABO
        INNER JOIN SERVICIOS S   
            ON S.CD_CODI_SER = HP.CD_CODI_SER_HPRO
        INNER JOIN CONCEPTOS_SERV CS   
            ON ( S.CD_CODI_COSE_SER = CS.CD_CODI_COSE)
        LEFT JOIN HIST_PROCONS HC   
            ON HP.NU_NUME_HPRO = HC.NU_NUME_HPRO_HPCO
        LEFT JOIN ESPECIALIDADES E   
            ON HC.CD_CODI_ESP_HPCO = E.CD_CODI_ESP
        INNER JOIN PACIENTES PACIENTES   
            ON PACIENTES.NU_HIST_PAC = M.NU_HIST_PAC_MOVI
        WHERE  NU_ESTA_MOVI <> 2
            AND NU_ESTA_LABO <> 2
            AND CD_CODI_COSE = '01'
            AND NU_TIPO_HPRO = 1
            AND PACIENTES.NU_HIST_PAC = v_NU_HIST_PAC ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;