CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_MOT_CAMB_CAMA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_COD_CODI_CAMA_MOT IN VARCHAR2,
  v_MOTIVO_CAMB_EST IN VARCHAR2,
  v_FECHA_MOT IN DATE,
  v_NUM_CONEX IN NUMBER
)
AS

BEGIN

	INSERT INTO MOT_CAMB_EST_CAMAS( 
		COD_CODI_CAMA_MOT, MOTIVO_CAMB_EST, FECHA_MOT, NUM_CONEX )
	VALUES ( 
		v_COD_CODI_CAMA_MOT, v_MOTIVO_CAMB_EST, TO_DATE(v_FECHA_MOT,'dd/mm/yyyy'), v_NUM_CONEX );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;