CREATE OR REPLACE PROCEDURE H3i_SP_EDITAR_IND_VAR
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_AUTO_VAR IN NUMBER,
  v_CD_CODI_VAR IN CHAR,
  v_TX_NOMBRE_VAR IN VARCHAR2,
  v_NU_ESTADO_VAR IN NUMBER,
  v_NU_TIPO_VAR IN NUMBER,
  v_TX_FORMU_VAR IN VARCHAR2,
  v_NU_AUTO_INDI_VAR IN NUMBER
)
AS

BEGIN

    UPDATE INDICADOR_VARIABLE
    SET CD_CODI_VAR = v_CD_CODI_VAR,
        TX_NOMBRE_VAR = v_TX_NOMBRE_VAR,
        NU_ESTADO_VAR = v_NU_ESTADO_VAR,
        NU_TIPO_VAR = v_NU_TIPO_VAR,
        TX_FORMU_VAR = v_TX_FORMU_VAR,
        NU_AUTO_INDI_VAR = v_NU_AUTO_INDI_VAR
    WHERE  NU_AUTO_VAR = v_NU_AUTO_VAR;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;