CREATE OR REPLACE PROCEDURE QyR3i_SP_EDIT_SOLICITUD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_ID_SOLICITUD IN NUMBER,
  v_FECHA_REGISTRO IN DATE,
  v_TIPO_SOLICITUD IN NUMBER,
  v_REGISTRADOR IN VARCHAR2,
  v_RECLAMANTE IN VARCHAR2,
  v_NOMBRE IN VARCHAR2,
  v_IDENTIFICADOR IN VARCHAR2,
  v_TELEFONO IN VARCHAR2,
  v_DIRECCION IN VARCHAR2,
  v_EMAIL IN VARCHAR2,
  v_IMPLICADO IN VARCHAR2,
  v_NOMBRE_IMPLICADO IN VARCHAR2,
  v_DESCRIPCION IN VARCHAR2,
  v_ENCARGADO IN VARCHAR2,
  v_CONFIRMACION IN NUMBER,
  v_ESTADO IN NUMBER,
  v_DIAS_HABILES IN NUMBER,
  v_FECHA_FINALIZACION IN DATE,
  v_FACULTAD IN VARCHAR2,
  v_CELULAR IN VARCHAR2,
  v_TRANSCRITO IN NUMBER
)
AS

BEGIN

    UPDATE QYR_SOLICITUD
    SET FE_FECH_INI_SOL = v_FECHA_REGISTRO,
        NU_NUME_TS_SOL = v_TIPO_SOLICITUD,
        TX_IDEN_REG_SOL = v_REGISTRADOR,
        TX_IDEN_REC_SOL = v_RECLAMANTE,
        TX_NOMB_REC_SOL = v_NOMBRE,
        TX_IDENT_REC_SOL = v_IDENTIFICADOR,
        TX_TELF_REC_SOL = v_TELEFONO,
        TX_DIRE_REC_SOL = v_DIRECCION,
        TX_EMAIL_REC_SOL = v_EMAIL,
        TX_IDEN_IMP_SOL = v_IMPLICADO,
        TX_NOMB_IMP_SOL = v_NOMBRE_IMPLICADO,
        TX_DESC_SOL = v_DESCRIPCION,
        TX_IDEN_ENC_SOL = v_ENCARGADO,
        NU_NUME_CON_SOL = v_CONFIRMACION,
        NU_NUME_EST_SOL = v_ESTADO,
        NU_NUME_ND_SOL = v_DIAS_HABILES,
        FE_FECH_FIN_SOL = v_FECHA_FINALIZACION,
        CD_CODI_PA_SOL = v_FACULTAD,
        TX_CELU_SOL = v_CELULAR,
        TX_TRANS_SOL = v_TRANSCRITO
    WHERE  NU_NUME_SOL = v_ID_SOLICITUD;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;