CREATE OR REPLACE PROCEDURE QyR3i_SP_EDIT_SEGUIMIENTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_ID_SEGUIMIENTO IN NUMBER,
    v_ID_SOLICITUD IN NUMBER,
    v_FECHA IN DATE,
    v_CONEXION IN NUMBER,
    v_DESCRIPCION IN VARCHAR2
)
AS

BEGIN

    UPDATE QYR_SEGUIMIENTO
    SET NU_NUME_SOL_SEG = v_ID_SOLICITUD,
      FE_FECH_INI_SEG = v_FECHA,
      NU_NUME_CON_SEG = v_CONEXION,
      TX_CONT_SEG = v_DESCRIPCION
    WHERE  NU_NUME_SEG = v_ID_SEGUIMIENTO;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;