CREATE OR REPLACE PROCEDURE QyR3i_SP_EDIT_BUZ_SOLICITUD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_ID_BUZON_SOLICITUDES IN NUMBER,
    v_TX_IDEN_EMI_BS IN VARCHAR2 DEFAULT NULL ,
    v_TX_IDEN_REC_BS IN VARCHAR2 DEFAULT NULL ,
    v_NU_IDEN_SOL_BS IN NUMBER DEFAULT NULL ,-- 
    v_TX_OBS_BS IN VARCHAR2 DEFAULT NULL ,
    v_NU_EST_BS IN NUMBER DEFAULT NULL ,
    v_NU_TIPO_BS IN NUMBER DEFAULT NULL ,
    v_QFECH_FECHA_BS IN DATE DEFAULT NULL 
)
AS

BEGIN

    UPDATE QYR_BUZON_SOLICITUD
    SET TX_IDEN_EMI_BS = v_TX_IDEN_EMI_BS,
        TX_IDEN_REC_BS = v_TX_IDEN_REC_BS,
        NU_IDEN_SOL_BS = v_NU_IDEN_SOL_BS,
        TX_OBS_BS = v_TX_OBS_BS,
        NU_EST_BS = v_NU_EST_BS,
        NU_TIPO_BS = v_NU_TIPO_BS,
        FECH_FECHA_BS = v_QFECH_FECHA_BS
    WHERE  ID_BUZON_SOLICITUDES = v_ID_BUZON_SOLICITUDES;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;