CREATE OR REPLACE TRIGGER ACCI_CATASTROFE_NU_ACC_CATA__1 BEFORE INSERT ON ACCI_CATASTROFE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ACCI_CATASTROFE_NU_ACC_CATA_AC.NEXTVAL
    INTO   :NEW.NU_ACC_CATA_ACCA
    FROM   dual;
END;