CREATE OR REPLACE TRIGGER ACTIVIDAD_PYP_NU_CODI_ACTI_TRG BEFORE INSERT ON ACTIVIDAD_PYP
FOR EACH ROW
DECLARE 
 
BEGIN
    SELECT ACTIVIDAD_PYP_NU_CODI_ACTI_SEQ.NEXTVAL
    INTO   :NEW.NU_CODI_ACTI
    FROM   dual;
END;