CREATE OR REPLACE TRIGGER ACTIVIDAD_SALUD_UNAL_NU_CODI_1 BEFORE INSERT ON ACTIVIDAD_SALUD_UNAL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ACTIVIDAD_SALUD_UNAL_NU_CODI_A.NEXTVAL
    INTO   :NEW.NU_CODI_ACSA
    FROM   dual;
END;