CREATE OR REPLACE TRIGGER ADM_LIQUIDOS_ENF_NU_NUME_ALE_1 BEFORE INSERT ON ADM_LIQUIDOS_ENF
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT ADM_LIQUIDOS_ENF_NU_NUME_ALEN_.NEXTVAL
    INTO   :NEW.NU_NUME_ALEN
    FROM   dual;
END;