CREATE OR REPLACE TRIGGER ADSCRITOS_NU_CONSE_ADSC_TRG BEFORE INSERT ON ADSCRITOS
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT ADSCRITOS_NU_CONSE_ADSC_SEQ.NEXTVAL
    INTO   :NEW.NU_CONSE_ADSC
    FROM   dual;
END;