CREATE OR REPLACE TRIGGER ALTERACION_PULPAR_NU_AUTO_AL_1 BEFORE INSERT ON ALTERACION_PULPAR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ALTERACION_PULPAR_NU_AUTO_ALPU.NEXTVAL
    INTO   :NEW.NU_AUTO_ALPU
    FROM   dual;
END;