CREATE OR REPLACE TRIGGER ANULACION_AUTORIZACION_ADS_I_1 BEFORE INSERT ON ANULACION_AUTORIZACION_ADS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ANULACION_AUTORIZACION_ADS_ID_.NEXTVAL
    INTO   :NEW.ID_ANUL
    FROM   dual;
END;