CREATE OR REPLACE TRIGGER APLICACION_QUIM_MED_NU_NUME__1 BEFORE INSERT ON APLICACION_QUIM_MED
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT APLICACION_QUIM_MED_NU_NUME_AQ.NEXTVAL
    INTO   :NEW.NU_NUME_AQM
    FROM   dual;
END;