CREATE OR REPLACE TRIGGER ARCHIVO_PLANO_NU_AUTO_ARPL_TRG BEFORE INSERT ON ARCHIVO_PLANO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ARCHIVO_PLANO_NU_AUTO_ARPL_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ARPL
    FROM   dual;
END;