CREATE OR REPLACE TRIGGER AREA_SALUD_ID_IDEN_AS_TRG BEFORE INSERT ON AREA_SALUD
FOR EACH ROW
DECLARE 
   
BEGIN 
    SELECT AREA_SALUD_ID_IDEN_AS_SEQ.NEXTVAL
    INTO   :NEW.ID_IDEN_AS
    FROM   dual;
END;