CREATE OR REPLACE TRIGGER ARQUEO_CAJA_NU_AUTO_ARQUEO_TRG BEFORE INSERT ON ARQUEO_CAJA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ARQUEO_CAJA_NU_AUTO_ARQUEO_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ARQUEO
    FROM   dual;
END;