CREATE OR REPLACE TRIGGER AUDITORF3_NU_AUTO_AUDIT_TRG BEFORE INSERT ON AUDITORF3
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT AUDITORF3_NU_AUTO_AUDIT_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_AUDIT
    FROM   dual;
END;