CREATE OR REPLACE TRIGGER AUDITORIA_IMPRESION_HC_CD_CO_1 BEFORE INSERT ON AUDITORIA_IMPRESION_HC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITORIA_IMPRESION_HC_CD_CODI.NEXTVAL
    INTO   :NEW.CD_CODI_AIH
    FROM   dual;
END;