CREATE OR REPLACE TRIGGER AUDITAR_REG_GLOS_MEDICAM_AUT_1 BEFORE INSERT ON AUDITAR_REG_GLOS_MEDICAM
FOR EACH ROW
DECLARE 
  
BEGIN
     SELECT AUDITAR_REG_GLOS_MEDICAM_AUTO_.NEXTVAL
    INTO   :NEW.AUTO_REG_GLOS_MED
    FROM   dual;
END;