CREATE OR REPLACE TRIGGER AUDI_ESM_NU_AUTO_ESM_TRG BEFORE INSERT ON AUDI_ESM
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDI_ESM_NU_AUTO_ESM_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ESM
    FROM   dual;
END;