CREATE OR REPLACE TRIGGER AUDITAR_REGISTRO_GLOSADO_AUT_1 BEFORE INSERT ON AUDITAR_REGISTRO_GLOSADO
FOR EACH ROW
DECLARE 

BEGIN
    SELECT AUDITAR_REGISTRO_GLOSADO_AUTO_.NEXTVAL
    INTO   :NEW.AUTO_REG_GLOSA
    FROM   dual;
END;