CREATE OR REPLACE TRIGGER AUDITAR_DOCUMENTO_COD_AUDI_D_1 BEFORE INSERT ON AUDITAR_DOCUMENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_DOCUMENTO_COD_AUDI_DOC.NEXTVAL
    INTO   :NEW.COD_AUDI_DOCUM
    FROM   dual;
END;