CREATE OR REPLACE TRIGGER AUDITAR_DOCUM_MEDICAM_OBS_AU_1 BEFORE INSERT ON AUDITAR_DOCUM_MEDICAM_OBS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_DOCUM_MEDICAM_OBS_AUTO.NEXTVAL
    INTO   :NEW.AUTO_DOC_MED_OBS
    FROM   dual;
END;