  CREATE OR REPLACE TRIGGER AUDI_HUELLA_CONSENT_NU_AUTO__1 BEFORE INSERT ON AUDI_HUELLA_CONSENT
  FOR EACH ROW
  DECLARE 
      
  BEGIN

    SELECT AUDI_HUELLA_CONSENT_NU_AUTO_AH.NEXTVAL
      INTO   :NEW.NU_AUTO_AHC
      FROM   dual;
  END;