CREATE OR REPLACE TRIGGER AUDITAR_REGISTRO_HISTORY_AUT_1 BEFORE INSERT ON AUDITAR_REGISTRO_HISTORY
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_REGISTRO_HISTORY_AUTO_.NEXTVAL
    INTO   :NEW.AUTO_REG_HISTO
    FROM   dual;
END;