CREATE OR REPLACE TRIGGER AUDITAR_CATALOGO_MEDICAMENTO_1 BEFORE INSERT ON AUDITAR_CATALOGO_MEDICAMENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_CATALOGO_MEDICAMENTO_C.NEXTVAL
    INTO   :NEW.COD_CATAL_MEDICAM
    FROM   dual;
END;