CREATE OR REPLACE TRIGGER AUDITAR_TIPO_DOCU_CD_CODI_AT_1 BEFORE INSERT ON AUDITAR_TIPO_DOCU
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_TIPO_DOCU_CD_CODI_ATD_.NEXTVAL
    INTO   :NEW.CD_CODI_ATD
    FROM   dual;
END;