CREATE OR REPLACE TRIGGER AUDITAR_CATALOGO_PROFE_SUMIN_1 BEFORE INSERT ON AUDITAR_CATALOGO_PROFE_SUMIN
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUDITAR_CATALOGO_PROFE_SUMIN_C.NEXTVAL
    INTO   :NEW.COD_CATAL_PS
    FROM   dual;
END;