CREATE OR REPLACE TRIGGER AUTORIZACION_NU_CONSE_AUTOR_TR BEFORE INSERT ON AUTORIZACION
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT AUTORIZACION_NU_CONSE_AUTOR_SE.NEXTVAL
    INTO   :NEW.NU_CONSE_AUTOR
    FROM   dual;
END;