CREATE OR REPLACE TRIGGER CAMPO_PLANO_NU_AUTO_CAPL_TRG BEFORE INSERT ON CAMPO_PLANO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CAMPO_PLANO_NU_AUTO_CAPL_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_CAPL
    FROM   dual;
END;