CREATE OR REPLACE TRIGGER CAMPO_CABECERA_NU_AUTO_CAEN_TR BEFORE INSERT ON CAMPO_CABECERA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CAMPO_CABECERA_NU_AUTO_CAEN_SE.NEXTVAL
    INTO   :NEW.NU_AUTO_CAEN
    FROM   dual;
END;