CREATE OR REPLACE TRIGGER CAPITULO_NU_CONSE_CAPI_TRG BEFORE INSERT ON CAPITULO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CAPITULO_NU_CONSE_CAPI_SEQ.NEXTVAL
    INTO   :NEW.NU_CONSE_CAPI
    FROM   dual;
END;