CREATE OR REPLACE TRIGGER CARGOS_ADSCRITO_NU_NUME_CAAD_T BEFORE INSERT ON CARGOS_ADSCRITO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CARGOS_ADSCRITO_NU_NUME_CAAD_S.NEXTVAL
    INTO   :NEW.NU_NUME_CAAD
    FROM   dual;
END;