CREATE OR REPLACE TRIGGER CASO_CRITICO_HIST_CD_CASCRIT_1 BEFORE INSERT ON CASO_CRITICO_HIST
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CASO_CRITICO_HIST_CD_CASCRIT_H.NEXTVAL
    INTO   :NEW.CD_CASCRIT_HC
    FROM   dual;
END;