CREATE OR REPLACE TRIGGER CITAS_MEDICAS_NU_NUME_CIT_TRG BEFORE INSERT ON CITAS_MEDICAS
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT CITAS_MEDICAS_NU_NUME_CIT_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_CIT
    FROM   dual;
END;