CREATE OR REPLACE TRIGGER CITAS_CONFIRMADAS_NU_NUME_CC_T BEFORE INSERT ON CITAS_CONFIRMADAS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CITAS_CONFIRMADAS_NU_NUME_CC_S.NEXTVAL
    INTO   :NEW.NU_NUME_CC
    FROM   dual;
END;