CREATE OR REPLACE TRIGGER CLIENTES_APP_AUTO_NUM_CLI_TRG BEFORE INSERT ON CLIENTES_APP
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT CLIENTES_APP_AUTO_NUM_CLI_SEQ.NEXTVAL
    INTO   :NEW.AUTO_NUM_CLI
    FROM   dual;
END;