CREATE OR REPLACE TRIGGER COBROQX_CONCEPTO_NU_AUTO_CCQ_1 BEFORE INSERT ON COBROQX_CONCEPTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT COBROQX_CONCEPTO_NU_AUTO_CCQX_.NEXTVAL
    INTO   :NEW.NU_AUTO_CCQX
    FROM   dual;
END;