CREATE OR REPLACE TRIGGER COMP_DERECHO_ID_COMP_DERE_TRG BEFORE INSERT ON COMP_DERECHO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT COMP_DERECHO_ID_COMP_DERE_SEQ.NEXTVAL
    INTO   :NEW.ID_COMP_DERE
    FROM   dual;
END;