CREATE OR REPLACE TRIGGER CONCEPTO_HIST_PYP_NU_AUTO_CO_1 BEFORE INSERT ON CONCEPTO_HIST_PYP
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONCEPTO_HIST_PYP_NU_AUTO_CONC.NEXTVAL
    INTO   :NEW.NU_AUTO_CONCPYP
    FROM   dual;
END;