CREATE OR REPLACE TRIGGER CONDICION_VICTIMA_ID_CON_VIC_1 BEFORE INSERT ON CONDICION_VICTIMA
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT CONDICION_VICTIMA_ID_CON_VICT_.NEXTVAL
    INTO   :NEW.ID_CON_VICT
    FROM   dual;
END;