CREATE OR REPLACE TRIGGER CONEXIONES_NU_NUME_CONE_TRG BEFORE INSERT ON CONEXIONES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONEXIONES_NU_NUME_CONE_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_CONE
    FROM   dual;
END;