CREATE OR REPLACE TRIGGER CONEXION_INV_NU_AUTO_CINV_TRG BEFORE INSERT ON CONEXION_INV
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT CONEXION_INV_NU_AUTO_CINV_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_CINV
    FROM   dual;
END;