CREATE OR REPLACE TRIGGER CONFIGURA_FORM_CIR_COD_CONF__1 BEFORE INSERT ON CONFIGURA_FORM_CIR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONFIGURA_FORM_CIR_COD_CONF_FO.NEXTVAL
    INTO   :NEW.COD_CONF_FORM_CIR
    FROM   dual;
END;