CREATE OR REPLACE TRIGGER CONFIGURA_FORM_ANESTESIA_COD_1 BEFORE INSERT ON CONFIGURA_FORM_ANESTESIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONFIGURA_FORM_ANESTESIA_COD_C.NEXTVAL
    INTO   :NEW.COD_CONF_FORM_ANESTESIA
    FROM   dual;
END;