CREATE OR REPLACE TRIGGER CONTRAREF_DIAGNOSTICO_CD_DIA_1 BEFORE INSERT ON CONTRAREF_DIAGNOSTICO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONTRAREF_DIAGNOSTICO_CD_DIAG_.NEXTVAL
    INTO   :NEW.CD_DIAG
    FROM   dual;
END;