CREATE OR REPLACE TRIGGER CONTRAREFERENCIA_CD_CONTRARE_1 BEFORE INSERT ON CONTRAREFERENCIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONTRAREFERENCIA_CD_CONTRAREFE.NEXTVAL
    INTO   :NEW.CD_CONTRAREFERENCIA
    FROM   dual;
END;