CREATE OR REPLACE TRIGGER CONTRAREF_OFTALMOSCOPIA_CD_O_1 BEFORE INSERT ON CONTRAREF_OFTALMOSCOPIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONTRAREF_OFTALMOSCOPIA_CD_OFT.NEXTVAL
    INTO   :NEW.CD_OFTALMOSCOPIA
    FROM   dual;
END;