CREATE OR REPLACE TRIGGER CONTRAREF_ANAMNESIS_CD_ANAMN_1 BEFORE INSERT ON CONTRAREF_ANAMNESIS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONTRAREF_ANAMNESIS_CD_ANAMNES.NEXTVAL
    INTO   :NEW.CD_ANAMNESIS
    FROM   dual;
END;