CREATE OR REPLACE TRIGGER CONTRAREF_RETINOSCOPIA_CD_RE_1 BEFORE INSERT ON CONTRAREF_RETINOSCOPIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONTRAREF_RETINOSCOPIA_CD_RETI.NEXTVAL
    INTO   :NEW.CD_RETINOSCOPIA
    FROM   dual;
END;