CREATE OR REPLACE TRIGGER CONVENCION_PERIODONTOGRAMA_N_1 BEFORE INSERT ON CONVENCION_PERIODONTOGRAMA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONVENCION_PERIODONTOGRAMA_NU_.NEXTVAL
    INTO   :NEW.NU_AUTO_COPE
    FROM   dual;
END;