CREATE OR REPLACE TRIGGER CONVENIOS_NU_NUME_CONV_TRG BEFORE INSERT ON CONVENIOS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT CONVENIOS_NU_NUME_CONV_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_CONV
    FROM   dual;
END;