CREATE OR REPLACE TRIGGER DATOS_EXAMEN_NU_AUTO_DAEX_TRG BEFORE INSERT ON DATOS_EXAMEN
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT DATOS_EXAMEN_NU_AUTO_DAEX_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_DAEX
    FROM   dual;
END;