CREATE OR REPLACE TRIGGER DEF_DIFRENCIADOR_NU_AUTO_DED_1 BEFORE INSERT ON DEF_DIFRENCIADOR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT DEF_DIFRENCIADOR_NU_AUTO_DEDI_.NEXTVAL
    INTO   :NEW.NU_AUTO_DEDI
    FROM   dual;
END;