CREATE OR REPLACE TRIGGER DESP_MEDICAMENTOS_CD_CODI_DE_1 BEFORE INSERT ON DESP_MEDICAMENTOS
FOR EACH ROW
DECLARE 
    
BEGIN
     SELECT DESP_MEDICAMENTOS_CD_CODI_DEME.NEXTVAL
    INTO   :NEW.CD_CODI_DEME
    FROM   dual;
END;