CREATE OR REPLACE TRIGGER DETALLE_ARCHIVO_FISICO_NU_AU_1 BEFORE INSERT ON DETALLE_ARCHIVO_FISICO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT DETALLE_ARCHIVO_FISICO_NU_AUTO.NEXTVAL
    INTO   :NEW.NU_AUTO_DTAR
    FROM   dual;
END;