CREATE OR REPLACE TRIGGER DETALLE_HIFO_NU_AUTO_DEHF_TRG BEFORE INSERT ON DETALLE_HIFO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT DETALLE_HIFO_NU_AUTO_DEHF_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_DEHF
    FROM   dual;
END;