CREATE OR REPLACE TRIGGER DETAUT_NU_CONSE_DETAUT_TRG BEFORE INSERT ON DETAUT
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT DETAUT_NU_CONSE_DETAUT_SEQ.NEXTVAL
    INTO   :NEW.NU_CONSE_DETAUT
    FROM   dual;
END;