CREATE OR REPLACE TRIGGER DETALLE_GLOSA3i_NU_AUTO_DEGL_T BEFORE INSERT ON DETALLE_GLOSA3i
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT DETALLE_GLOSA3i_NU_AUTO_DEGL_S.NEXTVAL
    INTO   :NEW.NU_AUTO_DEGL
    FROM   dual;
END;