CREATE OR REPLACE TRIGGER DETALLE_HIVI_NU_AUTO_DEHI_TRG BEFORE INSERT ON DETALLE_HIVI
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT DETALLE_HIVI_NU_AUTO_DEHI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_DEHI
    FROM   dual;
END;