CREATE OR REPLACE TRIGGER DEVOLUCION_CIR_NU_NUME_DEV_C_1 BEFORE INSERT ON DEVOLUCION_CIR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT DEVOLUCION_CIR_NU_NUME_DEV_CIR.NEXTVAL
    INTO   :NEW.NU_NUME_DEV_CIR
    FROM   dual;
END;