CREATE OR REPLACE TRIGGER DOCUMENTOS_NU_NUME_DOCU_TRG BEFORE INSERT ON DOCUMENTOS
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT DOCUMENTOS_NU_NUME_DOCU_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_DOCU
    FROM   dual;
END;