CREATE OR REPLACE TRIGGER ENTIDAD_NU_AUTO_ENTI_TRG BEFORE INSERT ON ENTIDAD
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ENTIDAD_NU_AUTO_ENTI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ENTI
    FROM   dual;
END;