CREATE OR REPLACE TRIGGER ERROR_HOSPITAL_CONSECUTIVO_TRG BEFORE INSERT ON ERROR_HOSPITAL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ERROR_HOSPITAL_CONSECUTIVO_SEQ.NEXTVAL
    INTO   :NEW.CONSECUTIVO
    FROM   dual;
END;