CREATE OR REPLACE TRIGGER ERROR_CONSULTA_CONSECUTIVO_TRG BEFORE INSERT ON ERROR_CONSULTA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ERROR_CONSULTA_CONSECUTIVO_SEQ.NEXTVAL
    INTO   :NEW.CONSECUTIVO
    FROM   dual;
END;