CREATE OR REPLACE TRIGGER ESCALA_RANGOEDAD_NU_AUTO_RAE_1 BEFORE INSERT ON ESCALA_RANGOEDAD
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ESCALA_RANGOEDAD_NU_AUTO_RAED_.NEXTVAL
    INTO   :NEW.NU_AUTO_RAED
    FROM   dual;
END;