CREATE OR REPLACE TRIGGER ESPACIO_LAB_NU_AUTO_ESP_TRG BEFORE INSERT ON ESPACIO_LAB
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT ESPACIO_LAB_NU_AUTO_ESP_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ESP
    FROM   dual;
END;