CREATE OR REPLACE TRIGGER ESPECIALIDAD_X_ORDEN_CD_ESPO_1 BEFORE INSERT ON ESPECIALIDAD_X_ORDEN
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ESPECIALIDAD_X_ORDEN_CD_ESPORD.NEXTVAL
    INTO   :NEW.CD_ESPORDE
    FROM   dual;
END;