CREATE OR REPLACE TRIGGER ESPECIALIDAD_LIMITE_NU_NUME__1 BEFORE INSERT ON ESPECIALIDAD_LIMITE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ESPECIALIDAD_LIMITE_NU_NUME_ES.NEXTVAL
    INTO   :NEW.NU_NUME_ESPL
    FROM   dual;
END;