CREATE OR REPLACE TRIGGER EVENTO_PROCESPECIAL_NU_AUTO__1 BEFORE INSERT ON EVENTO_PROCESPECIAL
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT EVENTO_PROCESPECIAL_NU_AUTO_EV.NEXTVAL
    INTO   :NEW.NU_AUTO_EVENPE
    FROM   dual;
END;