CREATE OR REPLACE TRIGGER EVENTO_PROCESPECIAL_LOGHC_NU_1 BEFORE INSERT ON EVENTO_PROCESPECIAL_LOGHC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT EVENTO_PROCESPECIAL_LOGHC_NU_A.NEXTVAL
    INTO   :NEW.NU_AUTO_LOGHC_EPEL
    FROM   dual;
END;