CREATE OR REPLACE TRIGGER EXPRESION_INDICADORES_NU_AUT_1 BEFORE INSERT ON EXPRESION_INDICADORES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT EXPRESION_INDICADORES_NU_AUTO_.NEXTVAL
    INTO   :NEW.NU_AUTO_EXIN
    FROM   dual;
END;