CREATE OR REPLACE TRIGGER F_CDO_ENFERMERIA_NU_NUME_FCE_1 BEFORE INSERT ON F_CDO_ENFERMERIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT F_CDO_ENFERMERIA_NU_NUME_FCEN_.NEXTVAL
    INTO   :NEW.NU_NUME_FCEN
    FROM   dual;
END;