CREATE OR REPLACE TRIGGER F_TRATAMIENTO_NU_NUME_FT_TRG BEFORE INSERT ON F_TRATAMIENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT F_TRATAMIENTO_NU_NUME_FT_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_FT
    FROM   dual;
END;