CREATE OR REPLACE TRIGGER FAC_ADSC_NU_CONSE_FADSC_TRG BEFORE INSERT ON FAC_ADSC
FOR EACH ROW
DECLARE 
     
BEGIN
    SELECT FAC_ADSC_NU_CONSE_FADSC_SEQ.NEXTVAL
    INTO   :NEW.NU_CONSE_FADSC
    FROM   dual;
END;