CREATE OR REPLACE TRIGGER FACTURA_ADSCRITO_ID_IDEN_FAA_1 BEFORE INSERT ON FACTURA_ADSCRITO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FACTURA_ADSCRITO_ID_IDEN_FAAD_.NEXTVAL
    INTO   :NEW.ID_IDEN_FAAD
    FROM   dual;
END;