CREATE OR REPLACE TRIGGER FACTURAS_CONTADO_CREDITO_NU__1 BEFORE INSERT ON FACTURAS_CONTADO_CREDITO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FACTURAS_CONTADO_CREDITO_NU_AU.NEXTVAL
    INTO   :NEW.NU_AUTO_FCCR
    FROM   dual;
END;