CREATE OR REPLACE TRIGGER FACTOR_VAIN_NU_AUTO_FAVA_TRG BEFORE INSERT ON FACTOR_VAIN
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FACTOR_VAIN_NU_AUTO_FAVA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_FAVA
    FROM   dual;
END;