CREATE OR REPLACE TRIGGER FACTOR_RIESGO_HIST_CD_VAL_FA_1 BEFORE INSERT ON FACTOR_RIESGO_HIST
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FACTOR_RIESGO_HIST_CD_VAL_FACT.NEXTVAL
    INTO   :NEW.CD_VAL_FACTRIESG
    FROM   dual;
END;