CREATE OR REPLACE TRIGGER FALTANTES_SOBRANTES_CD_CODI__1 BEFORE INSERT ON FALTANTES_SOBRANTES
FOR EACH ROW
DECLARE 
     
BEGIN    
  SELECT FALTANTES_SOBRANTES_CD_CODI_FA.NEXTVAL
    INTO   :NEW.CD_CODI_FASO
    FROM   dual;
END;