CREATE OR REPLACE TRIGGER FORMATOS_HC_REG_CLAP_COD_FOR_1 BEFORE INSERT ON FORMATOS_HC_REG_CLAP
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FORMATOS_HC_REG_CLAP_COD_FOR_H.NEXTVAL
    INTO   :NEW.COD_FOR_HC_REG_CLAP
    FROM   dual;
END;