CREATE OR REPLACE TRIGGER FORMULAS_INVENTARIO_NU_AUTO__1 BEFORE INSERT ON FORMULAS_INVENTARIO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT FORMULAS_INVENTARIO_NU_AUTO_FO.NEXTVAL
    INTO   :NEW.NU_AUTO_FOIN
    FROM   dual;
END;