CREATE OR REPLACE TRIGGER G_REG_ACTIVIDADES_NU_NUME_GR_1 BEFORE INSERT ON G_REG_ACTIVIDADES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT G_REG_ACTIVIDADES_NU_NUME_GRAC.NEXTVAL
    INTO   :NEW.NU_NUME_GRAC
    FROM   dual;
END;