CREATE OR REPLACE TRIGGER G_REG_ENFERMERIA_NU_NUME_GRE_1 BEFORE INSERT ON G_REG_ENFERMERIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT G_REG_ENFERMERIA_NU_NUME_GREN_.NEXTVAL
    INTO   :NEW.NU_NUME_GREN
    FROM   dual;
END;