CREATE OR REPLACE TRIGGER GRUPO_HIST_NU_NUME_GRHI_TRG BEFORE INSERT ON GRUPO_HIST
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT GRUPO_HIST_NU_NUME_GRHI_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_GRHI
    FROM   dual;
END;