CREATE OR REPLACE TRIGGER GRUPOS_ESTS_POR_DOC_ESP_NU_G_1 BEFORE INSERT ON GRUPOS_ESTS_POR_DOC_ESP
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT GRUPOS_ESTS_POR_DOC_ESP_NU_GRU.NEXTVAL
    INTO   :NEW.NU_GRUP_EST_DOC_ESP
    FROM   dual;
END;