CREATE OR REPLACE TRIGGER GRUPO_ASIGNATURA_PERIODO_NU__1 BEFORE INSERT ON GRUPO_ASIGNATURA_PERIODO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT GRUPO_ASIGNATURA_PERIODO_NU_AU.NEXTVAL
    INTO   :NEW.NU_AUTO_GRAP
    FROM   dual;
END;