CREATE OR REPLACE TRIGGER HEMODINAMIA_NO_NUME_HEMODI_TRG BEFORE INSERT ON HEMODINAMIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HEMODINAMIA_NO_NUME_HEMODI_SEQ.NEXTVAL
    INTO   :NEW.NO_NUME_HEMODI
    FROM   dual;
END;