CREATE OR REPLACE TRIGGER HIST_GENO_RELACION_ARBOL_NU__1 BEFORE INSERT ON HIST_GENO_RELACION_ARBOL
FOR EACH ROW
DECLARE 
    
BEGIN 
    SELECT HIST_GENO_RELACION_ARBOL_NU_NU.NEXTVAL
    INTO   :NEW.NU_NUME_REL_ARB
    FROM   dual;
END;