CREATE OR REPLACE TRIGGER HIST_ODONTO_REG_CONS_CD_REG__1 BEFORE INSERT ON HIST_ODONTO_REG_CONS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_ODONTO_REG_CONS_CD_REG_CO.NEXTVAL
    INTO   :NEW.CD_REG_CONSULTA
    FROM   dual;
END;