CREATE OR REPLACE TRIGGER HIST_INSQUI_ASIG_CD_INSQUI_A_1 BEFORE INSERT ON HIST_INSQUI_ASIG
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_INSQUI_ASIG_CD_INSQUI_ASI.NEXTVAL
    INTO   :NEW.CD_INSQUI_ASIG
    FROM   dual;
END;