CREATE OR REPLACE TRIGGER HIST_ORTODONCIA_CONSULTAS_CD_1 BEFORE INSERT ON HIST_ORTODONCIA_CONSULTAS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_ORTODONCIA_CONSULTAS_CD_C.NEXTVAL
    INTO   :NEW.CD_CONS_ORTOD
    FROM   dual;
END;