CREATE OR REPLACE TRIGGER HIST_INSQUI_REL_CD_INSQUI_HC_T BEFORE INSERT ON HIST_INSQUI_REL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_INSQUI_REL_CD_INSQUI_HC_S.NEXTVAL
    INTO   :NEW.CD_INSQUI_HC
    FROM   dual;
END;