CREATE OR REPLACE TRIGGER HIST_CONSENT_NU_NUME_HCONSEN_1 BEFORE INSERT ON HIST_CONSENT
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_CONSENT_NU_NUME_HCONSENT_.NEXTVAL
    INTO   :NEW.NU_NUME_HCONSENT
    FROM   dual;
END;