CREATE OR REPLACE TRIGGER HIST_ODO_CD_COD_HIODO_TRG BEFORE INSERT ON HIST_ODO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT HIST_ODO_CD_COD_HIODO_SEQ.NEXTVAL
    INTO   :NEW.CD_COD_HIODO
    FROM   dual;
END;