CREATE OR REPLACE TRIGGER HIST_ODONTO_MEJARE_NU_MEJARE_T BEFORE INSERT ON HIST_ODONTO_MEJARE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_ODONTO_MEJARE_NU_MEJARE_S.NEXTVAL
    INTO   :NEW.NU_MEJARE
    FROM   dual;
END;