CREATE OR REPLACE TRIGGER HIST_MEDI_NU_NUME_HMED_TRG BEFORE INSERT ON HIST_MEDI
FOR EACH ROW
DECLARE 
    
    
BEGIN
    SELECT HIST_MEDI_NU_NUME_HMED_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_HMED
    FROM   dual;
END;