CREATE OR REPLACE TRIGGER HIST_NUME_CTRL_NU_NUME_HICL__1 BEFORE INSERT ON HIST_NUME_CTRL
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT HIST_NUME_CTRL_NU_NUME_HICL_HI.NEXTVAL
    INTO   :NEW.NU_NUME_HICL_HINUCTRL
    FROM   dual;
END;