CREATE OR REPLACE TRIGGER HIST_GENO_ARBOL_NU_NUME_ARB_TR BEFORE INSERT ON HIST_GENO_ARBOL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_GENO_ARBOL_NU_NUME_ARB_SE.NEXTVAL
    INTO   :NEW.NU_NUME_ARB
    FROM   dual;

END;