CREATE OR REPLACE TRIGGER HIST_PARTO_EVOL_NU_NUME_HIS__1 BEFORE INSERT ON HIST_PARTO_EVOL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_PARTO_EVOL_NU_NUME_HIS_PA.NEXTVAL
    INTO   :NEW.NU_NUME_HIS_PAR_EVOL
    FROM   dual;
END;