CREATE OR REPLACE TRIGGER HIST_ORTODONCIA_PACIENTE_CD__1 BEFORE INSERT ON HIST_ORTODONCIA_PACIENTE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_ORTODONCIA_PACIENTE_CD_PA.NEXTVAL
    INTO   :NEW.CD_PAC_ORTODONCIA
    FROM   dual;
END;