CREATE OR REPLACE TRIGGER HIST_PERIODONTO_CONSULTAS_CD_1 BEFORE INSERT ON HIST_PERIODONTO_CONSULTAS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_PERIODONTO_CONSULTAS_CD_C.NEXTVAL
    INTO   :NEW.CD_CONS_PER
    FROM   dual;
END;