CREATE OR REPLACE TRIGGER HIST_COIN_NU_AUTO_HCOI_TRG BEFORE INSERT ON HIST_COIN
FOR EACH ROW
DECLARE 
		
BEGIN
	SELECT HIST_COIN_NU_AUTO_HCOI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_HCOI
    FROM   dual;
END;