CREATE OR REPLACE TRIGGER HIST_GENO_PERSONA_ARBOL_NU_N_1 BEFORE INSERT ON HIST_GENO_PERSONA_ARBOL
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_GENO_PERSONA_ARBOL_NU_NUM.NEXTVAL
    INTO   :NEW.NU_NUME_PER_ARB
    FROM   dual;
END;