CREATE OR REPLACE TRIGGER HIST_BITACORA_HORA_NU_NUME_H_1 BEFORE INSERT ON HIST_BITACORA_HORA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_BITACORA_HORA_NU_NUME_HBH.NEXTVAL
    INTO   :NEW.NU_NUME_HBH
    FROM   dual;
END;