CREATE OR REPLACE TRIGGER HIST_ODONTO_PACIENTE_CD_PAC__1 BEFORE INSERT ON HIST_ODONTO_PACIENTE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HIST_ODONTO_PACIENTE_CD_PAC_OD.NEXTVAL
    INTO   :NEW.CD_PAC_ODONTO
    FROM   dual;
END;