CREATE OR REPLACE TRIGGER HORARIO_GRUPO_NU_AUTO_HOGR_TRG BEFORE INSERT ON HORARIO_GRUPO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HORARIO_GRUPO_NU_AUTO_HOGR_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_HOGR
    FROM   dual;
END;