CREATE OR REPLACE TRIGGER HOSPITALIZACION_RIPS_NU_CONS_1 BEFORE INSERT ON HOSPITALIZACION_RIPS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT HOSPITALIZACION_RIPS_NU_CONSE_.NEXTVAL
    INTO   :NEW.NU_CONSE_HOSP
    FROM   dual;
END;