CREATE OR REPLACE TRIGGER INDICADOR_NU_AUTO_INDI_TRG BEFORE INSERT ON INDICADOR
FOR EACH ROW
DECLARE 
    
BEGIN
     SELECT INDICADOR_NU_AUTO_INDI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_INDI
    FROM   dual;
END;