CREATE OR REPLACE TRIGGER INDICADOR_VARIABLE_NU_AUTO_V_1 BEFORE INSERT ON INDICADOR_VARIABLE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT INDICADOR_VARIABLE_NU_AUTO_VAR.NEXTVAL
    INTO   :NEW.NU_AUTO_VAR
    FROM   dual;
END;