CREATE OR REPLACE TRIGGER INDICADORES_REPORTES_SAMA_CD_1 BEFORE INSERT ON INDICADORES_REPORTES_SAMA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT INDICADORES_REPORTES_SAMA_CD_C.NEXTVAL
    INTO   :NEW.CD_COD_IRS
    FROM   dual;
END;