CREATE OR REPLACE TRIGGER INFORMORBILIDAD_INS_NU_AUTO__1 BEFORE INSERT ON INFORMORBILIDAD_INS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT INFORMORBILIDAD_INS_NU_AUTO_IN.NEXTVAL
    INTO   :NEW.NU_AUTO_ININ
    FROM   dual;
END;