CREATE OR REPLACE TRIGGER INSTRUMENTO_CD_INSTRUMENTO_TRG BEFORE INSERT ON INSTRUMENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT INSTRUMENTO_CD_INSTRUMENTO_SEQ.NEXTVAL
    INTO   :NEW.CD_INSTRUMENTO
    FROM   dual;
END;