CREATE OR REPLACE TRIGGER ITEM_ESDE_NU_AUTO_ITES_TRG BEFORE INSERT ON ITEM_ESDE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ITEM_ESDE_NU_AUTO_ITES_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_ITES
    FROM   dual;
END;