CREATE OR REPLACE TRIGGER ITEM_GRUPOETAREO_NU_AUTO_ITG_1 BEFORE INSERT ON ITEM_GRUPOETAREO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ITEM_GRUPOETAREO_NU_AUTO_ITGE_.NEXTVAL
    INTO   :NEW.NU_AUTO_ITGE
    FROM   dual;
END;