CREATE OR REPLACE TRIGGER ITEM_INFORMEMORBILIDAD_NU_AU_1 BEFORE INSERT ON ITEM_INFORMEMORBILIDAD
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ITEM_INFORMEMORBILIDAD_NU_AUTO.NEXTVAL
    INTO   :NEW.NU_AUTO_ITIN
    FROM   dual;
END;