CREATE OR REPLACE TRIGGER LABORATORIO_COT_NU_NUME_LCOT_T BEFORE INSERT ON LABORATORIO_COT
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT LABORATORIO_COT_NU_NUME_LCOT_S.NEXTVAL
    INTO   :NEW.NU_NUME_LCOT
    FROM   dual;
END;