CREATE OR REPLACE TRIGGER LABORATORIO_LAB_CD_AUTO_LAB_TR BEFORE INSERT ON LABORATORIO_LAB
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT LABORATORIO_LAB_CD_AUTO_LAB_SE.NEXTVAL
    INTO   :NEW.CD_AUTO_LAB
    FROM   dual;
END;