CREATE OR REPLACE TRIGGER LIQ_ELIMINADOS_NU_NUME_LIQEL_1 BEFORE INSERT ON LIQ_ELIMINADOS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT LIQ_ELIMINADOS_NU_NUME_LIQELI_.NEXTVAL
    INTO   :NEW.NU_NUME_LIQELI
    FROM   dual;
END;