CREATE OR REPLACE TRIGGER LOG_CAR_MAS_PAC_NU_AUTO_NUME_1 BEFORE INSERT ON LOG_CAR_MAS_PAC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT LOG_CAR_MAS_PAC_NU_AUTO_NUME_L.NEXTVAL
    INTO   :NEW.NU_AUTO_NUME_LCMP
    FROM   dual;
END;