CREATE OR REPLACE TRIGGER LOG_CAMBIO_NUMHISTPAC_NU_AUT_1 BEFORE INSERT ON LOG_CAMBIO_NUMHISTPAC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT LOG_CAMBIO_NUMHISTPAC_NU_AUTO_.NEXTVAL
    INTO   :NEW.NU_AUTO_LOG_CNUHP
    FROM   dual;
END;