CREATE OR REPLACE TRIGGER LOTE_ARTICULO_NU_AUTO_LTAR_TRG BEFORE INSERT ON LOTE_ARTICULO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT LOTE_ARTICULO_NU_AUTO_LTAR_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_LTAR
    FROM   dual;
END;