CREATE OR REPLACE TRIGGER MEDICAMENTOS_RIPS_NU_CONSE_M_1 BEFORE INSERT ON MEDICAMENTOS_RIPS
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT MEDICAMENTOS_RIPS_NU_CONSE_MER.NEXTVAL
    INTO   :NEW.NU_CONSE_MERI
    FROM   dual;
END;