CREATE OR REPLACE TRIGGER MODIF_TIPO_Y_NUM_DOC_ID_MODT_1 BEFORE INSERT ON MODIF_TIPO_Y_NUM_DOC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT MODIF_TIPO_Y_NUM_DOC_ID_MODTIP.NEXTVAL
    INTO   :NEW.ID_MODTIPNUMDOC
    FROM   dual;
END;