CREATE OR REPLACE TRIGGER MOT_CAMB_EST_CAMAS_COD_MOT_TRG BEFORE INSERT ON MOT_CAMB_EST_CAMAS
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT MOT_CAMB_EST_CAMAS_COD_MOT_SEQ.NEXTVAL
    INTO   :NEW.COD_MOT
    FROM   dual;
END;