CREATE OR REPLACE TRIGGER MOTIVOS_ANULACION_CITA_CD_CO_1 BEFORE INSERT ON MOTIVOS_ANULACION_CITA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT MOTIVOS_ANULACION_CITA_CD_CODI.NEXTVAL
    INTO   :NEW.CD_CODI_MOANCI
    FROM   dual;
END;