CREATE OR REPLACE TRIGGER MOTIVO_GLOSA_NU_NUME_MOGL_TRG BEFORE INSERT ON MOTIVO_GLOSA
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT MOTIVO_GLOSA_NU_NUME_MOGL_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_MOGL
    FROM   dual;
END;