CREATE OR REPLACE TRIGGER MOTIVO_CORRECCION_NU_AUTO_MT_1 BEFORE INSERT ON Motivo_correccion
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT Motivo_correccion_NU_AUTO_MTCO.NEXTVAL
    INTO   :NEW.NU_AUTO_MTCO
    FROM   dual;
END;