CREATE OR REPLACE TRIGGER NOPOS_SERV_NU_AUTO_NPSE_TRG BEFORE INSERT ON NOPOS_SERV
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT NOPOS_SERV_NU_AUTO_NPSE_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_NPSE
    FROM   dual;
END;