CREATE OR REPLACE TRIGGER NOTA_ENFERMERIA_NU_AUTO_NOEN_T BEFORE INSERT ON NOTA_ENFERMERIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT NOTA_ENFERMERIA_NU_AUTO_NOEN_S.NEXTVAL
    INTO   :NEW.NU_AUTO_NOEN
    FROM   dual;
END;