CREATE OR REPLACE TRIGGER ODONTO_RELA_NU_AUTO_RELA_TRG BEFORE INSERT ON ODONTO_RELA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ODONTO_RELA_NU_AUTO_RELA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_RELA
    FROM   dual;
END;