CREATE OR REPLACE TRIGGER ORDENO_EXTERNO_NU_COD_ORDEX_TR BEFORE INSERT ON ORDENO_EXTERNO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ORDENO_EXTERNO_NU_COD_ORDEX_SE.NEXTVAL
    INTO   :NEW.NU_COD_ORDEX
    FROM   dual;
END;