CREATE OR REPLACE TRIGGER ORDEN_MAQUINARIA_CD_MAQUINA_TR BEFORE INSERT ON ORDEN_MAQUINARIA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT ORDEN_MAQUINARIA_CD_MAQUINA_SE.NEXTVAL
    INTO   :NEW.CD_MAQUINA
    FROM   dual;
END;