CREATE OR REPLACE TRIGGER ORDEN_ESTERILIZACION_CD_ORDE_1 BEFORE INSERT ON ORDEN_ESTERILIZACION
FOR EACH ROW
DECLARE 
    
BEGIN
     SELECT ORDEN_ESTERILIZACION_CD_ORDENA.NEXTVAL
    INTO   :NEW.CD_ORDENA_ESTERILIZA
    FROM   dual;
END;