CREATE OR REPLACE TRIGGER PAGO_PROGRAMADO_CD_CODI_PAPR_T BEFORE INSERT ON PAGO_PROGRAMADO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PAGO_PROGRAMADO_CD_CODI_PAPR_S.NEXTVAL
    INTO   :NEW.CD_CODI_PAPR
    FROM   dual;
END;