CREATE OR REPLACE TRIGGER PARAMETRIZADOR_LEY_CD_CODI_P_1 BEFORE INSERT ON PARAMETRIZADOR_LEY
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PARAMETRIZADOR_LEY_CD_CODI_PAL.NEXTVAL
    INTO   :NEW.CD_CODI_PAL
    FROM   dual;
END;