CREATE OR REPLACE TRIGGER PERFIL_REPORTE_Pre_Id_TRG BEFORE INSERT ON PERFIL_REPORTE
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT PERFIL_REPORTE_Pre_Id_SEQ.NEXTVAL
    INTO   :NEW.Pre_Id
    FROM   dual;
END;