CREATE OR REPLACE TRIGGER PERFIL_REPORTEXTABLACAMPO_PT_1 BEFORE INSERT ON PERFIL_REPORTEXTABLACAMPO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PERFIL_REPORTEXTABLACAMPO_Ptc_.NEXTVAL
    INTO   :NEW.Ptc_Id
    FROM   dual;
END;