CREATE OR REPLACE TRIGGER PERFILES_NO_CODI_PERF_TRG BEFORE INSERT ON PERFILES
FOR EACH ROW
DECLARE 

BEGIN
    SELECT PERFILES_NO_CODI_PERF_SEQ.NEXTVAL
    INTO   :NEW.NO_CODI_PERF
    FROM   dual;
END;