CREATE OR REPLACE TRIGGER PERFILES_CORREO_NU_AUTO_PECO_T BEFORE INSERT ON PERFILES_CORREO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PERFILES_CORREO_NU_AUTO_PECO_S.NEXTVAL
    INTO   :NEW.NU_AUTO_PECO
    FROM   dual;
END;