CREATE OR REPLACE TRIGGER PRES_MOVIMIENTO_NU_AUTO_PRES_1 BEFORE INSERT ON PRES_MOVIMIENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PRES_MOVIMIENTO_NU_AUTO_PRES_M.NEXTVAL
    INTO   :NEW.NU_AUTO_PRES_MOV
    FROM   dual;
END;