CREATE OR REPLACE TRIGGER PRESENTACION_NU_AUTO_PRES_TRG BEFORE INSERT ON PRESENTACION
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT PRESENTACION_NU_AUTO_PRES_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_PRES
    FROM   dual;
END;