CREATE OR REPLACE TRIGGER PROCED_GLOSA_NU_NUME_PRGL_TRG BEFORE INSERT ON PROCED_GLOSA
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT PROCED_GLOSA_NU_NUME_PRGL_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_PRGL
    FROM   dual;
END;