CREATE OR REPLACE TRIGGER PROCEDIMIENTOS_RIPS_NU_CONSE_1 BEFORE INSERT ON PROCEDIMIENTOS_RIPS
FOR EACH ROW
DECLARE 
    
BEGIN 
    SELECT PROCEDIMIENTOS_RIPS_NU_CONSE_P.NEXTVAL
    INTO   :NEW.NU_CONSE_PRRI
    FROM   dual;
END;