CREATE OR REPLACE TRIGGER PROCESAMIENTO_MUESTRA_CD_COD_1 BEFORE INSERT ON PROCESAMIENTO_MUESTRA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PROCESAMIENTO_MUESTRA_CD_CODI_.NEXTVAL
    INTO   :NEW.CD_CODI_PRM
    FROM   dual;
END;