CREATE OR REPLACE TRIGGER PROCEDIMIENTO_ACADEMICO_ID_I_1 BEFORE INSERT ON PROCEDIMIENTO_ACADEMICO
FOR EACH ROW
DECLARE 
    
BEGIN
     SELECT PROCEDIMIENTO_ACADEMICO_ID_IDE.NEXTVAL
    INTO   :NEW.ID_IDEN_PRA
    FROM   dual;
END;