CREATE OR REPLACE TRIGGER PROG_CIR_CD_CODI_PROG_TRG BEFORE INSERT ON PROG_CIR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT PROG_CIR_CD_CODI_PROG_SEQ.NEXTVAL
    INTO   :NEW.CD_CODI_PROG
    FROM   dual;
END;