CREATE OR REPLACE TRIGGER QUIROFANOS_CD_CODI_QUI_TRG BEFORE INSERT ON QUIROFANOS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT QUIROFANOS_CD_CODI_QUI_SEQ.NEXTVAL
    INTO   :NEW.CD_CODI_QUI
    FROM   dual;
END;