CREATE OR REPLACE TRIGGER QYR_SOLICITUD_RESPUESTA_NU_N_1 BEFORE INSERT ON QYR_SOLICITUD_RESPUESTA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT QYR_SOLICITUD_RESPUESTA_NU_NUM.NEXTVAL
    INTO   :NEW.NU_NUME_SR
    FROM   dual;
END;