CREATE OR REPLACE TRIGGER QYR_ESTADO_SOLICITUD_NU_NUME_1 BEFORE INSERT ON QYR_ESTADO_SOLICITUD
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT QYR_ESTADO_SOLICITUD_NU_NUME_E.NEXTVAL
    INTO   :NEW.NU_NUME_ES
    FROM   dual;
END;