CREATE OR REPLACE TRIGGER QYR_SEGUIMIENTO_NU_NUME_SEG_TR BEFORE INSERT ON QYR_SEGUIMIENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT QYR_SEGUIMIENTO_NU_NUME_SEG_SE.NEXTVAL
    INTO   :NEW.NU_NUME_SEG
    FROM   dual;
END;