CREATE OR REPLACE TRIGGER QYR_COMUNICADO_NU_NUME_COM_TRG BEFORE INSERT ON QYR_COMUNICADO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT QYR_COMUNICADO_NU_NUME_COM_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_COM
    FROM   dual;
END;