CREATE OR REPLACE TRIGGER R_ARTI_ACTI_NU_AUTO_RARA_TRG BEFORE INSERT ON R_ARTI_ACTI
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_ARTI_ACTI_NU_AUTO_RARA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_RARA
    FROM   dual;
END;