CREATE OR REPLACE TRIGGER R_ART_SER_CIR_CD_COD_ARTSERC_1 BEFORE INSERT ON R_ART_SER_CIR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_ART_SER_CIR_CD_COD_ARTSERCIR.NEXTVAL
    INTO   :NEW.CD_COD_ARTSERCIR
    FROM   dual;
END;