CREATE OR REPLACE TRIGGER R_CIR_MOVI_CD_INSQUI_ASIG_TRG BEFORE INSERT ON R_CIR_MOVI
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT R_CIR_MOVI_CD_INSQUI_ASIG_SEQ.NEXTVAL
    INTO   :NEW.CD_INSQUI_ASIG
    FROM   dual;
END;