CREATE OR REPLACE TRIGGER R_MEDI_REEMP_HOGR_NU_AUTO_RM_1 BEFORE INSERT ON R_MEDI_REEMP_HOGR
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_MEDI_REEMP_HOGR_NU_AUTO_RMRH.NEXTVAL
    INTO   :NEW.NU_AUTO_RMRH
    FROM   dual;
END;