CREATE OR REPLACE TRIGGER R_MOVICA_CAMP_NU_AUTO_RMC_TRG BEFORE INSERT ON R_MOVICA_CAMP
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT R_MOVICA_CAMP_NU_AUTO_RMC_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_RMC
    FROM   dual;
END;