CREATE OR REPLACE TRIGGER R_MOVICA_ACTIVI_NU_AUTO_RMA_TR BEFORE INSERT ON R_MOVICA_ACTIVI
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT R_MOVICA_ACTIVI_NU_AUTO_RMA_SE.NEXTVAL
    INTO   :NEW.NU_AUTO_RMA
    FROM   dual;
END;