CREATE OR REPLACE TRIGGER R_MOVICA_ARTIAC_NU_AUTO_RRMA_T BEFORE INSERT ON R_MOVICA_ARTIAC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_MOVICA_ARTIAC_NU_AUTO_RRMA_S.NEXTVAL
    INTO   :NEW.NU_AUTO_RRMA
    FROM   dual;
END;