CREATE OR REPLACE TRIGGER R_PAQU_ELE_NU_AUTO_RPEL_TRG BEFORE INSERT ON R_PAQU_ELE
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT R_PAQU_ELE_NU_AUTO_RPEL_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_RPEL
    FROM   dual;
END;