CREATE OR REPLACE TRIGGER R_PLAN_CON_OR_MED_NUM_R_PLAN_1 BEFORE INSERT ON R_PLAN_CON_OR_MED
FOR EACH ROW
DECLARE 
    
BEGIN
     SELECT R_PLAN_CON_OR_MED_NUM_R_PLAN_C.NEXTVAL
    INTO   :NEW.NUM_R_PLAN_CON_OR_MED
    FROM   dual;
END;