CREATE OR REPLACE TRIGGER R_PLAN_CON_OR_CONTRAREF_NUM__1 BEFORE INSERT ON R_PLAN_CON_OR_CONTRAREF
FOR EACH ROW
DECLARE 
    
BEGIN 
     SELECT R_PLAN_CON_OR_CONTRAREF_NUM_R_.NEXTVAL
    INTO   :NEW.NUM_R_PLAN_CON_OR_CONTRAREF
    FROM   dual;
END;