CREATE OR REPLACE TRIGGER R_PLAN_CONC_AUTO_INC_RPC_TRG BEFORE INSERT ON R_PLAN_CONC
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_PLAN_CONC_AUTO_INC_RPC_SEQ.NEXTVAL
    INTO   :NEW.AUTO_INC_RPC
    FROM   dual;
END;