CREATE OR REPLACE TRIGGER R_SER_ACTI_NU_CONS_RSA_TRG BEFORE INSERT ON R_SER_ACTI
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_SER_ACTI_NU_CONS_RSA_SEQ.NEXTVAL
    INTO   :NEW.NU_CONS_RSA
    FROM   dual;
END;