CREATE OR REPLACE TRIGGER R_SOSE_SERV_NU_AUTO_RSS_TRG BEFORE INSERT ON R_SOSE_SERV
FOR EACH ROW
DECLARE   
   
BEGIN
    SELECT R_SOSE_SERV_NU_AUTO_RSS_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_RSS
    FROM   dual;
END;