CREATE OR REPLACE TRIGGER R_SUBCC_LUAT_DEPE_NU_AUTO_RS_1 BEFORE INSERT ON R_SUBCC_LUAT_DEPE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT R_SUBCC_LUAT_DEPE_NU_AUTO_RSUL.NEXTVAL
    INTO   :NEW.NU_AUTO_RSULADP
    FROM   dual;
END;