CREATE OR REPLACE TRIGGER RECEPCION_TRABAJOS_ID_RECEPC_1 BEFORE INSERT ON RECEPCION_TRABAJOS
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT RECEPCION_TRABAJOS_ID_RECEPCIO.NEXTVAL
    INTO   :NEW.ID_RECEPCION
    FROM   dual;
END;