CREATE OR REPLACE TRIGGER RECIENNACIDO_RIPS_NU_CONSE_N_1 BEFORE INSERT ON RECIENNACIDO_RIPS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT RECIENNACIDO_RIPS_NU_CONSE_NAC.NEXTVAL
    INTO   :NEW.NU_CONSE_NACE
    FROM   dual;
END;