CREATE OR REPLACE TRIGGER REGISTRO_REABIERTO_NU_NUME_R_1 BEFORE INSERT ON REGISTRO_REABIERTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT REGISTRO_REABIERTO_NU_NUME_REG.NEXTVAL
    INTO   :NEW.NU_NUME_REGRE
    FROM   dual;
END;