CREATE OR REPLACE TRIGGER REGISTRO_NU_NUME_REG_TRG BEFORE INSERT ON REGISTRO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT REGISTRO_NU_NUME_REG_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_REG
    FROM   dual;
END;