CREATE OR REPLACE TRIGGER REGISTRO_EVENTO_SINIESTRO_ID_1 BEFORE INSERT ON REGISTRO_EVENTO_SINIESTRO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT REGISTRO_EVENTO_SINIESTRO_ID_R.NEXTVAL
    INTO   :NEW.ID_REG_EVENTO_SIN
    FROM   dual;
END;