CREATE OR REPLACE TRIGGER REGISTRO_CLAP_COD_REG_CLAP_TRG BEFORE INSERT ON REGISTRO_CLAP
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT REGISTRO_CLAP_COD_REG_CLAP_SEQ.NEXTVAL
    INTO   :NEW.COD_REG_CLAP
    FROM   dual;
END;