CREATE OR REPLACE TRIGGER REMISION_TRABAJO_ADSCRITO_NU_1 BEFORE INSERT ON REMISION_TRABAJO_ADSCRITO
FOR EACH ROW
DECLARE 
      
BEGIN
     SELECT REMISION_TRABAJO_ADSCRITO_NU_N.NEXTVAL
    INTO   :NEW.NU_NUME_RETRA
    FROM   dual;
END;