CREATE OR REPLACE TRIGGER REPORTE_PARAMETRIZADO_NU_AUT_1 BEFORE INSERT ON REPORTE_PARAMETRIZADO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT REPORTE_PARAMETRIZADO_NU_AUTO_.NEXTVAL
    INTO   :NEW.NU_AUTO_REPO_PARA
    FROM   dual;
END;