CREATE OR REPLACE TRIGGER RIPS_OTRO_SERVICIO_ID_IDEN_A_1 BEFORE INSERT ON RIPS_OTRO_SERVICIO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT RIPS_OTRO_SERVICIO_ID_IDEN_AT_.NEXTVAL
    INTO   :NEW.ID_IDEN_AT
    FROM   dual;
END;