CREATE OR REPLACE TRIGGER RIPS_USUARIO_ID_IDEN_US_TRG BEFORE INSERT ON RIPS_USUARIO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT RIPS_USUARIO_ID_IDEN_US_SEQ.NEXTVAL
    INTO   :NEW.ID_IDEN_US
    FROM   dual;
END;