CREATE OR REPLACE TRIGGER RIPS_PROCEDIMIENTO_ID_IDEN_A_1 BEFORE INSERT ON RIPS_PROCEDIMIENTO
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT RIPS_PROCEDIMIENTO_ID_IDEN_AP_.NEXTVAL
    INTO   :NEW.ID_IDEN_AP
    FROM   dual;
END;