CREATE OR REPLACE TRIGGER RIPS_CONSULTA_ID_IDEN_AC_TRG BEFORE INSERT ON RIPS_CONSULTA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT RIPS_CONSULTA_ID_IDEN_AC_SEQ.NEXTVAL
    INTO   :NEW.ID_IDEN_AC
    FROM   dual;
END;