CREATE OR REPLACE TRIGGER RIPS_TRANSACCION_ID_IDEN_AF_TR BEFORE INSERT ON RIPS_TRANSACCION
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT RIPS_TRANSACCION_ID_IDEN_AF_SE.NEXTVAL
    INTO   :NEW.ID_IDEN_AF
    FROM   dual;
END;