CREATE OR REPLACE TRIGGER RUTA_ARCHIVO_FISICO_NU_AUTO__1 BEFORE INSERT ON RUTA_ARCHIVO_FISICO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT RUTA_ARCHIVO_FISICO_NU_AUTO_RU.NEXTVAL
    INTO   :NEW.NU_AUTO_RUAR
    FROM   dual;
END;