CREATE OR REPLACE TRIGGER SCOP_OPCION_NU_NUME_SO_TRG BEFORE INSERT ON SCOP_OPCION
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT SCOP_OPCION_NU_NUME_SO_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_SO
    FROM   dual;
END;