CREATE OR REPLACE TRIGGER SCOP_VARIABLE_NU_NUME_SV_TRG BEFORE INSERT ON SCOP_VARIABLE
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SCOP_VARIABLE_NU_NUME_SV_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_SV
    FROM   dual;
END;