CREATE OR REPLACE TRIGGER SEGUIMIENTO_GESTION_SALUD_NU_1 BEFORE INSERT ON SEGUIMIENTO_GESTION_SALUD
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SEGUIMIENTO_GESTION_SALUD_NU_N.NEXTVAL
    INTO   :NEW.NU_NUME_SEGE
    FROM   dual;
END;