CREATE OR REPLACE TRIGGER SICLAP_TRABAJO_PARTO_PAR_NCO_1 BEFORE INSERT ON SICLAP_TRABAJO_PARTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SICLAP_TRABAJO_PARTO_par_ncons.NEXTVAL
    INTO   :NEW.par_nconsecutivo
    FROM   dual;
END;