CREATE OR REPLACE TRIGGER SICLAP_CONTROL_GES_NCONSECUT_1 BEFORE INSERT ON SICLAP_CONTROL
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT SICLAP_CONTROL_ges_nconsecutiv.NEXTVAL
    INTO   :NEW.ges_nconsecutivo
    FROM   dual;
END;