CREATE OR REPLACE TRIGGER SICLAP_EGRESO_EGR_NCONSECUTI_1 BEFORE INSERT ON SICLAP_EGRESO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SICLAP_EGRESO_egr_nconsecutivo.NEXTVAL
    INTO   :NEW.egr_nconsecutivo
    FROM   dual;
END;