CREATE OR REPLACE TRIGGER SICLAP_PARTO_PAR_NCONSECUTIV_1 BEFORE INSERT ON SICLAP_PARTO
FOR EACH ROW
DECLARE 
     
BEGIN
    SELECT SICLAP_PARTO_par_nconsecutivo_.NEXTVAL
    INTO   :NEW.par_nconsecutivo
    FROM   dual;
END;