CREATE OR REPLACE TRIGGER SICLAP_RECIEN_NACIDO_REC_NCO_1 BEFORE INSERT ON SICLAP_RECIEN_NACIDO
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT SICLAP_RECIEN_NACIDO_rec_ncons.NEXTVAL
    INTO   :NEW.rec_nconsecutivo
    FROM   dual;
END;