CREATE OR REPLACE TRIGGER SIGNOS_SINTOMAS_COD_SIG_SIN_TR BEFORE INSERT ON SIGNOS_SINTOMAS
FOR EACH ROW
DECLARE   
  
BEGIN
    SELECT SIGNOS_SINTOMAS_COD_SIG_SIN_SE.NEXTVAL
    INTO   :NEW.COD_SIG_SIN
    FROM   dual;   
END;