CREATE OR REPLACE TRIGGER SIGNOSVITALES_NU_AUTO_SIVI_TRG BEFORE INSERT ON SIGNOSVITALES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SIGNOSVITALES_NU_AUTO_SIVI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_SIVI
    FROM   dual;
END;