CREATE OR REPLACE TRIGGER SIGNOS_VITALES_NO_NUME_SIGVI_T BEFORE INSERT ON SIGNOS_VITALES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SIGNOS_VITALES_NO_NUME_SIGVI_S.NEXTVAL
    INTO   :NEW.NO_NUME_SIGVI
    FROM   dual;
END;