CREATE OR REPLACE TRIGGER SITIO_VACUNACION_NU_NUME_SIV_1 BEFORE INSERT ON SITIO_VACUNACION
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SITIO_VACUNACION_NU_NUME_SIVA_.NEXTVAL
    INTO   :NEW.NU_NUME_SIVA
    FROM   dual;
END;