CREATE OR REPLACE TRIGGER SOLI_CIR_NU_NUME_SOL_CIR_TRG BEFORE INSERT ON SOLI_CIR
FOR EACH ROW
DECLARE 
    
BEGIN 
    SELECT SOLI_CIR_NU_NUME_SOL_CIR_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_SOL_CIR
    FROM   dual;
END;