CREATE OR REPLACE TRIGGER SOLICITUD_MED_NU_NUME_SOLI_S_1 BEFORE INSERT ON SOLICITUD_MED
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SOLICITUD_MED_NU_NUME_SOLI_SME.NEXTVAL
    INTO   :NEW.NU_NUME_SOLI_SMED
    FROM   dual;
END;