CREATE OR REPLACE TRIGGER SP_CONDICION_NU_AUTO_COND_TRG BEFORE INSERT ON SP_CONDICION
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT SP_CONDICION_NU_AUTO_COND_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_COND
    FROM   dual;
END;