CREATE OR REPLACE TRIGGER SP_SUBIDA_NU_AUTO_SUBI_TRG BEFORE INSERT ON SP_SUBIDA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SP_SUBIDA_NU_AUTO_SUBI_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_SUBI
    FROM   dual;
END;