CREATE OR REPLACE TRIGGER SUBTIPOS_ALTERACIONES_NU_AUT_1 BEFORE INSERT ON SUBTIPOS_ALTERACIONES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT SUBTIPOS_ALTERACIONES_NU_AUTO_.NEXTVAL
    INTO   :NEW.NU_AUTO_SUAL
    FROM   dual;
END;