CREATE OR REPLACE TRIGGER Sysfail_NU_AUTO_FAIL_TRG BEFORE INSERT ON Sysfail
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT Sysfail_NU_AUTO_FAIL_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_FAIL
    FROM   dual;
END;