CREATE OR REPLACE TRIGGER TABLA_POBLA_NU_NUME_TPOB_TRG BEFORE INSERT ON TABLA_POBLA
FOR EACH ROW
DECLARE 
    
BEGIN
  SELECT TABLA_POBLA_NU_NUME_TPOB_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_TPOB
    FROM   dual;
END;