CREATE OR REPLACE TRIGGER TBL_ASOCIADO_ID_TABL_ASOC_TRG BEFORE INSERT ON TBL_ASOCIADO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TBL_ASOCIADO_ID_TABL_ASOC_SEQ.NEXTVAL
    INTO   :NEW.ID_TABL_ASOC
    FROM   dual;
END;