CREATE OR REPLACE TRIGGER TBL_CAMBIO_LUGATEN_CD_CAMBIO_1 BEFORE INSERT ON TBL_CAMBIO_LUGATEN
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TBL_CAMBIO_LUGATEN_CD_CAMBIO_L.NEXTVAL
    INTO   :NEW.CD_CAMBIO_LUGATEN
    FROM   dual;
END;