CREATE OR REPLACE TRIGGER TIPO_APLICACION_NU_NUME_TIAP_T BEFORE INSERT ON TIPO_APLICACION
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TIPO_APLICACION_NU_NUME_TIAP_S.NEXTVAL
    INTO   :NEW.NU_NUME_TIAP
    FROM   dual;
END;