CREATE OR REPLACE TRIGGER TIPO_DEPORTES_NU_AUTO_NUME_T_1 BEFORE INSERT ON TIPO_DEPORTES
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TIPO_DEPORTES_NU_AUTO_NUME_TIP.NEXTVAL
    INTO   :NEW.NU_AUTO_NUME_TIPDEP
    FROM   dual;
END;