CREATE OR REPLACE TRIGGER TIPO_LENTE_NU_AUTO_TILE_TRG BEFORE INSERT ON TIPO_LENTE
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TIPO_LENTE_NU_AUTO_TILE_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_TILE
    FROM   dual;
END;