CREATE OR REPLACE TRIGGER TIPO_VEHICULO_ID_TIP_VEHI_TRG BEFORE INSERT ON TIPO_VEHICULO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TIPO_VEHICULO_ID_TIP_VEHI_SEQ.NEXTVAL
    INTO   :NEW.ID_TIP_VEHI
    FROM   dual;
END;