CREATE OR REPLACE TRIGGER TIPO_EVENTO_ID_TIPO_EVENTO_TRG BEFORE INSERT ON TIPO_EVENTO
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TIPO_EVENTO_ID_TIPO_EVENTO_SEQ.NEXTVAL
    INTO   :NEW.ID_TIPO_EVENTO
    FROM   dual;
END;