CREATE OR REPLACE TRIGGER TRATAMIENTOS_NU_NUME_TRAT_TRG BEFORE INSERT ON TRATAMIENTOS
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TRATAMIENTOS_NU_NUME_TRAT_SEQ.NEXTVAL
    INTO   :NEW.NU_NUME_TRAT
    FROM   dual;
END;