CREATE OR REPLACE TRIGGER TRIAGE3i_NU_AUTO_TRIA_TRG BEFORE INSERT ON TRIAGE3i
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TRIAGE3i_NU_AUTO_TRIA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_TRIA
    FROM   dual;
END;