CREATE OR REPLACE TRIGGER TURNO_CAMA_NU_AUTO_TUCA_TRG BEFORE INSERT ON TURNO_CAMA
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TURNO_CAMA_NU_AUTO_TUCA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_TUCA
    FROM   dual;
END;