CREATE OR REPLACE TRIGGER TURNO_SALA_NU_AUTO_TUSA_TRG BEFORE INSERT ON TURNO_SALA
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TURNO_SALA_NU_AUTO_TUSA_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_TUSA
    FROM   dual;
END;