CREATE OR REPLACE TRIGGER TURNO_EQUIPO_DISP_NU_AUTO_TE_1 BEFORE INSERT ON TURNO_EQUIPO_DISP
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TURNO_EQUIPO_DISP_NU_AUTO_TEDI.NEXTVAL
    INTO   :NEW.NU_AUTO_TEDI
    FROM   dual;
END;