CREATE OR REPLACE TRIGGER TURNOS_MEDICOS_NU_NUME_TUME_TR BEFORE INSERT ON TURNOS_MEDICOS
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TURNOS_MEDICOS_NU_NUME_TUME_SE.NEXTVAL
    INTO   :NEW.NU_NUME_TUME
    FROM   dual;
END;