CREATE OR REPLACE TRIGGER TURNO_EQUIPO_NU_AUTO_TUEQ_TRG BEFORE INSERT ON TURNO_EQUIPO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT TURNO_EQUIPO_NU_AUTO_TUEQ_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_TUEQ
    FROM   dual;
END;