CREATE OR REPLACE TRIGGER TURNO_CAMA_DISP_NU_AUTO_TCDI_T BEFORE INSERT ON TURNO_CAMA_DISP
FOR EACH ROW
DECLARE 
      
BEGIN
    SELECT TURNO_CAMA_DISP_NU_AUTO_TCDI_S.NEXTVAL
    INTO   :NEW.NU_AUTO_TCDI
    FROM   dual;
END;