CREATE OR REPLACE TRIGGER TURNO_SALA_DISP_NU_AUTO_TSDI_T BEFORE INSERT ON TURNO_SALA_DISP
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT TURNO_SALA_DISP_NU_AUTO_TSDI_S.NEXTVAL
    INTO   :NEW.NU_AUTO_TSDI
    FROM   dual;
END;