CREATE OR REPLACE TRIGGER UNIDADES_MEDIDA_NU_AUTO_UNME_T BEFORE INSERT ON UNIDADES_MEDIDA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT UNIDADES_MEDIDA_NU_AUTO_UNME_S.NEXTVAL
    INTO   :NEW.NU_AUTO_UNME
    FROM   dual;
END;