CREATE OR REPLACE TRIGGER VALORIZACIONINV_DEPE_NU_AUTO_1 BEFORE INSERT ON VALORIZACIONINV_DEPE
FOR EACH ROW
DECLARE   
    
BEGIN
    SELECT VALORIZACIONINV_DEPE_NU_AUTO_V.NEXTVAL
    INTO   :NEW.NU_AUTO_VAIND
    FROM   dual;
END;