CREATE OR REPLACE TRIGGER VALORIZAINV_NU_AUTO_VAIND_TRG BEFORE INSERT ON VALORIZAINV
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT VALORIZAINV_NU_AUTO_VAIND_SEQ.NEXTVAL
    INTO   :NEW.NU_AUTO_VAIND
    FROM   dual;
END;