CREATE OR REPLACE TRIGGER VEHICULO_ID_VEHICULO_VEHI_TRG BEFORE INSERT ON VEHICULO
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT VEHICULO_ID_VEHICULO_VEHI_SEQ.NEXTVAL
    INTO   :NEW.ID_VEHICULO_VEHI
    FROM   dual;
END;