CREATE OR REPLACE TRIGGER VENTILACION_NO_NUME_VENTI_TRG BEFORE INSERT ON VENTILACION
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT VENTILACION_NO_NUME_VENTI_SEQ.NEXTVAL
    INTO   :NEW.NO_NUME_VENTI
    FROM   dual;
END;