CREATE OR REPLACE TRIGGER VIA_APLICACION_VACUNA_NU_NUM_1 BEFORE INSERT ON VIA_APLICACION_VACUNA
FOR EACH ROW
DECLARE 
    
BEGIN
    SELECT VIA_APLICACION_VACUNA_NU_NUME_.NEXTVAL
    INTO   :NEW.NU_NUME_VIAP
    FROM   dual;
END;