CREATE OR REPLACE TRIGGER VIGILANCIA_SALUD_ID_VISA_TRG BEFORE INSERT ON VIGILANCIA_SALUD
FOR EACH ROW
DECLARE 
  
BEGIN
    SELECT VIGILANCIA_SALUD_ID_VISA_SEQ.NEXTVAL
    INTO   :NEW.ID_VISA
    FROM   dual;
END;