CREATE TABLE HISTCOCINA(
	CODCOCI CHAR(11) NOT NULL,
	EMPRESA CHAR(13) NOT NULL,
	PLATO CHAR(20) NOT NULL,
	CANTIDAD NUMBER NOT NULL,
	FECHA CHAR(10) NOT NULL,
	HORAFIN CHAR(8) NOT NULL,
	ESTADO CHAR(1) NOT NULL 
);