CREATE TABLE TAB_AVATAR_PUESTO_MESA_HIST(
	CONSEC NUMBER NOT NULL,
	MESCOD NUMBER NOT NULL,
	CCOCOD CHAR(3) NOT NULL,
	IMG CHAR(50) NOT NULL,
	SEXOPER CHAR(10) NOT NULL,
	CODCATEPER CHAR(5) NOT NULL,
	PEDNUM1 CHAR(10),
	PEDNUM2 CHAR(10),
	PEDNUM3 CHAR(10),
	PEDNUM4 CHAR(10),
	FECHA CHAR(10) NOT NULL,
	HORA CHAR(8) NOT NULL
);

ALTER TABLE TAB_AVATAR_PUESTO_MESA_HIST ADD (
  CONSTRAINT PK_TAB_AVAT_PUESTO_HIST PRIMARY KEY (CONSEC));

CREATE SEQUENCE SEQ_TAB_AVAT_PUESTO_HIST START WITH 1;

CREATE OR REPLACE TRIGGER AUTO_INCREMENT_TAB_AVAT_HIST 
BEFORE INSERT ON TAB_AVATAR_PUESTO_MESA_HIST 
FOR EACH ROW

BEGIN
  SELECT SEQ_TAB_AVAT_PUESTO_HIST.NEXTVAL
  INTO   :NEW.CONSEC
  FROM   DUAL;
END;