CREATE TABLE TAB_FACTURA_CLIENTE(
	FACNROCLI NUMBER(10) NOT NULL,
	FACNROGRAL NUMBER(10) NOT NULL,
	FACCONS NUMBER NOT NULL,
	FACFECH CHAR(10) NOT NULL,
	FACHORA CHAR(8) NOT NULL,
	FACCEDCLI CHAR(11),
	FACNOMCLI CHAR(60),
	FACCODMES CHAR(10) NOT NULL,	
	FACSUBTOTAL NUMBER,
	FACPROPINA NUMBER,
	FACVALPROPINA NUMBER,
	FACIVA NUMBER,
	FACTOTAL NUMBER
);

ALTER TABLE TAB_FACTURA_CLIENTE
ADD CONSTRAINT CONS_PRMY_TAB_FACTURA_CLIENTE PRIMARY KEY (FACNROCLI, FACNROGRAL, FACCONS);