CREATE TABLE TAB_AVATAR_PUESTO_MESA(
	MESCOD NUMBER NOT NULL,
	CCOCOD CHAR(3) NOT NULL,
	IMG CHAR(50) NOT NULL,
	SEXOPER CHAR(10) NOT NULL,
	CODCATEPER CHAR(5) NOT NULL,
	PEDNUM1 CHAR(10),
	PEDNUM2 CHAR(10),
	PEDNUM3 CHAR(10),
	PEDNUM4 CHAR(10)
);


ALTER TABLE TAB_AVATAR_PUESTO_MESA
ADD CONSTRAINT CONS_PRMY_TAB_AVATAR_PUESTO_ME PRIMARY KEY (MESCOD, CCOCOD);