CREATE TABLE DETMESA(
    MESCOD NUMBER NOT NULL,
    EMPCOD CHAR(13),
   	POSMES VARCHAR2(20),
    PUESTOS NUMBER,
    PRIMARY KEY(MESCOD)
);

ALTER TABLE DETMESA
ADD CONSTRAINT FK_DETMESA_IN00018 
FOREIGN KEY (MESCOD)
REFERENCES INV00018(MESCOD);