CREATE TABLE TAB_FACTURAS_REVERSADAS(
	FACREVNROCLI NUMBER(10) NOT NULL,
	FACREVFECH CHAR(10) NOT NULL,
	FACREVHORA CHAR(8) NOT NULL
);

ALTER TABLE TAB_FACTURAS_REVERSADAS
ADD CONSTRAINT CONS_PRMY_TAB_FACTURA_REVERSADA PRIMARY KEY (FACREVNROCLI);