CREATE TABLE TABCOPYINV00018(
	NUMEROREVER NUMBER,
	MESCOD NUMBER(4,0), 
	MESESTADO CHAR(20), 
	MESDOCREQ CHAR(3), 
	MESNUMREQ CHAR(10), 
	MESNUMREQ2 CHAR(10), 
	MESNUMREQ3 CHAR(10), 
	MESNUMREQ4 CHAR(10), 
	MESUSUREQ CHAR(10), 
	MESHORAPED VARCHAR2(8)
);