CREATE GLOBAL TEMPORARY TABLE TT_CAB_FACTURA_GRAL(
	FACNROGRAL NUMBER(10) NOT NULL,
	FACEMPCGRAL CHAR(13) NOT NULL,
	FACNRO NUMBER(10) NOT NULL,
	FACNUMDOCGRAL CHAR(10) NOT NULL,
	FACFECHA CHAR(10) NOT NULL,
	FACHORA CHAR(8) NOT NULL,
	IVA NUMBER,
	SUBTOTAL NUMBER,
	TOTAL NUMBER

)ON COMMIT PRESERVE ROWS;


