CREATE GLOBAL TEMPORARY TABLE TT_TIME_MESA_CONTAINER(
	CODIGO_MESA NUMBER NOT NULL,
	TIEMPO_CONTAINER1 NUMBER DEFAULT 0,
	TIEMPO_CONTAINER2 NUMBER DEFAULT 0,
	TIEMPO_CONTAINER3 NUMBER DEFAULT 0,
	TIEMPO_CONTAINER4 NUMBER DEFAULT 0
) ON COMMIT PRESERVE ROWS;
