CREATE OR REPLACE PROCEDURE SP_ACOMER_LISTA_PEDIDOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CEDULA IN GEN0011.TERCOD%TYPE,
	OUT_CURSOR_PEDIDOS OUT SYS_REFCURSOR --- LISTA DE LOS PEDUDOS Y SU RESPECTIVO DETALLE
)
AS
	V_EMPRESA  SEG0001.EMPCOD%TYPE;		-- CODIGO DE LA EMPRESA A LA QUE PERTENECE EL COCINERO
	V_COUNT NUMBER;						-- CANTIDAD DE DATOS REGISTRADOS
BEGIN
	SELECT DISTINCT EMPCOD
	INTO V_EMPRESA
	FROM (SELECT EMPCOD
          FROM SEG0001
          WHERE USUCED = '16743485'
            --OR USUID = IN_CEDULA
          ORDER BY EMPCOD DESC)		    
	WHERE ROWNUM = 1;

	OPEN OUT_CURSOR_PEDIDOS FOR
		SELECT VEN0104.PEDNUMDOC NUM_DOCUMENTO, 
		    VEN0104.PEDNRO NUM_PEDIDO,
		    VEN0104.MESCOD COD_MESA, 
		    VEN0004.PEDPROCOD COD_PLATO, 
		    VEN0001.PRODES PLATO,
		    NVL(INV0015.LINDESCATE, 'Sin termino') TERMINO,
		    VEN0001.VENLINCDES DESCRIPCION,
		    VEN0004.PEDCHECK CANTIDAD, 
		    VEN0004.CCOCOD PUESTO
		FROM VEN0104
		INNER JOIN VEN0004
		    ON VEN0004.PEDNRO = VEN0104.PEDNRO
		INNER JOIN VEN0001
		    ON VEN0001.PROCOD = VEN0004.PEDPROCOD
		LEFT JOIN INV0015
		    ON INV0015.LINCODCATE = VEN0004.PEDBODL
		WHERE VEN0104.PEDFECH = TO_CHAR(SYSDATE, 'DD/MM/YYYY')
		    AND VEN0104.PEDMODCOD = 'PEDIDO'
		    AND VEN0104.COTEMPC = V_EMPRESA
		    AND VEN0004.PEDSAL = 'N' 
		ORDER BY NUM_DOCUMENTO, COD_MESA, PUESTO;
END;