CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_EVENT_SINIEST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_ID_TIPO_EVENTO IN NUMBER,
  v_ID_NUM_HIST_PAC IN VARCHAR2,
  v_FECHA IN DATE,
  v_DESCRIPCION IN VARCHAR2,
  v_LUGAR_EVENTO IN VARCHAR2,
  v_PERSONAL_APOYO IN VARCHAR2,
  v_QUIEN_REPORTA IN VARCHAR2,
  v_ELIMINADO IN NUMBER
)
AS

BEGIN

    INSERT INTO REGISTRO_EVENTO_SINIESTRO
    (ID_TIPO_EVENTO, ID_NUM_HIST_PAC, FECHA, DESCRIPCION, LUGAR_EVENTO, PERSONAL_APOYO, QUIEN_REPORTA, ELIMINADO )
    VALUES ( v_ID_TIPO_EVENTO, v_ID_NUM_HIST_PAC, v_FECHA, v_DESCRIPCION, v_LUGAR_EVENTO, v_PERSONAL_APOYO, v_QUIEN_REPORTA, v_ELIMINADO );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;