CREATE OR REPLACE PROCEDURE H3i_SP_EA_CREAR_SEG
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_EVENTO_ADVERSO IN NUMBER,
  v_FECHA IN DATE,
  v_MEMORANDO IN VARCHAR2,
  v_RESPONSABLE IN VARCHAR2,
  v_FECHA_PROXIMA IN DATE
)
AS

BEGIN
   	INSERT INTO EVENTO_ADVERSO_SEGUIMIENTO
     ( CD_EVENTO_ADVERSO_EAS, FE_FECH_EAS, TX_MEMO_EAS, TX_RESP_EAS, FE_FECH_SEGP_EAS )
    VALUES ( v_EVENTO_ADVERSO, v_FECHA, v_MEMORANDO, v_RESPONSABLE, v_FECHA_PROXIMA );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;