CREATE OR REPLACE PROCEDURE H3i_SP_RECU_PACIENT_ANEXO_UNAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_PACIENTE IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR
		SELECT NU_HIST_PAC_PAU, NU_DOCU_PAC_PAU,
			   NU_TIPD_PAC_PAU, CD_CODI_EST_PAU,
			   CD_CODI_PA_PAU, TX_ESTA_SIA_PAU,
			   CD_CODI_DEPE_PAU, TX_ESTA_SARA_PAU,
			   CD_CODI_S_PAU, TX_ESTU_PRAC_CLIN_PAU,
			   TX_ESTU_MOVI_ACAD_PAU, NU_NUME_MATR_PAU,
			   TX_GRADO_PAU, TX_TELE_PROC_PAU,
			   TX_LOC_PAU, CD_TIUS_PAU,
			   TX_TURN_PAU, NU_CARG_PAU,
			   NU_REGI_PAU, NU_DESP_PAU,
			   DE_PRAP_RES_PAU, DE_SGAP_RES_PAU,
			   NU_NOMB_RES_PAU, NU_SGNO_RES_PAU,
			   NU_CEL_RES_PAU, NU_VINC_PAU,
			   CalcularEdad (FE_NACI_PAC, SYSDATE, 0) AS EDAD,
			   CalcularEdad (FE_NACI_PAC, SYSDATE, 1) AS UME,
			   CASE 
					WHEN NVL(TO_CHAR(NU_NUME_REG_PAC), 0) = 0 THEN 1 
						ELSE ( 
								SELECT NU_TIAT_REG 
								FROM REGISTRO 
								WHERE NU_NUME_REG = NU_NUME_REG_PAC 
								AND NU_ESCU_REG <> 2 
								AND ID_ESTA_ASIS_REG <> '1'
							 )
			   END AMBITO_ATENCION,
			   NU_SEXO_PAC,
			   NU_ACCESO_PAU, DE_NOMB_ACCE_PAU,
			   TX_APERTURA_PAU, NU_CODI_BLOQ_PAU,
			   DE_NOMB_BLOQ_PAU, FE_BLOQ_PAU,
			   TX_PERI_BLOQ_PAU, TX_CONVO_PAU,
			   TX_DIRE_PROC_PAU, NU_CODI_EXPE_PAU,
			   DE_NIVEL_PAU, NU_CODI_SUBACC_PAU,
			   DE_SUBACC_APU, NU_PBM_PAU,
			   NU_CODI_FAC_PAU,	DEP.DE_DESC_DEPE AS DE_NOM_FAC_PAU,
			   NU_CODI_CARR_PAU, PA.TX_NOMB_PA AS DE_NOM_CARR_PAU,
			   CD_CODI_MUNI_PAU, CD_CODI_PAIS_PAU,
			   CD_CODI_DPTO_PAU, NU_HIST_PAC,
			   NU_TIPD_PAC,
			   RTRIM(LTRIM(TO_CHAR(NU_DOCU_PAC))) AS NU_DOCU_PAC,
			   DE_PRAP_PAC, DE_SGAP_PAC,
			   NO_NOMB_PAC, NO_SGNO_PAC,
			   FE_NACI_PAC, CD_CODI_DPTO_PAC,
			   CD_CODI_MUNI_PAC, DE_DIRE_PAC,
			   DE_TELE_PAC, NU_ESCI_PAC,
			   FE_HIST_PAC, NU_SITU_PAC,
			   CD_CODI_CAM_PAC,
			   NVL(TO_CHAR(NU_NUME_REG_PAC), 0) AS NU_NUME_REG_PAC,
			   NU_NIVE_PAC, NU_ESTA_PAC,
			   CD_CODI_ZORE_PAC, CD_CODI_LUAT_PAC,
			   DE_EMAIL_PAC, CD_CODI_OCUP_PAC,
			   NVL(TO_CHAR(NU_CONS_HIST_PAC), 0) AS NU_CONS_HIST_PAC,
			   NVL(TO_CHAR(NU_TIPO_PAC), 0) AS NU_TIPO_PAC,
			   CD_CODI_RELI_PAC, CD_CODI_BAR_PAC,
			   NVL(TO_CHAR(NU_GEST_PAC),0) AS NU_GEST_PAC,
			   FE_FECHMOD_AUDIT, TX_USUA_PAC,
			   CD_CODI_DPTO_TRAB_PAC, CD_CODI_MUNI_TRAB_PAC,
			   CD_CODI_DPTO_NACI_PAC, CD_CODI_MUNI_NACI_PAC,
			   TX_TELTRAB_PAC, TX_DIRTRAB_PAC,
			   TX_NOMBRESP_PAC, CD_CODI_PARE_PAC,
			   TX_DIRRESP_PAC, TX_TELRESP_PAC,
			   ME_INFOAD_PAC, NU_FALLE_PAC,
			   CD_CODI_ESCO_PAC, CD_CODI_PAIS_PAC,
			   CD_CODI_PAIS_NACI_PAC, CD_CODI_PAIS_TRAB_PAC,
			   NU_ACTI_EPS_PAC, NU_TERC_PAC,
			   TX_NOMBRECOMPLETO_PAC, NU_DATOS_EXT_PAC,
			   DE_CELU_PAC, TX_CODIGO_ETNI_PACI,
			   TX_DISCAPACIDAD_PACI, NU_AUTO_TIRH,
			   CD_CODI_LOC_PAC, INFO_PAC_COMPLETA,
			   DE_OTRO_TELE_PAC, FECH_INI_PAU,
			   FECH_FIN_PAU, TIENE_AHC
		FROM PACIENTES_ANEXO_UNAL
		INNER JOIN PACIENTES 
			ON (NU_HIST_PAC = NU_HIST_PAC_PAU)
		LEFT JOIN PROGRAMA_ACADEMICO PA 
			ON CD_CODI_PA_PAU = PA.CD_CODI_PA
		LEFT JOIN DEPENDENCIA DEP 
			ON CD_CODI_DEPE_PAU = DEP.CD_CODI_DEPE
		WHERE NU_HIST_PAC_PAU = V_PACIENTE;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;