CREATE OR REPLACE PROCEDURE H3i_SP_EA_EDITAR_MEJORA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_ID_MEJORA IN NUMBER,
  v_EVENTO_ADVERSO IN NUMBER,
  v_MEMORANDO IN VARCHAR2,
  v_RESPONSABLE IN VARCHAR2,
  v_FECHA IN DATE
)
AS

BEGIN

   UPDATE EVENTO_ADVERSO_MEJORA
      SET CD_EVENTO_ADVERSO_EAM = v_EVENTO_ADVERSO,
          TX_MEMO_EAM = v_MEMORANDO,
          TX_RESP_EAM = v_RESPONSABLE,
          FE_FECH_SEG_EAM = v_FECHA
    WHERE  NU_NUME_EAM = v_ID_MEJORA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;