CREATE OR REPLACE PROCEDURE H3i_SP_SIGNOSVITALES_EVOL_CREA --PROCEDIMIENTO ALMACENADO QUE PERMITE GUARDAR UN REGISTRO PARA SIGNOS VITALES 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_HEVO_SIVI IN NUMBER,
  v_NU_NUME_HEVO_SIVI IN NUMBER,
  v_NU_AUTO_SIVI IN NUMBER,
  v_NU_VALOR_SIVI IN VARCHAR2
)
AS

BEGIN

	INSERT INTO HISTEVOL_SIGNOSVITALES( 
		NU_NUME_HICL_HEVO_SIVI, NU_NUME_HEVO_SIVI, NU_AUTO_SIVI, NU_VALOR_SIVI )
	VALUES ( 
		v_NU_NUME_HICL_HEVO_SIVI, v_NU_NUME_HEVO_SIVI, v_NU_AUTO_SIVI, v_NU_VALOR_SIVI );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;