CREATE OR REPLACE PROCEDURE H3i_SP_CONSU_REGIST_ADMIS_CONV -- PROCEDIMIENTO ALMACENADO QUE PERMITE RECUPERAR EL CONVENIO DE UN REGISTRO DE ADMISION 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_REG_RECO IN NUMBER,
  v_NU_NUME_CONV_RECO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT * 
		FROM R_REGISTRO_CONV 
		WHERE  NU_NUME_REG_RECO = v_NU_NUME_REG_RECO
		AND NU_NUME_CONV_RECO = v_NU_NUME_CONV_RECO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;