CREATE OR REPLACE PROCEDURE H3i_SP_RECUPERAR_SIG_SIN /*PROCEDIMIENTO ALMACENADO QUE PERMITE RECUPERAR LOS SIGNOS Y SINTOMAS */
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO_SISTEMA IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT COD_SIG_SIN ,
			COD_SIS_SIG_SIN ,
			NOM_SIG_SIN ,
			TIPO_TRIAGE 
		FROM SIGNOS_SINTOMAS 
		WHERE  COD_SIS_SIG_SIN = v_CODIGO_SISTEMA ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;