CREATE GLOBAL TEMPORARY TABLE TT_LABORATORIOS_PAC(    
    NU_NUME_LABO NUMBER(22),
    NU_NUME_MOVI_LABO NUMBER(22),
    CD_CODI_SER_LABO VARCHAR2(12),
    CT_CANT_LABO NUMBER(22),
    VL_UNID_LABO FLOAT(22),
    VL_COPA_LABO FLOAT(22),
    ID_ESTA_ASIS_LABO VARCHAR2(1),
    NO_NOMB_SER VARCHAR2(255),
    NO_NOMB_MED VARCHAR2(70),
    CD_CODI_ESP_LABO VARCHAR2(3),
    CD_CODI_MEDI_LABO VARCHAR2(10),
    NU_AUTO_LABO VARCHAR2(50),
    CD_CODI_COSE_SER VARCHAR2(2)
) ON COMMIT DELETE ROWS;
