CREATE OR REPLACE PROCEDURE H3i_SP_RECU_TODOS_PRES_ELMNTS
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CV_1 OUT SYS_REFCURSOR
)
				   
AS 
BEGIN
	OPEN CV_1 FOR 
		SELECT ID_ELEMENTO,
			DESCRIPCION,
			ID_TIP_ELEMENTO
		FROM PRES_ELEMENTOS;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
