CREATE OR REPLACE PROCEDURE H3i_SP_CREA_RIPS_TRANSACCION
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_CD_PREST_AF IN VARCHAR2,
    v_RAZON_SOCIAL IN VARCHAR2,
    v_TIPO_IDEN IN VARCHAR2,
    v_NU_IDEN IN VARCHAR2,
    v_NU_FACTURA IN VARCHAR2,
    v_FECHA_EXPED IN DATE,
    v_FECHA_INI IN DATE,
    v_FECHA_FIN IN DATE,
    v_CD_EPS IN VARCHAR2,
    v_NOMBRE_EPS IN VARCHAR2,
    v_CONTRATO IN VARCHAR2,
    v_PLAN_BENEFICIO IN VARCHAR2,
    v_POLIZA IN VARCHAR2,
    v_COPAGO IN NUMBER,
    v_VALOR_COMISION IN NUMBER,
    v_VALOR_DESCUENTO IN NUMBER,
    v_VALOR_NETO IN NUMBER
)
AS

BEGIN

    INSERT INTO RIPS_TRANSACCION( 
        CD_PREST_AF, TX_RAZON_SOCIAL_AF, 
        TI_IDEN_AF, NU_IDEN_AF, 
        NU_FAC_AF, FE_EXPED_AF, 
        FE_INI_AF, FE_FIN_AF, 
        CD_NIT_EPS_AF, NO_NOM_EPS_AF, 
        NU_CONTR_AF, DE_PLAN_BENE_AF, 
        NU_POLI_AF, VL_COPA_AF, 
        VL_COMI_AF, VL_TL_DESC_AF, 
        VL_NETO_AF )
    VALUES( 
        v_CD_PREST_AF, v_RAZON_SOCIAL, 
        v_TIPO_IDEN, v_NU_IDEN, 
        v_NU_FACTURA, v_FECHA_EXPED, 
        v_FECHA_INI, v_FECHA_FIN, 
        v_CD_EPS, v_NOMBRE_EPS, 
        v_CONTRATO, v_PLAN_BENEFICIO, 
        v_POLIZA, v_COPAGO, 
        v_VALOR_COMISION, v_VALOR_DESCUENTO, 
        v_VALOR_NETO );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;