CREATE OR REPLACE PROCEDURE H3i_SP_RECU_NUM_REPE_RESULT1
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NU_NUME_RESU VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
	
AS
BEGIN

	OPEN CV_1 FOR
		SELECT NVL(MAX(TO_NUMBER(NU_NUME_REPE_RESU))+1,1) REPETICION 
		FROM RESULTADOS1 
		WHERE NU_NUME_RESU = V_NU_NUME_RESU;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);	
END;
 