CREATE OR REPLACE PROCEDURE H3i_SP_INSER_RESERVA_ESP_LAB
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_HORA_INICIO_RLAB IN DATE,
  v_HORA_FINAL_RLAB IN DATE,
  v_ES_GRUPAL_RLAB IN NUMBER,
  v_NU_AUTO_ESP_RLAB IN NUMBER,
  v_CD_CODI_MED_RES_RLAB IN VARCHAR2
)
AS

BEGIN

	INSERT INTO RESERVA_LAB( 
		HORA_INICIO_RLAB, HORA_FINAL_RLAB, 
		ES_GRUPAL_RLAB, NU_AUTO_ESP_RLAB, 
		CD_CODI_MED_RES_RLAB )
	VALUES( 
		v_HORA_INICIO_RLAB, v_HORA_FINAL_RLAB, 
		v_ES_GRUPAL_RLAB, v_NU_AUTO_ESP_RLAB, 
		v_CD_CODI_MED_RES_RLAB );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;