CREATE PROCEDURE H3i_SP_ACTPROCMUESIMPRILABCLIN
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_CODI_PRM IN NUMBER,
	V_FE_FECH_IMPR_MUES_PRM IN DATE,
	V_HO_HORA_IMPR_MUES_PRM IN VARCHAR2,
	V_CD_MEDI_IMPR_PRM IN VARCHAR2
) 
					
AS
BEGIN
		
	UPDATE PROCESAMIENTO_MUESTRA
	SET FE_FECH_IMPR_MUES_PRM = V_FE_FECH_IMPR_MUES_PRM,
		HO_HORA_IMPR_MUES_PRM = V_HO_HORA_IMPR_MUES_PRM,
		CD_MEDI_IMPR_PRM = V_CD_MEDI_IMPR_PRM,
		CD_CODI_ESM_PRM = '3'
	WHERE CD_CODI_PRM = V_CD_CODI_PRM;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
		
