CREATE OR REPLACE PROCEDURE H3i_ELIM_CAT_PROF_SUMIN_AUDIT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_COD_CATAL_PS IN NUMBER
)
AS

BEGIN

	DELETE AUDITAR_ESTA_FECHA_CAT_PROFE_S
	WHERE  COD_CATAL_PS_AEFCPS = v_COD_CATAL_PS;


	DELETE AUDITAR_CATALOGO_PROFE_SUMIN
	WHERE  COD_CATAL_PS = v_COD_CATAL_PS;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;