CREATE OR REPLACE PROCEDURE H3i_SP_RECUPERAR_ESP_LAB
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_AUTO_LAB IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT NU_AUTO_ESP ,
			IDENTIFICADOR 
		FROM ESPACIO_LAB 
		WHERE  CD_AUTO_LAB_ESP = v_CD_AUTO_LAB
		ORDER BY NU_AUTO_ESP ASC ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;