CREATE OR REPLACE PROCEDURE H3i_SP_ELIMINAR_RELAESGGEG3i
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_TX_CODIGO_GEGL_REG IN VARCHAR2,
  v_TX_CODIGO_ESGL_REG IN VARCHAR2
)
AS

BEGIN

   	DELETE R_ESG_GEG
    WHERE  LTRIM(TX_CODIGO_GEGL_REG) = LTRIM(v_TX_CODIGO_GEGL_REG)
        AND LTRIM(TX_CODIGO_ESGL_REG) = LTRIM(v_TX_CODIGO_ESGL_REG);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;