CREATE OR REPLACE PROCEDURE H3i_SP_CREA_RIPS_OTRO_SERVICIO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_FACTURA IN VARCHAR2,
  v_PRESTADOR IN VARCHAR2,
  v_TIPO_IDEN IN VARCHAR2,
  v_NU_IDEN IN VARCHAR2,
  v_AUTORIZACION IN VARCHAR2,
  v_TIPO_SERVICIO IN VARCHAR2,
  v_CODIGO_SERVICIO IN VARCHAR2,
  v_SERVICIO IN VARCHAR2,
  v_CANTIDAD IN VARCHAR2,
  v_VALOR_UNITARIO IN VARCHAR2,
  v_VALOR_TOTAL_MATERIAL IN VARCHAR2
)
AS

BEGIN

    INSERT INTO RIPS_OTRO_SERVICIO( 
        NU_FACT_AT, CD_PRES_AT, 
        TI_IDEN_US_AT, NU_IDEN_US_AT, 
        NU_AUTO_AT, TI_SERV_AT, 
        CD_SERV_AT, NO_SERV_AT, 
        NU_CANT_AT, VL_UNIT_AT, 
        VL_TL_MATE_AT )
    VALUES ( 
        v_NU_FACTURA, v_PRESTADOR, 
        v_TIPO_IDEN, v_NU_IDEN, 
        v_AUTORIZACION, v_TIPO_SERVICIO, 
        v_CODIGO_SERVICIO, v_SERVICIO, 
        v_CANTIDAD, v_VALOR_UNITARIO, 
        v_VALOR_TOTAL_MATERIAL );


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;