CREATE OR REPLACE PROCEDURE H3i_SP_INC_ACT_SECCIONS_LABCLI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIGO IN VARCHAR2,
	V_CODIGO_AREA IN VARCHAR2,
	V_NOMBRE IN VARCHAR2,  
	V_DESCRIPCION IN VARCHAR2,
	V_ESTADO IN NUMBER   
)

AS   
	CONTADOR NUMBER := 0;
BEGIN
	SELECT COUNT(*) 
	INTO  CONTADOR
	FROM SECCIONES 
	WHERE CD_CODI_SEC = V_CODIGO;

	IF (CONTADOR >= 1) THEN
		BEGIN  
			UPDATE SECCIONES
			SET NO_NOMB_SEC = V_NOMBRE,
				NO_DESC_SEC = V_DESCRIPCION,
				CODIGO_ARLAB_SEC = V_CODIGO_AREA,
				ESTADO_SEC = V_ESTADO
			WHERE CD_CODI_SEC = V_CODIGO;
		END;
	ELSE
		INSERT INTO SECCIONES(
			CD_CODI_SEC,
			NO_NOMB_SEC,
			NO_DESC_SEC,
			CODIGO_ARLAB_SEC,
			ESTADO_SEC)
		VALUES(
			V_CODIGO,
			V_NOMBRE,
			V_DESCRIPCION,
			V_CODIGO_AREA,
			V_ESTADO);
	END IF;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;    