CREATE OR REPLACE PROCEDURE H3i_SP_CONS_EXAM_RECEP_MUESTRA 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NU_HIST_PAC IN VARCHAR2 DEFAULT NULL,
	V_FECHA_INI IN DATE DEFAULT NULL,
	V_FECHA_FIN IN DATE DEFAULT NULL,
	CV_1 OUT SYS_REFCURSOR
)
					
AS
BEGIN
	
	OPEN CV_1 FOR
		SELECT NU_NUME_IND_SER, 
			CD_CODI_CONV,
			TX_NOMBRECOMPLETO_PAC,
			NU_DOCU_PAC,
			NU_HIST_PAC,
			CD_CODI_SER,
			NO_NOMB_SER,
			NU_CANT_HPRO,
			NO_NOMB_MED,
			NU_NUME_LABO_HPRO,
			NU_NUME_MOVI_HPRO,
			FE_FECH_MOVI
		FROM HIST_PROC 
		INNER JOIN SERVICIOS 
			ON CD_CODI_SER_HPRO = CD_CODI_SER
		INNER JOIN MOVI_CARGOS 
			ON NU_NUME_MOVI = NU_NUME_MOVI_HPRO
		INNER JOIN PACIENTES 
			ON NU_HIST_PAC = NU_HIST_PAC_MOVI
		INNER JOIN CONVENIOS 
			ON NU_NUME_CONV = NU_NUME_CONV_MOVI	
		INNER JOIN MEDICOS MO 
			ON CD_CODI_MED = CD_MEDI_ORDE_MOVI
		LEFT JOIN PROCESAMIENTO_MUESTRA 
			ON NU_NUME_LABO_HPRO = NU_NUME_LABO_PRM 
			AND NU_NUME_MOVI_HPRO = NU_NUME_MOVI_PRM
		WHERE NU_HIST_PAC = NVL(V_NU_HIST_PAC, NU_HIST_PAC) 
			AND	NU_TIPO_HPRO = 2 
			AND CD_CODI_PRM IS NULL
			AND	FE_FECH_HPRO BETWEEN NVL(V_FECHA_INI, FE_FECH_HPRO)  AND NVL(V_FECHA_FIN, FE_FECH_HPRO);


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;