CREATE OR REPLACE PROCEDURE H3i_ELIMFECHESTCATPROFSUMIAUDI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_COD_NUM_ESTA_AEFCPS NUMBER	
)
					
AS
BEGIN
	
	DELETE FROM AUDITAR_ESTA_FECHA_CAT_PROFE_S
    WHERE COD_NUM_ESTA_AEFCPS = V_COD_NUM_ESTA_AEFCPS;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;	