CREATE OR REPLACE PROCEDURE H3i_SP_CON_DETGLOSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN  cv_1 FOR
		SELECT NU_AUTO_DEGL ,
			NU_AUTO_GLOS_DEGL ,
			NU_NUME_FACU_DEGL ,
			NU_TIPOFACU_DEGL ,
			TX_CODIGO_GEGL_DEGL ,
			TX_CODIGO_ESGL_DEGL ,
			TX_OBSERVACION_DEGL ,
			NU_NUME_MOVI_DEGL ,
			NU_IDDETALLEMOVI_DEGL ,
			NU_VALOR_DEGL ,
			NU_VALORACEPTADO_DEGL ,
			GENERAL_GLOSA3i.TX_NOMBRE_GEGL ,
			ESPECIFICO_GLOSA3i.TX_NOMBRE_ESGL 
		FROM DETALLE_GLOSA3i 
		INNER JOIN GENERAL_GLOSA3i    
			ON TX_CODIGO_GEGL = DETALLE_GLOSA3i.TX_CODIGO_GEGL_DEGL
		INNER JOIN ESPECIFICO_GLOSA3i    
			ON TX_CODIGO_ESGL = DETALLE_GLOSA3i.TX_CODIGO_ESGL_DEGL
		WHERE  NU_AUTO_GLOS_DEGL = v_CODIGO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;