CREATE OR REPLACE PROCEDURE H3i_SP_CREA_GRALGLOSA3i
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_TX_CODIGO_GEGL IN VARCHAR2,
  v_TX_NOMBRE_GEGL IN VARCHAR2,
  v_NU_ESTADO_GEGL IN NUMBER
)
AS

BEGIN

   	INSERT INTO GENERAL_GLOSA3i( 
   		TX_CODIGO_GEGL, TX_NOMBRE_GEGL, NU_ESTADO_GEGL )
    VALUES( 
    	v_TX_CODIGO_GEGL, v_TX_NOMBRE_GEGL, v_NU_ESTADO_GEGL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;