CREATE OR REPLACE PROCEDURE H3i_SP_CREA_LABORATORIO /*PROCEDIMIENTO ALMACENADO QUE PERMITE CREAR UN LABORATORIO*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_CODIGO OUT NUMBER,
    v_COD_CARGO IN NUMBER DEFAULT NULL ,
    v_CANTIDAD IN NUMBER DEFAULT NULL ,
    v_VALOR_UNITARIO IN FLOAT DEFAULT NULL ,
    v_VAL_CUOTA_MODERADORA IN FLOAT DEFAULT NULL ,
    v_COD_SERVICIO IN VARCHAR2 DEFAULT NULL ,
    v_ESPECIALIDAD IN VARCHAR2 DEFAULT NULL ,
    v_COD_MEDICO_REALIZA IN VARCHAR2 DEFAULT NULL ,
    v_NIVEL IN NUMBER DEFAULT NULL ,
    v_ESTADO IN NUMBER DEFAULT NULL ,
    v_NO_AUTORIZACION IN VARCHAR2 DEFAULT NULL ,
    v_TIPO_DIAGNOSTICO IN VARCHAR2 DEFAULT NULL ,
    v_CAUSA_EXTERNA IN VARCHAR2 DEFAULT NULL ,
    v_DIAS_INCAPACIDAD IN NUMBER DEFAULT NULL ,
    v_VIA_ACCESO IN VARCHAR2 DEFAULT NULL ,
    v_COD_SALA IN VARCHAR2 DEFAULT NULL ,
    v_TIPO_ANESTESIA IN VARCHAR2 DEFAULT NULL ,
    v_USO_EN_HISTORIA_CLINICA IN NUMBER DEFAULT NULL ,
    v_EDAD_PACIENTE IN NUMBER DEFAULT NULL ,
    v_COMPLETO_PARA_RIPS IN VARCHAR2 DEFAULT NULL ,
    v_FINALIDAD_PROCEDIMIENTO IN VARCHAR2 DEFAULT NULL ,
    v_FINALIDAD_CONSULTA IN VARCHAR2 DEFAULT NULL ,
    v_CONEXION_ANULA IN NUMBER DEFAULT NULL ,
    v_FECHA_ANULA IN DATE DEFAULT NULL 
)
AS

BEGIN

    INSERT INTO LABORATORIO(
        NU_NUME_MOVI_LABO, CT_CANT_LABO, 
        VL_UNID_LABO, VL_COPA_LABO, 
        CD_CODI_SER_LABO, CD_CODI_ESP_LABO, 
        CD_CODI_MEDI_LABO, NU_NIVE_LABO, 
        NU_ESTA_LABO, NU_AUTO_LABO, 
        ID_CODI_TIDI_LABO, ID_CODI_CAEX_LABO, 
        NU_DIIN_LABO, CD_CODI_VIAC_LABO, 
        CD_CODI_SALA_LABO, CD_CODI_TIAN_LABO, 
        NU_ESHI_LABO, NU_EDAD_LABO, 
        ID_ESTA_ASIS_LABO, TX_CODI_RRTT_LABO, 
        TX_CODI_RFF_LABO, NU_CONE_ANUL_LABO, 
        FE_ANUL_LABO )
    VALUES ( 
        v_COD_CARGO, v_CANTIDAD, 
        v_VALOR_UNITARIO, v_VAL_CUOTA_MODERADORA, 
        v_COD_SERVICIO, v_ESPECIALIDAD, 
        v_COD_MEDICO_REALIZA, v_NIVEL, 
        v_ESTADO, v_NO_AUTORIZACION, 
        v_TIPO_DIAGNOSTICO, v_CAUSA_EXTERNA, 
        v_DIAS_INCAPACIDAD, v_VIA_ACCESO, 
        v_COD_SALA, v_TIPO_ANESTESIA, 
        v_USO_EN_HISTORIA_CLINICA, v_EDAD_PACIENTE, 
        v_COMPLETO_PARA_RIPS, v_FINALIDAD_PROCEDIMIENTO, 
        v_FINALIDAD_CONSULTA, v_CONEXION_ANULA, 
        v_FECHA_ANULA );

    SELECT NU_NUME_LABO 
    INTO v_CODIGO 
    FROM LABORATORIO
    WHERE NU_NUME_LABO = (SELECT MAX(NU_NUME_LABO) FROM LABORATORIO);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;