CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_ANULACION_ADS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_FECH_ANUL IN DATE,
    v_NU_DOCU_USUA_ANUL IN VARCHAR2,
    v_CD_IDEN_READ IN NUMBER,
    v_CD_CODI_AUTORIZA_AUAD_ANUL IN VARCHAR2,
    v_TX_JUSTIFICACION_AUAD_ANUL IN VARCHAR2,
    v_VL_DESCONTADO_PRE_AUAD_UNAL IN NUMBER
)
AS
    v_NU_AUTO_AUAD NUMBER(10,0);

BEGIN

    UPDATE AUTORIZACION_ADSCRITOS
    SET NU_ESTA_ANULA_AUAD = 0
    WHERE  NU_AUTO_AUAD IN( SELECT AUTORIZACION_ADSCRITOS.NU_AUTO_AUAD 
                            FROM REGISTRO_ADSCRITO 
                            INNER JOIN AUTORIZACION_ADSCRITOS    
                                ON AUTORIZACION_ADSCRITOS.CD_CODI_AUTORIZA_AUAD = REGISTRO_ADSCRITO.TXT_COD_BARRA_READ
                            WHERE  REGISTRO_ADSCRITO.CD_IDEN_READ = v_CD_IDEN_READ );
    
    SELECT NU_AUTO_AUAD 
    INTO v_NU_AUTO_AUAD
    FROM REGISTRO_ADSCRITO 
    INNER JOIN AUTORIZACION_ADSCRITOS    
        ON CD_CODI_AUTORIZA_AUAD = TXT_COD_BARRA_READ
    WHERE  CD_IDEN_READ = v_CD_IDEN_READ 
        AND ROWNUM <= 1;


    INSERT INTO ANULACION_AUTORIZACION_ADS( 
        FECH_ANUL, NU_DOCU_USUA_ANUL, 
        NU_AUTO_AUAD, CD_CODI_AUTORIZA_AUAD_ANUL, 
        TX_JUSTIFICACION_AUAD_ANUL, VL_DESCONTADO_PRE_AUAD_UNAL)
    VALUES( 
        v_FECH_ANUL, v_NU_DOCU_USUA_ANUL, 
        v_NU_AUTO_AUAD, v_CD_CODI_AUTORIZA_AUAD_ANUL, 
        v_TX_JUSTIFICACION_AUAD_ANUL, v_VL_DESCONTADO_PRE_AUAD_UNAL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;