CREATE OR REPLACE PROCEDURE H3i_ICEBERGHMLGCN_ACT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_CODI_ICEBERG IN VARCHAR2,
	V_NO_NOMB_ICEBERG IN VARCHAR2
)
	
AS
	V_CODIGO NUMBER;
BEGIN
	
	SELECT COUNT(1) 
	INTO V_CODIGO
	FROM ICEBERG_REFERENCIAS 
	WHERE CD_CODI_ICEBERG = V_CD_CODI_ICEBERG;

	
	IF V_CODIGO = 0 THEN
    	BEGIN
			INSERT INTO ICEBERG_REFERENCIAS 
			VALUES (V_CD_CODI_ICEBERG,V_NO_NOMB_ICEBERG);
    	END;
    ELSE
    	BEGIN
      		UPDATE ICEBERG_REFERENCIAS SET NO_NOMB_ICEBERG = V_NO_NOMB_ICEBERG
        	WHERE CD_CODI_ICEBERG = V_CD_CODI_ICEBERG;
    	END; 
    END IF;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;