CREATE OR REPLACE PROCEDURE H3i_SP_ACTUALIZAR_AUTORIZACION
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_AUTORIZACION IN VARCHAR2,
  v_NUME_RETRA IN VARCHAR2
)
AS

BEGIN

   	UPDATE REMISION_TRABAJO_ADSCRITO
    SET NU_AUTO_RETRA = v_AUTORIZACION
    WHERE  NU_HIST_PAC_RETRA = v_NUME_RETRA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;