CREATE OR REPLACE PROCEDURE H3i_SP_CONS_CABECERA_GLOSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_ID_GLOSA IN NUMBER,
    cv_1 OUT SYS_REFCURSOR
)
AS
    --DECLARE @ID_GLOSA AS INT = 6
    v_ID_ESTADO_GLOSA NUMBER(10,0);
    v_NOMBRE_ESTADO NVARCHAR2(500);
    v_NIT_ADSCRITO NVARCHAR2(50);

BEGIN

    SELECT NU_AUTO_ESGL_GLOS 
    INTO v_ID_ESTADO_GLOSA
    FROM GLOSA3i 
    WHERE  NU_AUTO_GLOS = v_ID_GLOSA;


    SELECT TX_NOMBRE_ESGLO 
    INTO v_NOMBRE_ESTADO
    FROM ESTADO_GLOSA3i 
    WHERE  NU_AUTO_ESGLO = v_ID_ESTADO_GLOSA;


    SELECT CD_NIT_EPS_GLOS
    INTO v_NIT_ADSCRITO
    FROM GLOSA3i 
    WHERE  NU_AUTO_GLOS = v_ID_GLOSA;


    OPEN  cv_1 FOR
        SELECT ADSCRITOS.DE_NOMB_ADSC NOMBRE_ADSCRITO  ,
            ADSCRITOS.CD_CODI_ADSC NIT_ADSCRITO  ,
            FACTURA_ADSCRITO.* ,
            v_ID_ESTADO_GLOSA ID_ESTADO_GLOSA  ,
            v_NOMBRE_ESTADO NOMBRE_ESTADO  
        FROM FACTURA_ADSCRITO 
        INNER JOIN ADSCRITOS    
            ON ADSCRITOS.NU_CONSE_ADSC = FACTURA_ADSCRITO.NU_CONSE_ADSC_FAAD
        WHERE  ADSCRITOS.CD_CODI_ADSC = v_NIT_ADSCRITO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;