CREATE OR REPLACE PROCEDURE H3i_SP_CREA_ESPECIGLOSA3i
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_TX_CODIGO_ESGL IN VARCHAR2,
  v_TX_NOMBRE_ESGL IN VARCHAR2,
  v_NU_ESTADO_ESGL IN NUMBER
)
AS

BEGIN

   	INSERT INTO ESPECIFICO_GLOSA3i( 
   		TX_CODIGO_ESGL, TX_NOMBRE_ESGL, NU_ESTADO_ESGL )
    VALUES( 
    	v_TX_CODIGO_ESGL, v_TX_NOMBRE_ESGL, v_NU_ESTADO_ESGL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;