CREATE PROCEDURE H3i_SP_OBTN_DET_FACTCNT_CREDIT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIGO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
   
AS
BEGIN
	OPEN CV_1 FOR
		SELECT MOVI_CARGOS.NU_NUME_MOVI Codigo,
			SERVICIOS.NO_NOMB_SER Descripcion,
			FACTURAS_CONTADO.NU_CONS_MOVI_FACO Cantidad,   
			MOVI_CARGOS.VL_UNID_MOVI vunitario,
			(MOVI_CARGOS.VL_UNID_MOVI - MOVI_CARGOS.VL_COPA_MOVI) vtotal,
			MOVI_CARGOS.VL_COPA_MOVI vcopago
		FROM PACIENTES PACIENTES 
		CROSS JOIN ((LABORATORIO LABORATORIO
			INNER JOIN MOVI_CARGOS MOVI_CARGOS 
				ON (LABORATORIO.NU_NUME_MOVI_LABO = MOVI_CARGOS.NU_NUME_MOVI))
			INNER JOIN FACTURAS_CONTADO FACTURAS_CONTADO 
				ON (MOVI_CARGOS.NU_NUME_FACO_MOVI = FACTURAS_CONTADO.NU_NUME_FACO))
		INNER JOIN SERVICIOS SERVICIOS 
			ON (SERVICIOS.CD_CODI_SER = LABORATORIO.CD_CODI_SER_LABO)
		INNER JOIN FACTURAS_CONTADO_CREDITO 
			ON NU_AUTO_FCCR_FACO = NU_AUTO_FCCR
		WHERE NU_AUTO_FCCR_FACO = V_CODIGO
		GROUP BY MOVI_CARGOS.NU_NUME_MOVI,SERVICIOS.NO_NOMB_SER,
			FACTURAS_CONTADO.NU_CONS_MOVI_FACO,MOVI_CARGOS.VL_UNID_MOVI,
			FACTURAS_CONTADO.VL_TOTA_FACO,MOVI_CARGOS.VL_COPA_MOVI;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;