CREATE OR REPLACE PROCEDURE H3I_ICEBERGSERPORNOMB_CON
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NO_NOMB_SER IN VARCHAR2,
  	V_CD_CODI_ESP IN VARCHAR2,
  	CV_1 OUT SYS_REFCURSOR
)
 
AS
BEGIN
	OPEN CV_1 FOR
		SELECT CD_CODI_SER,NO_NOMB_SER 
		FROM SERVICIOS 
		INNER JOIN R_esp_ser RES 
			ON CD_CODI_SER_RES = CD_CODI_SER 
		WHERE RES.CD_CODI_ESP_RES = V_CD_CODI_ESP
		  	AND NO_NOMB_SER LIKE '%' + V_NO_NOMB_SER + '%';

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;