CREATE OR REPLACE PROCEDURE H3i_SP_REPORTE_AUTORIZACIONES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_FECHAINI IN DATE,
    v_FECHAFIN IN DATE,
    cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN  cv_1 FOR
        SELECT NU_TIPD_PAC ,
            NU_TIPO_DOC TIPODOC  ,
            NU_DOCU_PAC ,
            TX_NOM_COMPLE PACIEN  ,
            CD_CODI_ESP_LABO ,
            NO_NOMB_ESP ESPECI  ,
            CD_CODI_MED_MOVI ,
            NO_NOMB_MED PROFES  ,
            ( SELECT EPS.NO_NOMB_EPS 
              FROM CONVENIOS CONVENIOS
              INNER JOIN EPS EPS   
                  ON CONVENIOS.CD_NIT_EPS_CONV = EPS.CD_NIT_EPS
              INNER JOIN MOVI_CARGOS MOV   
                  ON MOV.NU_NUME_CONV_MOVI = CONVENIOS.NU_NUME_CONV
              WHERE  MOV.NU_NUME_MOVI = MOVI_CARGOS.NU_NUME_MOVI 
                  AND ROWNUM <= 1 ) ADMINI  ,
            ( SELECT CONVENIOS.CD_NOMB_CONV 
              FROM MOVI_CARGOS MOV
              INNER JOIN CONVENIOS CONVENIOS   
                  ON MOV.NU_NUME_CONV_MOVI = CONVENIOS.NU_NUME_CONV
              WHERE  MOV.NU_NUME_MOVI = MOVI_CARGOS.NU_NUME_MOVI ) CONVEN  ,
            FE_AUTORIZA_AUAD ,
            NU_NUME_MOVI ,
            (NVL(VAL_PAGPAC_AUAD, 0) + NVL(VAL_PAGCONV_AUAD, 0)) VALOR  ,
            NVL(PORC_CUBRIMIENTO_AUAD, 0) PORC_CUBRIMIENTO_AUAD  ,
            NVL(VAL_PAGPAC_AUAD, 0) VAL_PAGPAC_AUAD  ,
            NVL(VAL_PAGCONV_AUAD, 0) VAL_PAGCONV_AUAD  ,
            NU_ESTA_ANULA_AUAD ,
            CD_CODI_AUTORIZA_AUAD ,
            AUTORIZACION_ADSCRITOS.NU_AUTO_AUAD ,
            NVL(AUTORIZACION_ADSCRITOS.CD_CODI_COAD_AUAD, ' ') CD_CODI_COAD_AUAD  ,
            NVL(AUTORIZACION_ADSCRITOS.CD_CODI_ADSC_AUAD, ' ') CD_CODI_ADSC_AUAD  ,
            NVL(DE_NOMB_COAD, ' ') DE_NOMB_COAD  ,
            TX_NOM_ADSCR_READ DE_NOMB_ADSC  ,
            FE_VENCI_READ ,
            ID_ANUL 
        FROM REGISTRO_ADSCRITO 
        INNER JOIN AUTORIZACION_ADSCRITOS    
            ON CD_CODI_AUTORIZA_AUAD = TXT_COD_BARRA_READ
        INNER JOIN PACIENTES    
            ON NU_HIST_PAC = NU_HIST_PAC_READ
        -- se pone en relacion al documento contra la historia de registro_autorizacion, por problema en codigo (NO_DOCU_PAC) 
        INNER JOIN R_LABO_AUTO    
            ON NU_AUTO_AUAD_LAAU = AUTORIZACION_ADSCRITOS.NU_AUTO_AUAD
        INNER JOIN LABORATORIO    
            ON NU_NUME_LABO_LAAU = NU_NUME_LABO
        INNER JOIN ESPECIALIDADES    
            ON CD_CODI_ESP = CD_CODI_ESP_LABO
        INNER JOIN MOVI_CARGOS   
            ON NU_NUME_MOVI_LABO = NU_NUME_MOVI
        LEFT JOIN ANULACION_AUTORIZACION_ADS AAA   
            ON TXT_COD_BARRA_READ = AAA.CD_CODI_AUTORIZA_AUAD_ANUL
        LEFT JOIN MEDICOS    
            ON CD_CODI_MED_MOVI = CD_CODI_MED
        INNER JOIN CONVENIO_ADSC    
            ON CD_CODI_COAD = CD_CODI_COAD_AUAD
        WHERE  AAA.ID_ANUL IS NULL
            AND FE_AUTORIZA_AUAD BETWEEN v_FECHAINI AND v_FECHAFIN
        ORDER BY FE_AUTORIZA_AUAD ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;