CREATE TABLE SPTYT.AUDITAR_REGISTRO_GLOSADO
(
  AUTO_REG_GLOSA                 NUMBER(19)     NOT NULL,
  COD_AUDI_DOCUM_ARG             NUMBER(19)     NOT NULL,
  IDEN_USUARIO_ARG               VARCHAR2(30 CHAR) NOT NULL,
  VALOR_FACTURADO_ARG            NUMBER(38,2),
  VALOR_GLOSADO_ARG              NUMBER(38,2),
  VALOR_PAGAR_ARG                NUMBER(38,2),
  DE_OBSERVACION_ARG             VARCHAR2(4000),
  ESTADO_ARG                     NUMBER(10)     DEFAULT (0)                   NOT NULL,
  CAUSA_CODIGO_CONCIL_ARG        VARCHAR2(20 CHAR),
  VALOR_FACTUR_CONCIL_ARG        NUMBER(38,2),
  VALOR_GLOSADA_CONCIL_ARG       NUMBER(38,2),
  VALOR_RATIFIC_CONCIL_ARG       NUMBER(38,2),
  VALOR_LEVANTADA_CONCIL_ARG     NUMBER(38,2),
  VALOR_ACEPTADO_CONCIL_ARG      NUMBER(38,2),
  VALOR_MANTENIDO_CONCIL_ARG     NUMBER(38,2),
  VALOR_PAGAR_CONCIL_ARG         NUMBER(38,2),
  DE_OBSERV_CONCIL_ARG           VARCHAR2(4000),
  ESTADO_CONCIL_ARG              NUMBER(10),
  DE_OBSERV_OTRAINST_CONCIL_ARG  VARCHAR2(4000),
  FE_FECHA_ARG                   DATE           DEFAULT SYSDATE               NOT NULL,
  BT_ES_TUTELA                   NUMBER(1)      DEFAULT (0)                   NOT NULL,
  BT_ES_CTC                      NUMBER(1)      DEFAULT (0)                   NOT NULL,
  COD_REG_GLO_PADRE              NUMBER(19),
  IDEN_USUARIO_FARM_ARG          VARCHAR2(30 CHAR),
  BT_CONCILIA_MASIVO             NUMBER(1)      DEFAULT (0)                   NOT NULL,
  VALOR_ACEPTADO_ULT_RESP_OPL    NUMBER(38,2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;