CREATE TABLE SPTYT.AUDITAR_RESPUESTA_DOCU_OBJET
(
  AUTO_RESP_DOC_OBJ        NUMBER(19)           NOT NULL,
  CODIGO_DOC_OBJETADO      NUMBER(19)           NOT NULL,
  IDEN_USUARIO_RESP_RDO    VARCHAR2(30 CHAR)    NOT NULL,
  TXT_RESPUESTA_RDO        VARCHAR2(4000 CHAR)  NOT NULL,
  FECHA_RESP_RDO           DATE                 NOT NULL,
  NU_NUM_RESPUESTA         NUMBER(10)           NOT NULL,
  NU_VALOR_RATIFICADO_RDO  NUMBER(18,2),
  NU_VALOR_LEVANTADO_RDO   NUMBER(18,2),
  DE_CAUSAL_RDO            VARCHAR2(4000),
  DE_OBSERVACION           VARCHAR2(4000),
  DE_OBSERVACION_RDO       VARCHAR2(4000),
  NU_VALOR_ACEPTADO_RDO    NUMBER(18,2),
  BT_ACEPTA_TODO           NUMBER(1)            DEFAULT (0)                   NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;