CREATE OR REPLACE PROCEDURE H3i_SP_CONS_AGEN_CITS_ATD_XEST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_FECHAINICIAL IN DATE,
	V_FECHAFINAL IN DATE,
	V_CODESTUDIANTE IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
 )

AS
BEGIN

	OPEN CV_1 FOR 
		SELECT CD_CODI_MED_CIT,
			CD_CODI_SER_CIT,
			NU_HIST_PAC_CIT,
			NU_DURA_CIT,
			FE_ELAB_CIT,
			FE_FECH_CIT,
			NU_DIA_CIT,
			TO_NUMBER(NU_NUME_MOVI_CIT) NU_NUME_MOVI_CIT,
			TO_NUMBER(NU_PRIM_CIT) NU_PRIM_CIT,
			FE_HORA_CIT,
			TO_NUMBER(NU_ESTA_CIT) NU_ESTA_CIT,
			TO_NUMBER(NU_NUME_CONE_CIT) NU_NUME_CONE_CIT,
			NU_CONE_CALL_CIT,
			CD_CODI_ESP_CIT,
			CD_CODI_CONS_CIT,
			TO_NUMBER(NU_NUME_CONV_CIT) NU_NUME_CONV_CIT,
			TO_NUMBER(NU_TIPO_CIT) NU_TIPO_CIT,
			DE_DESC_CIT,
			TO_NUMBER(CITAS_MEDICAS.NU_NUME_CIT) NU_NUME_CIT,
			CD_MEDI_ORDE_CIT,
			TO_NUMBER(NU_CONFIR_CIT) NU_CONFIR_CIT,
			NO_NOMB_SER,
			NO_NOMB_ESP,
			NU_OPCI_SER,
			NU_NIVE_SER,
			NU_ESGRUPAL_SER,
			M.NO_NOMB_MED AS NOM_ESTUD,
			NVL(CC.NU_NUME_CC, -1) AS CONFIRMACION, -- Agregado
			CITAS_MEDICAS.TX_CAUSA_INASISTENCIA,
			CX.USUARIO AS CAJERO
		FROM CITAS_MEDICAS 
		INNER JOIN SERVICIOS 
			ON CD_CODI_SER_CIT = CD_CODI_SER
		INNER JOIN MEDICOS M 
			ON CD_CODI_MED = CD_CODI_MED_EST_CIT
		INNER JOIN ESPECIALIDADES 
			ON CD_CODI_ESP = CD_CODI_ESP_CIT
		INNER JOIN CONEXIONES CX 
			ON CX.NU_NUME_CONE = CITAS_MEDICAS.NU_NUME_CONE_CIT
		--	INNER JOIN USUARIOS US ON US.ID_IDEN_USUA = CX.USUARIO
		LEFT JOIN CITAS_CONFIRMADAS CC 
			ON CITAS_MEDICAS.NU_NUME_CIT = CC.NU_NUME_CIT
		INNER JOIN HISTORIACLINICA HC 
			ON HC.CD_MED_REAL_HICL = M.CD_CODI_MED
		WHERE FE_FECH_CIT BETWEEN V_FECHAINICIAL 
			AND V_FECHAFINAL
			AND	M.NU_DOCU_MED = NVL(V_CODESTUDIANTE, CD_CODI_MED_EST_CIT)
		GROUP BY CD_CODI_MED_CIT,
			CD_CODI_SER_CIT,
			NU_HIST_PAC_CIT,
			NU_DURA_CIT,
			FE_ELAB_CIT,
			FE_FECH_CIT,
			NU_DIA_CIT,
			NU_NUME_MOVI_CIT,
			NU_PRIM_CIT,
			FE_HORA_CIT,
			NU_ESTA_CIT,
			NU_NUME_CONE_CIT,
			NU_CONE_CALL_CIT,
			CD_CODI_ESP_CIT,
			CD_CODI_CONS_CIT,
			NU_NUME_CONV_CIT,
			NU_TIPO_CIT,
			DE_DESC_CIT,
			CITAS_MEDICAS.NU_NUME_CIT,
			CD_MEDI_ORDE_CIT,
			NU_CONFIR_CIT,
			NO_NOMB_SER,
			NO_NOMB_ESP,
			NU_OPCI_SER,
			NU_NIVE_SER,
			NU_ESGRUPAL_SER,
			M.NO_NOMB_MED,
			NVL(CC.NU_NUME_CC, -1),
			CITAS_MEDICAS.TX_CAUSA_INASISTENCIA,
			CX.USUARIO
		ORDER	BY FE_FECH_CIT;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;