CREATE PROCEDURE H3i_SP_LIST_LISTA_ESPERA_CIT_MED
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHA_INI IN DATE DEFAULT NULL,       
	V_FECHA_FIN IN DATE DEFAULT NULL,       
	V_NU_ESTA_LECM IN NUMBER DEFAULT NULL,
	CV_1 OUT SYS_REFCURSOR
)

AS

BEGIN
	OPEN CV_1 FOR 
		SELECT NU_AUTO_LECM,
	      	NU_HIST_PAC_LECM,
	      	CD_CODI_ESP_LECM,
	      	CD_CODI_MED_LECM,
	      	ID_IDEN_USUA_LECM,
	      	FE_FECH_LECM,
	      	NU_ESTA_LECM,
		  	TX_NOMBRECOMPLETO_PAC,
		  	NO_NOMB_ESP,
		  	NO_NOMB_MED,
		  	NO_NOMB_USUA,
		  	NU_TIPD_PAC,
		  	NU_DOCU_PAC
		FROM LISTA_ESPERA_CITA_MEDICA 
		INNER JOIN PACIENTES 
			ON NU_HIST_PAC = NU_HIST_PAC_LECM
		INNER JOIN ESPECIALIDADES 
			ON CD_CODI_ESP = CD_CODI_ESP_LECM
		INNER JOIN MEDICOS 
			ON CD_CODI_MED = CD_CODI_MED_LECM
		INNER JOIN USUARIOS 
			ON ID_IDEN_USUA = ID_IDEN_USUA_LECM
		WHERE NU_ESTA_LECM = NVL(V_NU_ESTA_LECM, NU_ESTA_LECM) 
			AND FE_FECH_LECM BETWEEN NVL(V_FECHA_INI, FE_FECH_LECM) 
			AND NVL(V_FECHA_FIN, FE_FECH_LECM);


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;