CREATE OR REPLACE PROCEDURE H3i_SP_RECU_PREPARACIONE_CITA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_CIT IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    INSERT INTO tt_v_PREPARACIONES_2 (
        SELECT DISTINCT SP.CD_CODI_PREP_SER 
        FROM CITAS_MEDICAS CM
        INNER JOIN SERVICIOS_PREPARACIONES_CITA SPC   
            ON CM.NU_NUME_CIT = SPC.NU_NUME_CIT
        INNER JOIN SERVICIOS_PREPARACION SP   
            ON SPC.CD_CODI_PREP_SER = SP.CD_CODI_PREP_SER
        WHERE  SPC.NU_NUME_CIT = v_NU_NUME_CIT);

   OPEN  cv_1 FOR
      SELECT TX_DESC_PREPARACION 
      FROM SERVICIOS_PREPARACION 
      WHERE  CD_CODI_PREP_SER IN( SELECT CD_CODI_PREP_SER 
                                  FROM tt_v_PREPARACIONES_2);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;