CREATE PROCEDURE SP_REPORTESFULL
(
	@IN_CODIGO_OPN VARCHAR(10),
	@IN_FECHA_INI DATE,
	@IN_FECHA_FIN DATE
)
AS
	EXEC SP_REPORTE3 @IN_CODIGO_OPN = @IN_CODIGO_OPN, @IN_FECHA_INI = @IN_FECHA_INI , @IN_FECHA_FIN = @IN_FECHA_FIN 
	EXEC SP_REPORTE2 @IN_CODIGO_OPN = @IN_CODIGO_OPN, @IN_FECHA_INI = @IN_FECHA_INI , @IN_FECHA_FIN = @IN_FECHA_FIN 
GO