BEGIN
	-- NUMERO DEL MES INICIAL Y FINAL (PARAMETROS DE ENTRADA)
	DECLARE @FECHA1 VARCHAR(10) = '01-01-2015';
	DECLARE @FECHA2 VARCHAR(10) = '10-04-2015';
	DECLARE @CODIGO VARCHAR(10) = 'AUT_PAG';
	-- CADENA CONSULTA
	DECLARE @CADENA VARCHAR(100) = 'FOR [MES] IN (';
	DECLARE @MESINI INT = MONTH(CONVERT(datetime,@FECHA1,103));
	DECLARE @MESFIN INT = MONTH(CONVERT(datetime,@FECHA2,103));
	
	-- ==============
	-- CICLO PARA MOSTRAR LA CANTIDAD DE MESES X
	DECLARE @CONTADOR INT = @MESINI;
	WHILE (@CONTADOR < @MESFIN)
	BEGIN
		SET @CADENA = @CADENA + '['+CONVERT(VARCHAR,@CONTADOR)+']';
		SET @CONTADOR = @CONTADOR + 1;
	END

	SET @CADENA = @CADENA + ')';	
	

	SELECT @CADENA;
END