CREATE OR REPLACE FUNCTION  FN_TablaDocumentosGlosados
(
    USUARIOFARM IN VARCHAR, 
    ESTADO IN INT
)
    RETURN TYPE_TAB_DocumensGlosados
IS
    V_TABLA  TYPE_TAB_DocumensGlosados := TYPE_TAB_DocumensGlosados();
    -------------------------------------
    TYPE RECORDTYPE IS RECORD (
        COL1 NUMBER(19), COL2 VARCHAR2(4000), 
        COL3 NUMBER(19), COL4 NUMBER(19),
        COL5 NUMBER(38,2), COL6 NUMBER(38,2),
        COL7 NUMBER(38,2), COL8 NUMBER(10),
        COL9 DATE, COL10 VARCHAR2(30),
        COL11 VARCHAR2(20)
        );
    -------------------------------------        
    
CURSOR CV_1 IS
SELECT
COD_AUDI_DOCUM_ARG,
DE_OBSERVACION_ARG, 
AUTO_REG_GLOSA,
COD_AUDI_DOCUM_ARG,
VALOR_FACTURADO_ARG,
VALOR_GLOSADO_ARG,
VALOR_PAGAR_ARG,
ESTADO_ARG,
FE_FECHA_ARG,
IDEN_USUARIO_FARM_ARG,
CAUSA_CODIGO_CONCIL_ARG
FROM AUDITAR_REGISTRO_GLOSADO ARG 
INNER JOIN AUDITAR_DOCUMENTO ON ARG.COD_AUDI_DOCUM_ARG = COD_AUDI_DOCUM                                      
WHERE ESTADO_ARG = ESTADO
AND IDEN_USUARIO_FARM_ARG = NVL(USUARIOFARM, IDEN_USUARIO_FARM_ARG)
AND (DOC_FUE_REPORTADO IS NULL OR DOC_FUE_REPORTADO = 0)
AND ROWNUM <= 20
ORDER BY VALOR_FACTURADO_ARG DESC;    
-------------------------------------        
OUTTABLE RECORDTYPE;    

BEGIN
    
    OPEN CV_1;
    FETCH CV_1 INTO OUTTABLE;

    WHILE CV_1%FOUND
    LOOP
        V_TABLA.EXTEND;
        V_TABLA(V_TABLA.LAST) := TYPE_FN_TablaDocumenGlosados(
                OUTTABLE.COL1, OUTTABLE.COL2,
                OUTTABLE.COL3, OUTTABLE.COL4,
                OUTTABLE.COL5, OUTTABLE.COL6,
                OUTTABLE.COL7, OUTTABLE.COL8,
                OUTTABLE.COL9, OUTTABLE.COL10,
                OUTTABLE.COL11
            );
        FETCH CV_1 INTO OUTTABLE;
    END LOOP;

    CLOSE CV_1;

    RETURN V_TABLA;

        
EXCEPTION 
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;





--CREACION DEL TYPO COMO OBJECTO QUE SERA LA TABLA
CREATE TYPE TYPE_FN_TablaDocumenGlosados AS OBJECT (
    COD_AUDI_DOCUM_ARG NUMBER(19), 
    DE_OBSERVACION_ARG VARCHAR2(4000), 
    AUTO_REG_GLOSA NUMBER(19), 
    COD_AUDI_DOCUM_ARG_2 NUMBER(19),
    VALOR_FACTURADO_ARG NUMBER(38,2), 
    VALOR_GLOSADO_ARG NUMBER(38,2),
    VALOR_PAGAR_ARG NUMBER(38,2), 
    ESTADO_ARG NUMBER(10),
    FE_FECHA_ARG DATE, 
    IDEN_USUARIO_FARM_ARG VARCHAR2(30),
    COLCAUSA_CODIGO_CONCIL_ARG11 VARCHAR2(20)
);

--CREACION DEL TYPE COMO UNA TBLA DE ESE TIPOP
CREATE TYPE TYPE_TAB_DocumensGlosados IS TABLE OF TYPE_FN_TablaDocumenGlosados;

