CREATE OR REPLACE PROCEDURE H3i_CONSUL_ARCH_ADS_REIMP_XPAC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NUM_HIST_PAC IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)	 
AS
BEGIN
	
	OPEN CV_1 FOR
		SELECT DISTINCT CD_IDEN_READ, 
			CD_CODI_AUTORIZA_AUAD, 
			FE_AUTORIZA_AUAD, TX_NOM_ADSCR_READ,
			USUARIO, 
			TX_NOMBRECOMPLETO_PAC, 
			NU_ESTA_ANULA_AUAD, 
			ID_ANUL,
			NVL (VAL_PAGCONV_AUAD, 0) VAL_PAGCONV_AUAD,
			NVL (CD_CODI_COAD_AUAD, '') CD_CODI_COAD_AUAD,
			NVL (CD_CODI_ADSC_AUAD, '') CD_CODI_ADSC_AUAD
		FROM AUTORIZACION_ADSCRITOS AA 
		INNER JOIN REGISTRO_ADSCRITO 
			ON CD_CODI_AUTORIZA_AUAD = TXT_COD_BARRA_READ
		INNER JOIN PACIENTES 
			ON  NU_HIST_PAC = NU_HIST_PAC_READ 
		inner join CONEXIONES 
			ON NU_NUME_CONE = NU_NUME_CONE_AUAD
		LEFT JOIN ANULACION_AUTORIZACION_ADS AAA 
			ON TXT_COD_BARRA_READ = AAA.CD_CODI_AUTORIZA_AUAD_ANUL
		WHERE NU_HIST_PAC = V_NUM_HIST_PAC;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;