CREATE OR REPLACE PROCEDURE H3i_ICEBERG_FACONCTRLPRINT_ACT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NU_NUME_FACO IN NUMBER,
	V_NU_NUME_IMPRE OUT NUMBER
)
AS
	V_IMPRESION NUMBER;
BEGIN	

	SELECT MAX(NU_NUME_IMPRE) 
	INTO V_IMPRESION
	FROM ICEBERG_FACTURAS_CONTADO 
	WHERE NU_NUME_FACO = V_NU_NUME_FACO;

	UPDATE ICEBERG_FACTURAS_CONTADO 
	SET NU_NUME_IMPRE = V_IMPRESION + 1 
	WHERE NU_NUME_FACO = V_NU_NUME_FACO;

	SELECT MAX(NU_NUME_IMPRE) NU_NUME_IMPRE 
	INTO V_NU_NUME_IMPRE
	FROM ICEBERG_FACTURAS_CONTADO 
	WHERE NU_NUME_FACO = V_NU_NUME_FACO;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;