CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_CARGO_ADSC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_NU_NUME_MOVI_CAAD IN NUMBER,
    v_NU_TIPO_CAAD IN NUMBER,
    v_CD_CODI_ARTI_CAAD IN VARCHAR2 DEFAULT NULL ,
    --@NU_NUME_COAD_CAAD int ,
    v_NU_AUTO_CAAD IN VARCHAR2 DEFAULT NULL ,
    v_CT_CANT_CAAD IN NUMBER,
    v_VL_UNID_CAAD IN FLOAT
)
AS

BEGIN

    INSERT INTO CARGOS_ADSCRITO( 
        NU_NUME_MOVI_CAAD, NU_TIPO_CAAD, CD_CODI_ARTI_CAAD, 
        NU_AUTO_CAAD, CT_CANT_CAAD, VL_UNID_CAAD )
    VALUES ( 
        v_NU_NUME_MOVI_CAAD, v_NU_TIPO_CAAD, v_CD_CODI_ARTI_CAAD, 
        v_NU_AUTO_CAAD, v_CT_CANT_CAAD, v_VL_UNID_CAAD );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;