
CREATE OR REPLACE PROCEDURE H3i_SP_OBT_NUM_CONC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CV_1 OUT SYS_REFCURSOR
)
AS
	V_ULTIMO_NUM_CONCE NUMBER;
	V_EXISTE NUMBER;
BEGIN
	SELECT COUNT (NO_NUM_CONCE_READ)
	INTO V_EXISTE
	FROM REGISTRO_ADSCRITO;

	IF(V_EXISTE <> 0) THEN

		BEGIN
			
			SELECT MAX(NO_NUM_CONCE_READ) AS ULTIMO_NUM_AUTORIZACION 
			INTO ULTIMO_NUM_CONCE
			FROM REGISTRO_ADSCRITO;
			
		END;

	ELSE

		BEGIN
		  	V_ULTIMO_NUM_CONCE := 0;
		END;

	END IF;

	
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;								