create or replace PROCEDURE SP_ACOMER_VISUALIZA_FAC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_MESA IN INV00018.MESCOD%TYPE,  -- CODIGO DE LA MESA DEL PEDIDO 	
	IN_PUESTOS_ARRAY IN TYPE_PEDIDOS_ARRAY,	-- PUESTOS QUE SE VAN A FACTURAR
	OUT_CURSOR_VISUALIZA OUT SYS_REFCURSOR,   -- CURSOR CON LOS DATOS DE LA CABECERA DE FACTURA
	OUT_FECHA OUT VARCHAR2
)
AS
BEGIN
	-- SE REALIZA LA CONSULTA CON CADA UNO DE LOS DATOS INGRESADOS EN MESA
	FOR I IN IN_PUESTOS_ARRAY.FIRST..IN_PUESTOS_ARRAY.LAST
	LOOP
		INSERT INTO TT_VISUALIZA_FAC
			SELECT I CONSEC, B.PRODES NOMBRE, A.PEDUNI UNIDAD,A.PEDVAL*A.PEDUNI VALOR
			FROM VEN0004 A
			INNER JOIN VEN0001 B
				ON B.PROCOD = A.PEDPROCOD
			INNER JOIN VEN0104 C
				ON A.PEDNRO = C.PEDNRO 
			INNER JOIN INV00018 D
				ON D.MESCOD = IN_CODIGO_MESA
				AND C.PEDNUMDOC IN (D.MESNUMREQ,D.MESNUMREQ2,D.MESNUMREQ3,D.MESNUMREQ4)--AND C.PEDNUMDOC IN ('20150250','20150134')
				AND A.CCOCOD = CAST(IN_PUESTOS_ARRAY(I) AS CHAR(3))
			WHERE A.PEDSAL IN ('N','T','E');
      COMMIT;
	END LOOP;



	OPEN OUT_CURSOR_VISUALIZA FOR
		SELECT TRIM(DESCRIPCION_PRODUCTO) PRODUCTO,
			SUM(UNIDADES_PRODUCTO) UNIDAD,
			SUM(VALOR_PRODUCTO) VALOR,
			SUM(VALOR_PRODUCTO)*(19/100) VALOR_IVA
		FROM TT_VISUALIZA_FAC
		GROUP BY DESCRIPCION_PRODUCTO;



	SELECT TO_CHAR(SYSDATE(),'DD')||'/'||TO_CHAR(SYSDATE(),'MM')||'/'||TO_CHAR(SYSDATE(), 'YYYY')
	INTO OUT_FECHA
	FROM DUAL;
		
END;