create or replace PROCEDURE SP_ACOMER_ESTADO_MESA_FAC
(
	IN_CODIGO_MESA IN INV00018.MESCOD%TYPE,  -- CODIGO DE LA MESA DEL PEDIDO 	
	OUT_ESTADO OUT NUMBER					 -- ESTADO DE LA MESA 
)
AS
BEGIN
	SELECT 
		CASE MESESTADO 
			WHEN 'Activo' THEN 1
			ELSE 0
		END ESTADO
	INTO OUT_ESTADO
	FROM INV00018
	WHERE MESCOD = IN_CODIGO_MESA;
END;