create or replace PROCEDURE SP_ACOMER_FACTURA_MESA_FIN
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, 	-- CODIGO DE LA MESA DEL PEDIDO 	
	IN_PUESTOS IN NUMBER					-- SABER SI LA FACTURACION ES POR PUESTOS
)
AS
	V_CONTADOR NUMBER; -- CANTIDAD DE PUESTOS QUE FALTA POR FACTURAR
	V_CODIGO_PEDIDO TYPE_PEDIDOS_ARRAY; -- CODIGO DE LOS PEDIDOS QUE HAY EN MESA

BEGIN
	-- 1: FACTURACION POR PUESTOS
	-- 0: FACTURACION COMPLETA POR MESA

	IF(IN_PUESTOS = 0) THEN
		BEGIN
			-- SE LIVERA LA MESA COLOCANDOLA DISPONIBLE PARA CREAR UN NUEVO PEDIDO 
			UPDATE INV00018
			SET MESESTADO = 'Activo',
				MESDOCREQ = '',
				MESNUMREQ = '',
				MESNUMREQ2 = '',
				MESNUMREQ3 = '',
				MESNUMREQ4 = '',
				MESUSUREQ = '',
				MESHORAPED = ''
			WHERE MESCOD = IN_CODIGO_MESA;
		END;
	ELSE
		BEGIN
			-- CODIGO DE LOS PEDIDOS EN LA MESA
			SELECT MESNUMREQ, MESNUMREQ2,
				MESNUMREQ3, MESNUMREQ4
			INTO V_CODIGO_PEDIDO(0), V_CODIGO_PEDIDO(1),
				V_CODIGO_PEDIDO(3), V_CODIGO_PEDIDO(4)
			FROM INV00018
			WHERE MESCOD = IN_CODIGO_MESA;

			-- CANTIDAD DE PUESTOS POR FACTURAR
			SELECT COUNT(*)
			INTO V_CONTADOR
		    FROM VEN0004 A
		    INNER JOIN VEN0104 B
		        ON A.PEDNRO = B.PEDNRO
		        AND B.PEDNUMDOC IN (V_CODIGO_PEDIDO(0), V_CODIGO_PEDIDO(1),	V_CODIGO_PEDIDO(3), V_CODIGO_PEDIDO(4))
		    WHERE PEDSAL NOT IN ('F');		    

		    -- SI EL CONTADOR ES 0 SE LIBERA LA MESA
		    IF(V_CONTADOR = 0) THEN 
		    	-- SE LIVERA LA MESA COLOCANDOLA DISPONIBLE PARA CREAR UN NUEVO PEDIDO 
				UPDATE INV00018
				SET MESESTADO = 'Activo',
					MESDOCREQ = '',
					MESNUMREQ = '',
					MESNUMREQ2 = '',
					MESNUMREQ3 = '',
					MESNUMREQ4 = '',
					MESUSUREQ = '',
					MESHORAPED = ''
				WHERE MESCOD = IN_CODIGO_MESA;
				SP_ACOMER_LIBERAR_MESA_UNIDA(IN_CODIGO_MESA);
				--RAISE_APPLICATION_ERROR(-20001,'Se libera:'||V_CONTADOR);           
		    END IF;
		    
		END;
	END IF;
	
END;