create or replace PROCEDURE SP_ACOMER_PEDIDOS_CAB
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================	
(
	IN_CODIGO_RESTAURANTE IN  GEN0006.EMPCOD%TYPE,	   -- RESTAURANTE AL CUAL SE LE HACE EL PEDIDO
	IN_CODIGO_DOCUMENTO_PEDIDO IN GEN0012.DOCCOD%TYPE, -- VDOCUMENTO DE PEDIDO PARA SABER EL NUMERO DE PEDIDO DEPENDIENDO EL RESTAURANTE 
	IN_CODIGO_MESERO IN SEG0001.USUID%TYPE,        	   -- CEDULA DEL MESERO QUE ESTA TOMANDO EL PEDIDO 
	IN_CODIGO_MESA_USADA IN INV00018.MESCOD%TYPE,	   -- CODIGO DE LA MESA
	OUT_NUMERO_PEDIDO OUT VEN0104.PEDNRO%TYPE		   -- CODIGO DEL PEDIDO
)
AS
	V_CODIGO_PAIS VEN0104.PEDPAIC%TYPE;  -- VARIABLE QUE CONTIENE EL CODIGO DEL PAIS 
	V_CODIGO_PEDIDO GEN0012.DOCNRO%TYPE; -- CODIGO CON EL CUAL QUEDA REGISTRADO LOS PEDIDOS DE UNA MESA
	V_FECHA_PEDIDO VEN0104.PEDFECH%TYPE; -- FEHCA QUE SE REALIZO EL PEDIDO
	V_USUARIO SEG0001.USUID%TYPE;		 -- IDENTIFCARDOR (USUARIO) DEL MESERO
	V_HORA_PEDIDO VEN0104.PEDHORA%TYPE;  -- HORA QUE SE TOMA EL PEDIDO 
	V_NUMERO_PEDIDO VEN0104.PEDNRO%TYPE; -- NUMERO DE PEDIDO

BEGIN
-- =============================================
-- CONSULTA EL CODIGO DEL PAIS CON LA CEDULA DEL MESERO
	SELECT DISTINCT SEG0001.EMPPAIC 
	INTO V_CODIGO_PAIS
	FROM SEG0001 
	WHERE SEG0001.USUCED = IN_CODIGO_MESERO;

-- =============================================
-- CONSULTA EL NUMERO DE PEDIDO 
	SELECT TO_NUMBER(GEN0012.DOCNRO + 1)
	INTO V_CODIGO_PEDIDO
	FROM GEN0012
	WHERE GEN0012.DOCCOD = IN_CODIGO_DOCUMENTO_PEDIDO
		AND GEN0012.EMPPAIC = V_CODIGO_PAIS
		AND GEN0012.EMPCOD = IN_CODIGO_RESTAURANTE;	

-- =============================================
-- ACTUALIZO EL NUMERO DE DOCUMENTO
	UPDATE GEN0012
		SET  DOCNRO = V_CODIGO_PEDIDO
	WHERE GEN0012.DOCCOD = IN_CODIGO_DOCUMENTO_PEDIDO
		AND GEN0012.EMPPAIC = V_CODIGO_PAIS
		AND GEN0012.EMPCOD = IN_CODIGO_RESTAURANTE;	

-- =============================================
-- CONSULTA LA FECHA DEL SYSTEMA
	SELECT TO_DATE(SYSDATE, 'DD/MM/YYY')
	INTO V_FECHA_PEDIDO
	FROM DUAL;		

-- =============================================
-- CONSULTA EL USUARIO DEL MESERO
	SELECT DISTINCT SEG0001.USUID
	INTO V_USUARIO
	FROM SEG0001
	WHERE SEG0001.USUCED = '16743485'
        AND ROWNUM = 1;

-- =============================================
-- CONSULTA LA HORA DE LA TOMA DEK PEDIDO 
	SELECT TO_CHAR(SYSDATE,'HH:MI:SS')
	INTO V_HORA_PEDIDO
	FROM DUAL;

-- =============================================
-- CONSULTA LA HORA DE LA TOMA DEK PEDIDO 
	SELECT NVL(MAX(PEDNRO),0) + 1
	INTO V_NUMERO_PEDIDO
	FROM VEN0104;

	OUT_NUMERO_PEDIDO := V_NUMERO_PEDIDO;

-- =============================================
-- INSERCION DE LOS DATOS DEL PEDIDO CABECERA
	INSERT INTO VEN0104(PEDPAIC, PEDEMPC, PEDCODDOC, PEDNUMDOC, 
		PEDFECH, PEDFECE, COTPAIC, COTEMPC, 
		PEDVENCOD, PEDFAC, PEDLC, PEDDEDT, 
		PEDFLE, PEDMODCOD, PEDORDCOM, PEDOTM, 
		PEDTDEOM, USUPAIC, USUEMPC, VENUSUARIO, 
		MESCOD, PEDHORA,PEDNRO)
	VALUES (V_CODIGO_PAIS, IN_CODIGO_RESTAURANTE, IN_CODIGO_DOCUMENTO_PEDIDO, V_CODIGO_PEDIDO,
		V_FECHA_PEDIDO, V_FECHA_PEDIDO, V_CODIGO_PAIS, IN_CODIGO_RESTAURANTE,
		IN_CODIGO_MESERO,'N','0','0',
		'0','PEDIDO','01','N',
		'0',V_CODIGO_PAIS,IN_CODIGO_RESTAURANTE,V_USUARIO,
		IN_CODIGO_MESA_USADA,V_HORA_PEDIDO, V_NUMERO_PEDIDO);
END SP_ACOMER_PEDIDOS_CAB;