create or replace PROCEDURE SP_ACOMER_MENU
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CURSOR_CATEGORIAS OUT SYS_REFCURSOR,    -- CURSOR QUE TENDRA LOS DATOS DE  LAS CATEGORIAS DE COMIDAS
	CURSOR_SUBCATEGORIAS OUT SYS_REFCURSOR, -- CURSOR QUE TENDRA LOS DATOS DE LAS SUBCATEGORIAS DE COMIDAS
	CURSOR_TERMINOS OUT SYS_REFCURSOR,      -- CURSOR QUE TENDRA LOS DATOS DE LOS TERMINOS DE LA COMIDA EN CASO DE TENERLOS
	CURSOR_COMIDA OUT SYS_REFCURSOR			-- CRUSRO QUE TENDRA LOS DATOS DE CADA UNO DE LAS COMIDAD OFRECIDAS
)
AS
BEGIN
-- =============================================
-- CATEGORIAS DE LAS COMIDAS
	OPEN CURSOR_CATEGORIAS FOR
		SELECT DISTINCT TRIM(CATECOD) COD_CATEGORIA,
			TRIM(CATEDES) DESCRIPCION,
			TRIM(CATIMG) IMAGEN
		FROM INV0013 
		WHERE CATEEMPCOD = PKG_CONTAINER1
			OR CATEEMPCOD = PKG_CONTAINER2
			OR CATEEMPCOD = PKG_CONTAINER3
			OR CATEEMPCOD = PKG_CONTAINER4
		ORDER BY COD_CATEGORIA;

-- =============================================
-- SUBCATEGORIAS DE LAS COMIDAS
	OPEN CURSOR_SUBCATEGORIAS FOR
		SELECT DISTINCT TRIM(CATECOD) COD_CATEGORIA,
			TRIM(SUBCATECOD) COD_SUBCATEGORIA,
			TRIM(SUBCATEDES) DESCRIPCION
		FROM INV0014
		WHERE CATEEMPCOD = PKG_CONTAINER1
			OR CATEEMPCOD = PKG_CONTAINER2
			OR CATEEMPCOD = PKG_CONTAINER3
			OR CATEEMPCOD = PKG_CONTAINER4
		ORDER BY COD_CATEGORIA, COD_SUBCATEGORIA;
		

-- =============================================
-- TERMINOS DE LAS COMIDAS
	OPEN CURSOR_TERMINOS FOR
		SELECT  DISTINCT TRIM(CATECOD) COD_CATEGORIA,
			TRIM(SUBCATECOD) COD_SUBCATEGORIA, 
			SUBSTR(TRIM(LINCODCATE),0,LENGTH(TRIM(LINCODCATE))-1) COD_TERMINO,
			TRIM(LINDESCATE) TERMINOS
		FROM INV0015
		WHERE CATEEMPCOD = PKG_CONTAINER1
			OR CATEEMPCOD = PKG_CONTAINER2
			OR CATEEMPCOD = PKG_CONTAINER3
			OR CATEEMPCOD = PKG_CONTAINER4
			-- ADICIONAR LAS DEMAS CODIGOS DE LOS RESTUARANTES QUE OFRECEN
		ORDER BY COD_CATEGORIA, COD_SUBCATEGORIA, COD_TERMINO;

-- =============================================
-- TERMINOS DE LAS COMIDAS
	OPEN CURSOR_COMIDA FOR
		SELECT DISTINCT TRIM(A.PRECIO) PRECIO, 
            TRIM(A.COD_PRODUCTO) COD_PRODUCTO,
            TRIM(B.PRODES) NOMBRE, 
            TRIM(B.VENCATCOD) CATEGORIA,
            TRIM(B.VENSCATCOD) SUB_CATEGORIA, 
            NVL(B.VENLINCCOD, 'SIN_TERMINO') TERMINOS
        FROM (	SELECT MAX(A.PROPRE) PRECIO,
	                A.PROCOD COD_PRODUCTO	                
	            FROM VEN00012 A
	            WHERE A.VENEMPC = PKG_CONTAINER1
	            	OR A.VENEMPC = PKG_CONTAINER2
	            	OR A.VENEMPC = PKG_CONTAINER3
	            	OR A.VENEMPC = PKG_CONTAINER4
	            GROUP BY A.PROCOD) A
        LEFT JOIN VEN0001 B
            ON A.COD_PRODUCTO = B.PROCOD
        ORDER BY CATEGORIA, SUB_CATEGORIA,TERMINOS;

END SP_ACOMER_MENU;