create or replace PROCEDURE SP_ACOMER_PEDIDOS_DET
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================	
(
	IN_CODIGO_RESTAURANTE IN  GEN0006.EMPCOD%TYPE,	   -- RESTAURANTE AL CUAL SE LE HACE EL PEDIDO
	IN_CODIGO_DOCUMENTO_PEDIDO IN GEN0012.DOCCOD%TYPE, -- VDOCUMENTO DE PEDIDO PARA SABER EL NUMERO DE PEDIDO DEPENDIENDO EL RESTAURANTE 
	IN_CODIGO_PEDIDO IN VEN0004.PEDNRO%TYPE,		   -- NUMERO DE PEDIDO
	IN_CODIGO_ITME IN VEN0001.PROCOD%TYPE,			   -- CODIGO DEL ALIMENTO O ITEM QUE SE ESTA PIDIENDO 
	IN_CODIGO_TERMINO IN VEN0004.PEDBODL%TYPE,		   -- CODIGO DEL TERMINO DE LA COMIDAS
	IN_PUESTO_MESA IN VEN0004.CCOCOD%TYPE,			   -- PUESTO DE MESA DEL CUAL SE ESTA SOLICITANDO
	IN_CANTIDAD IN VEN0004.PEDUNI%TYPE,				   -- CANTIDAD DEL PRODUCTO
	IN_CODIGO_MESERO IN SEG0001.USUID%TYPE        	   -- CEDULA DEL MESERO QUE ESTA TOMANDO EL PEDIDO 
)
AS
	V_CODIGO_PAIS VEN0104.PEDPAIC%TYPE;  			-- VARIABLE QUE CONTIENE EL CODIGO DEL PAIS 
	V_CONTADOR_ITEMS_PEDIDO VEN0004.PEDLIN%TYPE;    -- CONTADOS DE LOS ITEM A PEDIR 
	V_PRECIO_ITEM VEN00012.PROPRE%TYPE;				-- PRECIO DEL ITEM SELECCIONADO
	V_VALOR_IVA  CNT0014.DEDPOR%TYPE;				-- VALOR DEL IVA PARA EL PRODUCTO
	V_IVA_ITEM VEN0004.PEDVALIVA%TYPE;				-- VALOR DEL PRODUCTO CON IVA
	V_TOTAL_ITEM VEN0004.PEDVALTUN%TYPE;			-- VALOR TOTAL CON LA CANTIDAD DEL ITEM 
	V_ALIAS_ITEM VEN0001.PROABR%TYPE;				-- ALIAS DEL PRODUCTO 
	V_RFPORDTO VEN0001.RFPORDTO%TYPE;				-- RFPORDTO 
	V_VALDESC VEN0004.peddcval%TYPE;				-- peddcval

BEGIN
-- =============================================
-- CONSULTA EL CODIGO DEL PAIS CON LA CEDULA DEL MESERO
	SELECT DISTINCT SEG0001.EMPPAIC 
	INTO V_CODIGO_PAIS
	FROM SEG0001 
	WHERE SEG0001.USUCED = IN_CODIGO_MESERO;

-- =============================================
-- CONSULTA EL CODIGO DEL PAIS CON LA CEDULA DEL MESERO
	SELECT MAX(VEN0004.PEDLIN) + 1
	INTO V_CONTADOR_ITEMS_PEDIDO
	FROM VEN0004 
	WHERE VEN0004.PEDNRO = IN_CODIGO_PEDIDO;

	IF(V_CONTADOR_ITEMS_PEDIDO IS NULL) THEN
		BEGIN
			V_CONTADOR_ITEMS_PEDIDO := 1;
		END;
	END IF;

-- =============================================
-- CONSULTA EL PRECIO DEL ITEM SELECCIONADO
	SELECT VEN00012.PROPRE
	INTO V_PRECIO_ITEM
	FROM VEN00012
	WHERE VENEMPC = IN_CODIGO_RESTAURANTE
	    AND LIPCOD = '01'
	    AND PROCOD = IN_CODIGO_ITME;

-- =============================================
-- CONSULTA EL IVA PARA EL PRODUCTO
	SELECT CNT0014.DEDPOR
	INTO V_VALOR_IVA
	FROM VEN0001 
	LEFT JOIN CNT0014  
	    ON VEN0001.FDEDCOD = CNT0014.DEDCOD 
	    AND VEN0001.FDEDSC = CNT0014.DEDSUBCOD
	    AND VEN0001.FDEDANO = CNT0014.DEDANO 
	WHERE VEN0001.VENEMPPAI = V_CODIGO_PAIS 
	    AND VEN0001.VENEMPC = IN_CODIGO_RESTAURANTE 
	    AND VEN0001.PROCOD = IN_CODIGO_ITME;

-- =============================================
-- VALOR DEL PRODUCTO CON EL IVA
	V_IVA_ITEM := (((V_VALOR_IVA/100)*(V_PRECIO_ITEM)) + V_PRECIO_ITEM);

-- =============================================
-- SE CALCULA EL PRECIO TOTAL CONLA CANTIDAD PEDIDA DEL ITEM
	V_TOTAL_ITEM := IN_CANTIDAD * V_IVA_ITEM;

-- =============================================
-- CONSULTA EL ALIAS DEL ITEM O PRODUCTO
	SELECT PROABR, RFPORDTO
	INTO V_ALIAS_ITEM, V_RFPORDTO
	FROM VEN0001
	WHERE VEN0001.VENEMPPAI = V_CODIGO_PAIS
		AND VEN0001.VENEMPC = IN_CODIGO_RESTAURANTE
		AND VEN0001.PROCOD = IN_CODIGO_ITME;

	IF(V_RFPORDTO > 0) THEN
		BEGIN
			V_VALDESC := (V_PRECIO_ITEM * IN_CANTIDAD * V_RFPORDTO) / 100;
		END;
	ELSE
		BEGIN
			V_RFPORDTO := 0;
			V_VALDESC := 0;
		END;
	END IF;

--- =============================================
-- INSERTAR DETALLE DE LOS PEDIDOS
	INSERT INTO VEN0004(PEDPAIC, PEDEMPC, PEDCODDOC,PEDNRO,
		PEDLIN, PEDPROCOD, PEPC, PEC,
		CCOCOD, PEDUNI, PEDVAL, PEDVALCPI, 
		PEDPORIVA, PEDVALIVA, PEDVALTUN, PEDSUCDET,
		PEDALIAS, PEDPORDC, PEDDCVAL, PEDSAL,
		PEDBODL, PEDCHECK)
	VALUES(V_CODIGO_PAIS, IN_CODIGO_RESTAURANTE, IN_CODIGO_DOCUMENTO_PEDIDO, IN_CODIGO_PEDIDO,
		V_CONTADOR_ITEMS_PEDIDO, IN_CODIGO_ITME, V_CODIGO_PAIS, IN_CODIGO_RESTAURANTE,
		IN_PUESTO_MESA, IN_CANTIDAD, V_PRECIO_ITEM, 0,
		V_VALOR_IVA, V_IVA_ITEM, V_TOTAL_ITEM, '01',
		V_ALIAS_ITEM, V_RFPORDTO, V_VALDESC, 'N',
		IN_CODIGO_TERMINO, IN_CANTIDAD);
END SP_ACOMER_PEDIDOS_DET;