create or replace PROCEDURE SP_ACOMER_MESAS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CURSOR_MESAS OUT SYS_REFCURSOR --CURSOR QUE TENDRA LOS DATOS DE LA MESA (EMP, IDENTIFICADOR, PUESTOS, COORDENADAS)
)
AS
BEGIN
	-- EJECUTA LOS TIEMPOS DE DEMORA DE LOS PEDIDOS
	SP_ACOMER_TIEMPO_PEDIDO();

	-- CARGA AL CURSOR 
	OPEN CURSOR_MESAS FOR
		SELECT INV.MESCOD COD_MESA,
			CASE TRIM(INV.MESESTADO)
                WHEN 'Ocupado' THEN
                    '0'
                ELSE '1'
		    END ESTADO,
		    --NVL(TRIM(INV.MESESTADO),'Activo') ESTADO,
		    DM.EMPCOD COD_EMPRESA,
		    DM.POSMES POSICION,
		    CASE DM.PUESTOS
				WHEN 0 THEN 4
				ELSE DM.PUESTOS
			END PUESTOS,
		    --NVL(DM.PUESTOS, 4) PUESTOS,
		    INV.MESHORAPED ATENCION,
		    GREATEST(TT.TIEMPO_CONTAINER1, TT.TIEMPO_CONTAINER2, TT.TIEMPO_CONTAINER3, TT.TIEMPO_CONTAINER4) TIEMPO
		FROM INV00018 INV
		INNER JOIN DETMESA DM
		    ON DM.MESCOD = INV.MESCOD
		INNER JOIN TT_TIME_MESA_CONTAINER TT
            ON TT.CODIGO_MESA = INV.MESCOD
		ORDER BY INV.MESCOD;			
END SP_ACOMER_MESAS;