CREATE TABLE AUDITAR_REG_FILTRO_SESION(
		AUTO_REG_FILTRO NUMBER NOT NULL,
		ID_IDEN_USA_SESION VARCHAR2(30) NOT NULL,
		COD_GLOSA_ARFS VARCHAR2(255) NULL,
		FILTRAR_FECHA_ARFS NUMBER DEFAULT 0 NOT NULL,
		FECHA_DESDE_ARFS DATE NULL,
		FECHA_HASTA_ARFS DATE NULL,
		ESM_DISPENSA_ARFS VARCHAR2(255) NULL,
		ESM_NOMBRE_ARFS VARCHAR2(255) NULL,
		OPCION_ORDEN_ARFS NUMBER DEFAULT 1 NOT NULL,
		TIPO_ORDEN_ARFS NUMBER DEFAULT 1 NOT NULL ,
		TIPO_DOCUMENTO VARCHAR2(20) NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_AUDITAR_REG_FILTRO_SESION ON AUDITAR_REG_FILTRO_SESION
(AUTO_REG_FILTRO)
LOGGING
NOPARALLEL;

ALTER TABLE AUDITAR_REG_FILTRO_SESION ADD (
  CONSTRAINT PK_AUDITAR_REG_FILTRO_SESION
 PRIMARY KEY
 (AUTO_REG_FILTRO));


 CREATE SEQUENCE SEQUENCE_AUTO_REG_ START WITH 1;

 CREATE OR REPLACE TRIGGER TIG_AUDITAR_REG_FILTRO_SESION 
BEFORE INSERT ON AUDITAR_REG_FILTRO_SESION 
FOR EACH ROW

BEGIN
  SELECT SEQUENCE_AUTO_REG_.NEXTVAL
  INTO   :new.AUTO_REG_FILTRO
  FROM   dual;
END;