CREATE OR REPLACE PROCEDURE SP_ACOMER_PEDIDOS_CANCEL_REST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_MESA IN INV00018.MESCOD%TYPE  -- CODIGO DE LA MESA QU SE CANCELA
)	
AS
	ARRAY_CODIGOS_EMP PKG_ACOMER_PROCEDURES.TYPE_PEDIDOS_ARRAY; -- ARRAY DE LOS CODIGOS DE LOS CONTAINER
	ARRAY_NUMEROS_PED PKG_ACOMER_PROCEDURES.TYPE_PEDIDOS_ARRAY; -- ARRAY DE LOS NUMEROS DE LOS PEDIDOS
	V_MESA_UNIDA NUMBER;
    V_CONTADOR_ENTREGADOS NUMBER := 0;
BEGIN
	-- ==========================================
	-- LLENA EL ARRAY CON LOS CODIGOS DE LOS CONTAINER
	ARRAY_CODIGOS_EMP(1) := PKG_ACOMER_PROCEDURES.PKG_CONTAINER1;
	ARRAY_CODIGOS_EMP(2) := PKG_ACOMER_PROCEDURES.PKG_CONTAINER2;
	ARRAY_CODIGOS_EMP(3) := PKG_ACOMER_PROCEDURES.PKG_CONTAINER3;
	ARRAY_CODIGOS_EMP(4) := PKG_ACOMER_PROCEDURES.PKG_CONTAINER4;

	-- ==========================================
	-- SE LLENA EL ARRAY CON LOS NUMEROS DE PEDIDOS DE LA MESA
	SELECT MESNUMREQ, MESNUMREQ2,
		MESNUMREQ3, MESNUMREQ4
	INTO ARRAY_NUMEROS_PED(1), ARRAY_NUMEROS_PED(2),
		ARRAY_NUMEROS_PED(3), ARRAY_NUMEROS_PED(4)
	FROM INV00018
	WHERE MESCOD = CAST(IN_CODIGO_MESA AS NUMBER);

	-- ==========================================
	-- SE HACE EL CONTEO DE CUANTOS PEDIDOS HAN SIDO ENTREGADOS 
	FOR I IN ARRAY_NUMEROS_PED.FIRST..ARRAY_NUMEROS_PED.LAST
	LOOP
		BEGIN
			SELECT NVL(SUM(PEDUNI),0) - NVL(SUM(PEDCHECK),0) + V_CONTADOR_ENTREGADOS TOTAL_ENTREGADOS
			INTO V_CONTADOR_ENTREGADOS
			FROM VEN0004 A
			INNER JOIN VEN0104 B
			    ON A.PEDNRO = B.PEDNRO
			    AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));						
		END;
	END LOOP;

	-- ==========================================
	-- IDENTIFICA SI ES UNA MESA QUE ESTA UNIDA
	BEGIN
		SELECT 1
		INTO V_MESA_UNIDA
		FROM UNIONMESA
		WHERE MESCOD = IN_CODIGO_MESA
		    OR MESCODUNI = IN_CODIGO_MESA;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN 
			V_MESA_UNIDA := 0;
	END;

	-- ==========================================
	-- SI NO SE HAN ENTREGADO 
	IF(V_CONTADOR_ENTREGADOS = 0) THEN 
		BEGIN
			FOR I IN ARRAY_NUMEROS_PED.FIRST..ARRAY_NUMEROS_PED.LAST
			LOOP
				IF (ARRAY_NUMEROS_PED(I) <> ' ') THEN 
					-- ==========================================
					-- SE ACTUALIZA EL PEDIDO CANCELADO PARA CAMBIAR LUEGO DE TABLA
					UPDATE VEN0104
					SET PEDMODCOD = 'CANCEL'
					WHERE PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    		AND PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));

			    	-- SE ACTUALIZA EL DETALLE DEL PEDIDO CANCELADO 
			    	UPDATE VEN0004
					SET PEDSAL = 'C'
					WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
										FROM VEN0004 A
										INNER JOIN VEN0104 B
											ON A.PEDNRO = B.PEDNRO
											AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
			    					)
						AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));

					-- ==========================================
			    	-- SE CAMBIA A LA TABLA CANCELADOS
			    	INSERT INTO PEDCAN
			    	SELECT * 
			    	FROM VEN0104
			    	WHERE PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    		AND PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));

			    	-- SE CAMBIA A LA TABLA CANCELADOS 
			    	INSERT INTO PEDDETCAN
			    	SELECT * 
			    	FROM VEN0004
			    	WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
										FROM VEN0004 A
										INNER JOIN VEN0104 B
											ON A.PEDNRO = B.PEDNRO
											AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
			    					)
						AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));

					-- ==========================================
			    	-- SE ELIINAN LOS PLATOS QUE SE CANCELAN DE LA TABLA
			    	DELETE 
					FROM VEN0004
					WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
										FROM VEN0004 A
										INNER JOIN VEN0104 B
											ON A.PEDNRO = B.PEDNRO
											AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
			    					)
						AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));
				END IF;
			END LOOP;	

			-- SI LA MESA ESTA UNIDA CON OTRA SE LIBERA DE PEDIDOS PERO QUEDA OCUPADA HASTA FACTURAR EL PEDIDO DE LA OTRA MESA
			IF(V_MESA_UNIDA = 1) THEN
				BEGIN	
					-- SE QUITAN TODOS LOS PEDIDOS QUE ESTAN LIGADOS A LA MESA 
					UPDATE INV00018
					SET MESDOCREQ = '',
						MESNUMREQ = '',
						MESNUMREQ2 = '',
						MESNUMREQ3 = '',
						MESNUMREQ4 = ''
					WHERE MESCOD = IN_CODIGO_MESA;
				END;
			ELSE
				BEGIN
					UPDATE INV00018
					SET MESNUMREQ = '',
						MESNUMREQ2 = '',
						MESNUMREQ3 = '',
						MESNUMREQ4 = '',
						MESUSUREQ = '',
						MESDOCREQ = '',
						MESESTADO = 'Activo',
						MESHORAPED = ''
					WHERE MESCOD = IN_CODIGO_MESA;
				END;
			END IF;		
		END;

	-- ==========================================
	-- SI EN LA MESA YA FUE ENTREGADO UNO O MAS PEDIDOS
	ELSE
		BEGIN
			FOR I IN ARRAY_NUMEROS_PED.FIRST..ARRAY_NUMEROS_PED.LAST
			LOOP
				-- CONTEO DE ENTREGAS EN ESE PEDIDO 
				SELECT SUM(A.PEDUNI) - SUM(PEDCHECK)
				INTO V_CONTADOR_ENTREGADOS
				FROM VEN0004 A
				INNER JOIN VEN0104 B
					ON A.PEDNRO = B.PEDNRO    
				WHERE B.MESCOD = IN_CODIGO_MESA
					AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
					AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));
				
				-- SI HAY ENTREGAS EN ESE EDIDO 
				IF(V_CONTADOR_ENTREGADOS > 0) THEN 
					DECLARE
						DATACURSOR1 VEN0004.CCOCOD%TYPE;
						DATACURSOR2 VEN0004.PEDUNI%TYPE;
						DATACURSOR3 VEN0004.PEDCHECK%TYPE;
						DATACURSOR4 VEN0004.PEDPROCOD%TYPE;						
						DATACURSOR5 NUMBER;
						DATACURSOR6 VEN0004.PEDNRO%TYPE;

						CURSOR CURSOR_1(IN_CURSOR2 IN CHAR, IN_CURSOR3 IN CHAR) IS
							SELECT A.CCOCOD, A.PEDUNI, A.PEDCHECK,
    							A.PEDPROCOD, A.PEDUNI - A.PEDCHECK,
    							A.PEDNRO
							FROM VEN0004 A
							INNER JOIN VEN0104 B
							    ON A.PEDNRO = B.PEDNRO    
							    AND B.PEDNUMDOC = IN_CURSOR2
							    AND B.PEDEMPC = IN_CURSOR3;
					BEGIN
						OPEN CURSOR_1(ARRAY_NUMEROS_PED(I), ARRAY_CODIGOS_EMP(I));
						FETCH CURSOR_1 INTO DATACURSOR1, DATACURSOR2, DATACURSOR3, DATACURSOR4, DATACURSOR5, DATACURSOR6;
						LOOP
							EXIT WHEN CURSOR_1%NOTFOUND;

							-- SI HAY UNA ENTREA EN EL PEDIDO 
							IF(DATACURSOR5 > 0) THEN 
								-- CANTIDAD DIFERENTE A LA CANTIDAD ENTREGADA 
								IF(DATACURSOR2 <> DATACURSOR5) THEN 
									DECLARE
										ARRAY_PLATOS PKG_ACOMER_PROCEDURES.TYPE_PEDIDOS_ARRAY;
										ARRAY_CANTIDAD PKG_ACOMER_PROCEDURES.TYPE_PEDIDOS_ARRAY;
										ARRAY_PUESTOS PKG_ACOMER_PROCEDURES.TYPE_PEDIDOS_ARRAY;
										V_CODIGO_MENSAJE NUMBER;
									BEGIN
										ARRAY_PLATOS(1) := DATACURSOR4;
										ARRAY_CANTIDAD(1) := DATACURSOR5;
										ARRAY_PUESTOS(1) := DATACURSOR1;

										PKG_ACOMER_PROCEDURES.SP_ACOMER_PEDIDOS_CANCEL(0,IN_CODIGO_MESA,ARRAY_PLATOS,
																					   ARRAY_CANTIDAD,ARRAY_PUESTOS,
																					   V_CODIGO_MENSAJE);
									END;
								ELSE
									BEGIN
										DELETE 
										FROM VEN0004
										WHERE CCOCOD = DATACURSOR1
											AND PEDPROCOD = DATACURSOR4
											AND PEDNRO = DATACURSOR6
    										AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));										
									END;
								END IF;							
							END IF;
							FETCH CURSOR_1 INTO DATACURSOR1, DATACURSOR2, DATACURSOR3, DATACURSOR4, DATACURSOR5, DATACURSOR6;
						END LOOP;
						CLOSE CURSOR_1;
					END;
				ELSE 
					BEGIN
						-- SE ACTUALIZA EL PEDIDO 
						UPDATE VEN0104
						SET PEDMODCOD = 'CANCEL'
						WHERE PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
				    		AND PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));

				    	-- SE ACTUALIZA EL DETALLE DEL PEDIDO CANCELADO 
				    	UPDATE VEN0004
						SET PEDSAL = 'C'
						WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
											FROM VEN0004 A
											INNER JOIN VEN0104 B
												ON A.PEDNRO = B.PEDNRO
												AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
				    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
				    					)
							AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));


						INSERT INTO PEDCAN
				    	SELECT * 
				    	FROM VEN0104
				    	WHERE PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
				    		AND PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10));

				    	-- SE CAMBIA A LA TABLA CANCELADOS 
				    	INSERT INTO PEDDETCAN
				    	SELECT * 
				    	FROM VEN0004
				    	WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
											FROM VEN0004 A
											INNER JOIN VEN0104 B
												ON A.PEDNRO = B.PEDNRO
												AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
				    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
				    					)
							AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));

					-- ==========================================
			    	-- SE ELIINAN LOS PLATOS QUE SE CANCELAN DE LA TABLA
			    	DELETE 
					FROM VEN0004
					WHERE PEDNRO IN (	SELECT DISTINCT A.PEDNRO 
										FROM VEN0004 A
										INNER JOIN VEN0104 B
											ON A.PEDNRO = B.PEDNRO
											AND B.PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13))
			    							AND B.PEDNUMDOC = CAST(ARRAY_NUMEROS_PED(I) AS CHAR(10))
			    					)
						AND PEDEMPC = CAST(ARRAY_CODIGOS_EMP(I) AS CHAR(13));
					END;
				END IF;
			END LOOP;
		END;
	END IF;
END;