CREATE OR REPLACE PROCEDURE SP_ACOMER_MESAS_UNIDAS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_MESA IN DETMESA.MESCOD%TYPE, -- CODIGO DE LA MESA QUE SE VA A BUSCAR SUS UNIONES
	OUT_MESAS_UNIDAS OUT SYS_REFCURSOR,    -- CURSOR QUE CONTIENE LAS MESAS QUE VAN UNIDAD EN LA MESA CLICKEADA
	OUT_MESA_PRINCIPAL OUT DETMESA.MESCOD%TYPE  -- CODIGO DE LA MESA PRINCIPAL
)
AS
	V_MESA_PRINCIPAL DETMESA.MESCOD%TYPE;
BEGIN
	-- ================================
	-- CONSULTO LAS MESAS UNIDAD A LA PRINCIPAL 	
	BEGIN
		SELECT DISTINCT 1
		INTO V_MESA_PRINCIPAL	 
		FROM UNIONMESA
		WHERE MESCOD = IN_CODIGO_MESA;
	EXCEPTION
		WHEN OTHERS THEN
			V_MESA_PRINCIPAL := 0;
	END;

	-- ==============================
	-- SI NO ES MESA PRINCIPAL BUSCO CUAL ES 
	IF(V_MESA_PRINCIPAL = 0) THEN		
		-- ========================
		-- CONSULTA LA MESA PRINCIPAL
		SELECT DISTINCT MESCOD
		INTO V_MESA_PRINCIPAL
		FROM UNIONMESA
		WHERE MESCODUNI = IN_CODIGO_MESA;

		-- =========================
		-- CONSULTA DE LAS MESAS
		OPEN OUT_MESAS_UNIDAS FOR
			SELECT DISTINCT MESCODUNI		
			FROM UNIONMESA
			WHERE MESCOD = V_MESA_PRINCIPAL
			ORDER BY MESCOD;

		--
		OUT_MESA_PRINCIPAL := V_MESA_PRINCIPAL;
	ELSE
		-- ========================
		-- CONSULTA DE LAS MESAS
		OPEN OUT_MESAS_UNIDAS FOR
			SELECT DISTINCT MESCODUNI		
			FROM UNIONMESA
			WHERE MESCOD = IN_CODIGO_MESA
			ORDER BY MESCOD;

		--
		OUT_MESA_PRINCIPAL := IN_CODIGO_MESA;
	END IF;

	
	
END;