CREATE OR REPLACE PROCEDURE SP_ACOMER_DETALLE_PEDIDO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA QUE HA HECHO PEDIDO
	OUT_CURSOR OUT SYS_REFCURSOR
)
AS
	V_PEDIDO1 INV00018.MESNUMREQ%TYPE; -- CODIGO DEL PEDIDO AL RESTAURANTE 1 SI HA DE TENER PEDIDOS  
	V_PEDIDO2 INV00018.MESNUMREQ%TYPE; -- CODIGO DEL PEDIDO AL RESTAURANTE 2 SI HA DE TENER PEDIDOS 
	V_PEDIDO3 INV00018.MESNUMREQ%TYPE; -- CODIGO DEL PEDIDO AL RESTAURANTE 3 SI HA DE TENER PEDIDOS 
	V_PEDIDO4 INV00018.MESNUMREQ%TYPE; -- CODIGO DEL PEDIDO AL RESTAURANTE 4 SI HA DE TENER PEDIDOS 
BEGIN
-- ======================
-- CONSULTA CODIGO DE PEDIDOS DE LA MESA
	SELECT MESNUMREQ, MESNUMREQ2, 
		MESNUMREQ3, MESNUMREQ4
	INTO V_PEDIDO1, V_PEDIDO2,
		V_PEDIDO3, V_PEDIDO4
	FROM INV00018
	WHERE MESCOD = IN_CODIGO_MESA;

-- =====================
-- CONSULTA 
	OPEN OUT_CURSOR FOR
		SELECT DISTINCT C.PRODES PLATO, 
		    A.PEDUNI CANTIDAD,
		    SUBSTR(A.CCOCOD,2) PUESTO,
		    C.PROCOD CODIGO,
		    D.CATIMG IMAGEN
		FROM VEN0004 A
		INNER JOIN VEN0104 B
		    ON A.PEDNRO = B.PEDNRO
		    AND B.PEDNUMDOC IN (V_PEDIDO1,V_PEDIDO2,V_PEDIDO3,V_PEDIDO4)
		INNER JOIN VEN0001 C
		    ON A.PEDPROCOD = C.PROCOD
		INNER JOIN INV0013 D
      		ON C.VENCATCOD = D.CATECOD
		WHERE A.PEDSAL NOT IN ('F','C');
END;