CREATE OR REPLACE PROCEDURE SP_ACOMER_MESAS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CURSOR_MESAS OUT SYS_REFCURSOR, --CURSOR QUE TENDRA LOS DATOS DE LA MESA (EMP, IDENTIFICADOR, PUESTOS, COORDENADAS)
	CURSOR_PEDIDO OUT SYS_REFCURSOR --CURSOR QUE TENDRA LA LISTA DE PEDIDOS ACTUVOS EN EL MOMENTO 
)
AS
BEGIN
	-- ===========================
	-- CURSOR DE LAS MESAS
	OPEN CURSOR_MESAS FOR
		SELECT INV.MESCOD COD_MESA,
			CASE TRIM(INV.MESESTADO)
                WHEN 'Ocupado' THEN
                    '0'
                ELSE '1'
		    END ESTADO,
		    --NVL(TRIM(INV.MESESTADO),'Activo') ESTADO,
		    DM.EMPCOD COD_EMPRESA,
		    DM.POSMES POSICION,
		    CASE DM.PUESTOS
				WHEN 0 THEN 4
				ELSE DM.PUESTOS
			END PUESTOS,
		    --NVL(DM.PUESTOS, 4) PUESTOS,
		    INV.MESHORAPED ATENCION
		FROM INV00018 INV
		INNER JOIN DETMESA DM
		    ON DM.MESCOD = INV.MESCOD
		ORDER BY INV.MESCOD;
END;