CREATE OR REPLACE PROCEDURE SP_ACOMER_NOMBRE_PLATOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_PLATO IN VEN0001.PROCOD%TYPE, -- CODIGO DEL PLATO QUE SE CONSULTA
	OUT_NOMBRE_PLATO OUT VEN0001.PRODES%TYPE, -- NOMBRE DEL PLATO
	OUT_NOMBRE_IMAGEN OUT INV0013.CATIMG%TYPE
)
AS
BEGIN
	-- CONSULTA EL NOMBRE DEL PLATO CON EL CODIGO CORRESPONDIENTE
	SELECT DISTINCT A.PRODES, B.CATIMG
	INTO OUT_NOMBRE_PLATO, OUT_NOMBRE_IMAGEN
	FROM VEN0001 A
	INNER JOIN INV0013 B
		ON A.VENCATCOD = B.CATECOD
	WHERE PROCOD = IN_CODIGO_PLATO;
END;