CREATE OR REPLACE PROCEDURE SP_ACOMER_DATOS_CLIENTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
( 
	IN_CEDULA_CLIENTE IN GEN0024.CLICOD%TYPE, -- CODIGO DEL CLIENTE
	OUT_NOMBRE_CLIENTE OUT GEN0024.CLINOM1%TYPE -- NOMBRE DEL CLIENTE
)
AS
	V_CONTADOR NUMBER;  -- SABER SI EL CLIENTE EXISTE
BEGIN
	-- EXISTENCIA DEL CLIENTE
	SELECT COUNT(*)
	INTO V_CONTADOR
	FROM GEN0024
	WHERE CLICOD = IN_CEDULA_CLIENTE;

	IF(V_CONTADOR = 1) THEN 
		-- CONSULTA EL NOMBRE DEL CLIENTE 
		SELECT CLINOM1
		INTO OUT_NOMBRE_CLIENTE
		FROM GEN0024
		WHERE CLICOD = IN_CEDULA_CLIENTE;

	ELSE
		OUT_NOMBRE_CLIENTE := 'SIN_REGISTRO';
	END IF;
	
END;