CREATE OR REPLACE PROCEDURE SP_ACOMER_CODIGO_CONTAINERS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	OUT_CONTAINER1 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 1
	OUT_CONTAINER2 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 2
	OUT_CONTAINER3 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 3
	OUT_CONTAINER4 OUT GEN0006.EMPCOD%TYPE   -- CODIGO DEL CONTAINER 4
)
AS
BEGIN
	--SE ASGINAN LOS NOMBRES PERTENECIENTES A CADA CONTAINER O RESTAURANTE
	OUT_CONTAINER1 := PKG_ACOMER_PROCEDURES.PKG_CONTAINER1;
	OUT_CONTAINER2 := PKG_ACOMER_PROCEDURES.PKG_CONTAINER2;
	OUT_CONTAINER3 := PKG_ACOMER_PROCEDURES.PKG_CONTAINER3;
	OUT_CONTAINER4 := PKG_ACOMER_PROCEDURES.PKG_CONTAINER4;

END;