CREATE OR REPLACE PROCEDURE SP_ACOMER_ACT_PEDIDO_CLI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_REGISTRADO_BD NUMBER, -- SABER SI YA ESTA REGISTRADO O NO
	IN_CEDULA_CLIENTE VEN0104.PCLICOD%TYPE, -- CEDULA DEL CLIENTE
	IN_NOMBRE_CLINETE VEN0104.PCLINOM%TYPE, -- NOMBRE DEL CLIENTE
	IN_FORMA_PAGO VEN0104.PFPGCOD%TYPE,      -- FORMA DE PAGO
	IN_CODIGO_EMPRESA GEN0006.EMPCOD%TYPE,	-- CODIGO DE LA EMPRESA
	IN_NUMERO_DOCUMENTO CNT00071.MOVDOCNRO%TYPE  -- CODIGO DEL PEDIDO 
)
AS
	V_DIR_CLIENTE VEN0003.DIRCOD%TYPE;  -- INFORMACION PARA CLIENTES QUE ESTAN REGISTRADOS
	V_DIRECCION VEN0003.DIRCLIDIR%TYPE; -- INFORMACION PARA CLIENTES QUE ESTAN REGISTRADOS
	V_NUMERO_PEDIDO VEN0004.PEDNRO%TYPE;-- NUMERO DE PEDIDO  
BEGIN
	-- ==================
	-- CODIGO DEL PEDIDO EN DETALLE
	SELECT PEDNRO 
	INTO V_NUMERO_PEDIDO
	FROM VEN0104
	WHERE PEDEMPC = IN_CODIGO_EMPRESA
		AND PEDNUMDOC = IN_NUMERO_DOCUMENTO;

	-- 1: ESTA REGISTRADO EN LA BASE DE DATOS
	-- 0: NO ESTA REGISTRADO EN LA BASE DE DATOS

	-- ===================
	-- SI EL CLIENTE ESTA REGISTRADO EN BD
	IF(IN_REGISTRADO_BD = 1) THEN
		BEGIN
			-- CONSULTAMOS LA INFROMACION ADICIONAL 
			SELECT DIRCOD, DIRCLIDIR 
			INTO V_DIR_CLIENTE,V_DIRECCION 
			FROM  VEN0003 
			WHERE CLICOD = IN_CEDULA_CLIENTE 
				AND SUCTERCOD = '01' 
				AND ROWNUM <= 1;

			-- SE ACTUALIZAN LOS DATOS DEL PEDIDO
			UPDATE VEN0104
			SET PCLICOD = IN_CEDULA_CLIENTE, 
				PCLINOM = IN_NOMBRE_CLINETE, 
				PSUCCLI = '01', 
				PFPGCOD = IN_FORMA_PAGO,
				PCLICUP = 0, 
				PDIRCOD = V_DIR_CLIENTE, 
				PDIRNOM = V_DIRECCION
			WHERE PEDEMPC = IN_CODIGO_EMPRESA
				AND PEDNUMDOC = IN_NUMERO_DOCUMENTO;

			-- SE ACTUALIZA EL ESTADO DEL PEDIDO A FACTURADO
			UPDATE VEN0004
			SET PEDSAL = 'F'
			WHERE PEDNRO = V_NUMERO_PEDIDO;

		END;
	ELSE
		BEGIN
			-- SE ACTUALIZAN LOS DATOS DEL PEDIDO
			UPDATE VEN0104
			SET PCLICOD = IN_CEDULA_CLIENTE, 
				PCLINOM = IN_NOMBRE_CLINETE, 
				PSUCCLI = '01', 
				PFPGCOD = IN_FORMA_PAGO,
				PCLICUP = 0 				
			WHERE PEDEMPC = IN_CODIGO_EMPRESA
				AND PEDNUMDOC = IN_NUMERO_DOCUMENTO;

			-- SE ATUALIZA EL ESTADO DEL PEDIDO A FACTURADO
			UPDATE VEN0004
			SET PEDSAL = 'F'
			WHERE PEDNRO = V_NUMERO_PEDIDO;
		END;
	END IF;
END;