CREATE OR REPLACE PROCEDURE SP_ACOMER_CONSULTA_HISTCOCINA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_COCINERO IN GEN0011.TERCOD%TYPE,
	OUT_CURSOR OUT SYS_REFCURSOR -- CRUSR CON LOS DATOS DEL HISTORIAL 
)
AS 
	V_EMPRESA_COCINERO SEG0001.EMPCOD%TYPE; -- EMPRESA A LA QUE PERTENECE EL COCINERO 
	V_CONTADOR NUMBER;
BEGIN
	/*SELECT EMPCOD
	INTO V_EMPRESA_COCINERO
	FROM SEG0001
	WHERE USUCED = IN_CODIGO_COCINERO;*/

	V_EMPRESA_COCINERO := '901.023.461-1';

	-- SABER CUANTOS DATOS HAY EN HISTORIAL
	SELECT COUNT(*)
	INTO V_CONTADOR
	FROM HISTCOCINA A
	INNER JOIN VEN0001 B
		ON A.PLATO = B.PROCOD
	WHERE EMPRESA = V_EMPRESA_COCINERO
	ORDER BY FECHA, HORAFIN;


	IF(V_CONTADOR = 0) THEN 
		BEGIN
			OPEN OUT_CURSOR FOR
				SELECT 'SIN_DATOS' PLATO, 'SIN_DATOS' CANTIDAD,
				    'SIN_DATOS' FECHA, 'SIN_DATOS' HORAFIN 
				FROM DUAL;
		END;

	ELSE
		BEGIN
			OPEN OUT_CURSOR FOR
				SELECT PRODES PLATO, CANTIDAD,
				    FECHA, HORAFIN 
				FROM HISTCOCINA A
				INNER JOIN VEN0001 B
					ON A.PLATO = B.PROCOD
				WHERE EMPRESA = V_EMPRESA_COCINERO
				ORDER BY FECHA, HORAFIN;
		END;
	END IF;
	
END;