CREATE OR REPLACE PROCEDURE SP_ACOMER_FACTURACION_PEDIDOS
(
	IN_TIPO_PRECIO IN GEN0024.LIPCOD%TYPE, -- PRECIO QUE SE LE DEBE AJUSTAR AL PEDUDO
	IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA DEL PEDIDO 
	IN_PUESTOS_ARRAY IN PKG_ACOMER_RESTAURANTES.TYPE_PEDIDOS_ARRAY -- PUESTOS QUE SE VAN A FACTURAR
)
AS
	V_NUMDOC1 INV00018.MESNUMREQ%TYPE;-- NUMERO DE PEDIDO QUE HAY EN LA MESA AL RESTAURANTE 1
	V_NUMDOC2 INV00018.MESNUMREQ2%TYPE;-- NUMERO DE PEDIDO QUE HAY EN LA MESA AL RESTAURANTE 2
	V_NUMDOC3 INV00018.MESNUMREQ3%TYPE;-- NUMERO DE PEDIDO QUE HAY EN LA MESA AL RESTAURANTE 3
BEGIN
	-- ===================================
	-- IDENTIFICAR LOS PEDIDOS QUE HAY EN LA MESA 
	SELECT NVL(MESNUMREQ,''), 
		NVL(MESNUMREQ2,''), 
		NVL(MESNUMREQ3,'')
	INTO V_NUMDOC1, V_NUMDOC2,
		V_NUMDOC3
	FROM INV00018
	WHERE MESCOD = IN_CODIGO_MESA;

	SELECT TO_NUMBER(GEN0012.DOCNRO + 1)
	INTO V_CODIGO_PEDIDO
	FROM GEN0012
	WHERE GEN0012.DOCCOD = 'PD'
		AND GEN0012.EMPPAIC = '169'
		AND GEN0012.EMPCOD = IN_CODIGO_RESTAURANTE;	
END; 