CREATE OR REPLACE PROCEDURE SP_ACOMER_ENTREGAR_PEDIDO_MESA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_PUESTOS IN TYPE_PEDIDOS_ARRAY, 				-- 
	IN_PLATOS IN TYPE_PEDIDOS_ARRAY,				--
	IN_NUMERO_DOCUMENTO IN VEN0104.PEDNUMDOC%TYPE,  -- NUMERO DE DOCUMENTO
	IN_CODIGO_EMPRESA IN VEN0004.PEDEMPC%TYPE 		-- CODIGO DE LA EMPRESA

)
AS 	
	V_PEDNRO VEN0104.PEDNRO%TYPE;
	V_FALTANTES VEN0004.PEDCHECK%TYPE;
BEGIN
	FOR I IN IN_PUESTOS.FIRST..IN_PUESTOS.LAST
	LOOP
		SELECT DISTINCT A.PEDCHECK, A.PEDNRO
		INTO V_FALTANTES, V_PEDNRO
		FROM VEN0004 A
		INNER JOIN VEN0104 B
		    ON A.PEDNRO = B.PEDNRO
		    AND B.PEDNUMDOC = IN_NUMERO_DOCUMENTO
		WHERE A.PEDEMPC = IN_CODIGO_EMPRESA
		    AND A.CCOCOD = CAST(IN_PUESTOS(I) AS CHAR(13))
		    AND A.PEDPROCOD = CAST(IN_PLATOS(I) AS CHAR(20));
		
		IF(V_FALTANTES = 0) THEN 
			UPDATE VEN0004
			SET PEDSAL = 'E'
			WHERE PEDNRO = V_PEDNRO
				AND PEDEMPC = IN_CODIGO_EMPRESA;
		END IF;
		
	END LOOP;
END;