CREATE OR REPLACE PROCEDURE SP_ACOMER_REGISTRO_CLIENTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_CLIENTE IN GEN0024.CLICOD%TYPE, 	-- CODIGO DEL CLIENTE QUE VA HACER REGISTRADO
	IN_NOMBRE_CLINETE IN GEN0024.CLINOM1%TYPE,	-- NOMBRE DLE CLIENTE QUE SE VA A REGISTRAR
	IN_DIRECCION_CLIENTE IN GEN0024.SUCTERDIR%TYPE, -- DIRECCION DEL CLIENTE QUE SE VA A REGISTRAR
	IN_CORREO_CLIENTE IN GEN0024.CLICNT%TYPE,		-- CORREO DEL CLIENTE QUE SE VA A REGISTRAR
	IN_TELEFONO_CLIENTE IN GEN0024.SUCTERTEL%TYPE,  -- TELEFONO DEL CLIENTE QUE SE VA A REGISTRAR
	OUT_CODIGO_MENSAJE OUT NUMBER					-- CODIGO DE MENSAJE	
)
AS
	V_CONTADOR NUMBER;
BEGIN
	-- =============================================
	-- O: CLIENTE YA SE ENCUENTRA REGISTRADO EN LA BASE DE DATOS 
	-- 1: REGISTRO COMPLETADO
	-- 2: REGISTRO ERRONEO

	-- =============================================
	-- CONSULTA SI YA EXISTE UN REGISTRO CON EL CODIGO INGRESADO 
	SELECT COUNT(*)
	INTO V_CONTADOR
	FROM GEN0024
	WHERE CLICOD = IN_CODIGO_CLIENTE;

	-- SI HAY UN REGISTRO 
	IF(V_CONTADOR >= 1) THEN 
		BEGIN
			-- SE INDICA QUE EL CLEINTE YA HA SIDO REGISTRADO 
			OUT_CODIGO_MENSAJE := 0;			
		END;
	ELSE
		BEGIN
			INSERT INTO GEN0024(
				CLICOD, CLINOM1,
				SUCTERDIR, CLICNT,
				SUCTERTEL, CLIPAICOD,
				LIPCOD, SUCTERCOD,
				CLIDIRENT)
			VALUES(
				IN_CODIGO_CLIENTE, IN_NOMBRE_CLINETE,
				IN_DIRECCION_CLIENTE, IN_CORREO_CLIENTE,
				IN_TELEFONO_CLIENTE, '169',
				'01','01',
				IN_CORREO_CLIENTE);

			IF(SQL%ROWCOUNT = 1) THEN 
				-- INSERCION COMPLETADA
				OUT_CODIGO_MENSAJE := 1;
			ELSE 
				OUT_CODIGO_MENSAJE := 2;
			END IF;
		END;
	END IF;	
END;