CREATE OR REPLACE PROCEDURE SP_ACOMER_NOMBRE_COCINAS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CEDULA IN TAB_REL_ROL.TERCOD%TYPE,			-- CEDULA DE QUIEN INCIIA
	OUT_NOMBRE_REST OUT GEN0006.EMPNOM%TYPE  		-- NOMBRE DE LA EMPRESA A LA QUE PERTENECE
)
AS
BEGIN
	-- CONSULTA EL NOMBRE DE LA EMPRESA A LA QUE PERTENECE
	SELECT TRIM (EMPNOM)
	INTO OUT_NOMBRE_REST
	FROM TAB_REL_ROL A
	INNER JOIN GEN0006 B
		ON A.EMPCOD = B.EMPCOD
	WHERE A.TERCOD = IN_CEDULA;
END;