CREATE OR REPLACE PROCEDURE SP_ACOMER_ENTREGA_PEDIDO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_EMPRESA VEN0004.PEDEMPC%TYPE, -- CODIGO DE LA EMPRESA A LA QUE PERTENECE EL PLATO
	IN_CODIGO_PEDIDO VEN0004.PEDNRO%TYPE,	-- CODIGO DE PEDIDO QUE SE LE ASIGNA AL PLATO
	IN_NOMBRE_PLATO VEN0004.PEDPROCOD%TYPE	-- CODIGO DEL PLATO QUE SE ESTA ENTREGANDO	
)
AS
	V_CODIGO_PLATO VEN0001.PROCOD%TYPE; -- CODIGO DEL PLATO QUE SE VA A ENTREGAR
BEGIN
	-- CONSULTA EL CODIGO DEL PLATO QUE SE INDICA YA ESTA LISTO PARA ENTREGAR
	SELECT PROCOD
	INTO V_CODIGO_PLATO
	FROM VEN0001
	WHERE PRODES = IN_NOMBRE_PLATO;		
	
	-- ACTUALIZA EL PEDIDO ESPECIFICO 
	UPDATE VEN0004
	SET PEDCHECK = 0,
		PEDSAL = 'T'
	WHERE PEDEMPC = IN_CODIGO_EMPRESA
		AND PEDNRO = IN_CODIGO_PEDIDO
		AND PEDPROCOD = V_CODIGO_PLATO;
		
	COMMIT;
END;