CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_AUTORI_ADSCRITOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_CD_CODI_AUTORIZA_AUAD IN VARCHAR2,
    V_FE_AUTORIZA_AUAD IN DATE,
    V_NU_ESTA_ANULA_AUAD IN NUMBER,
    V_NU_NUME_CONE_AUAD IN NUMBER,
    iV_NU_NUME_LABO_LAAU IN NUMBER,
    V_NU_VALO_LAAU IN NUMBER,
    V_PORC_CUBRIMIENTO_AUAD IN NUMBER,
    V_VAL_PAGPAC_AUAD IN NUMBER,
    V_VAL_PAGCONV_AUAD IN NUMBER,
    V_CD_CODI_ADSC_AUAD IN VARCHAR2,
    V_CD_CODI_COAD_AUAD IN VARCHAR2
)   
AS
  V_NU_NUME_LABO_LAAU NUMBER := iV_NU_NUME_LABO_LAAU;
BEGIN
    INSERT INTO AUTORIZACION_ADSCRITOS (
        CD_CODI_AUTORIZA_AUAD,
        FE_AUTORIZA_AUAD,
        NU_ESTA_ANULA_AUAD,
        NU_NUME_CONE_AUAD,
        PORC_CUBRIMIENTO_AUAD,
        VAL_PAGPAC_AUAD,
        VAL_PAGCONV_AUAD,
        CD_CODI_ADSC_AUAD,
        CD_CODI_COAD_AUAD)
    VALUES (
        V_CD_CODI_AUTORIZA_AUAD,
        V_FE_AUTORIZA_AUAD,
        V_NU_ESTA_ANULA_AUAD,
        V_NU_NUME_CONE_AUAD,
        V_PORC_CUBRIMIENTO_AUAD,
        V_VAL_PAGPAC_AUAD,
        V_VAL_PAGCONV_AUAD,
        V_CD_CODI_ADSC_AUAD,
        V_CD_CODI_COAD_AUAD);

    SELECT  NU_NUME_LABO
    INTO V_NU_NUME_LABO_LAAU
    FROM LABORATORIO
    WHERE NU_NUME_MOVI_LABO = iV_NU_NUME_LABO_LAAU;

    INSERT INTO R_LABO_AUTO (NU_AUTO_AUAD_LAAU,
        NU_NUME_LABO_LAAU,
        NU_VALO_LAAU)
    VALUES (
        (SELECT MAX (NU_AUTO_AUAD) FROM AUTORIZACION_ADSCRITOS),
        V_NU_NUME_LABO_LAAU,
        V_NU_VALO_LAAU);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;