CREATE OR REPLACE PROCEDURE H3i_SP_LIST_MOV_FACTCONT_CREDI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NU_NUME_FACO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
				
AS
BEGIN
	OPEN CV_1 FOR
		SELECT  NU_NUME_FACO,
		NU_NUME_MOVI,
		NU_DOCU_PAC,
		TX_NOMBRECOMPLETO_PAC,
		CD_CODI_SER,
		NO_NOMB_SER,
		NO_NOMB_ESP,
		'Completo' EST_RIPS,
		VL_COPA_MOVI,
		VL_UNID_MOVI,
		(VL_UNID_MOVI - VL_COPA_MOVI) VL_TOTAL,
		FE_FECH_MOVI
		FROM MOVI_CARGOS 
		INNER JOIN PACIENTES 
			ON NU_HIST_PAC_MOVI = NU_HIST_PAC
		INNER JOIN FACTURAS_CONTADO 
			ON NU_NUME_FACO_MOVI = NU_NUME_FACO
		INNER JOIN CONVENIOS 
			ON NU_NUME_CONV_MOVI = NU_NUME_CONV
		INNER JOIN EPS 
			ON CD_NIT_EPS_CONV = CD_NIT_EPS
		INNER JOIN LABORATORIO 
			ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
		INNER JOIN SERVICIOS 
			ON CD_CODI_SER = CD_CODI_SER_LABO
		INNER JOIN ESPECIALIDADES 
			ON CD_CODI_ESP = CD_CODI_ESP_LABO
		WHERE  NU_ESTA_MOVI <> 2 -- SE EXCLUYEN LOS ANULADOS
			AND NU_ESTA_FACO = 1 --SOLO SE INCLUIRAN LAS FACTURAS QUE F
			AND NU_NUME_FACO = V_NU_NUME_FACO
		ORDER BY NU_NUME_MOVI;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END  ;
