CREATE OR REPLACE PROCEDURE H3i_SP_ANULAR_PAGO_CUOTA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_NO_PAGO_PROGRAMADO IN NUMBER
)
AS
     v_PAGADOS NUMBER(10,0) := 0;
     v_PLAN_DE_PAGO NUMBER(10,0) := 0;
     v_NO_CUOTAS NUMBER(10,0) := 0;

BEGIN

    UPDATE ABONO_RECIBO_CAJA
    SET NU_NUME_ESTADO = 0
    WHERE  CD_CODI_PAPR_ABRC = v_NO_PAGO_PROGRAMADO
        AND NU_NUME_ESTADO = 1;
   
    
    UPDATE PAGO_PROGRAMADO
    SET NU_NUME_ESTADO = 0
    WHERE  CD_CODI_PAPR = v_NO_PAGO_PROGRAMADO;


    SELECT CD_CODI_PLP_PAPR 
    INTO v_PLAN_DE_PAGO
    FROM PAGO_PROGRAMADO 
    WHERE  CD_CODI_PAPR = v_NO_PAGO_PROGRAMADO;


    SELECT COUNT(*)  
    INTO v_NO_CUOTAS
    FROM PAGO_PROGRAMADO 
    WHERE  CD_CODI_PLP_PAPR = v_PLAN_DE_PAGO;


    SELECT COUNT(*)  
    INTO v_PAGADOS
    FROM PAGO_PROGRAMADO 
    WHERE  CD_CODI_PLP_PAPR = v_PLAN_DE_PAGO
        AND NU_NUME_ESTADO = 1;


    IF ( v_NO_CUOTAS > v_PAGADOS ) THEN
    
        BEGIN
            UPDATE PLAN_PAGOS
            SET NU_NUME_ESTADO = 0
            WHERE  CD_CODI_PLP = v_PLAN_DE_PAGO;   
        END;
    END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;