CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_PAGO_PROGRAMADO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_PLAN_DE_PAGOS IN NUMBER,
  v_NU_CUOTA IN NUMBER,
  v_FECHA_PROGRAMADA IN VARCHAR2,
  v_MONTO_PROGRAMADO IN NUMBER,
  v_TIPO_PROGRA IN NUMBER,
  v_TIPO_MONTO IN NUMBER,
  v_ESTADO IN NUMBER,
  v_NO_CONEXION IN NUMBER
)
AS

BEGIN

    INSERT INTO PAGO_PROGRAMADO( 
        CD_CODI_PLP_PAPR, NU_CUOTA, 
        FE_FECH_PAPR, VL_VAL_MONTO, 
        NU_TIPO_PROGRA, NU_TIPO_MONTO, 
        NU_NUME_ESTADO, NU_CONE_PLP )
    VALUES( 
        v_CD_PLAN_DE_PAGOS, v_NU_CUOTA, 
        v_FECHA_PROGRAMADA, v_MONTO_PROGRAMADO, 
        v_TIPO_PROGRA, v_TIPO_MONTO, 
        v_ESTADO, v_NO_CONEXION );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;