CREATE OR REPLACE PROCEDURE H3i_SP_CREA_CARGO_ELEMENTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER DEFAULT NULL ,
  v_TIPO IN NUMBER DEFAULT NULL ,
  v_SUM_VAL_DETALLES IN FLOAT DEFAULT NULL ,
  v_SUM_VAL_CUOTA_MODERADORA IN FLOAT DEFAULT NULL ,
  v_ESTADO IN NUMBER DEFAULT 1 ,
  v_NO_HISTORIA IN VARCHAR2 DEFAULT NULL ,
  v_NO_FACTURA_EPS IN NUMBER DEFAULT 0 ,
  v_FECHA_HORA IN DATE DEFAULT NULL ,
  v_NO_REGISTRO IN NUMBER DEFAULT 0 ,
  v_NO_CONVENIO IN NUMBER DEFAULT NULL ,
  v_NO_FACTURA_PACIENTE IN NUMBER DEFAULT 0 ,
  v_AMBITO_DE_ATENCION IN NUMBER DEFAULT 1 ,
  v_AREA_QUE_GENERA IN VARCHAR2 DEFAULT NULL ,
  v_NO_PAQUETE IN NUMBER DEFAULT 0 ,
  v_COD_MEDICO_REALIZA IN VARCHAR2 DEFAULT NULL ,
  v_COD_MEDICO_ORDENA IN VARCHAR2 DEFAULT NULL ,
  v_BONO IN VARCHAR2 DEFAULT NULL ,
  v_CONEXION IN NUMBER DEFAULT NULL ,
  v_POSICION_EN_FACTURA_EPS IN NUMBER DEFAULT NULL ,
  v_TIPO_COPAGO IN NUMBER DEFAULT NULL ,
  v_LUGAR_ATENCION IN VARCHAR2 DEFAULT NULL ,
  v_ES_GESTANTE IN NUMBER DEFAULT 0 ,--0 (0 HOMBRE, 1 MUJER EN EMBARAZO)
  v_REGIMEN_PACIENTE IN VARCHAR2 DEFAULT NULL ,
  v_USO_EN_HISTORIA_CLINICA IN NUMBER DEFAULT NULL 
)
AS

BEGIN

    --1. Insertar en la tabla MOVI_CARGOS 
    INSERT INTO MOVI_CARGOS( 
        NU_NUME_MOVI, NU_TIPO_MOVI, 
        VL_UNID_MOVI, VL_COPA_MOVI, 
        NU_ESTA_MOVI, NU_HIST_PAC_MOVI, 
        NU_NUME_FAC_MOVI, FE_FECH_MOVI, 
        NU_NUME_REG_MOVI, NU_NUME_CONV_MOVI, 
        NU_NUME_FACO_MOVI, NU_TIAT_MOVI, 
        CD_CODI_CECO_MOVI, NU_NUME_PAQU_MOVI, 
        CD_CODI_MED_MOVI, CD_MEDI_ORDE_MOVI, 
        DE_BONO_MOVI, NU_NUME_CONE_MOVI, 
        NU_POSI_FACT_MOVI, NU_TIPO_COPA_MOVI, 
        CD_CODI_LUAT_MOVI, ES_GESTANTE, 
        CD_REGIMEN_MOVI, NU_BLHIS_MOVI )
    VALUES ( 
        v_CODIGO, v_TIPO, 
        v_SUM_VAL_DETALLES, v_SUM_VAL_CUOTA_MODERADORA, 
        v_ESTADO, v_NO_HISTORIA, 
        v_NO_FACTURA_EPS, v_FECHA_HORA, 
        v_NO_REGISTRO, v_NO_CONVENIO, 
        v_NO_FACTURA_PACIENTE, 1, 
        v_AREA_QUE_GENERA, NVL(v_NO_PAQUETE, 0), 
        v_COD_MEDICO_REALIZA, v_COD_MEDICO_ORDENA, 
        v_BONO, v_CONEXION, 
        v_POSICION_EN_FACTURA_EPS, v_TIPO_COPAGO, 
        v_LUGAR_ATENCION, v_ES_GESTANTE, 
        v_REGIMEN_PACIENTE, v_USO_EN_HISTORIA_CLINICA );


    --2. Insertar en la tabla MOVI_SEMA_COTIZ
    INSERT INTO MOVI_SEMA_COTIZ( 
        NU_NUME_MOVI, NU_SEMCOTIZ_MOVSEMCOT )
    VALUES ( v_CODIGO, 0 );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;