CREATE OR REPLACE PROCEDURE H3i_SP_ACTU_CRGO_MEDIC_DEVUEL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_CODIGO IN INT
)

AS
    V_VL_UNID_MOVI NUMBER;
    V_VL_COPA_MOVI NUMBER;
    V_CD_CODI_CECO_MOVI VARCHAR2(11);
BEGIN
    -------------------
    SELECT SUM(FOM.CT_CANT_FORM * FOM.VL_UNID_FORM),
        SUM(FOM.VL_COPA_FORM),
        MOV.CD_CODI_CECO_MOVI
    INTO V_VL_UNID_MOVI, 
        V_VL_COPA_MOVI, 
        V_CD_CODI_CECO_MOVI
    FROM MOVI_CARGOS MOV
    INNER JOIN FORMULAS FOM
        ON FOM.NU_NUME_MOVI_FORM = MOV.NU_NUME_MOVI
    WHERE MOV.NU_NUME_MOVI = V_CODIGO
    GROUP BY CD_CODI_CECO_MOVI;
    -------------------
    UPDATE MOVI_CARGOS
    SET    
        NU_ESTA_MOVI = CASE WHEN V_VL_UNID_MOVI > 0 THEN NU_ESTA_MOVI ELSE 2 END,
        VL_UNID_MOVI = V_VL_UNID_MOVI,
        VL_COPA_MOVI = V_VL_COPA_MOVI
    WHERE  
        NU_NUME_MOVI = V_CODIGO;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;