CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_CARGO_COT_LABO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_MOVI_LCOT IN NUMBER DEFAULT NULL ,
  v_CD_CODI_ESP_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_CD_CODI_SER_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_CT_CANT_LCOT IN NUMBER DEFAULT NULL ,
  v_VL_UNID_LCOT IN FLOAT DEFAULT NULL ,
  v_VL_COPA_LCOT IN FLOAT DEFAULT NULL ,
  v_CD_CODI_MEDI_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_NU_NIVE_LCOT IN NUMBER DEFAULT NULL ,
  v_ID_CODI_TIPR_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_CODI_PRAT_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_CODI_EMBA_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_NU_ESTA_LCOT IN NUMBER DEFAULT NULL ,
  v_NU_AUTO_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_DE_COND_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_CODI_TIDI_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_CODI_CAEX_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_NU_DIIN_LCOT IN NUMBER DEFAULT NULL ,
  v_DE_PRES_LCOT IN NUMBER DEFAULT NULL ,
  v_CD_CODI_TIDI_LCOT IN VARCHAR2 DEFAULT NULL ,
  /*@NU_NUME_LCOT int,*/
  v_CD_CODI_VIAC_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_CD_CODI_SALA_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_CD_CODI_TIAN_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_NU_ESHI_LCOT IN NUMBER DEFAULT NULL ,
  v_NU_EDAD_LCOT IN NUMBER DEFAULT NULL ,
  v_CD_CODI_FICO_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_ACTO_QUIR_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_ID_ESTA_ASIS_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_TX_CODI_RRTT_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_TX_CODI_RPP_LCOT IN VARCHAR2 DEFAULT NULL ,
  v_TX_CODI_RFF_LCOT IN VARCHAR2 DEFAULT NULL 
)
AS

BEGIN

    INSERT INTO LABORATORIO_COT( 
        NU_NUME_MOVI_LCOT, CD_CODI_ESP_LCOT, 
        CD_CODI_SER_LCOT, CT_CANT_LCOT, 
        VL_UNID_LCOT, VL_COPA_LCOT, 
        CD_CODI_MEDI_LCOT, NU_NIVE_LCOT, 
        ID_CODI_TIPR_LCOT, ID_CODI_PRAT_LCOT, 
        ID_CODI_EMBA_LCOT, NU_ESTA_LCOT, 
        NU_AUTO_LCOT, DE_COND_LCOT, 
        ID_CODI_TIDI_LCOT, ID_CODI_CAEX_LCOT, 
        NU_DIIN_LCOT, DE_PRES_LCOT, 
        CD_CODI_TIDI_LCOT, CD_CODI_VIAC_LCOT, 
        CD_CODI_SALA_LCOT, CD_CODI_TIAN_LCOT, 
        NU_ESHI_LCOT, NU_EDAD_LCOT, 
        CD_CODI_FICO_LCOT, ID_ACTO_QUIR_LCOT, 
        ID_ESTA_ASIS_LCOT, TX_CODI_RRTT_LCOT, 
        TX_CODI_RPP_LCOT, TX_CODI_RFF_LCOT )
    VALUES ( 
        v_NU_NUME_MOVI_LCOT, v_CD_CODI_ESP_LCOT, 
        v_CD_CODI_SER_LCOT, v_CT_CANT_LCOT, 
        v_VL_UNID_LCOT, v_VL_COPA_LCOT, 
        v_CD_CODI_MEDI_LCOT, v_NU_NIVE_LCOT, 
        v_ID_CODI_TIPR_LCOT, v_ID_CODI_PRAT_LCOT, 
        v_ID_CODI_EMBA_LCOT, v_NU_ESTA_LCOT, 
        v_NU_AUTO_LCOT, v_DE_COND_LCOT, 
        v_ID_CODI_TIDI_LCOT, v_ID_CODI_CAEX_LCOT, 
        v_NU_DIIN_LCOT, v_DE_PRES_LCOT, 
        v_CD_CODI_TIDI_LCOT, v_CD_CODI_VIAC_LCOT, 
        v_CD_CODI_SALA_LCOT, v_CD_CODI_TIAN_LCOT,
         v_NU_ESHI_LCOT, v_NU_EDAD_LCOT, 
         v_CD_CODI_FICO_LCOT, v_ID_ACTO_QUIR_LCOT, 
         v_ID_ESTA_ASIS_LCOT, v_TX_CODI_RRTT_LCOT, 
         v_TX_CODI_RPP_LCOT, v_TX_CODI_RFF_LCOT );


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;