CREATE OR REPLACE PROCEDURE H3i_SP_CAM_EST_FAC_CONT_CRE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  v_MOTIVO IN VARCHAR2,
  v_USUARIO IN VARCHAR2,
  v_ESTADO IN NUMBER
)
AS

BEGIN

    INSERT INTO FACTURAS_ANULADAS_CRED( 
        NU_NUME_FAC__FACA, USUARIO )
    VALUES (
       v_CODIGO, v_USUARIO);


    UPDATE FACTURAS_CONTADO_CREDITO
    SET NU_ESTADO_FCCR = v_ESTADO,
        CD_CODI_MOT_ANU_FACON = v_MOTIVO
    WHERE  NU_AUTO_FCCR = v_CODIGO;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;