CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_TARIFA_BASE
(
  v_NO_NOMB_TARB IN VARCHAR2 DEFAULT NULL ,
  v_NU_INLI_TARB IN NUMBER DEFAULT NULL ,
  v_VL_BASE_TARB IN FLOAT DEFAULT NULL ,
  v_CD_CODI_ANO_TARB IN NUMBER DEFAULT NULL 
)
AS
    v_CD_CODI NUMBER(10,0);

BEGIN

    SELECT( SELECT MAX(TO_NUMBER(CD_CODI_TARB))  
            FROM TARIFA_BASE) + 1
    INTO v_CD_CODI
    FROM DUAL;


    IF ( v_CD_CODI IS NULL ) THEN
        v_CD_CODI := 1 ;
    END IF;


    INSERT INTO TARIFA_BASE( 
        CD_CODI_TARB, NO_NOMB_TARB, 
        NU_INLI_TARB, VL_BASE_TARB, 
        CD_CODI_ANO_TARB, NU_VAMU_TARB )
    VALUES ( 
        v_CD_CODI, v_NO_NOMB_TARB, 
        v_NU_INLI_TARB, v_VL_BASE_TARB, 
        v_CD_CODI_ANO_TARB, NULL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;