CREATE OR REPLACE PROCEDURE H3i_SP_CONS_CARG_DESP_FORM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_HIST_PAC IN VARCHAR2,
  v_FECHA_INI IN DATE,
  v_FECHA_FIN IN DATE,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   --
   -- SELECCIONAR LOS LABORATORIOS CORRESPONDIENTES A LOS CARGOS FACTURABLES           
   --
   OPEN  cv_1 FOR
      SELECT FOM.NU_NUME_FORM ,
             FOM.NU_NUME_MOVI_FORM ,
             FOM.CD_CODI_ELE_FORM ,
             TO_NUMBER(FOM.CT_CANT_FORM) CT_CANT_FORM  ,
             FOM.VL_UNID_FORM ,
             FOM.VL_COPA_FORM ,
             SME.NO_NOMB_ARTI_SMED ,
             MED_REALIZA.NO_NOMB_MED ,
             MED_REALIZA.CD_CODI_MED 
        FROM FORMULAS FOM
        INNER JOIN tt_CARGOS_2 CAR   
            ON FOM.NU_NUME_MOVI_FORM = CAR.NU_NUME_MOVI
            AND FOM.NU_ESTA_FORM <> 2
        INNER JOIN SOLICITUD_MED SME   
            ON CAR.NU_NUME_MOVI = SME.NU_NUME_MOVI_SMED
            AND SME.CD_CODI_ARTI_SMED = FOM.CD_CODI_ELE_FORM
        INNER JOIN MEDICOS MED_REALIZA   
            ON FOM.CD_CODI_MED_FORM = MED_REALIZA.CD_CODI_MED
        GROUP BY FOM.NU_NUME_FORM,FOM.NU_NUME_MOVI_FORM,
            FOM.CD_CODI_ELE_FORM,FOM.CT_CANT_FORM,
            FOM.VL_UNID_FORM,FOM.VL_COPA_FORM,
            SME.NO_NOMB_ARTI_SMED,MED_REALIZA.NO_NOMB_MED,
            MED_REALIZA.CD_CODI_MED ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;