CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_R_SER_TARB
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================

(
    v_CD_CODI_SER_RST IN VARCHAR2 DEFAULT NULL ,
    v_CD_CODI_TARB_RST IN VARCHAR2 DEFAULT NULL ,
    v_VL_VALO_RST IN FLOAT DEFAULT NULL ,
    v_CD_ALTE_RST IN VARCHAR2 DEFAULT NULL ,
    v_NU_TILI_RST IN NUMBER DEFAULT NULL ,
    v_CD_ALT2_RST IN VARCHAR2 DEFAULT NULL ,
    v_ID_GERI_RST IN NUMBER DEFAULT NULL 
)
AS

BEGIN

    INSERT INTO R_SER_TARB( 
        CD_CODI_SER_RST, CD_CODI_TARB_RST, 
        VL_VALO_RST, CD_ALTE_RST, 
        NU_TILI_RST, CD_ALT2_RST, 
        ID_GERI_RST )
    VALUES( 
        v_CD_CODI_SER_RST, v_CD_CODI_TARB_RST, 
        v_VL_VALO_RST, v_CD_ALTE_RST, 
        v_NU_TILI_RST, v_CD_ALT2_RST, 
        1 );
   

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;