CREATE OR REPLACE PROCEDURE H3i_SP_CONS_ANEXO_TECNICO_N3
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NUHISTPAC IN VARCHAR2 DEFAULT NULL,
	V_NUMSOLSER IN VARCHAR2 DEFAULT NULL,
	CV_1 OUT SYS_REFCURSOR
)
AS
	V_NO_NOMB_DPTO DEPARTAMENTOS.NO_NOMB_DPTO%TYPE;
	V_NO_NOMB_MUNI MUNICIPIOS.NO_NOMB_MUNI%TYPE;
	V_DESC_PRI_DIAG VARCHAR2(270);
	V_DESC_SEG_DIAG VARCHAR2(270);
	V_DESC_TERC_DIAG VARCHAR2(270);
	V_NU_NUME_LABO_RLAD NUMBER;
	V_NO_NOMB_ESP ESPECIALIDADES.NO_NOMB_ESP%TYPE;
BEGIN
	------------------------------DEP_PAC-------------------------------------------
	SELECT D.NO_NOMB_DPTO
	INTO V_NO_NOMB_DPTO 
	FROM DEPARTAMENTOS D 
	INNER JOIN PACIENTES PAC 
		ON PAC.CD_CODI_DPTO_PAC = D.CD_CODI_DPTO 
	WHERE PAC.NU_HIST_PAC = V_NUHISTPAC 
		AND D.CD_CODI_PAIS_DPTO = '57';

	------------------------------MUN_PAC-------------------------------------------
	SELECT M.NO_NOMB_MUNI 
	INTO V_NO_NOMB_MUNI
	FROM MUNICIPIOS M 
	INNER JOIN PACIENTES PAC 
		ON PAC.CD_CODI_MUNI_PAC = M.CD_CODI_MUNI 
	WHERE PAC.CD_CODI_DPTO_PAC = M.CD_CODI_DPTO_MUNI 
		AND PAC.NU_HIST_PAC =  V_NUHISTPAC 
		AND M.CD_CODI_PAIS_MUNI = '57';

	------------------------------NU_NUME_LABO_RLAD-------------------------------------------
	SELECT MAX(RLD.NU_NUME_LABO_RLAD) 
	INTO V_NU_NUME_LABO_RLAD
	FROM DIAGNOSTICO D 
	INNER JOIN R_LABO_DIAG RLD 
		ON D.CD_CODI_DIAG = RLD.CD_CODI_DIAG_RLAD
	INNER JOIN LABORATORIO L 
		ON RLD.NU_NUME_LABO_RLAD = L.NU_NUME_LABO
	INNER JOIN MOVI_CARGOS MV 
		ON L.NU_NUME_MOVI_LABO = MV.NU_NUME_MOVI
	WHERE ROWNUM <= 1;

	------------------------------DESC_PRI_DIAG-------------------------------------------
	SELECT D.CD_CODI_DIAG||'-'||D.DE_DESC_DIAG
	INTO V_DESC_PRI_DIAG
	FROM DIAGNOSTICO D 
	INNER JOIN R_LABO_DIAG RLD 
		ON D.CD_CODI_DIAG = RLD.CD_CODI_DIAG_RLAD
	INNER JOIN LABORATORIO L 
		ON RLD.NU_NUME_LABO_RLAD = L.NU_NUME_LABO
	INNER JOIN MOVI_CARGOS MV 
		ON L.NU_NUME_MOVI_LABO = MV.NU_NUME_MOVI
	WHERE MV.NU_HIST_PAC_MOVI = V_NUHISTPAC 
		AND RLD.ID_TIPO_DIAG_RLAD = 'PR' 
		AND MV.NU_NUME_FAC_MOVI = 0 
		AND RLD.NU_NUME_LABO_RLAD = V_NU_NUME_LABO_RLAD;

	------------------------------DESC_SEG_DIAG-------------------------------------------
	SELECT D.CD_CODI_DIAG||'-'|| D.DE_DESC_DIAG  
	INTO V_DESC_SEG_DIAG
	FROM DIAGNOSTICO D 
	INNER JOIN R_LABO_DIAG RLD 
		ON D.CD_CODI_DIAG = RLD.CD_CODI_DIAG_RLAD
	INNER JOIN LABORATORIO L 
		ON RLD.NU_NUME_LABO_RLAD = L.NU_NUME_LABO
	INNER JOIN MOVI_CARGOS MV 
		ON L.NU_NUME_MOVI_LABO = MV.NU_NUME_MOVI
	WHERE MV.NU_HIST_PAC_MOVI = V_NUHISTPAC 
		AND RLD.ID_TIPO_DIAG_RLAD = 'R1' 
		AND	MV.NU_NUME_FAC_MOVI = 0 
		AND	RLD.NU_NUME_LABO_RLAD = V_NU_NUME_LABO_RLAD;

	------------------------------DESC_TERC_DIAG-------------------------------------------
	SELECT D.CD_CODI_DIAG||'-'|| D.DE_DESC_DIAG  
	INTO V_DESC_TERC_DIAG
	FROM DIAGNOSTICO D 
	INNER JOIN R_LABO_DIAG RLD 
		ON D.CD_CODI_DIAG = RLD.CD_CODI_DIAG_RLAD
	INNER JOIN LABORATORIO L 
		ON RLD.NU_NUME_LABO_RLAD = L.NU_NUME_LABO
	INNER JOIN MOVI_CARGOS MV 
		ON L.NU_NUME_MOVI_LABO = MV.NU_NUME_MOVI
	WHERE MV.NU_HIST_PAC_MOVI = V_NUHISTPAC 
		AND RLD.ID_TIPO_DIAG_RLAD = 'R2' 
		AND	MV.NU_NUME_FAC_MOVI = 0 
		AND	RLD.NU_NUME_LABO_RLAD = V_NU_NUME_LABO_RLAD;

	------------------------------NOM_ESPECI_REGI-------------------------------------------
	SELECT NO_NOMB_ESP 
	INTO V_NO_NOMB_ESP
	FROM ESPECIALIDADES 
	INNER JOIN REGISTRO RG
		ON CD_CODI_ESP = RG.CD_CODI_ESP_REG;

	OPEN CV_1 FOR 
		SELECT SS.NU_AUTO_SOSE, 
			SYSDATE AS FECHA, 
			E.ID_TIPO_IDEN_ENTI,
			E.NIT, 
			E.ENTIDAD,
			E.CD_CODI_PSS_ENTI,
			E.DE_TELE_ENTI, 
			E.DE_DIRE_ENTI,
			D.NO_NOMB_DPTO,
			E.CD_CODI_DPTO_ENTI,
			M.NO_NOMB_MUNI, 
			E.CD_CODI_MUNI_ENTI,
			AD.NO_NOMB_EPS,
			AD.CD_NIT_EPS,
			AD.CD_CODI_EPS,
			PAC.DE_PRAP_PAC, 
			PAC.DE_SGAP_PAC,
			PAC.NO_NOMB_PAC,
			PAC.NO_SGNO_PAC,
			PAC.NU_TIPD_PAC,
			PAC.NU_DOCU_PAC, 
			PAC.FE_NACI_PAC,
			PAC.DE_DIRE_PAC,
			PAC.DE_TELE_PAC,
			REG.NO_NOMB_REG,
			REG.ID_CODI_TIUS_REG, 
			RTI.TX_DESC_RTT,
			V_NO_NOMB_DPTO DEP_PAC,
			V_NO_NOMB_MUNI MUN_PAC,
			PAC.CD_CODI_DPTO_PAC, 
			PAC.CD_CODI_MUNI_PAC,
			REG.ID_CODI_TIUS_REG,
			SS.CD_ORAT_SOSE, 
			SS.CD_UBIC_SOSE,
			SS.CD_CODI_ESP_SSOL,
			ESP.NO_NOMB_ESP,
			SS.CD_CAMA_SOSE,
			S.NO_NOMB_SER DE_DESC_SER_RSS, 
			S.NU_OPCI_SER NU_CASE_RSS,
			SO.cd_serv_soli CD_CODI_SER_RSS,
			SO.de_desc_soli, 
			SO.DE_JUST_SOLI DE_JUST_RSS, 
			SO.CT_CANT_SOLI,
			SO.cd_espe_soli, 
			ME.NO_NOMB_MED,
			SS.CD_DIPR_SOSE,
			RG.NU_TIAT_REG,			
			V_DESC_PRI_DIAG DESC_PRI_DIAG,
			SS.CD_DISG_SOSE,			
			V_DESC_SEG_DIAG DESC_SEG_DIAG,
			SS.CD_DITR_SOSE, 
			V_DESC_TERC_DIAG DESC_TERC_DIAG,			
			NVL(RG.CD_CODI_CAMA_REG,'0') CAMA_PAC, 
			NVL(RG.NU_TIAT_REG,0) TIPO_ATENCION, 
			NVL(RG.ID_CODI_CAEX_REG,0) CAUSA_EXT,
			V_NO_NOMB_ESP NOM_ESPECI_REGI
		FROM ENTIDAD E 
		INNER JOIN DEPARTAMENTOS D 
			ON CD_CODI_DPTO = CD_CODI_DPTO_ENTI 
		INNER JOIN MUNICIPIOS M 
			ON CD_CODI_MUNI = CD_CODI_MUNI_ENTI 
				AND M.CD_CODI_DPTO_MUNI = D.CD_CODI_DPTO
		INNER JOIN SOLICITUD_SERVICIOS SS 
		INNER JOIN CONVENIOS C 
			ON SS.NU_CONV_PAC_REG = C.NU_NUME_CONV 
		INNER JOIN EPS AD 
			ON AD.CD_NIT_EPS = C.CD_NIT_EPS_CONV 
		INNER JOIN PACIENTES PAC 
			ON PAC.NU_HIST_PAC = SS.NU_HIST_PAC_SOSE 
		INNER JOIN R_PAC_EPS RP 
			ON PAC.NU_HIST_PAC = RP.NU_HIST_PAC_RPE 
				AND RP.CD_NIT_EPS_RPE = AD.CD_NIT_EPS 
		INNER JOIN REGIMEN REG 
			ON RP.CD_CODI_REG_RPE = REG.CD_CODI_REG 
		INNER JOIN R_TIUS_TIUSF RTI 
			ON REG.ID_CODI_TIUS_REG = RTI.ID_CODI_TIUS_RTT 
		INNER JOIN R_SOSE_SOLI RSO 
			ON SS.NU_AUTO_SOSE = RSO.NU_AUTO_SOSE_RSO 
		INNER JOIN Solicitudes SO 
			ON RSO.NU_AUTO_SOLI_RSO = So.nu_auto_soli 
		INNER JOIN SERVICIOS S 
			ON SO.cd_serv_soli = S.CD_CODI_SER
		INNER JOIN ESPECIALIDADES ESP 
			ON SO.cd_espe_soli = ESP.CD_CODI_ESP 
		INNER JOIN MEDICOS ME 
			ON So.cd_medi_soli = ME.CD_CODI_MED
		LEFT JOIN REGISTRO RG 
			ON RG.NU_HIST_PAC_REG = SS.NU_HIST_PAC_SOSE 
				AND RG.ID_ESTA_ASIS_REG = 0 
				AND RG.NU_ESCU_REG <> 2
			ON SS.NU_AUTO_SOSE = V_NUMSOLSER  
				AND D.CD_CODI_PAIS_DPTO = '57';

END;