CREATE TABLE SPTYT.AUDIT3I
(
  AUDITID          NUMBER(18)                   NOT NULL,
  TYPE             VARCHAR2(1),
  TABLENAME        VARCHAR2(128 CHAR),
  PRIMARYKEYFIELD  VARCHAR2(1000 CHAR),
  PRIMARYKEYVALUE  VARCHAR2(1000 CHAR),
  FIELDNAME        VARCHAR2(128 CHAR),
  OLDVALUE         VARCHAR2(4000),
  NEWVALUE         VARCHAR2(4000),
  UPDATEDATE       DATE,
  USERNAME         VARCHAR2(128 CHAR),
  IDSESIONSERVER   NUMBER(18),
  NOCONEXION       NUMBER(18)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE OR REPLACE TRIGGER SPTYT.Audit3i_AuditID_TRG BEFORE INSERT ON SPTYT.AUDIT3I
FOR EACH ROW
DECLARE 
   
BEGIN
    SELECT Audit3i_AuditID_SEQ.NEXTVAL
    INTO   :NEW.AuditID
    FROM   dual;
END;