CREATE OR REPLACE PROCEDURE H3i_SP_INGRDETAORDEN_SERVICIO 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NoHICL IN NUMBER,
  v_NoEVOLUCION IN NUMBER DEFAULT 0 ,
  v_CODSERVICIO IN VARCHAR2,
  v_CANTIDAD IN NUMBER,
  v_OBSERVACION IN vARCHAR2,
  v_POSICION IN NUMBER,
  v_NoORDEN IN NUMBER,
  v_TIPO IN NUMBER,
  v_CODESPECIALIDAD IN VARCHAR2 DEFAULT NULL ,
  v_NU_LABO_EVOL IN NUMBER DEFAULT NULL 
)
AS
   v_NumID NUMBER;

BEGIN

    INSERT INTO HIST_PROC( 
        NU_NUME_HICL_HPRO, NU_NUME_HEVO_HPRO, 
        CD_CODI_SER_HPRO, NU_CANT_HPRO, 
        DE_INDI_HPRO, NU_POSI_HPRO, 
        NU_ORDE_HPRO, NU_TIPO_HPRO, 
        NU_ESTA_HPRO, NU_LABO_EVOL)
    VALUES ( 
      v_NoHICL, v_NoEVOLUCION, 
      v_CODSERVICIO, v_CANTIDAD, 
      v_OBSERVACION, v_POSICION, 
      v_NoORDEN, v_TIPO, 
      1, v_NU_LABO_EVOL);

   IF ( v_TIPO = 1 ) THEN
    
    --SOLO SI SE TRATA DE CONSULTAS
     BEGIN
        SELECT NU_NUME_HPRO 
        INTO v_NumID 
        FROM HIST_PROC
        WHERE NU_NUME_HPRO = (SELECT MAX(NU_NUME_HPRO) FROM HIST_PROC);

        
        INSERT INTO HIST_PROCONS
          ( NU_NUME_HPRO_HPCO, CD_CODI_ESP_HPCO )
          VALUES ( v_NumID, v_CODESPECIALIDAD );
     
     END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;