CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_DX --	PROCEDIMIENTO ALMACENADO QUE PERMITE GUARDAR LOS DIAGNOSTICOS 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_DIAG IN VARCHAR2,
  v_NU_NOTI_DIAG IN NUMBER,
  v_NU_APLI_DIAG IN NUMBER,
  v_NU_EDIN_DIAG IN NUMBER,
  v_NU_EDFI_DIAG IN NUMBER,
  v_NU_CIE_DIAG IN NUMBER,
  v_DE_OBSE_DIAG IN VARCHAR2,
  v_DE_DESC_DIAG IN VARCHAR2,
  v_INHABIL IN NUMBER DEFAULT NULL ,
  v_CD_CODI_DIAG_REL IN VARCHAR2
)
AS

BEGIN

   INSERT INTO DIAGNOSTICO
     ( CD_CODI_DIAG, NU_NOTI_DIAG, NU_APLI_DIAG, NU_EDIN_DIAG, NU_EDFI_DIAG, NU_CIE_DIAG, DE_OBSE_DIAG, DE_DESC_DIAG, INHABIL, CD_CODI_DIAG_REL )
     VALUES ( v_CD_CODI_DIAG, v_NU_NOTI_DIAG, v_NU_APLI_DIAG, v_NU_EDIN_DIAG, v_NU_EDFI_DIAG, v_NU_CIE_DIAG, v_DE_OBSE_DIAG, v_DE_DESC_DIAG, v_INHABIL, v_CD_CODI_DIAG_REL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;