CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_CONSENTIMIENTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_HCONSENT IN NUMBER,
  v_NOEVO IN NUMBER,
  v_ES_OTRO_DOCUMENTO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT * 
        FROM HIST_CONSENT 
               JOIN FORMATOS_CONSENTIMIENTO    ON NU_NUME_FOCO = NU_NUME_FOCO_HCONSENT
       WHERE  NU_NUME_HICL_HCONSENT = v_NU_NUME_HICL_HCONSENT
                AND NU_NUME_HEVO_HCONSENT = v_NoEVO
                AND ES_OTRO_DOCUMENTO = v_ES_OTRO_DOCUMENTO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;