CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_PARTO -- PROCEDIMIENTO ALMACENADO QUE PERMITE GUARDAR UN REGISTRO PARA PARTOGRAMA 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_PAR IN VARCHAR2,
  v_CD_CODI_ENF IN VARCHAR2,
  v_NU_LABO IN NUMBER,
  v_HORA_PAR_ENF IN DATE,
  v_POS_MAT_PAR IN VARCHAR2,
  v_TEN_ART_PAR IN VARCHAR2,
  v_PUL_MAT_PAR IN NUMBER,
  v_FRE_CAR_FET_PAR IN VARCHAR2,
  v_DUR_CON_PAR IN NUMBER,
  v_FRE_CON_PAR IN NUMBER,
  v_DOL_LOC_INT_PAR IN VARCHAR2,
  v_NU_COL_PAR IN NUMBER
)
AS
   v_temp NUMBER(1, 0) := 0;

BEGIN

   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE ( SELECT COUNT(NU_NUME_HICL_PAR)  
               FROM HIST_PARTO 
                WHERE  NU_NUME_HICL_PAR = v_NU_NUME_HICL_PAR
                         AND NU_LABO = v_NU_LABO
                         AND NU_COL_PAR = v_NU_COL_PAR ) = 0;
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;
      
   IF v_temp = 1 THEN
    
    --NO EXISTE REGISTRO PARTOGRAMA
   BEGIN
      INSERT INTO HIST_PARTO
        ( NU_NUME_HICL_PAR, CD_CODI_ENF, NU_LABO, HORA_PAR_ENF, POS_MAT_PAR, TEN_ART_PAR, PUL_MAT_PAR, FRE_CAR_FET_PAR, DUR_CON_PAR, FRE_CON_PAR, DOL_LOC_INT_PAR, NU_COL_PAR )
        VALUES ( v_NU_NUME_HICL_PAR, v_CD_CODI_ENF, v_NU_LABO, v_HORA_PAR_ENF, v_POS_MAT_PAR, v_TEN_ART_PAR, v_PUL_MAT_PAR, v_FRE_CAR_FET_PAR, v_DUR_CON_PAR, v_FRE_CON_PAR, v_DOL_LOC_INT_PAR, v_NU_COL_PAR );
   
   END;
   ELSE
   
   BEGIN
      UPDATE HIST_PARTO
         SET CD_CODI_ENF = v_CD_CODI_ENF,
             HORA_PAR_ENF = v_HORA_PAR_ENF,
             POS_MAT_PAR = v_POS_MAT_PAR,
             TEN_ART_PAR = v_TEN_ART_PAR,
             PUL_MAT_PAR = v_PUL_MAT_PAR,
             FRE_CAR_FET_PAR = v_FRE_CAR_FET_PAR,
             DUR_CON_PAR = v_DUR_CON_PAR,
             FRE_CON_PAR = v_FRE_CON_PAR,
             DOL_LOC_INT_PAR = v_DOL_LOC_INT_PAR
       WHERE  NU_NUME_HICL_PAR = v_NU_NUME_HICL_PAR
        AND NU_LABO = v_NU_LABO
        AND NU_COL_PAR = v_NU_COL_PAR;
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;