CREATE OR REPLACE PROCEDURE H3i_GUARDAR_CONTRAREFERENCIA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CDCONTRA OUT NUMBER,
  v_PLANTILLA IN NUMBER,
  v_DOCUMENTOPACIENTE IN VARCHAR2,
  v_CODTDOC IN NUMBER,
  v_NUMLABO IN NUMBER,
  v_FECHA_REGISTRA IN DATE,
  v_HORA_REGISTRA IN DATE,
  v_NOMBRERESPONSABLE IN VARCHAR2,
  v_CODPARENTESCO IN VARCHAR2,
  v_DIRECCIONRESPONSABLE IN VARCHAR2,
  v_TELEFONORESPONSABLE IN VARCHAR2,
  v_SERVICIO IN VARCHAR2,
  v_OBSERVACION IN VARCHAR2,
  v_ATENCION IN NUMBER
)
AS

BEGIN

    INSERT INTO CONTRAREFERENCIA( 
      PLANTILLA, DOCPAC, CODTDOC, 
      NUME_LABO, FECHA_REGISTRA, HORA_REGISTRA, 
      NOMBRERESPONSABLE, CODPARENTESCO, DIRECCIONRESPONSABLE, 
      TELEFONORESPONSABLE, SERVICIO_CONTRAREF, OBSERVACION_CONTRAREF, 
      CD_ATENCION )
    VALUES ( 
      v_PLANTILLA, v_DOCUMENTOPACIENTE, v_CODTDOC, 
      v_NUMLABO, v_FECHA_REGISTRA, v_HORA_REGISTRA, 
      v_NOMBRERESPONSABLE, v_CODPARENTESCO, v_DIRECCIONRESPONSABLE, 
      v_TELEFONORESPONSABLE, v_SERVICIO, v_OBSERVACION, 
      v_ATENCION );


    SELECT CD_CONTRAREFERENCIA 
    INTO v_CDCONTRA 
    FROM CONTRAREFERENCIA
    WHERE CD_CONTRAREFERENCIA = (SELECT MAX(CD_CONTRAREFERENCIA) FROM CONTRAREFERENCIA);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;