CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_HISTORIACLINICA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NoLABO IN NUMBER,
  v_NoPLANTILLA IN NUMBER,
  v_MED_ASIG IN VARCHAR2,
  v_MED_DILI IN VARCHAR2,
  v_ESTADO IN NUMBER,
  v_FECHORAINICIO IN DATE,
  v_TIPO_PROF IN NUMBER DEFAULT 0 ,
  v_CD_CODI_CIR_HICL IN NUMBER DEFAULT 0 ,
  v_NoHICL OUT NUMBER
)
AS

BEGIN

    INSERT INTO HISTORIACLINICA( 
      NU_NUME_LABO_HICL, NU_NUME_PLHI_HICL, 
      FE_FECH_HICL, CD_MED_ASIG_HICL, 
      CD_MED_REAL_HICL, NU_ESGU_HICL, 
      FE_FECINI_HICL, NU_TIPO_MEDI_HICL, 
      CD_CODI_CIR_HICL )
    VALUES ( 
      v_NoLABO, v_NoPLANTILLA, 
      SYSDATE, v_MED_ASIG, 
      v_MED_DILI, v_ESTADO, 
      v_FECHORAINICIO, v_TIPO_PROF, 
      v_CD_CODI_CIR_HICL );

     SELECT NU_NUME_HICL 
        INTO v_NoHICL 
        FROM HISTORIACLINICA
        WHERE NU_NUME_HICL = (SELECT MAX(NU_NUME_HICL) FROM VARIABLE_INDICADOR);
   

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;