CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_PARTO_FECHA_MAYOR
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_FECHA_INSERTAR IN DATE,
	V_NU_NUME_HICL_PAR IN VARCHAR2,
	V_NU_LABO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
 )	
AS

BEGIN
	OPEN CV_1 FOR
		SELECT COUNT(NU_NUME_HIS_PAR) AS NUM_FECHAS_MAYORES
		FROM HIST_PARTO
		WHERE NU_NUME_HICL_PAR = V_NU_NUME_HICL_PAR
		AND NU_LABO = V_NU_LABO
		AND  HORA_PAR_MED > V_FECHA_INSERTAR;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
	