CREATE OR REPLACE PROCEDURE H3I_SP_CONS_VALGRAFCyD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NUMHIST IN VARCHAR2,
  v_Plantilla IN NUMBER,
  v_ORDEN IN NUMBER,
  iv_HICLREF IN NUMBER DEFAULT 0 ,
  cv_1 OUT SYS_REFCURSOR
)
AS
   v_HICLREF NUMBER := iv_HICLREF;
   v_TIPO NUMBER(10,0);

BEGIN

   IF v_HICLREF = 0 THEN
    v_HICLREF := NULL ;
   END IF;
   SELECT RGP.NU_TIPOGR_RGR 

     INTO v_TIPO
     FROM HIST_GRACyD HG
            INNER JOIN HISTORIACLINICA HC   ON HG.NU_NUME_HICL_HIGR = HC.NU_NUME_HICL
            INNER JOIN R_GRACyD_RPC RGP   ON ( RGP.NU_NUME_PLHI_RPC_RGR = HC.NU_NUME_PLHI_HICL
            AND NU_INDI_RPC_RGR = NU_INDI_RPC_HIGR )
    WHERE  HC.NU_NUME_PLHI_HICL = v_Plantilla
             AND HG.NU_INDI_RPC_HIGR = v_ORDEN;
   IF v_TIPO IS NULL THEN
    
   BEGIN
      SELECT NU_TIPOGR_RGR 

        INTO v_TIPO
        FROM R_PLAN_CONC RPC
               INNER JOIN R_GRACyD_RPC RGD   ON RPC.NU_NUME_PLHI_RPC = RGD.NU_NUME_PLHI_RPC_RGR
               AND NU_INDI_RPC_RGR = NU_INDI_RPC
       WHERE  RPC.NU_NUME_PLHI_RPC = v_PLANTILLA
                AND NU_INDI_RPC_RGR = v_ORDEN;
   
   END;
   END IF;
   OPEN  cv_1 FOR
      SELECT NU_NUME_HICL_HIGR ,
             FE_FECH_HICL ,
             NU_INDI_RPC_HIGR ,
             NU_XVALOR_HIGR ,
             NU_YVALOR_HIGR 
        FROM HIST_GRACyD HG
               INNER JOIN HISTORIACLINICA HC   ON HG.NU_NUME_HICL_HIGR = HC.NU_NUME_HICL
               INNER JOIN R_GRACyD_RPC RGP   ON ( RGP.NU_NUME_PLHI_RPC_RGR = HC.NU_NUME_PLHI_HICL
               AND NU_INDI_RPC_RGR = NU_INDI_RPC_HIGR
               AND RGP.NU_TIPOGR_RGR = v_TIPO )
               INNER JOIN LABORATORIO L   ON L.NU_NUME_LABO = HC.NU_NUME_LABO_HICL
               INNER JOIN MOVI_CARGOS M   ON M.NU_NUME_MOVI = L.NU_NUME_MOVI_LABO
       WHERE  NU_HIST_PAC_MOVI = v_NUMHIST
                AND NU_NUME_HICL <= NVL(v_HICLREF, NU_NUME_HICL)
        ORDER BY NU_NUME_HICL_HIGR ASC ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;