CREATE OR REPLACE PROCEDURE H3i_SP_OBTENER_GRAFICOS_DISPON -- PROCEDIMIENTO ENCARGADO DE OBTENER LOS GRAFICOS DISPONIBLES PARA CONVENCIONES PARA HISTORIA CLINICA 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_TIPO_COHI IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT CD_CODI_COHI ,
             NU_NUME_COHI 
        FROM CONCEPTO_HIST 
       WHERE  NU_TIPO_COHI = v_NU_TIPO_COHI ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;