CREATE OR REPLACE PROCEDURE H3i_GUARDAR_DX_CONTRAREF
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  v_DXPRINCIPAL IN VARCHAR2,
  v_DXRELA IN VARCHAR2
)
AS

BEGIN

   INSERT INTO CONTRAREF_DIAGNOSTICO
     ( CD_CONTRAREFERENCIA, DX_PRINCIPAL, DX_RELA )
     VALUES ( v_CODIGO, v_DXPRINCIPAL, v_DXRELA );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;