CREATE OR REPLACE PROCEDURE H3i_GUARDAR_AGUDEZA_CONTRAREF
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGOCONTRA IN NUMBER,
  v_OPTOTIPO IN VARCHAR2,
  v_L_SN_OD_VAL IN VARCHAR2,
  v_L_SN_OI_VAL IN VARCHAR2,
  v_L_SN_AMBOS_VAL IN VARCHAR2,
  v_L_CN_OD_VAL IN VARCHAR2,
  v_L_CN_OI_VAL IN VARCHAR2,
  v_L_CN_AMBOS_VAL IN VARCHAR2,
  v_C_SN_OD_VAL IN VARCHAR2,
  v_C_SN_OI_VAL IN VARCHAR2,
  v_C_SN_AMBOS_VAL IN VARCHAR2,
  v_C_CN_OD_VAL IN VARCHAR2,
  v_C_CN_OI_VAL IN VARCHAR2,
  v_C_CN_AMBOS_VAL IN VARCHAR2
)
AS

BEGIN

   INSERT INTO CONTRAREF_AGUDEZA
     ( CD_CONTRAREFERENCIA, OPTOTIPO, L_SN_OD_VAL, L_SN_OI_VAL, L_SN_AMBOS_VAL, L_CN_OD_VAL, L_CN_OI_VAL, L_CN_AMBOS_VAL, C_SN_OD_VAL, C_SN_OI_VAL, C_SN_AMBOS_VAL, C_CN_OD_VAL, C_CN_OI_VAL, C_CN_AMBOS_VAL )
     VALUES ( v_CODIGOCONTRA, v_OPTOTIPO, v_L_SN_OD_VAL, v_L_SN_OI_VAL, v_L_SN_AMBOS_VAL, v_L_CN_OD_VAL, v_L_CN_OI_VAL, v_L_CN_AMBOS_VAL, v_C_SN_OD_VAL, v_C_SN_OI_VAL, v_C_SN_AMBOS_VAL, v_C_CN_OD_VAL, v_C_CN_OI_VAL, v_C_CN_AMBOS_VAL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;