CREATE OR REPLACE PROCEDURE H3i_SP_HISTICDAS_INS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_HICL IN NUMBER,
  v_INDI IN NUMBER,
  v_DIENTE IN VARCHAR2,
  v_DIENTEPRESENTE IN NUMBER,
  v_CODIGOAUSENTE IN VARCHAR2 DEFAULT NULL ,
  v_SUPERFICIES IN VARCHAR2 DEFAULT NULL 
)
AS

BEGIN

   	INSERT INTO HIST_ICDAS_SIMPLIFICADO( 
   		NU_NUME_HICL_HIIC, NU_NUME_INDI_HIIC, 
   		TX_DIENTE_HIIC, NU_DIENTEPRESENTE_HIIC, 
   		TX_CODIGOAUSENTE_HIIC, TX_SUPERFICIES_HIIC )
     VALUES ( v_HICL, v_INDI, 
     	v_DIENTE, v_DIENTEPRESENTE, 
     	v_CODIGOAUSENTE, v_SUPERFICIES );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;