CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_CERTIF_APTIVISUAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NU_NUME_HICL_HIVI IN NUMBER,
	V_NU_NUME_HEVO_HIVI  IN NUMBER,
	V_TX_DX_HIVI  IN VARCHAR2,
	V_TX_DXRELACION_HIVI  IN VARCHAR2,
	V_TX_BRIOMIOD_HIVI  IN VARCHAR2,
	V_TX_BRIOMIOI_HIVI  IN VARCHAR2,
	V_TX_OFTALMIOD_HIVI  IN VARCHAR2,
	V_TX_OFTALMIOI_HIVI  IN VARCHAR2,
	V_NU_AUTO_HIVI OUT NUMBER,
	V_TX_OB_HIVI  IN VARCHAR2,
	V_TX_OPTO_HIVI IN VARCHAR2,
	--Modificación
	V_txtLejosAVOd  IN VARCHAR2,	  
	V_txtLejosAVOi  IN VARCHAR2,
	V_txtLejosAVAo  IN VARCHAR2,
	V_txtLejosSCOd  IN VARCHAR2,
	V_txtLejosSCOi  IN VARCHAR2,
	V_txtLejosSCAo  IN VARCHAR2,
	V_txtCercaAVOd  IN VARCHAR2,
	V_txtCercaAVOi  IN VARCHAR2,
	V_txtCercaAVAo  IN VARCHAR2,
	V_txtCercaSCOd  IN VARCHAR2,
	V_txtCercaSCOi  IN VARCHAR2,
	V_txtCercaSCAO  IN VARCHAR2,
	V_TX_VISION_CERCANA  IN VARCHAR2,
	V_TX_OFTALMIOI_HIVI_1 IN  VARCHAR2,
	V_TX_PPC IN  VARCHAR2,
	V_rbtCorrecionOptica  IN NUMBER 
) 						
AS

BEGIN
	INSERT INTO HIST_APVI( 
		NU_NUME_HICL_HIVI, NU_NUME_HEVO_HIVI,  
		TX_DX_HIVI, TX_DXRELACION_HIVI, 
		TX_BRIOMIOD_HIVI, TX_BRIOMIOI_HIVI, 
		TX_OFTALMIOD_HIVI, TX_OFTALMIOI_HIVI, 
		TX_OB_HIVI,TX_OPTO_HIVI,
		txtLejosAVOd,txtLejosAVOi,
		txtLejosAVAo,txtLejosSCOd,
		txtLejosSCOi,txtLejosSCAo,
		txtCercaAVOd,txtCercaAVOi,
		txtCercaAVAo,txtCercaSCOd,
		txtCercaSCOi,txtCercaSCAO,
		TX_VISION_CERCANA,TX_OFTALMIOI_HIVI_1,
		TX_PPC,rbtCorrecionOptica)
	VALUES (
		V_NU_NUME_HICL_HIVI, V_NU_NUME_HEVO_HIVI,
		V_TX_DX_HIVI, V_TX_DXRELACION_HIVI, V_TX_BRIOMIOD_HIVI,
		V_TX_BRIOMIOI_HIVI, V_TX_OFTALMIOD_HIVI, 
		V_TX_OFTALMIOI_HIVI, V_TX_OB_HIVI,
		V_TX_OPTO_HIVI,	V_txtLejosAVOd,
		V_txtLejosAVOi,	V_txtLejosAVAo,
		V_txtLejosSCOd,	V_txtLejosSCOi,
		V_txtLejosSCAo,	V_txtCercaAVOd,
		V_txtCercaAVOi,	V_txtCercaAVAo,
		V_txtCercaSCOd,	V_txtCercaSCOi,
		V_txtCercaSCAO,	V_TX_VISION_CERCANA,
		V_TX_OFTALMIOI_HIVI_1, V_TX_PPC,V_rbtCorrecionOptica);

	SELECT NU_AUTO_HIVI 
	INTO V_NU_AUTO_HIVI 
	FROM HIST_APVI
	WHERE NU_AUTO_HIVI = (SELECT MAX(NU_AUTO_HIVI) FROM HIST_APVI);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;