CREATE OR REPLACE PROCEDURE H3i_SP_RELACIONES_PLANTILLA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_IDPLANTILLA IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT TO_NUMBER(NU_NUME_PLHI_B_REPA) IDPLANTILLA_1  ,
             TO_NUMBER(RP.NU_NUME_COHI_B_REPA) IDCONCEPTO_1  ,
             TO_NUMBER(RP.NU_INDI_RPC_B_REPA) NoORDENCONCEPTO_1  ,
             TO_NUMBER(NU_NUME_PLHI_A_REPA) IDPLANTILLA  ,
             TO_NUMBER(RP.NU_NUME_COHI_A_REPA) IDCONCEPTO  ,
             TO_NUMBER(RP.NU_INDI_RPC_A_REPA) NoORDENCONCEPTO  
        FROM RELACION_PLANTILLA RP
       WHERE  RP.NU_NUME_PLHI_B_REPA = v_IDPLANTILLA
      UNION ALL 
      SELECT TO_NUMBER(NU_NUME_PLHI_A_REPA) IDPLANTILLA_1  ,
             TO_NUMBER(RP.NU_NUME_COHI_A_REPA) IDCONCEPTO_1  ,
             TO_NUMBER(RP.NU_INDI_RPC_A_REPA) NoORDENCONCEPTO_1  ,
             TO_NUMBER(NU_NUME_PLHI_B_REPA) IDPLANTILLA  ,
             TO_NUMBER(RP.NU_NUME_COHI_B_REPA) IDCONCEPTO  ,
             TO_NUMBER(RP.NU_INDI_RPC_B_REPA) NoORDENCONCEPTO  
        FROM RELACION_PLANTILLA RP
       WHERE  RP.NU_NUME_PLHI_A_REPA = v_IDPLANTILLA ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;