CREATE OR REPLACE PROCEDURE H3i_SP_HC_PYP_GUARDA_ACTI_PAC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NUM_HISTCLI IN NUMBER,
  v_PACIENTE IN VARCHAR2,
  v_CONCEPTO IN NUMBER,
  v_ACTIVIDAD IN VARCHAR2,
  v_VAL_DILIG IN VARCHAR2
)
AS

BEGIN

   INSERT INTO PYP_DETECT_PAC_HIST
     ( CD_CODI_ACTI_PYPPAC, NU_NUME_COHI_PYPPAC, NU_NUME_HCLI_PYPPAC, NUM_HIST_PAC_PYPPAC, VALOR_PYPPAC )
     VALUES ( v_ACTIVIDAD, v_CONCEPTO, v_NUM_HISTCLI, v_PACIENTE, v_VAL_DILIG );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;