CREATE OR REPLACE PROCEDURE H3I_SP_cONSuLTaTENfTO_ASOC_ENF
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_PLANTILLA IN NUMBER,
	V_EVENTO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
					
AS
BEGIN
	OPEN CV_1 FOR
		SELECT	NVL(MAX(H.NU_NUME_HICL), 0) ULTIMAHC
		FROM	EVENTO_ENFERMERIA E 
		INNER JOIN R_HIST_HIST R 
			ON E.NU_NUME_HICL_EVEN = R.NU_NUME_HICL_PPAL_RHH
		INNER JOIN HISTORIACLINICA H 
			ON H.NU_NUME_HICL = R.NU_NUME_HICL_SECU_RHH 
			AND H.NU_NUME_PLHI_HICL = V_PLANTILLA
		WHERE	E.NU_AUTO_EVEN = V_EVENTO;
END;