CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_VALOR_FAVA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_IDPACIENTE IN VARCHAR2,
  v_IDPLANTILLA IN VARCHAR2,
  v_NUMCONCEPTO IN VARCHAR2,
  v_ORDENCPTO IN NUMBER,
  v_NUMHCLI IN VARCHAR2,
  v_NUMLABO IN VARCHAR2,
  v_FECHA IN DATE,
  v_VALOR IN NUMBER,
  v_IDMEDICO IN VARCHAR2,
  v_PROFESIONAL IN NUMBER
)
AS

BEGIN

    INSERT INTO FACTOR_RIESGO_HIST( 
        CD_COD_PAC_FACTRIESG, CD_COD_PLANT_FACTRIESG, 
        NU_NUM_CPTO_FACTRIESG, NU_ORD_CPTO_FACTRIESG, 
        NU_NUMHC_FACTRIESG, NU_NUMLABO_FACTRIESG, 
        FE_FECHA_REG_FARI, VALOR_FACTRIESG, 
        CD_CODMEDI_REAL_FARI, CD_COD_PROF_FARI)
    VALUES( 
      v_IDPACIENTE, v_IDPLANTILLA, 
      v_NUMCONCEPTO, v_ORDENCPTO, 
      v_NUMHCLI, v_NUMLABO, 
      TO_DATE(v_FECHA,'dd/mm/yyyy'), 
      v_VALOR, v_IDMEDICO, 
      v_PROFESIONAL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;