CREATE OR REPLACE PROCEDURE H3i_SP_EVENTENFERMERIA_PAC_CON /*PROCEDIMIENTO PARA CONSULTAR SI UN PACIENTE TIENE UN EVENTO DE ENFERMERÍA ABIERTO*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NoHISTPAC IN VARCHAR2,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT NU_AUTO_EVEN ,
             NU_NUME_HICL_EVEN 
        FROM EVENTO_ENFERMERIA 
       WHERE  NU_HIST_PAC_EVEN = v_NoHISTPAC
                AND NU_ESTADO_EVEN = 1 ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;