CREATE OR REPLACE PROCEDURE H3i_SP_GDA_RELA_PCNT_HST_HIMS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_HISTORIA_PAC VARCHAR2,
	V_HISTORIA_CLINICA NUMBER
)
	
AS
BEGIN
	INSERT INTO R_PAC_HICL_MIHIMS(
		NU_HIST_PAC_RPACHCL,
        NU_NUME_HICL_RPACHICL,
        FE_FECH_RPACHICL)
    VALUES
        (V_HISTORIA_PAC, V_HISTORIA_CLINICA,SYSDATE);
        
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

