CREATE OR REPLACE PROCEDURE H3i_SP_HC_LISTARFORMATSxDB_EXT
(
	V_NomBaseDatos IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
	
AS
	V_SCRIPT VARCHAR2(2000);
BEGIN
	--SELECT PART
	V_SCRIPT := 'SELECT	DISTINCT CD_NOMB_FIN, 
					CD_CODI_FIN, 
					NU_NUME_PLHI, 
					NU_SERV_PLHI,
					NU_AUTO_ENPL_PLHI,
					NU_PERMADJARCHIVO_PLHI,
					ES_PSICOACTIVO,
					ES_CONTRAREFERENCIA';

	--FROM PART
	V_SCRIPT := V_SCRIPT ||'FROM '||V_NomBaseDatos||'.PLANTILLA_HIST,'
								  ||V_NomBaseDatos||'.R_PLANTILLA_HIST,'
								  ||V_NomBaseDatos||'.FINALIDAD_HIST,'
								  ||V_NomBaseDatos||'.R_ESPE_PLHI';

	--WHERE PART
	V_SCRIPT := V_SCRIPT || 'WHERE	NU_NUME_PLHI = NU_NUME_PLHI_R  
							AND	NU_FINA_PLHI = CD_CODI_FIN  
							AND	NU_NUME_PLHI = NU_PLHI
							AND	(NU_PRCO_PLHI = C OR NU_PRCO_PLHI = P)
							AND	NU_ESTA_PLHI = 1 
							AND	CD_NOMB_FIN != NOTA DE EVOLUCION
							AND	NU_NUME_PLHI NOT IN ( SELECT TOP(1) NU_NUME_PLHI_CLAP FROM CONFIGURA_CLAP) -- CLAP PRINCIPAL
							AND	NU_NUME_PLHI NOT IN ( SELECT TOP(1) NU_INGRE_PLHI_CLAP FROM CONFIGURA_CLAP)-- CLAP INGRESO
							AND	NU_NUME_PLHI NOT IN  ( SELECT TOP(1) NU_SEGUI_PLHI_CLAP FROM CONFIGURA_CLAP) -- CLAP EGRESO 
							ORDER  BY NU_SERV_PLHI DESC ,CD_NOMB_FIN';

	OPEN CV_1 FOR V_SCRIPT;
END;
	
					

	
	
	
