CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_O_ACTUA_VACUNA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_NUM_DOSIS IN INT,
    V_NUM_HIST_PACIENTE IN VARCHAR2,
    V_COD_VACUNA IN VARCHAR2,
    V_FECHA IN DATE,
    V_FECHA_REGISTRO IN DATE,
    V_NUM_COME_VACUNA IN INT,
    V_TIPO_VACUNA IN VARCHAR2,
    V_NU_NUME_MOVI_VACU IN NUMBER,
    V_ESTADO_VACUNA IN VARCHAR2,
    V_NU_APL_INSTI IN NUMBER,
    V_TX_NO_LOTE IN VARCHAR2,
    V_TX_LAB IN VARCHAR2,
    V_FE_VENC IN DATE,
    V_TX_IPS IN VARCHAR2,
    V_TX_OBS IN VARCHAR2,
    V_TX_SITIO IN VARCHAR2,
    V_TX_TIPO IN VARCHAR2,
    V_TX_VIA IN VARCHAR2,
	V_TX_PAI IN NUMBER,
	V_TX_ESQUEMA IN NUMBER,
	V_TX_CONDICION IN NUMBER

 )
 AS
 	V_ID INT;
 	V_COMPARACION VARCHAR2(20) := '';
 BEGIN
 	SELECT NU_AUTO_VACU  
 	INTO V_ID
    FROM VACUNACION 
    WHERE NU_HIST_PAC_VACU = V_NUM_HIST_PACIENTE 
    AND CD_CODI_SERV_VACU = V_COD_VACUNA
    AND TX_TIPO_VACU = V_TIPO_VACUNA
    AND NU_DOSIS_VACU = V_NUM_DOSIS 
	AND ROWNUM <= 1;


	IF(NVL(V_COMPARACION,'###') <> NVL(TO_CHAR(V_ID),'###')) THEN
		BEGIN
			INSERT INTO VACUNACION (
				NU_HIST_PAC_VACU, CD_CODI_SERV_VACU, 
		        NU_DOSIS_VACU, FE_FECH_VACU, FE_REGI_VACU, 
		        NU_NUME_CONE_VACU, TX_TIPO_VACU, 
		        NU_NUME_MOVI_VACU, TX_ESTA_VACU,
		        NU_APL_INSTI, TX_NO_LOTE,
		        TX_LAB, FE_VENC,
		        TX_IPS, TX_OBS,
		        TX_SITIO, TX_TIPO,
		        TX_VIA, TX_PAI,
		        TX_ESQUEMA, TX_CONDICION)
			VALUES (
				V_NUM_HIST_PACIENTE, V_COD_VACUNA, 
				V_NUM_DOSIS, V_FECHA,
	       		V_FECHA_REGISTRO, V_NUM_COME_VACUNA, 
	       		V_TIPO_VACUNA, V_NU_NUME_MOVI_VACU, 
	       		V_ESTADO_VACUNA, V_NU_APL_INSTI,
		        V_TX_NO_LOTE, V_TX_LAB,
		        V_FE_VENC, V_TX_IPS,
		        V_TX_OBS, V_TX_SITIO,
		        V_TX_TIPO, V_TX_VIA,
		        V_TX_PAI, V_TX_ESQUEMA,
		        V_TX_CONDICION);
			END;
	ELSE
		BEGIN
			UPDATE VACUNACION 
		    SET NU_HIST_PAC_VACU = V_NUM_HIST_PACIENTE,
			    CD_CODI_SERV_VACU = V_COD_VACUNA, 
			    NU_DOSIS_VACU = V_NUM_DOSIS, 
			    FE_FECH_VACU = V_FECHA, 
			    FE_REGI_VACU = V_FECHA_REGISTRO, 
			    NU_NUME_CONE_VACU = V_NUM_COME_VACUNA,
			    TX_TIPO_VACU = V_TIPO_VACUNA, 
			    NU_NUME_MOVI_VACU = V_NU_NUME_MOVI_VACU,
			    TX_ESTA_VACU = V_ESTADO_VACUNA,
			    NU_APL_INSTI = V_NU_APL_INSTI,
			    TX_NO_LOTE = V_TX_NO_LOTE,
			    TX_LAB = V_TX_LAB,
			    FE_VENC = V_FE_VENC,
			    TX_IPS = V_TX_IPS,
			    TX_OBS = V_TX_OBS,
			    TX_SITIO=V_TX_SITIO,
			    TX_TIPO=V_TX_TIPO,
			    TX_VIA=V_TX_VIA,
			    TX_PAI = V_TX_PAI,
			    TX_ESQUEMA = V_TX_ESQUEMA,
			    TX_CONDICION = V_TX_CONDICION
		    WHERE NU_AUTO_VACU = V_ID;
		END;
	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);

END H3i_SP_GUARDAR_O_ACTUA_VACUNA; 