CREATE OR REPLACE PROCEDURE H3i_SP_MODI_TIPO_NUM_DOC_PCNTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NUM_HISTORIA_PACIENTE VARCHAR2,
	V_NUM_DOC_ACT VARCHAR2,
	V_NUM_TIP_DOC_ACT NUMBER
)
AS
BEGIN

	UPDATE PACIENTES 
	SET NU_DOCU_PAC = V_NUM_DOC_ACT,
		NU_TIPD_PAC = V_NUM_TIP_DOC_ACT 	
	WHERE NU_HIST_PAC = V_NUM_HISTORIA_PACIENTE;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);

END H3i_SP_MODI_TIPO_NUM_DOC_PCNTE;