CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_AFILIACION_MASIVO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_HISTORIA IN VARCHAR2,
    V_NIT IN VARCHAR2,
    V_REGIMEN IN VARCHAR2,
    V_ORDEN IN NUMBER,
    V_CARNE IN VARCHAR2
)
AS
	V_CANTIDAD_DATOS NUMBER;
BEGIN

	SELECT COUNT(RPE.NU_HIST_PAC_RPE)
	INTO V_CANTIDAD_DATOS
	FROM R_PAC_EPS RPE 
	WHERE NU_HIST_PAC_RPE = V_HISTORIA 
	AND RPE.CD_NIT_EPS_RPE = V_NIT 
	AND CD_CODI_REG_RPE=V_REGIMEN 
	AND NU_AFIL_RPE=V_ORDEN;

	IF(V_CANTIDAD_DATOS = 0) THEN

		BEGIN
			UPDATE R_PAC_EPS
		   	SET NU_ESTA_RPE = 0,
		     	NU_ESTA_REP = 1,
		     	CD_CARN_RPE = V_CARNE  
		   	WHERE NU_HIST_PAC_RPE = V_HISTORIA 
		   	AND  CD_NIT_EPS_RPE = V_NIT 
		   	AND  CD_CODI_REG_RPE = V_REGIMEN 
		   	AND  NU_AFIL_RPE = V_ORDEN;

		   	INSERT INTO R_PAC_EPS (
		   		NU_HIST_PAC_RPE, CD_NIT_EPS_RPE, 
		   		CD_CODI_REG_RPE, NU_AFIL_RPE, 
		   		CD_CARN_RPE, NU_ESTA_RPE, 
		   		NU_ESTA_REP)
	      	VALUES (
	      		V_HISTORIA, V_NIT, 
	      		V_REGIMEN, V_ORDEN, 
	      		V_CARNE, 1, 0);
	    END;

	ELSE

		BEGIN
			UPDATE R_PAC_EPS
		    SET NU_ESTA_RPE = 1,
		     	NU_ESTA_REP = 0,
		    	CD_CARN_RPE = V_CARNE  
		    WHERE NU_HIST_PAC_RPE = V_HISTORIA 
		    AND  CD_NIT_EPS_RPE = V_NIT 
		    AND  CD_CODI_REG_RPE = V_REGIMEN 
		    AND  NU_AFIL_RPE = V_ORDEN;
		END;

	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUARD_AFILIACION_MASIVO;