CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_PACIENTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_TIPD_PAC IN NUMBER,
  v_NU_DOCU_PAC IN VARCHAR2,
  v_DE_PRAP_PAC IN VARCHAR2,
  v_DE_SGAP_PAC IN VARCHAR2,
  v_NO_NOMB_PAC IN VARCHAR2,
  v_NO_SGNO_PAC IN VARCHAR2,
  v_FE_NACI_PAC IN DATE,
  v_NU_NUME_REG_PAC IN NUMBER,
  v_NU_SEXO_PAC IN NUMBER,
  v_CD_CODI_LUAT_PAC IN VARCHAR2,
  v_CD_CODI_DPTO_PAC IN VARCHAR2,
  v_CD_CODI_MUNI_PAC IN VARCHAR2,
  v_DE_DIRE_PAC IN VARCHAR2,
  v_DE_TELE_PAC IN VARCHAR2,
  v_NU_ESCI_PAC IN NUMBER,
  v_FE_HIST_PAC IN DATE,
  v_CD_CODI_CAM_PAC IN VARCHAR2,
  v_NU_ESTA_PAC IN NUMBER,
  v_CD_CODI_ZORE_PAC IN VARCHAR2,
  v_DE_EMAIL_PAC IN VARCHAR2,
  v_CD_CODI_OCUP_PAC IN VARCHAR2,
  v_NU_CONS_HIST_PAC IN VARCHAR2,
  v_NU_TIPO_PAC IN NUMBER,
  v_CD_CODI_RELI_PAC IN VARCHAR2,
  v_CD_CODI_BAR_PAC IN VARCHAR2,
  v_NU_GEST_PAC IN NUMBER,
  v_CD_CODI_DPTO_TRAB_PAC IN VARCHAR2,
  v_CD_CODI_MUNI_TRAB_PAC IN VARCHAR2,
  v_CD_CODI_DPTO_NACI_PAC IN VARCHAR2,
  v_CD_CODI_MUNI_NACI_PAC IN VARCHAR2,
  v_TX_TELTRAB_PAC IN VARCHAR2,
  v_TX_DIRTRAB_PAC IN VARCHAR2,
  v_TX_NOMBRESP_PAC IN VARCHAR2,
  v_CD_CODI_PARE_PAC IN VARCHAR2,
  v_TX_DIRRESP_PAC IN VARCHAR2,
  v_TX_TELRESP_PAC IN VARCHAR2,
  v_ME_INFOAD_PAC IN VARCHAR2,
  v_NU_FALLE_PAC IN NUMBER,
  v_NU_HIST_PAC IN VARCHAR2,
  v_CD_CODI_PAIS_PAC IN VARCHAR2,
  v_CD_CODI_PAIS_TRAB_PAC IN VARCHAR2,
  v_CD_CODI_PAIS_NACI_PAC IN VARCHAR2,
  v_CD_CODI_ESCO_PAC IN VARCHAR2,
  v_NU_ACTI_EPS_PAC IN NUMBER,
  v_NU_TERC_PAC IN NUMBER,
  v_NU_DATOS_EXT_PAC IN NUMBER,
  v_DE_CELU_PAC IN VARCHAR2,
  v_CODIGOETNIA IN VARCHAR2 DEFAULT NULL ,
  v_DISCAPACIDAD IN VARCHAR2 DEFAULT NULL ,
  v_NU_AUTO_TIRH IN NUMBER,
  v_NU_ISDESPLAZADO_PAC IN NUMBER,
  v_CD_CODI_LOC_PAC IN VARCHAR2 DEFAULT NULL ,
  v_DE_OTRO_TELE_PAC IN VARCHAR2 DEFAULT NULL ,
  v_TX_CODIGO_TICO_PAC IN VARCHAR2 DEFAULT NULL ,
  v_NUEVO OUT NUMBER
)
AS
   v_temp NUMBER(1, 0) := 0;

BEGIN

   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE ( SELECT COUNT(NU_HIST_PAC)  
               FROM PACIENTES 
                WHERE  NU_HIST_PAC = v_NU_HIST_PAC ) = 0;
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;
      
  IF v_temp = 1 THEN
    
    -- SE TRATA DE UN PACIENTE NUEVO  
      BEGIN
          INSERT INTO PACIENTES(
            NU_TIPD_PAC, NU_DOCU_PAC, 
            DE_PRAP_PAC, DE_SGAP_PAC, 
            NO_NOMB_PAC, NO_SGNO_PAC, 
            FE_NACI_PAC, NU_NUME_REG_PAC, 
            NU_SEXO_PAC, CD_CODI_LUAT_PAC, 
            CD_CODI_DPTO_PAC, CD_CODI_MUNI_PAC, 
            DE_DIRE_PAC, DE_TELE_PAC, 
            NU_ESCI_PAC, FE_HIST_PAC, 
            CD_CODI_CAM_PAC, NU_ESTA_PAC, 
            CD_CODI_ZORE_PAC, DE_EMAIL_PAC, 
            CD_CODI_OCUP_PAC, NU_CONS_HIST_PAC, 
            NU_TIPO_PAC, CD_CODI_RELI_PAC, 
            CD_CODI_BAR_PAC, NU_GEST_PAC, 
            CD_CODI_DPTO_TRAB_PAC, CD_CODI_MUNI_TRAB_PAC, 
            CD_CODI_DPTO_NACI_PAC, CD_CODI_MUNI_NACI_PAC, 
            TX_TELTRAB_PAC, TX_DIRTRAB_PAC, 
            TX_NOMBRESP_PAC, CD_CODI_PARE_PAC, 
            TX_DIRRESP_PAC, TX_TELRESP_PAC, 
            ME_INFOAD_PAC, NU_FALLE_PAC, 
            NU_HIST_PAC, CD_CODI_PAIS_PAC, 
            CD_CODI_PAIS_TRAB_PAC, CD_CODI_PAIS_NACI_PAC, 
            CD_CODI_ESCO_PAC, NU_ACTI_EPS_PAC, 
            NU_TERC_PAC, NU_DATOS_EXT_PAC, 
            DE_CELU_PAC, TX_CODIGO_ETNI_PACI, 
            TX_DISCAPACIDAD_PACI, NU_AUTO_TIRH, 
            CD_CODI_LOC_PAC, DE_OTRO_TELE_PAC, 
            NU_ISDESPLAZADO_PAC, TX_CODIGO_TICO_PAC)
          VALUES ( 
            v_NU_TIPD_PAC, v_NU_DOCU_PAC, 
            v_DE_PRAP_PAC, v_DE_SGAP_PAC, 
            v_NO_NOMB_PAC, v_NO_SGNO_PAC, 
            v_FE_NACI_PAC, v_NU_NUME_REG_PAC, 
            v_NU_SEXO_PAC, v_CD_CODI_LUAT_PAC, 
            v_CD_CODI_DPTO_PAC, v_CD_CODI_MUNI_PAC, 
            v_DE_DIRE_PAC, v_DE_TELE_PAC, 
            v_NU_ESCI_PAC, v_FE_HIST_PAC, 
            v_CD_CODI_CAM_PAC, v_NU_ESTA_PAC, 
            v_CD_CODI_ZORE_PAC, v_DE_EMAIL_PAC, 
            v_CD_CODI_OCUP_PAC, v_NU_CONS_HIST_PAC, 
            v_NU_TIPO_PAC, v_CD_CODI_RELI_PAC, 
            v_CD_CODI_BAR_PAC, v_NU_GEST_PAC, 
            v_CD_CODI_DPTO_TRAB_PAC, v_CD_CODI_MUNI_TRAB_PAC, 
            v_CD_CODI_DPTO_NACI_PAC, v_CD_CODI_MUNI_NACI_PAC, 
            v_TX_TELTRAB_PAC, v_TX_DIRTRAB_PAC, 
            v_TX_NOMBRESP_PAC, v_CD_CODI_PARE_PAC, 
            v_TX_DIRRESP_PAC, v_TX_TELRESP_PAC, 
            v_ME_INFOAD_PAC, v_NU_FALLE_PAC, 
            v_NU_HIST_PAC, v_CD_CODI_PAIS_PAC, 
            v_CD_CODI_PAIS_TRAB_PAC, v_CD_CODI_PAIS_NACI_PAC, 
            v_CD_CODI_ESCO_PAC, v_NU_ACTI_EPS_PAC, 
            v_NU_TERC_PAC, v_NU_DATOS_EXT_PAC, 
            v_DE_CELU_PAC, v_CODIGOETNIA, 
            v_DISCAPACIDAD, v_NU_AUTO_TIRH, 
            v_CD_CODI_LOC_PAC, v_DE_OTRO_TELE_PAC, 
            v_NU_ISDESPLAZADO_PAC, v_TX_CODIGO_TICO_PAC);

      v_NUEVO := 1 ;
   
      END;
  ELSE
   
      BEGIN
          UPDATE PACIENTES
          SET NU_TIPD_PAC = v_NU_TIPD_PAC,
              NU_DOCU_PAC = v_NU_DOCU_PAC,
              DE_PRAP_PAC = v_DE_PRAP_PAC,
              DE_SGAP_PAC = v_DE_SGAP_PAC,
              NO_NOMB_PAC = v_NO_NOMB_PAC,
              NO_SGNO_PAC = v_NO_SGNO_PAC,
              FE_NACI_PAC = v_FE_NACI_PAC,
              NU_NUME_REG_PAC = v_NU_NUME_REG_PAC,
              NU_SEXO_PAC = v_NU_SEXO_PAC,
              CD_CODI_LUAT_PAC = v_CD_CODI_LUAT_PAC,
              CD_CODI_DPTO_PAC = v_CD_CODI_DPTO_PAC,
              CD_CODI_MUNI_PAC = v_CD_CODI_MUNI_PAC,
              DE_DIRE_PAC = v_DE_DIRE_PAC,
              DE_TELE_PAC = v_DE_TELE_PAC,
              NU_ESCI_PAC = v_NU_ESCI_PAC,
              FE_HIST_PAC = v_FE_HIST_PAC,
              CD_CODI_CAM_PAC = v_CD_CODI_CAM_PAC,
              NU_ESTA_PAC = v_NU_ESTA_PAC,
              CD_CODI_ZORE_PAC = v_CD_CODI_ZORE_PAC,
              DE_EMAIL_PAC = v_DE_EMAIL_PAC,
              CD_CODI_OCUP_PAC = v_CD_CODI_OCUP_PAC,
              NU_CONS_HIST_PAC = v_NU_CONS_HIST_PAC,
              NU_TIPO_PAC = v_NU_TIPO_PAC,
              CD_CODI_RELI_PAC = v_CD_CODI_RELI_PAC,
              CD_CODI_BAR_PAC = v_CD_CODI_BAR_PAC,
              NU_GEST_PAC = v_NU_GEST_PAC,
              CD_CODI_DPTO_TRAB_PAC = v_CD_CODI_DPTO_TRAB_PAC,
              CD_CODI_MUNI_TRAB_PAC = v_CD_CODI_MUNI_TRAB_PAC,
              CD_CODI_DPTO_NACI_PAC = v_CD_CODI_DPTO_NACI_PAC,
              CD_CODI_MUNI_NACI_PAC = v_CD_CODI_MUNI_NACI_PAC,
              TX_TELTRAB_PAC = v_TX_TELTRAB_PAC,
              TX_DIRTRAB_PAC = v_TX_DIRTRAB_PAC,
              TX_NOMBRESP_PAC = v_TX_NOMBRESP_PAC,
              CD_CODI_PARE_PAC = v_CD_CODI_PARE_PAC,
              TX_DIRRESP_PAC = v_TX_DIRRESP_PAC,
              TX_TELRESP_PAC = v_TX_TELRESP_PAC,
              ME_INFOAD_PAC = v_ME_INFOAD_PAC,
              NU_FALLE_PAC = v_NU_FALLE_PAC,
              CD_CODI_PAIS_PAC = v_CD_CODI_PAIS_PAC,
              CD_CODI_PAIS_TRAB_PAC = v_CD_CODI_PAIS_TRAB_PAC,
              CD_CODI_PAIS_NACI_PAC = v_CD_CODI_PAIS_NACI_PAC,
              CD_CODI_ESCO_PAC = v_CD_CODI_ESCO_PAC,
              NU_ACTI_EPS_PAC = v_NU_ACTI_EPS_PAC,
              NU_TERC_PAC = v_NU_TERC_PAC,
              NU_DATOS_EXT_PAC = v_NU_DATOS_EXT_PAC,
              DE_CELU_PAC = v_DE_CELU_PAC,
              TX_CODIGO_ETNI_PACI = v_CODIGOETNIA,
              TX_DISCAPACIDAD_PACI = v_DISCAPACIDAD,
              NU_AUTO_TIRH = v_NU_AUTO_TIRH,
              CD_CODI_LOC_PAC = v_CD_CODI_LOC_PAC,
              INFO_PAC_COMPLETA = 1,
              DE_OTRO_TELE_PAC = v_DE_OTRO_TELE_PAC,
              NU_ISDESPLAZADO_PAC = v_NU_ISDESPLAZADO_PAC,
              TX_CODIGO_TICO_PAC = v_TX_CODIGO_TICO_PAC
          WHERE  NU_HIST_PAC = v_NU_HIST_PAC;

          v_NUEVO := 0;   
      END;
  END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_GUARDAR_PACIENTE;