CREATE OR REPLACE PROCEDURE SP_ACOMER_FACTURAS_CONTRATOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	IN_CODIGO_CONTRATO CAR0011.CARNUMCONT%TYPE, -- CODIGO DEL CONTRATO QUE SOLICIT LAS FACTURAS
	OUT_FACTURAS OUT SYS_REFCURSOR  	   		-- VARIABLE CONTIENE TODAS LAS FACUTRAS DE UN CONTRATO
)
AS
BEGIN
	OPEN OUT_FACTURAS FOR
		SELECT CONTRATO.CARNUMCONT COD_CONTRATO,
			CONTRATO.CARCONTVLR VALOR_CONTRATO,
			CONTRATO.CARNUMCUOT CUOTAS,
			CONTRATO.CARPLZDIAS PLAZOS,
			CONTRATO.CARVLRCUOT VAL_CUOTA,
			CONTRATO.CARCONTOBJ OBJ_CONTRATO,
			FACTURA.CONTFEC FEC_FACTURA,
			FACTURA.CONTVLRPAG VALOR_PAGAR
		FROM CAR00111 FACTURA
		INNER JOIN CAR0011 CONTRATO
			ON CONTRATO.CARNUMCONT = FACTURA.CARNUMCONT
			AND CONTRATO.CARNUMCONT = IN_CODIGO_CONTRATO;
END;