CREATE OR REPLACE PROCEDURE SP_ACOMER_EMPRESAS_CONTRATOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	OUT_EMPRESAS OUT SYS_REFCURSOR,  -- VARIABLE CONTIENE TODAS LAS EMPRESAS 
	OUT_CONTRATOS OUT SYS_REFCURSOR, -- VARIABLE CONTIENE TODOS LOS CONTRATOS CON LAS EMPRESAS DE LA VARIABLE ANTERIOR
	OUT_FACTURAS OUT SYS_REFCURSOR	 -- VARIABLE CONTIENE TODAS LAS FACTURAS DE LOS CONTRATOS DE LA VARIABLE ANTERIOR
)
AS
BEGIN
	-- ========================================
	-- CONSULTA DE LAS EMPRESAS CON CONTRATO 
	OPEN OUT_EMPRESAS FOR
		SELECT EMPCOD COD_EMPRESA,
			EMPNOM NOM_EMPRESA
		FROM GEN0006
		ORDER BY NOM_EMPRESA;

	-- ========================================
	-- CONSULTA DE LOS CONTRATOS DE LAS EMPRESAS
	OPEN OUT_CONTRATOS FOR
		SELECT EMPRESAS.EMPCOD COD_EMPRESA,
			CONTRATO.CARNUMCONT COD_CONTRATO,
			CONTRATO.CARCONTVLR VALOR_CONTRATO,
			CONTRATO.CARNUMCUOT CUOTAS,
			CONTRATO.CARPLZDIAS PLAZOS,
			CONTRATO.CARVLRCUOT VAL_CUOTA,
			CONTRATO.CARCONTOBJ OBJ_CONTRATO,
			CONTRATO.CARPOLFECIN FECHA_INICIO,
			CONTRATO.CARPOLFECFIN FECHA_FIN,
			CONTRATO.CARFECFIRM FECHA_FIRMA
		FROM GEN0006 EMPRESAS
		INNER JOIN CAR0011 CONTRATO
			ON CONTRATO.CAREMPCOD = EMPRESAS.EMPCOD
		ORDER BY COD_EMPRESA,
			FECHA_INICIO,
			COD_CONTRATO;

	-- ========================================
	-- CONSULTA DE LAS FACTURAS DE LOS CONTRATOS 
	OPEN OUT_FACTURAS FOR		
		SELECT CONTRATO.CARNUMCONT COD_CONTRATO,
			CONTRATO.CARCONTVLR VALOR_CONTRATO,	
			FACTURA.CONTFEC FEC_FACTURA,
			FACTURA.CONTVLRPAG VALOR_PAGAR,
			CASE FACTURA.CONTESTPAG
                WHEN 'Pendiente' THEN 'P'
                ELSE 'C'
			END ESTADO
		FROM CAR00111 FACTURA
		INNER JOIN CAR0011 CONTRATO
			ON CONTRATO.CARNUMCONT = FACTURA.CARNUMCONT
		ORDER BY FEC_FACTURA ASC;
END;