CREATE OR REPLACE TRIGGER TRG_CAB_FACTURA_GRAL
BEFORE INSERT ON CAB_FACTURA_GRAL 
FOR EACH ROW
DECLARE	
BEGIN
	-- CONSULTA EL TOTAL DE FACTURA, SUBTOTAL E IVA
	SELECT SUM(B.FACVALIVA), (SUM(B.FACVALIVA)/1.19), (SUM(B.FACVALIVA) - (SUM(B.FACVALIVA)/1.19)) 
	INTO :NEW.TOTAL, :NEW.SUBTOTAL, :NEW.IVA
	FROM VEN0008 A
	INNER JOIN VEN00081 B
		ON B.FACNRO = A.FACNRO
		AND A.FACEMPC = :NEW.FACEMPCGRAL
		AND B.FACEMPC = A.FACEMPC
		AND A.FACNUMDOC = :NEW.FACNUMDOCGRAL
	WHERE A.FACNRO = :NEW.FACNRO;


END;