CREATE OR REPLACE PROCEDURE H3i_SP_CONS_PRESUP_ADSC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECH_INICIO IN DATE, 
	V_FECH_FIN IN DATE,
	CV_1 OUT SYS_REFCURSOR
)        
AS
BEGIN
    OPEN CV_1 FOR
        SELECT DISTINCT A.CD_CODI_ADSC,
            A.NU_CONSE_ADSC,
            A.DE_NOMB_ADSC,
            A.NU_ESTA_ADSC,
            A.NU_TIPCONT_ADSC,
            A.NU_LABO_DENTAL, 
            NVL(C.CD_CODI_COAD,'ND') AS CD_CODI_COAD,
            NVL(C.DE_NOMB_COAD,'ND') AS DE_NOMB_COAD,		
            SUM(CAST(AA.VAL_PAGCONV_AUAD AS NUMBER)) VL_MONTO,
            1 AUTORIZACION,
            NVL(C.VL_CUPO_COAD,'0') AS MONT_CONS,
            SUM(CAST(AA.VAL_PAGCONV_AUAD AS NUMBER)) AS MONT_EJEC, 
            NVL(C.VL_CUIN_COAD,0) AS MONT_INDV,
            NVL(C.VL_CUPO_COAD,0) - SUM(CAST(AA.VAL_PAGCONV_AUAD AS NUMBER)) AS MONT_SALD,
            CASE A.NU_LABO_DENTAL
                WHEN 0 THEN 'NORMAL'
                WHEN 1 THEN 'DENTAL'
            END	TIPO         
        FROM ADSCRITOS A 
        INNER JOIN CONVENIO_ADSC C 
            ON NU_CONSE_ADSC = C.NU_CONSE_ADSC_COAD
        INNER JOIN AUTORIZACION_ADSCRITOS AA 
            ON CD_CODIGO_ADSC = CD_CODI_ADSC_AUAD 
            AND CD_CODI_COAD = CD_CODI_COAD_AUAD
        INNER JOIN REGISTRO_ADSCRITO 
            ON TXT_COD_BARRA_READ = CD_CODI_AUTORIZA_AUAD
        LEFT JOIN ANULACION_AUTORIZACION_ADS AUA 
            ON CD_CODI_AUTORIZA_AUAD_ANUL= CD_CODI_AUTORIZA_AUAD
        WHERE ID_ANUL IS NULL 
            AND AA.FE_AUTORIZA_AUAD >= V_FECH_INICIO 
            AND AA.FE_AUTORIZA_AUAD <= V_FECH_FIN
        GROUP BY A.CD_CODI_ADSC, A.NU_CONSE_ADSC,
                 A.DE_NOMB_ADSC, A.NU_ESTA_ADSC,
                 A.NU_TIPCONT_ADSC, A.NU_LABO_DENTAL,
                 C.CD_CODI_COAD, C.DE_NOMB_COAD,
                 C.VL_CUPO_COAD, C.VL_CUIN_COAD,
                 C.VL_SALD_COAD, A.NU_LABO_DENTAL
        ORDER BY A.CD_CODI_ADSC;
END;