CREATE OR REPLACE PROCEDURE H3i_SP_CONS_ANTECED_TIPO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NUMHISPAC IN VARCHAR2,
	V_ANTEC_ALERGICO IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
AS
	V_ANIOS_ATENCIONES NUMBER;
	V_EXISTE NUMBER;
	V_VAR_VALOR VARCHAR2(4000);
	V_CPTO_EVAL NUMBER;
	V_CONTADOR NUMBER;
	V_VAR_IDREG NUMBER;
	V_VAR_VALOR_ANTEC VARCHAR2(4000);
	V_VAR_RES NUMBER;
BEGIN
	--
	SELECT COUNT(*)
	V_EXISTE
	FROM CONTROL 
	WHERE CD_CONC_CONT = 'ANIOS_ATENCION_ANTECED';
	--
	IF (V_EXISTE) THEN
		BEGIN			
			SELECT CAST(VL_VALO_CONT AS INT) 
			INTO V_ANIOS_ATENCIONES
			FROM CONTROL 
			WHERE CD_CONC_CONT = 'ANIOS_ATENCION_ANTECED';								
		END;
	ELSE
		BEGIN
			V_ANIOS_ATENCIONES := 5;
		END;
	END IF;

	--
	--Obtenemos todas las atenciones del paciente del tiempo parametrizado o por defecto
	INSERT INTO TT_TMPANTENCIONES
			SELECT H.NU_NUME_HICL,
				H.NU_NUME_PLHI_HICL,
				L.NU_NUME_LABO,
				M.NU_NUME_MOVI,
				H.FE_FECH_HICL,
				L.CD_CODI_SER_LABO,
				S.NO_NOMB_SER,
				L.CD_CODI_ESP_LABO,
				E.NO_NOMB_ESP,
				NU_NUME_REG_MOVI	
			FROM MOVI_CARGOS M 
			INNER JOIN LABORATORIO L 
				ON M.NU_NUME_MOVI = L.NU_NUME_MOVI_LABO
			INNER JOIN HISTORIACLINICA H 
				ON L.NU_NUME_LABO = H.NU_NUME_LABO_HICL
			INNER JOIN SERVICIOS S 
				ON L.CD_CODI_SER_LABO = S.CD_CODI_SER
			INNER JOIN ESPECIALIDADES E 
				ON L.CD_CODI_ESP_LABO = E.CD_CODI_ESP
			WHERE NU_HIST_PAC_MOVI = V_NUMHISPAC
				AND	NU_ESTA_MOVI <> 2
				AND	NU_ESTA_LABO <> 2
				AND (TO_DATE(FE_FECH_HICL,'YYYY') -  TO_DATE(SYSDATE,'YYYY')) <= V_ANIOS_ATENCIONES		
	
		UNION ALL
			--AUmentando las notas de enfermeria
			SELECT	H.NU_NUME_HICL,
				H.NU_NUME_PLHI_HICL,
				0,
				0,
				H.FE_FECH_HICL,
				'0',
				'NOTAS DE ENFERMERÍA',
				'ENF',
				'ENFERMERÍA',
				0			
			FROM HISTORIACLINICA H 
			INNER JOIN EVENTO_ENFERMERIA 
				ON NU_NUME_HICL_EVEN = NU_NUME_HICL
			WHERE NU_NUME_LABO_HICL = 0 
				AND NU_HIST_PAC_EVEN = V_NUMHISPAC
				AND	(TO_DATE(FE_FECH_HICL,'YYYY') -  TO_DATE(SYSDATE,'YYYY')) <= V_ANIOS_ATENCIONES;

	--
	
	INSERT INTO	TT_TMPANTENCIONESRELACIONADAS
		SELECT	*	
		FROM TT_TMPANTENCIONES T 
		INNER JOIN (	SELECT	NU_NUME_PLHI_A_REPA IDPLANTILLA, 
							RP.NU_NUME_COHI_A_REPA IDCONCEPTO, 
							RP.NU_INDI_RPC_A_REPA NoORDENCONCEPTO
						FROM RELACION_PLANTILLA RP
					UNION ALL						
						SELECT NU_NUME_PLHI_B_REPA IDPLANTILLA, 
							RP.NU_NUME_COHI_B_REPA IDCONCEPTO, 
							RP.NU_INDI_RPC_B_REPA NoORDENCONCEPTO
						FROM RELACION_PLANTILLA RP) RP
			ON T.NU_NUME_PLHI_HICL = RP.IDPLANTILLA;
		
	--

	INSERT INTO TT_TMPCONCEPTOSANTECEDENTE
			SELECT	TT_TMPANTENCIONES.*,
					RPC.NU_INDI_RPC,
					RPC.NU_NUME_GRHI_RPC,
					C.NU_NUME_COHI,
					C.NU_TIPO_COHI,
					C.TX_TITULO_COHI,
					FN_VALORCONCEPTOHC(NU_NUME_HICL, NU_NUME_COHI, NU_INDI_RPC, NU_TIPO_COHI,1) VALOR,
					ANTE_ALERG	
			FROM TT_TMPANTENCIONES 
			INNER JOIN R_PLAN_CONC RPC 
				ON NU_NUME_PLHI_HICL = RPC.NU_NUME_PLHI_RPC
			INNER JOIN VALCONC_HIST1 
				ON NU_NUME_COHI_RPC=NU_NUME_COHI_VAHI1 
				AND NU_NUME_PLHI_VAHI1 = NU_NUME_PLHI_RPC
			INNER JOIN CONCEPTO_HIST C 
			ON C.NU_NUME_COHI = RPC.NU_NUME_COHI_RPC
			WHERE NU_ANTE_VAHI1 = 1
				AND	NU_TIPO_COHI NOT IN (8, 9, 10, 11, 12)
				AND	ANTE_ALERG = V_ANTEC_ALERGICO
	
		UNION	ALL
	
			SELECT	TA.NU_NUME_HICL,
				TA.NU_NUME_PLHI_HICL,
				TA.NU_NUME_LABO,
				TA.NU_NUME_MOVI,
				TA.FE_FECH_HICL,
				TA.CD_CODI_SER_LABO,
				TA.NO_NOMB_SER,
				TA.CD_CODI_ESP_LABO,
				TA.NO_NOMB_ESP,
				NU_NUME_REG_MOVI,
				RPC.NU_INDI_RPC,
				RPC.NU_NUME_GRHI_RPC,
				C.NU_NUME_COHI,
				C.NU_TIPO_COHI,	
				C.TX_TITULO_COHI,	
				FN_VALORCONCEPTOHC(NU_NUME_HICL, NU_NUME_COHI, NU_INDI_RPC, NU_TIPO_COHI,1) VALOR,
				ANTE_ALERG
			FROM TT_TMPANTENCIONESRELACIONADAS TA 
			INNER JOIN R_PLAN_CONC RPC 
				ON (NU_NUME_PLHI_HICL = RPC.NU_NUME_PLHI_RPC
				AND TA.IDCONCEPTO = RPC.NU_NUME_COHI_RPC 
				AND TA.NoORDENCONCEPTO = RPC.NU_INDI_RPC  )
			INNER JOIN VALCONC_HIST1 
				ON NU_NUME_COHI_RPC=NU_NUME_COHI_VAHI1 
				AND NU_NUME_PLHI_VAHI1 = NU_NUME_PLHI_RPC
			INNER JOIN CONCEPTO_HIST C 
				ON C.NU_NUME_COHI = RPC.NU_NUME_COHI_RPC
			WHERE NU_ANTE_VAHI1 <> 1
			AND	NU_TIPO_COHI NOT IN (8, 9, 10, 11, 12)
			AND	ANTE_ALERG = V_ANTEC_ALERGICO;
		
	--

	INSERT INTO TT_TMPCONCEPTOSANTECEDENTE2
		SELECT TT.*,
			ROWNUM
		FROM TT_TMPCONCEPTOSANTECEDENTE;
	
	--
	INSERT INTO TT_TMPVALORESDISTINTOS
		SELECT DISTINCT VALOR, NU_NUME_COHI	
		FROM TT_TMPCONCEPTOSANTECEDENTE2
		WHERE VALOR IS NOT NULL;

	--	
	SELECT COUNT(*) 
	INTO V_CONTADOR
	FROM TT_TMPVALORESDISTINTOS;	

	WHILE (V_CONTADOR > 0) 
	LOOP	

		--
		SELECT VALOR, NU_NUME_COHI
		INTO V_VAR_VALOR, V_CPTO_EVAL
		FROM TT_TMPVALORESDISTINTOS
		WHERE ROWNUM = 1;
					
		--				
		SELECT  = ID_REG, VALOR
		INTO V_VAR_IDREG, V_VAR_VALOR_ANTEC
		FROM TT_TMPCONCEPTOSANTECEDENTE2
		WHERE VALOR = V_VAR_VALOR 
			AND NU_NUME_COHI = V_CPTO_EVAL

		--				
		INSERT INTO TT_TMPREGANTECEDENTES 
		VALUES(V_VAR_IDREG, V_VAR_VALOR_ANTEC);
				
		Delete TT_TMPVALORESDISTINTOS
		WHERE VALOR = v_VAR_VALOR 
			AND NU_NUME_COHI = v_CPTO_EVAL;

		--
		SELECT COUNT(*) 
		INTO V_CONTADOR
		FROM TT_TMPVALORESDISTINTOS;	
	END LOOP;	
	
	--	
	SELECT COUNT(*) 
	INTO V_VAR_RES
	FROM TT_TMPREGANTECEDENTES;	

	--

	OPEN CV_1 FOR
		SELECT	ID_REG,
			T.NU_NUME_HICL,
			T.NU_NUME_PLHI_HICL,
			NU_NUME_LABO,
			NU_NUME_MOVI,
			FE_FECH_HICL,
			CD_CODI_SER_LABO,
			NO_NOMB_SER,
			CD_CODI_ESP_LABO,
			NO_NOMB_ESP,
			NU_NUME_REG_MOVI,
			NU_INDI_RPC,
			NU_NUME_GRHI_RPC,
			NU_NUME_COHI,
			NU_TIPO_COHI,
			TX_TITULO_COHI,
			VALOR,
			ANTE_ALERG
		FROM TT_TMPCONCEPTOSANTECEDENTE2 T 	
		WHERE VALOR IS NOT NULL
			AND ID_REG IN (SELECT ID_REG_ANT FROM TT_TMPREGANTECEDENTES);
	
END;