CREATE OR REPLACE PROCEDURE H3I_ALERTA_DX
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	 V_HISTORIA IN VARCHAR2,
	 CV_1 OUT SYS_REFCURSOR
)
AS

BEGIN
	OPEN CV_1 FOR 
		SELECT DISTINCT VC.NOM__DIA_VISA
		FROM V_DATOS_HISTCLINICA V
		INNER JOIN DIAGNOSTICO D 
			ON V.TX_VALOR_CONC = DE_DESC_DIAG
		INNER JOIN VIGILANCIA_SALUD VC 
			ON D.CD_CODI_DIAG = COD_DIA_VISA
		WHERE NU_NUME_LABO_HICL IN 
			(	SELECT NU_NUME_LABO 
			    FROM MOVI_CARGOS MC 
			    INNER JOIN LABORATORIO L 
			    	ON L.NU_NUME_MOVI_LABO = MC.NU_NUME_MOVI 
			    WHERE MC.NU_HIST_PAC_MOVI = V_HISTORIA)
		AND NU_NUME_COHI in (6794, 6791,6792,6793)
		AND NOTIFICACION_VISA = 'INDIVIDUAL';
END;