CREATE OR REPLACE PROCEDURE H3i_SP_CONS_PRESUP_ADSC_T2
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_FECH_INICIO IN DATE, 
    V_FECH_FIN IN DATE,
    V_CODI_ADSCRITOS IN VARCHAR2,
    V_COD_CONVENIO_ADSC IN VARCHAR2,
    CV_1 OUT SYS_REFCURSOR
)        
AS
BEGIN
    OPEN CV_1 FOR
        SELECT A.CD_CODI_ADSC,
            A.NU_CONSE_ADSC,
            A.DE_NOMB_ADSC,
            A.NU_ESTA_ADSC,
            A.NU_TIPCONT_ADSC,
            A.NU_LABO_DENTAL,
            A.CD_CODIGO_ADSC,
            CASE A.NU_LABO_DENTAL
                WHEN 0 THEN 'NORMAL'
                WHEN 1 THEN 'DENTAL'
            END TIPO,
            NVL(C.CD_CODI_COAD, 'ND') AS CD_CODI_COAD,
            NVL(C.DE_NOMB_COAD, 'ND') AS DE_NOMB_COAD,
            NVL(C.VL_CUPO_COAD,0) AS MONT_CONS,            
            NVL(CAST(VAL_PAGCONV_AUAD AS NUMBER), 0) AS MONT_EJEC,
            NVL(C.VL_CUIN_COAD,0) AS MONT_INDV,            
            NVL(C.VL_CUPO_COAD,0) - NVL(CAST(VAL_PAGCONV_AUAD AS NUMBER), 0) AS MONT_SALD,
            VAL_PAGCONV_AUAD AS VL_MONTO,
            CD_CODI_AUTORIZA_AUAD AS CD_CODI_AUTORIZA,
            FE_AUTORIZA_AUAD AS FE_FECHA,
            1 AS AUTORIZACION
			FROM ADSCRITOS A INNER JOIN CONVENIO_ADSC C 
                ON NU_CONSE_ADSC = C.NU_CONSE_ADSC_COAD
			INNER JOIN AUTORIZACION_ADSCRITOS AA 
                ON CD_CODIGO_ADSC = CD_CODI_ADSC_AUAD 
                AND CD_CODI_COAD = CD_CODI_COAD_AUAD
			INNER JOIN REGISTRO_ADSCRITO 
                ON TXT_COD_BARRA_READ = CD_CODI_AUTORIZA_AUAD
			LEFT JOIN ANULACION_AUTORIZACION_ADS AUA 
                ON CD_CODI_AUTORIZA_AUAD_ANUL= CD_CODI_AUTORIZA_AUAD
			WHERE ID_ANUL IS NULL 
                AND FE_AUTO_READ BETWEEN V_FECH_INICIO AND V_FECH_FIN 
                AND  A.CD_CODIGO_ADSC = V_CODI_ADSCRITOS 
                AND CD_CODI_COAD = V_COD_CONVENIO_ADSC
END;