CREATE OR REPLACE PROCEDURE H3i_SP_CALENDARIO_CON
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINICIO IN DATE,
	V_FECHAFINAL IN DATE,
	V_TIPO IN NUMBER DEFAULT NULL,
	CV_1 OUT SYS_REFCURSOR
) 
AS
BEGIN
	OPEN CV_1 FOR
		SELECT * 
		FROM CALENDARIO 
		WHERE FE_FECH_CALE >= V_FECHAINICIO
			AND FE_FECH_CALE <= V_FECHAFINAL
			AND ((NU_TIPO_CALE = V_TIPO) OR (V_TIPO IS NULL));
END;