CREATE OR REPLACE PROCEDURE H3i_ICEBERGREFERENCIAS_BOR
-- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_CODI_ICEBERG IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)

AS
	V_CODIGO VARCHAR2(12);
	V_RETORNO VARCHAR2(12) := 'OK';
BEGIN
	
	SELECT COUNT(1)
	INTO V_CODIGO
	FROM ICEBERG_ARTICULOS
	WHERE CD_CODI_ICEBERG = V_CD_CODI_ICEBERG;

	IF ( V_CODIGO = 1) THEN 

		BEGIN
			V_RETORNO := 'ARTICULOS';
		END;

	ELSE

		BEGIN	
			SELECT COUNT(1)
			INTO V_CODIGO
			FROM ICEBERG_ARTICULOS
			WHERE CD_CODI_ICEBERG = V_CD_CODI_ICEBERG;

			IF(V_CODIGO = 1) THEN
				BEGIN
					V_RETORNO := 'SERVICIOS';
				END;

			ELSE
				BEGIN
					DELETE FROM ICEBERG_REFERENCIAS
					WHERE CD_CODI_ICEBERG = V_CD_CODI_ICEBERG;
				END;
			END IF;
		END;
	END IF;

	OPEN CV_1 FOR
		SELECT V_RETORNO AS RETORNO
		FROM DUAL;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;