CREATE OR REPLACE PROCEDURE H3i_SP_CREA_GESTION_GLOSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_NU_NUME_CONE_GEGL IN NUMBER,
    V_NU_NUME_ITGL_GEGL IN NUMBER,
    V_NU_TIPO_GEGL IN NUMBER,
    V_NU_NUME_TIGE_GEGL IN NUMBER DEFAULT -1,
    V_DE_OBSE_GEGL IN VARCHAR2,
    V_FE_FECH_GEGL IN DATE,
    V_VL_ACEP_GEGL IN NUMBER,
    V_VL_RECH_GEGL IN NUMBER,
    V_NU_NCRE_GEGL IN NUMBER,
    V_NU_ESTA_GEGL IN NUMBER
)

   
AS
    V_FK_NU_NUME_TIGE_GEGL NUMBER := V_NU_TIPO_GEGL;
BEGIN
    

    INSERT INTO GESTION_GLOSA (
        NU_NUME_CONE_GEGL, NU_NUME_ITGL_GEGL,
        NU_TIPO_GEGL, NU_NUME_TIGE_GEGL,
        DE_OBSE_GEGL, FE_FECH_GEGL,
        VL_ACEP_GEGL, VL_RECH_GEGL,
        NU_NCRE_GEGL, NU_ESTA_GEGL)
    VALUES (
        V_NU_NUME_CONE_GEGL, V_NU_NUME_ITGL_GEGL,
        V_NU_TIPO_GEGL, V_FK_NU_NUME_TIGE_GEGL,
        V_DE_OBSE_GEGL, V_FE_FECH_GEGL,
        V_VL_ACEP_GEGL, V_VL_RECH_GEGL,
        V_NU_NCRE_GEGL, V_NU_ESTA_GEGL);

    UPDATE GLOSA3I
    SET NU_AUTO_ESGL_GLOS =
      ( SELECT NU_AUTO_ESGLO
        FROM (SELECT NU_AUTO_ESGLO
              FROM ESTADO_GLOSA3I         
              WHERE NU_AUTO_ESGLO = V_NU_ESTA_GEGL)
        WHERE ROWNUM <= 1)                 
    WHERE NU_AUTO_GLOS = V_NU_NUME_CONE_GEGL  ;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;