CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_REQUISICION
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO OUT NUMBER,
  v_CD_CODI_CECO_RMED IN VARCHAR2,
  v_ID_ESTA_RMED IN NUMBER,
  v_DE_FAR_BOD_RMED IN VARCHAR2,
  v_NU_CONE1_RMED IN NUMBER
)
AS

BEGIN

    INSERT INTO REQUISICION_MED( 
        FE_FECH_REQU_RMED, CD_CODI_CECO_RMED, 
        ID_ESTA_RMED, DE_FAR_BOD_RMED, 
        NU_CONE1_RMED )
    VALUES(
        SYSDATE , v_CD_CODI_CECO_RMED ,
    v_ID_ESTA_RMED , v_DE_FAR_BOD_RMED ,
    v_NU_CONE1_RMED);
       


    SELECT CD_CODI_REQU_RMED 
    INTO v_CODIGO 
    FROM REQUISICION_MED
    WHERE CD_CODI_REQU_RMED = (SELECT MAX(CD_CODI_REQU_RMED) FROM REQUISICION_MED);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;