CREATE OR REPLACE PROCEDURE H3i_SP_CREA_FOR_PAGO_FAC_CONT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	v_NU_NUME_FACO_RFF IN NUMBER,
	v_NU_NUME_FOPA_RFF IN VARCHAR2,
	v_NU_MONTO_RFF IN NUMBER
)
AS

BEGIN

	INSERT INTO R_FOP_FACO( 
		NU_NUME_FACO_RFF, NU_NUME_FOPA_RFF, 
		NU_MONTO_RFF )
	VALUES( 
		v_NU_NUME_FACO_RFF, v_NU_NUME_FOPA_RFF, 
		v_NU_MONTO_RFF );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;