CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_SOLICITUD_MEDICA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_NU_DOCU_PAC_SMED IN VARCHAR2,
    v_CD_CODI_ARTI_SMED IN VARCHAR2,
    v_NO_NOMB_ARTI_SMED IN VARCHAR2,
    v_DE_UNME_SMED IN VARCHAR2,
    v_DE_CTRA_SMED IN VARCHAR2,
    v_DE_DOSIS_SMED IN VARCHAR2,
    v_NU_CANT_SMED IN NUMBER,
    v_NU_CANT_PEND_SMED IN NUMBER,
    v_NU_ESTA_SMED IN NUMBER,
    v_CD_CODI_MED_SMED IN VARCHAR2,
    v_NU_NUME_HICL_SMED IN NUMBER,
    v_ID_ORDENO_SMED IN NUMBER,
    v_NU_NUME_MOVI_SMED IN NUMBER DEFAULT NULL ,
    v_NU_ESTA_DEVO_SMED IN NUMBER,
    v_NU_NUME_HMED_SMED IN NUMBER DEFAULT NULL ,
    v_CD_CODI_REQU_RMED IN NUMBER,
    v_NU_CIR_SMED IN NUMBER
)
AS
    v_CODIGO NUMBER(10,0);

BEGIN

    INSERT INTO SOLICITUD_MED( 
        NU_DOCU_PAC_SMED, CD_CODI_ARTI_SMED, 
        NO_NOMB_ARTI_SMED, DE_UNME_SMED, 
        DE_CTRA_SMED, DE_DOSIS_SMED, 
        NU_CANT_SMED, NU_CANT_PEND_SMED, 
        NU_ESTA_SMED, CD_CODI_MED_SMED, 
        NU_NUME_HICL_SMED, ID_ORDENO_SMED, 
        NU_NUME_MOVI_SMED, NU_ESTA_DEVO_SMED, 
        NU_NUME_HMED_SMED, NU_CIR_SMED )
    VALUES(v_NU_DOCU_PAC_SMED, v_CD_CODI_ARTI_SMED ,
        v_NO_NOMB_ARTI_SMED , v_DE_UNME_SMED ,
        v_DE_CTRA_SMED , v_DE_DOSIS_SMED ,
        v_NU_CANT_SMED , v_NU_CANT_PEND_SMED ,
        v_NU_ESTA_SMED , v_CD_CODI_MED_SMED ,
        v_NU_NUME_HICL_SMED , v_ID_ORDENO_SMED ,
        v_NU_NUME_MOVI_SMED , v_NU_ESTA_DEVO_SMED ,
        v_NU_NUME_HMED_SMED , v_NU_CIR_SMED );


    SELECT NU_NUME_SOLI_SMED 
    INTO v_CODIGO 
    FROM SOLICITUD_MED
    WHERE NU_NUME_SOLI_SMED = (SELECT MAX(NU_NUME_SOLI_SMED) FROM SOLICITUD_MED);


    ----Insertar la relacion del detalle(SOLICITUD_MED) con la requisicion(REQUISICION_MED)
    INSERT INTO R_RMED_SMED( 
        CD_CODI_REQU_RMED_RRS, NU_NUME_SOLI_SMED_RRS )
    VALUES(v_CD_CODI_REQU_RMED, v_CODIGO);


    ---------
    --actualizar la tabla HIST_MEDI
    IF ( v_ID_ORDENO_SMED = 1 ) THEN

        BEGIN
            UPDATE HIST_MEDI
                SET NU_ESTA_ENT_HMED = 1
            WHERE  NU_NUME_HICL_HMED = v_NU_NUME_HICL_SMED
                AND NU_NUME_HEVO_HMED = v_NU_ESTA_DEVO_SMED
                AND CD_CODI_ARTI_HMED = v_CD_CODI_ARTI_SMED
                AND NU_ESTA_ENT_HMED = 0;
        END;

    END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;