CREATE OR REPLACE PROCEDURE H3i_SP_ACT_GLOSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIGO IN NUMBER DEFAULT 0,
	V_RADICADION IN DATE DEFAULT SYSDATE,
	V_GENERA IN DATE,
	V_IDRADICACION IN VARCHAR2,
	V_NITEPS IN VARCHAR2,
	V_CONEX IN NUMBER,
	V_ESTADO IN NUMBER,
	V_ULTIMO OUT NUMBER
)			 

AS
	V_EXISTE NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO V_EXISTE
	FROM GLOSA3i
	WHERE NU_AUTO_GLOS = V_CODIGO;

	IF(V_EXISTE >= 1) THEN
		BEGIN
			UPDATE GLOSA3i
			SET FE_RADICACION_GLOS = V_RADICADION,
				FE_GENERA_GLOS = V_GENERA,
				TX_RADICAEXT_GLOS = V_IDRADICACION,
				CD_NIT_EPS_GLOS = V_NITEPS,
				NU_AUTO_ESGL_GLOS = V_ESTADO
			WHERE NU_AUTO_GLOS = V_CODIGO;

			V_ULTIMO := V_CODIGO;
		END;

	ELSE

		BEGIN
			INSERT INTO GLOSA3i (
				FE_RADICACION_GLOS, FE_GENERA_GLOS, 
				TX_RADICAEXT_GLOS, CD_NIT_EPS_GLOS, 
				NU_NUME_CONEX_GLOS, NU_AUTO_ESGL_GLOS)
			VALUES (
				V_RADICADION, V_GENERA,
				V_IDRADICACION, V_NITEPS,
				V_CONEX, V_ESTADO);

			SELECT NU_AUTO_GLOS 
			INTO V_ULTIMO 
			FROM GLOSA3i
			WHERE NU_AUTO_GLOS = (SELECT MAX(NU_AUTO_GLOS) FROM GLOSA3i);
		END;

	END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;