CREATE OR REPLACE PROCEDURE H3i_ICEBERGSERVICIOS_CON
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR
		SELECT ISER.CD_CODI_SER,SER.NO_NOMB_SER,
			ISER.CD_CODI_ICEBERG,IREF.NO_NOMB_ICEBERG,
			ISER.CD_CECOS_ICEBERG 
		FROM ICEBERG_SERVICIOS ISER 
		INNER JOIN ICEBERG_REFERENCIAS IREF 
			ON ISER.CD_CODI_ICEBERG = IREF.CD_CODI_ICEBERG
		INNER JOIN SERVICIOS SER 
			ON ISER.CD_CODI_SER = SER.CD_CODI_SER
		ORDER BY ISER.CD_CECOS_ICEBERG,SER.CD_CODI_SER;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

