CREATE OR REPLACE PROCEDURE H3i_ICEBERGREFPORNOMB_CON
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NO_NOMB_ICEBERG IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)

AS
BEGIN
	OPEN CV_1 FOR
		SELECT NO_NOMB_ICEBERG,CD_CODI_ICEBERG 
		FROM ICEBERG_REFERENCIAS 
		WHERE NO_NOMB_ICEBERG LIKE '%' || V_NO_NOMB_ICEBERG || '%';

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
