CREATE OR REPLACE PROCEDURE H3i_ICEBERGHMLGCNSER_ACT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_CODI_SER IN VARCHAR2,
	V_CD_CODI_ICEBERG IN VARCHAR2,
	V_CD_CECOS_ICEBERG IN VARCHAR2
)

AS	
	V_CODIGO NUMBER;
BEGIN
	SELECT COUNT(1)
	INTO V_CODIGO
	FROM ICEBERG_SERVICIOS
	WHERE CD_CODI_SER = V_CD_CODI_SER;

	IF(V_CODIGO = 0) THEN

		BEGIN
			INSERT INTO ICEBERG_SERVICIOS
			VALUES (
				V_CD_CODI_SER, V_CD_CODI_ICEBERG,
				V_CD_CECOS_ICEBERG);
		END;

	ELSE

		BEGIN
			UPDATE ICEBERG_SERVICIOS
			SET CD_CODI_ICEBERG = V_CD_CODI_ICEBERG,
				CD_CECOS_ICEBERG = V_CD_CECOS_ICEBERG
			WHERE CD_CODI_SER = V_CD_CODI_SER;
		END;

	END IF;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;