CREATE OR REPLACE PROCEDURE H3i_SP_OBTENR_DETALLE_FACTCNT2
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CODIGO IN NUMBER,
	CV_1 OUT SYS_RERCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR
		SELECT DISTINCT 
			(	CASE C.NU_ALTE_CONV 
					WHEN 0 THEN SERVICIOS.CD_CODI_SER 
					ELSE TB.CD_ALTE_RST 
				END) Codigo,
			SERVICIOS.NO_NOMB_SER Descripcion,
			FACTURAS_CONTADO.NU_CONS_MOVI_FACO Cantidad,   
			MOVI_CARGOS.VL_UNID_MOVI vunitario,
			(MOVI_CARGOS.VL_UNID_MOVI - MOVI_CARGOS.VL_COPA_MOVI) vtotal,
			MOVI_CARGOS.VL_COPA_MOVI vcopago
		FROM PACIENTES PACIENTES 
		CROSS JOIN ((LABORATORIO LABORATORIO
			INNER JOIN MOVI_CARGOS MOVI_CARGOS 
				ON (LABORATORIO.NU_NUME_MOVI_LABO = MOVI_CARGOS.NU_NUME_MOVI))
			INNER JOIN FACTURAS_CONTADO FACTURAS_CONTADO 
				ON (MOVI_CARGOS.NU_NUME_FACO_MOVI = FACTURAS_CONTADO.NU_NUME_FACO))
		INNER JOIN SERVICIOS SERVICIOS 
			ON (SERVICIOS.CD_CODI_SER = LABORATORIO.CD_CODI_SER_LABO)
		INNER JOIN CONVENIOS C 
			ON MOVI_CARGOS.NU_NUME_CONV_MOVI = C.NU_NUME_CONV
		LEFT JOIN R_SER_TARB TB 
			ON SERVICIOS.CD_CODI_SER = TB.CD_CODI_SER_RST 
			AND TB.CD_CODI_TARB_RST = C.CD_CODI_TARB_CONV
		WHERE NU_NUME_FACO = v_CODIGO
		GROUP BY MOVI_CARGOS.NU_NUME_MOVI,SERVICIOS.NO_NOMB_SER,
			FACTURAS_CONTADO.NU_CONS_MOVI_FACO,MOVI_CARGOS.VL_UNID_MOVI,
			FACTURAS_CONTADO.VL_TOTA_FACO,MOVI_CARGOS.VL_COPA_MOVI, 
			C.NU_ALTE_CONV, SERVICIOS.CD_CODI_SER, TB.CD_ALTE_RST;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;



		