CREATE OR REPLACE PROCEDURE H3I_SP_CONSULTA_FACTURA_HC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NoCargo IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN CV_1 FOR
		SELECT DISTINCT IFC.NU_NUME_FACO,
			IFC.TX_PREFIJO_ICEBERG,
			NU_NUME_ICEBERG,
			FC.FE_FECH_FACO,
			FC.VL_TOTA_FACO,
			FC.CAJERO,
			FC.NU_ESTA_FACO,
			IFC.IS_MANUAL,
			IFC.NU_NUME_IMPRE,
			MV.NU_NUME_MOVI,
			0 SALDO
		FROM ICEBERG_FACTURAS_CONTADO IFC 
		INNER JOIN  FACTURAS_CONTADO FC 
			ON IFC.NU_NUME_FACO = FC.NU_NUME_FACO
		INNER JOIN MOVI_CARGOS MV 
			ON FC.NU_NUME_FACO  = MV.NU_NUME_FACO_MOVI
		WHERE MV.NU_NUME_MOVI = V_NoCargo;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);		
END;
		