CREATE OR REPLACE PROCEDURE H3i_ACTU_DETA_CARG_MEDICA_DEVO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    V_CODIGO_CARGO IN NUMBER, 
    V_CODIGO_DETALLE IN NUMBER, 
    V_CANTIDAD_DEVUELTA IN NUMBER
)
    
AS
    V_VALOR_UNIT_COPAGO NUMBER;
    V_CANTIDAD_ORIGINAL FLOAT;
    V_NU_ESTA_FORM_ORIGINAL NUMBER;
BEGIN
    -----------------
    SELECT 
        CASE NVL(CT_CANT_FORM,0)
            WHEN 0 THEN 0
            ELSE (NVL(VL_COPA_FORM,0) / NVL(CT_CANT_FORM,0))
        END,
        CT_CANT_FORM,
        NU_ESTA_FORM
    INTO V_VALOR_UNIT_COPAGO,
        V_CANTIDAD_ORIGINAL,
        V_NU_ESTA_FORM_ORIGINAL
    FROM FORMULAS
    WHERE NU_NUME_FORM = V_CODIGO_DETALLE;

    -----------------
    UPDATE FORMULAS
    SET NU_ESTA_FORM =  CASE 
                            WHEN (V_CANTIDAD_ORIGINAL - V_CANTIDAD_DEVUELTA) <= 0
                                THEN 2
                            ELSE
                                V_NU_ESTA_FORM_ORIGINAL
                        END,
        CT_CANT_FORM = V_CANTIDAD_ORIGINAL - V_CANTIDAD_DEVUELTA,
        VL_COPA_FORM = V_VALOR_UNIT_COPAGO * V_CANTIDAD_DEVUELTA,
        NU_CTCONS_FORM = V_CANTIDAD_ORIGINAL - V_CANTIDAD_DEVUELTA
    WHERE NU_NUME_FORM = V_CODIGO_DETALLE;

    -----------------
    UPDATE (
        SELECT NU_ESTA_DEVO_SMED,
            NU_CANTDEV_SMED
        FROM SOLICITUD_MED SME
        INNER JOIN FORMULAS FOM
            ON SME.NU_NUME_MOVI_SMED = FOM.NU_NUME_MOVI_FORM
            AND SME.CD_CODI_ARTI_SMED =FOM.CD_CODI_ELE_FORM
        WHERE FOM.NU_NUME_FORM = V_CODIGO_DETALLE
            AND SME.NU_NUME_MOVI_SMED = V_CODIGO_CARGO) T
    SET T.NU_ESTA_DEVO_SMED = 1,
        T.NU_CANTDEV_SMED = NVL(T.NU_CANTDEV_SMED,0) + V_CANTIDAD_DEVUELTA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;




    