CREATE TABLE AUTORIZACION_SERVICIOS(
	NU_AUTO_AUSE NUMBER NOT NULL,
	TX_AUTORI_AUSE VARCHAR2(20) NULL,
	TX_PESO_AUSE VARCHAR2(20) NULL,
	TX_PEAU_AUSE VARCHAR2(50) NULL,
	TX_OBSE_AUSE VARCHAR2(500) NULL,
	NU_VIGE_AUSE NUMBER NULL,
	FE_FECH_AUSE DATE NULL,
	NU_AUTO_SOSE_AUSE NUMBER NULL,
	CD_REFE_AUSE VARCHAR2(10) NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--PRIMARY KEY
CREATE UNIQUE INDEX PK_AUTORIZACION_SERVICIOS  ON AUTORIZACION_SERVICIOS
(NU_AUTO_AUSE)
LOGGING
NOPARALLEL;


--CONSTRAINT PRIMARY KEY
ALTER TABLE AUTORIZACION_SERVICIOS ADD (
  	CONSTRAINT PK_AUTORIZACION_SERVICIOS
 	PRIMARY KEY
 	(NU_AUTO_AUSE));
