CREATE OR REPLACE PROCEDURE SP_LOGIN_ACOMER_OPERACION_F
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_USER_ID IN GEN0011.TERCOD%TYPE, -- IDENTIFICADOR CON EL QUE EL USUARIO HACE LOGIN 
	V_IN_USER_PASS IN VARCHAR2,			 -- CONTRASENA DE ACCESO 
	--V_IN_ACT_PASS IN VARCHAR2,			 -- CLAVE DE ACTIVACION O CREACION DE CONTRASENA
	V_OUT_USER_ID OUT GEN0011.TERCOD%TYPE, -- IDENTIFICACION DEL USUARIO QUE SE HIZO LOGIN
	V_OUT_MESS OUT VARCHAR2,			   -- MENSAJE DE SALIDA
	V_OUT_COD_MESS OUT NUMBER			   -- CODIGO DE MENSAJE
)
AS
	V_EXISTE NUMBER; 							-- VALIDA EXISTENCIA DEL USUARIO
	V_ULTIMO_LOG DATE; 							-- FECHA DE CREACION O CAMBIO DE CONTRASENA
	V_INTENTOS TAB_LOGIN_ACOMER.NUM_INTENTOS%TYPE; 	-- NUMERO DE INTENTOS DE LOGIN
	V_PASS TAB_LOGIN_ACOMER.CONTRAS_LOG%TYPE;		-- CONTRASENA REGISTRADA PARA EL USUAIRO
	V_ACTIVACION TAB_LOGIN_ACOMER.ID_ACTIVACION%TYPE;-- CODIGO DE ACTIVACION 
BEGIN
	BEGIN
		-- =============================================
		-- SE VALIDA QUE EL USUARIO SI EXISTA EN LA BD
		-- DE LO CONTRARIO SERA NOTIFICADO 
		SELECT GN.TERCOD
		INTO V_OUT_USER_ID
		FROM GEN0011 GN
		WHERE GN.TERCOD = V_IN_USER_ID
			AND ROWNUM =1;
	EXCEPTION 
		WHEN NO_DATA_FOUND THEN
			V_OUT_USER_ID := NULL;
			V_OUT_COD_MESS := -20001;
			V_OUT_MESS := 'El usuario no es valido o no existe';
	END;

	IF(V_OUT_USER_ID IS NOT NULL) THEN
		BEGIN
			-- =============================================
			-- SE VALIDA QUE EL USUARIO INGRESADO YA ESTA REGISTRADO
			-- EN USUARIOS DE LOGIN 
			SELECT COUNT(*)
			INTO V_EXISTE
			FROM TAB_LOGIN_ACOMER TLA
			WHERE TLA.USUARIO_LOG = FN_ENCRIPTAR_DATOS(V_OUT_USER_ID);

			IF(V_EXISTE > 0) THEN
				BEGIN
					SELECT MAX(UTL_MATCH.JARO_WINKLER_SIMILARITY(FN_DESENCRIPTAR_DATOS(CONTRAS_LOG),V_IN_USER_PASS))
					INTO V_EXISTE
					FROM TAB_HIST_LOGIN_aCOMER
					WHERE USUARIO_LOG = FN_ENCRIPTAR_DATOS(TRIM(V_IN_USER_ID))
						AND FEC_CREA_MOD BETWEEN SYSDATE - 180 AND SYSDATE;
				EXCEPTION
					WHEN NO_DATA_FOUND THEN
						V_EXISTE := 0;
					WHEN OTHERS THEN 
						RAISE_APPLICATION_ERROR (-20000, 'Error: '||SQLCODE||' '||SQLERRM);
				END;

				IF(V_EXISTE >= 95) THEN
					BEGIN
						V_OUT_USER_ID := V_IN_USER_ID;
						V_OUT_COD_MESS := 8;
						V_OUT_MESS := 'La clave ingresada coincide en un '||V_EXISTE||'% a alguna usada en los ultimos 6 mese, por favor digite una nueva';
					END;

				ELSE

					BEGIN
						UPDATE TAB_LOGIN_ACOMER
						SET CONTRAS_LOG = FN_ENCRIPTAR_DATOS(V_IN_USER_PASS),
							FEC_CREA_MOD = SYSDATE,
							NUM_INTENTOS = 0,
							ID_ACTIVACION = NULL
						WHERE USUARIO_LOG = FN_ENCRIPTAR_DATOS(V_OUT_USER_ID);
					EXCEPTION
						WHEN OTHERS THEN 
							RAISE_APPLICATION_ERROR (-20000, 'Error: '||SQLCODE||' '||SQLERRM);
					END;

					BEGIN
						V_OUT_USER_ID := V_IN_USER_ID;
						V_OUT_COD_MESS := 1;
						V_OUT_MESS := 'Acceso Correcto';
					END;
				END IF;

			ELSE

				BEGIN
					V_OUT_USER_ID := NULL;
					V_OUT_COD_MESS := -20001;
					V_OUT_MESS := 'El usuario ingresado no es valido o no existe';
				END;
			END IF;
		END;

	ELSE

		BEGIN
			V_OUT_USER_ID := NULL;
			V_OUT_COD_MESS := -20001;
			V_OUT_MESS := 'El usuario ingresado no es valido o no existe';
		END;
	END IF;
END;