CREATE OR REPLACE PROCEDURE SP_LOGIN_ACOMER
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_USER_ID IN GEN0011.TERCOD%TYPE, -- IDENTIFICADOR CON EL QUE EL USUARIO HACE LOGIN 
	V_IN_USER_PASS IN VARCHAR2,			 -- CONTRASENA DE ACCESO 
	V_IN_OPER IN VARCHAR2,				 -- OPERACION A REALIZAR (L - CONSULTA, C - INSERT, U - UPDATE, T - VALIDA TOKEN, - F - CREA CONTRA)
	V_IN_ACT_PASS IN VARCHAR2,			 -- CLAVE DE ACTIVACION O CREACION DE CONTRASENA
	V_OUT_USER_ID OUT GEN0011.TERCOD%TYPE, -- IDENTIFICACION DEL USUARIO QUE SE HIZO LOGIN
	V_OUT_MESS OUT VARCHAR2,			   -- MENSAJE DE SALIDA
	V_OUT_COD_MESS OUT NUMBER			   -- CODIGO DE MENSAJE
)
AS
	V_SP_USER_ID VARCHAR2(11);
	V_SP_MESS VARCHAR(100);
	V_SP_COD_MESS NUMBER;
BEGIN
	
	CASE V_IN_OPER
		-- =============================================
		-- OPERACION C
		WHEN 'C' THEN 
			BEGIN
				SP_LOGIN_ACOMER_OPERACION_C(V_IN_USER_ID,V_SP_USER_ID,V_SP_MESS,V_SP_COD_MESS);
				V_OUT_USER_ID := V_SP_USER_ID;
				V_OUT_MESS := V_SP_MESS;
				V_OUT_COD_MESS := V_SP_COD_MESS;
			END;
		-- =============================================
		-- OPERACION F
		WHEN 'F' THEN
			BEGIN
				SP_LOGIN_ACOMER_OPERACION_F(V_IN_USER_ID,V_IN_USER_PASS,V_SP_USER_ID,V_SP_MESS,V_SP_COD_MESS)
				V_OUT_USER_ID := V_SP_USER_ID;
				V_OUT_MESS := V_SP_MESS;
				V_OUT_COD_MESS := V_SP_COD_MESS;
			END;
		-- =============================================
		-- OPERACION L
		WHEN 'L' THEN
			BEGIN
				SP_LOGIN_ACOMER_OPERACION_L(V_IN_USER_ID,V_IN_USER_PASS,V_IN_ACT_PASS,V_SP_USER_ID,V_SP_MESS,V_SP_COD_MESS);
				V_OUT_USER_ID := V_SP_USER_ID;
				V_OUT_MESS := V_SP_MESS;
				V_OUT_COD_MESS := V_SP_COD_MESS;
			END;
		-- =============================================
		-- OPERACION T
		WHEN 'T' THEN
			BEGIN
				SP_LOGIN_ACOMER_OPERACION_T(V_IN_USER_ID,V_IN_ACT_PASS,V_SP_USER_ID,V_SP_MESS,V_SP_COD_MESS);
				V_OUT_USER_ID := V_SP_USER_ID;
				V_OUT_MESS := V_SP_MESS;
				V_OUT_COD_MESS := V_SP_COD_MESS;
			END;
		-- =============================================
		-- OPERACION U
		WHEN 'U' THEN
			BEGIN
				SP_LOGIN_ACOMER_OPERACION_U(V_IN_USER_ID,V_SP_USER_ID,V_SP_MESS,V_SP_COD_MESS);
				V_OUT_USER_ID := V_SP_USER_ID;
				V_OUT_MESS := V_SP_MESS;
				V_OUT_COD_MESS := V_SP_COD_MESS;
			END;
	END CASE;
END;