CREATE OR REPLACE PROCEDURE H3i_SP_DIAG_MAYOR_COSTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINI IN DATE,
	V_FECHAFIN IN DATE,
	V_FUERZA IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)

AS
BEGIN
	OPEN CV_1 FOR
		SELECT DIAGNOSTICO_CODIGO, 
			DIAGNOSTICO_NOMBRE, 
			COUNT(DISTINCT COD_AUDI_DOCUM) NUMERO_DE_FORMULAS,
			COUNT(AUTO_DOCU_MEDI_ADM) NUMERO_ITEM,
			ROUND(SUM(CANTIDAD_DESPACHADA_ADM), 2) NUMERO_UNIDADES,
			COUNT(DISTINCT AFILIADO_CODIGO) PACIENTES_ATENDIDOS,
			ROUND(TO_NUMBER(SUM(VALOR_TOTAL_ITEM_ADM)), 2) COSTO_TOTAL_FORMULA,
			ROUND(TO_NUMBER(SUM(VALOR_TOTAL_ITEM_ADM)/ COUNT(COD_AUDI_DOCUM)), 2) VALOR_PROMEDIO_FORMULA
		FROM AUDITAR_DOCUMENTO, 
			AUDITAR_ASIGNACION_DOCUM,
			AUDITAR_DOCU_MEDICAMENTO
		WHERE COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
			AND COD_AUDI_DOCUM = COD_AUDI_DOCUM_ADM
			AND FECHA_ASIG_AAD BETWEEN V_fechaIni AND V_fechaFin
			AND FUERZA_CODIGO = V_FUERZA
			AND ROWNUM <= 1
		GROUP BY DIAGNOSTICO_CODIGO, DIAGNOSTICO_NOMBRE
		ORDER BY COSTO_TOTAL_FORMULA DESC;

		
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

		