CREATE OR REPLACE PROCEDURE H3i_SP_PAC_MAYOR_COSTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINI IN DATE,
	V_FECHAFIN IN DATE,
	V_FUERZA IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)


AS
	V_DOCPAC VARCHAR2(255);
	V_TOTAL_RANGO NUMBER;
	V_MEDICAMENTOS VARCHAR(32767) := '';
	V_DIAGNOSTICOS VARCHAR(32767) := '';
	V_FORMULAS NUMBER ;
	V_COUNTMEDICAMENTOS NUMBER;
	V_DESPACHADO NUMBER; 

BEGIN
	----------------------------------------------------------------
	SELECT PAC.AFILIADO_CODIGO, PAC.SUMATORIA
	INTO V_DOCPAC, V_TOTAL_RANGO
	FROM (	SELECT AFILIADO_CODIGO, SUMATORIA
			FROM (	SELECT AFILIADO_CODIGO ,
						SUM(ADM.VALOR_TOTAL_ITEM_ADM) SUMATORIA
					FROM AUDITAR_DOCUMENTO AD , AUDITAR_ASIGNACION_DOCUM AAD, AUDITAR_DOCU_MEDICAMENTO ADM
					WHERE AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
						AND AD.COD_AUDI_DOCUM = ADM.COD_AUDI_DOCUM_ADM
						AND AAD.FECHA_ASIG_AAD BETWEEN V_FECHAINI AND V_FECHAFIN
						AND AD.FUERZA_CODIGO = V_FUERZA
					GROUP BY AFILIADO_CODIGO
					ORDER BY SUMATORIA DESC)
			WHERE ROWNUM <= 1) PAC;

	----------------------------------------------------------------
	SELECT AD.COD_AUDI_DOCUM DOCUMENTO,
	AD.ESM_ADSCRITO_NOMBRE,
	AD.AFILIADO_NOMBRE,
	AD.DIAGNOSTICO_NOMBRE,
	AD.NUMERO_FORMULA,
	ADM.GENERICO_NOMBRE_ADM,
	ADM.CANTIDAD_DESPACHADA_ADM,
	ADM.PRECIO_UNITARIO
	INTO TMP_DATOS    																------- TEMPORAL DE SQL SERVER TOCA CAMBIAR
	FROM AUDITAR_DOCU_MEDICAMENTO ADM, AUDITAR_DOCUMENTO AD
	WHERE AD.COD_AUDI_DOCUM = ADM.COD_AUDI_DOCUM_ADM
		AND AD.AFILIADO_CODIGO = V_DOCPAC
		AND AD.FUERZA_CODIGO = V_FUERZA;

	----------------------------------------------------------------
	SELECT  CONCAT ( CONCAT(V_MEDICAMENTOS,(CASE V_MEDICAMENTOS 
												WHEN '' 
													THEN '' 
												ELSE ' - ' 
											END)) , GENERICO_NOMBRE_ADM) 
	INTO V_MEDICAMENTOS 
	FROM TMP_DATOS;   																------- TEMPORAL DE SQL SERVER TOCA CAMBIAR

	----------------------------------------------------------------
	SELECT CONCAT ( CONCAT(V_DIAGNOSTICOS, (CASE V_DIAGNOSTICOS 
												WHEN '' 
													THEN '' 
												ELSE ' - ' 
											END)) , DIAGNOSTICO_NOMBRE) 
	INTO  V_DIAGNOSTICOS
	FROM TMP_DATOS;   																------- TEMPORAL DE SQL SERVER TOCA CAMBIAR

	----------------------------------------------------------------
	SELECT  COUNT(FORMULAS.DOCUMENTO)
	INTO V_FORMULAS
	FROM (	SELECT DISTINCT(DOCUMENTO) 
			FROM TMP_DATOS) FORMULAS;												------- TEMPORAL DE SQL SERVER TOCA CAMBIAR

	----------------------------------------------------------------
	SELECT COUNT(MEDI.GENERICO_NOMBRE_ADM)
	INTO  V_COUNTMEDICAMENTOS
	FROM (	SELECT (GENERICO_NOMBRE_ADM) 
			FROM TMP_DATOS) MEDI;												    ------- TEMPORAL DE SQL SERVER TOCA CAMBIAR

	----------------------------------------------------------------
	SELECT DISTINCT SUM(CANTIDAD_DESPACHADA_ADM) 
	INTO DESPACHADO
	FROM TMP_DATOS;											    					------- TEMPORAL DE SQL SERVER TOCA CAMBIAR

	----------------------------------------------------------------
	OPEN CV_1 FOR
		SELECT ESM_ADSCRITO_NOMBRE,
			AFILIADO_NOMBRE,
			V_DIAGNOSTICOS DIAGNOSTICOS,
			V_FORMULAS NUMERO_FORMULAS,
			V_MEDICAMENTOS MEDICAMENTOS,
			V_COUNTMEDICAMENTOS CANTIDAD_MEDICAMENTOS,
			CONCAT('', V_DESPACHADO) TOTAL_DESPACHADO,
			CONCAT('$ ' ,(ROUND(SUM(PRECIO_UNITARIO), 2)))VALOR_UNITARIO,
			CONCAT('$ ' , (TO_NUMBER(V_DESPACHADO) / TO_NUMBER(V_FORMULAS))) PROMEDIO_FORMULA, 
			CONCAT(ROUND(((TO_NUMBER(V_DESPACHADO) / TO_NUMBER(V_TOTAL_RANGO)) * 100) ,2), ' %') PORCENTAJE_CONSUMO
		FROM TMP_DATOS
		WHERE ROWNUM <= 1
		GROUP BY ESM_ADSCRITO_NOMBRE, AFILIADO_NOMBRE;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;