CREATE OR REPLACE PROCEDURE H3i_SP_REPORTE_CONSULTAS_ESPE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_FECHA_INICIAL IN DATE,
    v_FECHA_FINAL IN DATE,
    cv_1 OUT SYS_REFCURSOR
)
AS
  
BEGIN

    OPEN  cv_1 FOR
        SELECT NO_NOMB_ESP ,
            TO_CHAR(FE_FECH_HICL, 'YYYY') AÑO  ,
            TO_CHAR(FE_FECH_HICL, 'MM') MES  ,
            COUNT(NU_NUME_MOVI)  CANTIDAD  
        FROM HISTORIACLINICA 
        INNER JOIN LABORATORIO    
            ON NU_NUME_LABO = NU_NUME_LABO_HICL
        INNER JOIN MOVI_CARGOS    
            ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
        INNER JOIN ESPECIALIDADES    
            ON CD_CODI_ESP = CD_CODI_ESP_LABO
        WHERE  NU_TIPO_MOVI = 4
            AND FE_FECH_HICL BETWEEN v_FECHA_INICIAL AND v_FECHA_FINAL
        GROUP BY NO_NOMB_ESP, TO_CHAR(FE_FECH_HICL,'YYYY'), TO_CHAR(FE_FECH_HICL,'MM')
        ORDER BY NO_NOMB_ESP ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;