CREATE OR REPLACE PROCEDURE H3i_SP_INDI_PAC_MAY_COS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHAINI IN DATE,
	V_FECHAFIN IN DATE,
	CV_1 OUT SYS_REFCURSOR
)

AS
 	V_EJERCITO NUMBER;
	V_FUERZAAEREA NUMBER;
	V_ARMADA NUMBER;
BEGIN
	-----------------------------------------------------------
	SELECT VALOR_TOTAL_ITEM_ADM
	INTO V_EJERCITO
	FROM (	SELECT SUM(ADM.VALOR_TOTAL_ITEM_ADM) VALOR_TOTAL_ITEM_ADM			
			FROM AUDITAR_DOCUMENTO AD , AUDITAR_ASIGNACION_DOCUM AAD, AUDITAR_DOCU_MEDICAMENTO ADM
			WHERE AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
				AND AD.COD_AUDI_DOCUM = ADM.COD_AUDI_DOCUM_ADM
				AND AAD.FECHA_ASIG_AAD BETWEEN V_FECHAINI AND V_FECHAFIN
				AND AD.FUERZA_CODIGO = 70000
			ORDER BY SUM(ADM.VALOR_TOTAL_ITEM_ADM) DESC)
	WHERE ROWNUM <= 1;

	-----------------------------------------------------------
	SELECT VALOR_TOTAL_ITEM_ADM
	INTO V_FUERZAAEREA
	FROM (	SELECT SUM(ADM.VALOR_TOTAL_ITEM_ADM) VALOR_TOTAL_ITEM_ADM
			FROM AUDITAR_DOCUMENTO AD , AUDITAR_ASIGNACION_DOCUM AAD, AUDITAR_DOCU_MEDICAMENTO ADM
			WHERE AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
				AND AD.COD_AUDI_DOCUM = ADM.COD_AUDI_DOCUM_ADM
				AND AAD.FECHA_ASIG_AAD BETWEEN V_FECHAINI AND V_FECHAFIN
				AND AD.FUERZA_CODIGO = 50000
				ORDER BY SUM(ADM.VALOR_TOTAL_ITEM_ADM) DESC)
	WHERE ROWNUM <= 1;

	-----------------------------------------------------------
	SELECT VALOR_TOTAL_ITEM_ADM
	INTO V_ARMADA
	FROM (	SELECT SUM(ADM.VALOR_TOTAL_ITEM_ADM) VALOR_TOTAL_ITEM_ADM
			FROM AUDITAR_DOCUMENTO AD , AUDITAR_ASIGNACION_DOCUM AAD, AUDITAR_DOCU_MEDICAMENTO ADM
			WHERE AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
				AND AD.COD_AUDI_DOCUM = ADM.COD_AUDI_DOCUM_ADM
				AND AAD.FECHA_ASIG_AAD BETWEEN V_FECHAINI AND V_FECHAFIN
				AND AD.FUERZA_CODIGO = 60000
			order by SUM(ADM.VALOR_TOTAL_ITEM_ADM) desc)
	WHERE ROWNUM <= 1;

	-----------------------------------------------------------
	OPEN CV_1 FOR
		SELECT V_EJERCITO, V_FUERZAAEREA, V_ARMADA
		FROM DUAL;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;