CREATE OR REPLACE PROCEDURE H3i_SP_REP_PRES_X_ESTUDIANTE
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_DOCU_MED IN VARCHAR2,
  v_FEC_PRE_INI IN DATE,
  v_FEC_PRE_FIN IN DATE,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN  cv_1 FOR
        SELECT PRES_MOVIMIENTO.CD_CODI_MED_PM ,
            ( SELECT NO_NOMB_MED 
              FROM MEDICOS 
              WHERE  CD_CODI_MED = PRES_MOVIMIENTO.CD_CODI_MED_PM 
                  AND ROWNUM <= 1 ) NOMBREMEDI  ,
            PRES_ELEMENTOS.DESCRIPCION DESCRIPCIONELE  ,
            PRES_TIP_ELEMENTO.DESCRIPCION DESCRIPCIONTIP  ,
            PRES_ESTADOS.DES_ESTADO ,
            PRES_MOVIMIENTO.CANTIDAD ,
            PRES_MOVIMIENTO.FEC_PRESTAMO ,
            NVL(PRES_MOVIMIENTO.FEC_DEVOLUCION, '01/01/1900') FEC_DEVOLUCION  ,
            PRES_ELEMENTOS.ID_ELEMENTO 
        FROM ((( PRES_MOVIMIENTO PRES_MOVIMIENTO
        INNER JOIN PRES_ESTADOS PRES_ESTADOS   
            ON ( PRES_MOVIMIENTO.ID_ESTADO_PM = PRES_ESTADOS.ID_ESTADO )) 
        INNER JOIN PRES_ELEMENTOS PRES_ELEMENTOS   
            ON ( PRES_MOVIMIENTO.ID_ELEMENTO_PM = PRES_ELEMENTOS.ID_ELEMENTO )) 
        INNER JOIN PRES_TIP_ELEMENTO PRES_TIP_ELEMENTO   
            ON ( PRES_ELEMENTOS.ID_TIP_ELEMENTO = PRES_TIP_ELEMENTO.ID_TIP_ELEMENTO )) 
        WHERE  PRES_MOVIMIENTO.CD_CODI_MED_PM = v_NU_DOCU_MED
            AND PRES_MOVIMIENTO.FEC_PRESTAMO <= v_FEC_PRE_FIN
            AND PRES_MOVIMIENTO.FEC_PRESTAMO >= v_FEC_PRE_INI ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;