CREATE OR REPLACE PROCEDURE H3i_SP_INF_CUENTAS_CBR
(
    v_FECH_INI IN DATE,
    v_FECH_FIN IN DATE,
    v_IDADSCRITO IN NUMBER,
    cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    IF v_IDADSCRITO > 0 THEN
    
        BEGIN
            OPEN  cv_1 FOR
                SELECT FACTURA_ADSCRITO.NU_NUME_FAAD NOFACTURA  ,
                    ADSCRITOS.CD_CODI_ADSC NIT  ,
                    ADSCRITOS.DE_NOMB_ADSC RAZON  ,
                    FACTURA_ADSCRITO.FE_RECEP_FAAD FECHFACT  ,
                    FACTURA_ADSCRITO.VL_TOTAL_FAAD MONTOFACT  ,
                    SUM(DETALLE_GLOSA3i.NU_VALOR_DEGL)  VALORGLO  ,
                    SUM(DETALLE_GLOSA3i.NU_VALORACEPTADO_DEGL)  VALORACEP  ,
                    (FACTURA_ADSCRITO.VL_TOTAL_FAAD - SUM(DETALLE_GLOSA3i.NU_VALORACEPTADO_DEGL)) NETO  
                FROM ( ( DETALLE_GLOSA3i DETALLE_GLOSA3i
                INNER JOIN GLOSA3i GLOSA3i   
                    ON ( DETALLE_GLOSA3i.NU_AUTO_GLOS_DEGL = GLOSA3i.NU_AUTO_GLOS )) 
                INNER JOIN FACTURA_ADSCRITO FACTURA_ADSCRITO   
                    ON ( FACTURA_ADSCRITO.NU_NUME_FAAD = DETALLE_GLOSA3i.NU_NUME_FACU_DEGL )) 
                INNER JOIN ADSCRITOS ADSCRITOS   
                    ON ( FACTURA_ADSCRITO.NU_CONSE_ADSC_FAAD = ADSCRITOS.NU_CONSE_ADSC )
                GROUP BY FACTURA_ADSCRITO.NU_NUME_FAAD,ADSCRITOS.CD_CODI_ADSC,
                    ADSCRITOS.DE_NOMB_ADSC,FACTURA_ADSCRITO.FE_RECEP_FAAD,
                    FACTURA_ADSCRITO.VL_TOTAL_FAAD ;
        END;

    ELSE
   
        BEGIN
            OPEN  cv_1 FOR
                SELECT FACTURA_ADSCRITO.NU_NUME_FAAD NOFACTURA  ,
                    ADSCRITOS.CD_CODI_ADSC NIT  ,
                    ADSCRITOS.DE_NOMB_ADSC RAZON  ,
                    FACTURA_ADSCRITO.FE_RECEP_FAAD FECHFACT  ,
                    FACTURA_ADSCRITO.VL_TOTAL_FAAD MONTOFACT  ,
                    SUM(DETALLE_GLOSA3i.NU_VALOR_DEGL)  VALORGLO  ,
                    SUM(DETALLE_GLOSA3i.NU_VALORACEPTADO_DEGL)  VALORACEP  ,
                    (FACTURA_ADSCRITO.VL_TOTAL_FAAD - SUM(DETALLE_GLOSA3i.NU_VALORACEPTADO_DEGL) ) NETO  
                FROM ((DETALLE_GLOSA3i DETALLE_GLOSA3i
                INNER JOIN GLOSA3i GLOSA3i   
                    ON ( DETALLE_GLOSA3i.NU_AUTO_GLOS_DEGL = GLOSA3i.NU_AUTO_GLOS )) 
                INNER JOIN FACTURA_ADSCRITO FACTURA_ADSCRITO   
                    ON ( FACTURA_ADSCRITO.NU_NUME_FAAD = DETALLE_GLOSA3i.NU_NUME_FACU_DEGL )) 
                INNER JOIN ADSCRITOS ADSCRITOS   
                    ON ( FACTURA_ADSCRITO.NU_CONSE_ADSC_FAAD = ADSCRITOS.NU_CONSE_ADSC )
                WHERE  GLOSA3i.FE_GENERA_GLOS >= v_FECH_INI
                    AND GLOSA3i.FE_GENERA_GLOS <= v_FECH_FIN
                GROUP BY FACTURA_ADSCRITO.NU_NUME_FAAD,ADSCRITOS.CD_CODI_ADSC,
                    ADSCRITOS.DE_NOMB_ADSC,FACTURA_ADSCRITO.FE_RECEP_FAAD,
                    FACTURA_ADSCRITO.VL_TOTAL_FAAD ;   
        END;
        
    END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;