CREATE OR REPLACE PROCEDURE H3i_SP_LISTAR_MOTIVO_IDGLOSA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO_GLOSA IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    OPEN  cv_1 FOR
        SELECT DISTINCT (TX_CODIGO_GEGL_REG + TX_CODIGO_ESGL_REG) CODIGO  ,
            NU_AUTO_GLOS_DEGL ,
            TX_CODIGO_GEGL_REG ,
            TX_CODIGO_ESGL_REG ,
            (TX_NOMBRE_GEGL || ', ' || TX_NOMBRE_ESGL) NOMBRE  
        FROM R_ESG_GEG R
        INNER JOIN GENERAL_GLOSA3i G   
            ON G.TX_CODIGO_GEGL = R.TX_CODIGO_GEGL_REG
        INNER JOIN ESPECIFICO_GLOSA3i E   
            ON E.TX_CODIGO_ESGL = R.TX_CODIGO_ESGL_REG
        INNER JOIN DETALLE_GLOSA3i DG   
            ON DG.TX_CODIGO_GEGL_DEGL = G.TX_CODIGO_GEGL
        WHERE  DG.TX_CODIGO_ESGL_DEGL = E.TX_CODIGO_ESGL
            AND DG.NU_AUTO_GLOS_DEGL = v_CODIGO_GLOSA ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;