CREATE OR REPLACE PROCEDURE H3i_SP_INSER_PRES_MOVIMIENTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
    v_CD_CODI_MED IN VARCHAR2,
    v_ID_ELEMENTO IN NUMBER,
    v_CANTIDAD IN NUMBER,
    v_FEC_PRESTAMO IN DATE,
    v_FEC_DEVOLUCION IN DATE,
    v_ID_ESTADO IN NUMBER,
    cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

    INSERT INTO PRES_MOVIMIENTO( 
        CD_CODI_MED_PM, ID_ELEMENTO_PM, 
        CANTIDAD, FEC_PRESTAMO, 
        FEC_DEVOLUCION, ID_ESTADO_PM )
    VALUES( 
        v_CD_CODI_MED, v_ID_ELEMENTO, 
        v_CANTIDAD, TO_DATE(v_FEC_PRESTAMO,'dd/mm/yyyy'), 
        TO_DATE(v_FEC_DEVOLUCION,'dd/mm/yyyy'), v_ID_ESTADO );
   
   OPEN  cv_1 FOR
      SELECT NU_AUTO_PRES_MOV 
      FROM PRES_MOVIMIENTO
      WHERE NU_AUTO_PRES_MOV = (SELECT MAX(NU_AUTO_PRES_MOV) FROM PRES_MOVIMIENTO);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;