CREATE OR REPLACE PROCEDURE H3i_SP_CREA_ITEMREPUESTA_GL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_AUTO_REGL IN NUMBER,
  v_NU_AUTO_DEGL IN NUMBER,
  v_CONF_RES_RIGL IN VARCHAR2,
  v_TX_OBS_RIGL IN VARCHAR2,
  v_TIP_RES_RIGL IN NUMBER,
  v_VAL_ACEP_RIGL IN NUMBER
)
AS

BEGIN

   	INSERT INTO ITEM_RESPUESTA_GLOSA3i( 
   		NU_AUTO_REGL, NU_AUTO_DEGL, 
   		CONF_RES_RIGL, TX_OBS_RIGL, 
   		TIP_RES_RIGL, VAL_ACEP_RIGL )
    VALUES ( 
    	v_NU_AUTO_REGL, v_NU_AUTO_DEGL, 
    	v_CONF_RES_RIGL, v_TX_OBS_RIGL, 
    	v_TIP_RES_RIGL, v_VAL_ACEP_RIGL );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;