---CREAR LA TABLA
CREATE TABLE FICHA_NOTIFICACION(
	NU_AUTO_FINA NUMBER(18,0),
	TX_CODIGO_FINA VARCHAR2(20),
	TX_TITULO_FINA VARCHAR2(40),
	NU_ESTA_FINA NUMBER(3)	
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--PRIMARY KEY
CREATE UNIQUE INDEX PK_FICHA_NOTIFICACION ON FICHA_NOTIFICACION
(NU_AUTO_FINA)
LOGGING
NOPARALLEL;

--CONSTRAINT PRIMARY KEY
ALTER TABLE FICHA_NOTIFICACION ADD (
  CONSTRAINT PK_FICHA_NOTIFICACION
 PRIMARY KEY
 (NU_AUTO_FINA));
