---CREAR LA TABLA
CREATE TABLE ITEM_BUSQUEDAACTIVA(
	NU_ID_ITBU NUMBER(18,0),
	TX_TITULO_ITBU VARCHAR2(4000),
	NU_ESTA_ITBU NUMBER(3),
	TX_TITSALTO_ITBU VARCHAR2(20),
	NU_SALTO_ITBU NUMBER(3)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--PRIMARY KEY
CREATE UNIQUE INDEX PK_ITEM_BUSQUEDAACTIVA ON ITEM_BUSQUEDAACTIVA
(NU_ID_ITBU)
LOGGING
NOPARALLEL;

--CONSTRAINT PRIMARY KEY
ALTER TABLE ITEM_BUSQUEDAACTIVA ADD (
  CONSTRAINT PK_ITEM_BUSQUEDAACTIVA
 PRIMARY KEY
 (NU_ID_ITBU));
