---CREAR LA TABLA
 CREATE TABLE R_FINA_DIAG
(
  NU_AUTO_FINA_RFD  NUMBER(18,0) NOT NULL,
  CD_CODI_DIAG_RFD  VARCHAR2(20) NOT NULL 
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--PRIMARY KEY
CREATE UNIQUE INDEX PK_R_FINA_DIAG ON R_FINA_DIAG
(NU_AUTO_FINA_RFD, CD_CODI_DIAG_RFD)
LOGGING
NOPARALLEL;

--CONSTRAINT PRIMARY KEY
ALTER TABLE R_FINA_DIAG ADD (
  CONSTRAINT PK_R_FINA_DIAG
 PRIMARY KEY
 (NU_AUTO_FINA_RFD, CD_CODI_DIAG_RFD));

