---CREAR LA TABLA
 CREATE TABLE R_ITBU_DIAG
(
  NU_ID_ITBU_RID  NUMBER(18,0) NOT NULL,
  CD_CODI_DIAG_RID  VARCHAR2(40) NOT NULL 
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--PRIMARY KEY
CREATE UNIQUE INDEX PK_R_ITBU_DIAG ON R_ITBU_DIAG
(NU_ID_ITBU_RID, CD_CODI_DIAG_RID)
LOGGING
NOPARALLEL;

--CONSTRAINT PRIMARY KEY
ALTER TABLE R_ITBU_DIAG ADD (
  CONSTRAINT PK_R_ITBU_DIAG
 PRIMARY KEY
 (NU_ID_ITBU_RID, CD_CODI_DIAG_RID));

