CREATE OR REPLACE TRIGGER TG_FACTURA_CONTADO_ANUL 
AFTER UPDATE 
ON FACTURAS_CONTADO
FOR EACH ROW
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
DECLARE
	V_NUM_FACO NUMBER;
	V_NUM_MOVI NUMBER;
	V_ESTADO VARCHAR2(1);
	V_NUM_PAQUETE NUMBER;
BEGIN

	IF (:OLD.NU_ESTA_FACO <> :NEW.NU_ESTA_FACO) THEN
		BEGIN 
     		SELECT :NEW.NU_NUME_FACO, :NEW.NU_ESTA_FACO
     		INTO V_NUM_FACO, V_ESTADO
     		FROM DUAL;

	      	IF (V_ESTADO='0') THEN
	      		DECLARE
	      			CURSOR C_MOVI IS
	      				SELECT NU_NUME_MOVI, NU_NUME_PAQU_MOVI
						FROM MOVI_CARGOS
						WHERE NU_NUME_FACO_MOVI = V_NUM_FACO;
	     		BEGIN  
					OPEN C_MOVI;
					FETCH C_MOVI INTO V_NUM_MOVI, V_NUM_PAQUETE;

					WHILE C_MOVI%FOUND
					LOOP
						BEGIN
							INSERT INTO FACTURAS_ANULADAS (
								NU_NUME_MOVI_FACA ,NU_NUME_FAC__FACA, 
								NU_NUME_PAQU_FACA ) 
							VALUES(
								V_NUM_MOVI, V_NUM_FACO, 
								V_NUM_PAQUETE);

							FETCH C_MOVI INTO V_NUM_MOVI, V_NUM_PAQUETE ;
						END;
					END LOOP; 
					CLOSE C_MOVI;
	    		END;
	    	END IF;
		END;
	END IF;
END;