CREATE OR REPLACE TRIGGER TG_VAL_FAC_MOVI  
AFTER UPDATE
ON MOVI_CARGOS
FOR EACH ROW
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- ============================================= 
DECLARE
	V_NUME_MOVI NUMBER; 
	V_NUME_FAC NUMBER;
	V_ESTA_MOVI NUMBER;
BEGIN
	IF (:OLD.NU_ESTA_MOVI <> :NEW.NU_ESTA_MOVI) THEN
		DECLARE
			CURSOR CR IS 
				SELECT :NEW.NU_NUME_MOVI 
				FROM DUAL 
					WHERE :NEW.NU_ESTA_MOVI <> 2;
		BEGIN		
			OPEN  CR;
			FETCH CR INTO V_NUME_MOVI;
			
			WHILE CR%FOUND
			LOOP
				BEGIN
				
					SELECT  :OLD.NU_NUME_FAC_MOVI 
					INTO V_NUME_FAC
					FROM DUAL
					WHERE :OLD.NU_NUME_MOVI = V_NUME_MOVI;

					IF (V_NUME_FAC<>0) THEN
						BEGIN
							RAISE_APPLICATION_ERROR(16,'NO SE PUEDE ANULAR EL CARGO '||V_NUME_MOVI||' POR QUE YA TIENE ASIGNADA LA FACTURA '||V_NUME_FAC);
						  	ROLLBACK;
						END;
					END IF;

					FETCH CR INTO V_NUME_MOVI;

				END;
			END LOOP;
			CLOSE CR;
		END;
	END IF;
END;