CREATE OR REPLACE PROCEDURE H3i_SP_CREAR_HIST_SCOP_OBS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HS_HSO IN NUMBER,
  v_NU_NUME_MOVI_HSO IN NUMBER,
  v_NU_HIST_PAC_HSO IN VARCHAR2,
  v_FE_FECH_INGR_HSO IN DATE,
  v_DE_OBSE_HSO IN VARCHAR2,
  v_NU_TIPS_HSO IN NUMBER,
  v_NU_ESTA_HSO IN NUMBER
)
AS

BEGIN

   INSERT INTO HIST_SCOP_OBS
     ( NU_NUME_HS_HSO, NU_NUME_MOVI_HSO, NU_HIST_PAC_HSO, FE_FECH_INGR_HSO, DE_OBSE_HSO, NU_TIPS_HSO, NU_ESTA_HSO )
     VALUES ( v_NU_NUME_HS_HSO, v_NU_NUME_MOVI_HSO, v_NU_HIST_PAC_HSO, v_FE_FECH_INGR_HSO, v_DE_OBSE_HSO, v_NU_TIPS_HSO, v_NU_ESTA_HSO );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;