CREATE OR REPLACE PROCEDURE H3i_SP_PYP_GUARDA_PARAM_ACTIV
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CODIGO IN NUMBER,
  v_NOMBRE IN VARCHAR2,
  v_DESCRIPCION IN VARCHAR2
)
AS

BEGIN

   IF ( v_CODIGO <> 0 ) THEN
    
   BEGIN
      UPDATE PYP_ACTIV_INFO_OBLIG
         SET TX_NOMBRE_PYPACTPARAM = v_NOMBRE,
             TX_DESCRIP_PYPACTPARAM = v_DESCRIPCION
       WHERE  NU_AUTO_PYPACTPARAM = v_CODIGO;
   
   END;
   ELSE
   
   BEGIN
      INSERT INTO PYP_ACTIV_INFO_OBLIG
        ( TX_NOMBRE_PYPACTPARAM, TX_DESCRIP_PYPACTPARAM )
        VALUES ( v_NOMBRE, v_DESCRIPCION );
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;