CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_R_PLANTILLA_HIST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_PLHI_R IN NUMBER,
  v_NU_FINA_PLHI IN NUMBER,
  v_NU_SERV_PLHI IN VARCHAR2,
  v_NU_GECA_PLHI IN NUMBER,
  v_NU_PRCO_PLHI IN VARCHAR2,
  v_NU_VICA_PLHI IN NUMBER,
  v_NU_GENE_PLHI IN NUMBER,
  v_NU_REDI_PLHI IN NUMBER,
  v_NU_REDF_PLHI IN NUMBER,
  v_NU_CGES_PLHI IN NUMBER,
  v_NU_MODI_PLHI IN NUMBER,
  v_NU_TIEDI_PLHI IN NUMBER,
  v_NU_TIEDF_PLHI IN NUMBER
)
AS

BEGIN

    INSERT INTO R_PLANTILLA_HIST( 
        NU_NUME_PLHI_R, NU_FINA_PLHI, 
        NU_SERV_PLHI, NU_GECA_PLHI, 
        NU_PRCO_PLHI, NU_VICA_PLHI, 
        NU_GENE_PLHI, NU_REDI_PLHI, 
        NU_REDF_PLHI, NU_CGES_PLHI, 
        NU_MODI_PLHI, NU_TIEDI_PLHI, 
        NU_TIEDF_PLHI)
    VALUES( 
        v_NU_NUME_PLHI_R, v_NU_FINA_PLHI, 
        v_NU_SERV_PLHI, v_NU_GECA_PLHI, 
        v_NU_PRCO_PLHI, v_NU_VICA_PLHI, 
        v_NU_GENE_PLHI, v_NU_REDI_PLHI, 
        v_NU_REDF_PLHI, v_NU_CGES_PLHI, 
        v_NU_MODI_PLHI, v_NU_TIEDI_PLHI, 
        v_NU_TIEDF_PLHI);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;