CREATE OR REPLACE PROCEDURE H3i_SP_RELA_PLANT_INS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_PLANTILLA_A IN NUMBER,
  v_PLANTILLA_B IN NUMBER,
  v_IDCONCEPTO_A IN NUMBER,
  v_IDCONCEPTO_B IN NUMBER,
  v_No_ORDEN_CONCEPTO_A IN NUMBER,
  v_No_ORDEN_CONCEPTO_b IN NUMBER
)
AS

BEGIN

   	INSERT INTO RELACION_PLANTILLA( 
   		NU_NUME_PLHI_A_REPA, NU_NUME_PLHI_B_REPA, 
   		NU_NUME_COHI_A_REPA, NU_NUME_COHI_B_REPA, 
   		NU_INDI_RPC_A_REPA, NU_INDI_RPC_B_REPA )
    VALUES ( 
    	v_PLANTILLA_A, v_PLANTILLA_B, 
    	v_IDCONCEPTO_A, v_IDCONCEPTO_B, 
    	v_No_ORDEN_CONCEPTO_A, v_No_ORDEN_CONCEPTO_B );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;