CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_VALID_1_HIST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_COHI_VAHI1 IN NUMBER,
  v_NU_NUME_PLHI_VAHI1 IN NUMBER,
  v_NU_APLI_VAHI1 IN NUMBER,--6
  v_NU_OBLI_VAHI1 IN NUMBER,--1
  v_NU_EPIC_VAHI1 IN NUMBER,
  v_NU_ANTE_VAHI1 IN NUMBER,--4
  v_NU_DECI_VAHI1 IN NUMBER,--5
  v_DE_TEMIN_VAHI1 IN VARCHAR2,--2
  v_DE_TEMAX_VAHI1 IN VARCHAR2--3
)
AS

BEGIN

   INSERT INTO VALCONC_HIST1
     ( NU_NUME_COHI_VAHI1, NU_NUME_PLHI_VAHI1, NU_APLI_VAHI1, NU_OBLI_VAHI1, NU_EPIC_VAHI1, NU_ANTE_VAHI1, NU_DECI_VAHI1, DE_TEMIN_VAHI1, DE_TEMAX_VAHI1 )
     VALUES ( v_NU_NUME_COHI_VAHI1, v_NU_NUME_PLHI_VAHI1, v_NU_APLI_VAHI1, v_NU_OBLI_VAHI1, v_NU_EPIC_VAHI1, v_NU_ANTE_VAHI1, v_NU_DECI_VAHI1, v_DE_TEMIN_VAHI1, v_DE_TEMAX_VAHI1 );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;