CREATE OR REPLACE PROCEDURE H3i_SP_GUARDA_CONCEPTO_PLANTIL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_TIPO_CONCEPTO IN NUMBER,
  v_ACTUALIZAR IN NUMBER,
  /* VARIABLES PARA GRUPOS */
  v_NU_NUME_PLHI IN NUMBER,
  v_NU_NUME_GRHI IN NUMBER,
  v_NU_INDI_ORDEN IN NUMBER,
  v_NU_INGR_PADRE IN NUMBER,
  v_NU_NUGR_RPG IN NUMBER,
  v_NU_TOP IN NUMBER,
  v_NU_LEFT IN NUMBER,
  v_NU_ALTO IN NUMBER,
  v_NU_ANCHO IN NUMBER,
  v_NU_INDIDEP IN NUMBER,
  v_NU_INVACTASO IN NUMBER,
  v_TX_BORDES IN VARCHAR2 DEFAULT NULL ,
  v_C0LOR_FONDO IN VARCHAR2,
  v_COLOR_LETRA IN VARCHAR2,
  v_NU_ROTULOTOTALANCHO IN NUMBER,
  v_NU_ALINEAROTULO IN NUMBER,
  v_TAMANO_FUENTE IN NUMBER,
  v_NU_ROTULOPERPEN IN NUMBER,
  v_NU_ROTULOVISIBLE IN NUMBER,
  v_NU_NEGRILLA IN NUMBER,
  v_NU_ALINEAROTULOVERTICAL IN NUMBER,
  v_TX_COLORFONDO IN VARCHAR2 DEFAULT '#00FFFFFF' ,
  /* VARIABLES PARA CONCEPTOS*/
  v_NU_NUME_COHI_RPC IN NUMBER,
  v_NU_PATH_FILE IN NVARCHAR2 DEFAULT NULL ,
  v_TX_KEYESTILO_RPC IN VARCHAR2 DEFAULT NULL ,
  v_TX_CAMPOSASOCIA_RPC IN VARCHAR2 DEFAULT NULL ,
  v_TX_IDGROP_RPC IN VARCHAR2 DEFAULT NULL ,
  v_ES_SEMA_RPC IN NUMBER,
  v_TX_VALOR_SEMA_RPC IN VARCHAR2,
  v_TX_RELA_SEMA_RPC IN VARCHAR2,
  v_TX_DESC_SEMA_RPC IN VARCHAR2,
  v_TX_COLOR_SEMA_RPC IN VARCHAR2
)
AS

BEGIN

   IF ( v_ACTUALIZAR = 0 ) THEN
    
   BEGIN
      IF ( v_TIPO_CONCEPTO = -1 ) THEN
       
      BEGIN
         INSERT INTO R_PLAN_GRUP
           ( NU_NUME_PLHI_RPG, NU_NUME_GRHI_RPG, NU_INDI_RPG, NU_INGR_RPG, NU_NUGR_RPG, NU_TOP_RPG, NU_LEFT_RPG, NU_HEIGHT_RPG, NU_WIDTH_RPG, NU_INDIDEP_RPC_RPG, NU_INVACTASO_RPG, TX_BORDES_RPG, TX_hxCOLORROTULO_RPG, TX_hxCOLORLETRA_RPG, NU_ROTULOTOTALANCHO_RPG, NU_ALINEAROTULO_RPG, NU_TAMFUENTE_RPG, NU_ROTULOPERPEN_RPG, NU_ROTULOVISIBLE_RPG, NU_NEGRILLA_RPG, NU_ALINEAROTULOVERTICAL_RPG, TX_COLORFONDO_RPG )
           VALUES ( v_NU_NUME_PLHI, v_NU_NUME_GRHI, v_NU_INDI_ORDEN, v_NU_INGR_PADRE, v_NU_NUGR_RPG, v_NU_TOP, v_NU_LEFT, v_NU_ALTO, v_NU_ANCHO, v_NU_INDIDEP, v_NU_INVACTASO, v_TX_BORDES, v_C0LOR_FONDO, v_COLOR_LETRA, v_NU_ROTULOTOTALANCHO, v_NU_ALINEAROTULO, v_TAMANO_FUENTE, v_NU_ROTULOPERPEN, v_NU_ROTULOVISIBLE, v_NU_NEGRILLA, v_NU_ALINEAROTULOVERTICAL, v_TX_COLORFONDO );
      
      END;
      ELSE
      
      BEGIN
         INSERT INTO R_PLAN_CONC
           ( NU_NUME_PLHI_RPC, NU_NUME_COHI_RPC, NU_NUME_GRHI_RPC, NU_INGR_RPC, NU_INDI_RPC, NU_TOP_RPC, NU_LEFT_RPC, NU_HEIGHT_RPC, NU_WIDTH_RPC, NU_PATH_FILE, TX_NOMBRPT_RPC, TX_FORMRPT_RPC, NU_VISIBLE_RPC, NU_EDITA_RPC, NU_INDIDEP_RPC, TX_CAMPOSASOCIA_RPC, TX_hxCOLORLETRA_RPC, NU_ROTULOTOTALANCHO_RPC, NU_ALINEAROTULO_RPC, TX_IDGROP_RPC, TX_KEYESTILO_RPC, NU_TAMFUENTE_RPC, NU_ROTULOPERPEN_RPC, NU_ROTULOVISIBLE_RPC, NU_INVACTASO_RPC, NU_NEGRILLA_RPC, NU_ALINEAROTULOVERTICAL_RPC, TX_COLORFONDO_RPC, TX_hxCOLORROTULO_RPC, ES_SEMA_RPC, TX_VALOR_SEMA_RPC, TX_RELA_SEMA_RPC, TX_DESC_SEMA_RPC, TX_COLOR_SEMA_RPC )
           VALUES ( v_NU_NUME_PLHI, v_NU_NUME_COHI_RPC, v_NU_NUME_GRHI, v_NU_INGR_PADRE, v_NU_INDI_ORDEN, v_NU_TOP, v_NU_LEFT, v_NU_ALTO, v_NU_ANCHO, v_NU_PATH_FILE, NULL, NULL, 1, 0, v_NU_INDIDEP, v_TX_CAMPOSASOCIA_RPC, v_COLOR_LETRA, v_NU_ROTULOTOTALANCHO, v_NU_ALINEAROTULO, v_TX_IDGROP_RPC, v_TX_KEYESTILO_RPC, v_TAMANO_FUENTE, v_NU_ROTULOPERPEN, v_NU_ROTULOVISIBLE, v_NU_INVACTASO, v_NU_NEGRILLA, v_NU_ALINEAROTULOVERTICAL, v_TX_COLORFONDO, v_C0LOR_FONDO, v_ES_SEMA_RPC, v_TX_VALOR_SEMA_RPC, v_TX_RELA_SEMA_RPC, v_TX_DESC_SEMA_RPC, v_TX_COLOR_SEMA_RPC );
      
      END;
      END IF;
   
   END;
   ELSE
   
   BEGIN
      IF ( v_TIPO_CONCEPTO = -1 ) THEN
       DECLARE
         v_temp NUMBER(1, 0) := 0;
      
      BEGIN
         BEGIN
            SELECT 1 INTO v_temp
              FROM DUAL
             WHERE ( EXISTS ( SELECT NU_NUME_PLHI_RPG ,
                                     NU_NUME_GRHI_RPG 
                              FROM R_PLAN_GRUP 
                               WHERE  NU_NUME_PLHI_RPG = v_NU_NUME_PLHI
                                        AND NU_NUME_GRHI_RPG = v_NU_NUME_GRHI ) );
         EXCEPTION
            WHEN OTHERS THEN
               NULL;
         END;
            
         IF v_temp = 1 THEN
          
         BEGIN
            UPDATE R_PLAN_GRUP
               SET NU_INDI_RPG = v_NU_INDI_ORDEN,
                   NU_INGR_RPG = v_NU_INGR_PADRE,
                   NU_NUGR_RPG = v_NU_NUGR_RPG,
                   NU_TOP_RPG = v_NU_TOP,
                   NU_LEFT_RPG = v_NU_LEFT,
                   NU_HEIGHT_RPG = v_NU_ALTO,
                   NU_WIDTH_RPG = v_NU_ANCHO,
                   NU_INDIDEP_RPC_RPG = v_NU_INDIDEP,
                   NU_INVACTASO_RPG = v_NU_INVACTASO,
                   TX_BORDES_RPG = v_TX_BORDES,
                   TX_hxCOLORROTULO_RPG = v_C0LOR_FONDO,
                   TX_hxCOLORLETRA_RPG = v_COLOR_LETRA,
                   NU_ROTULOTOTALANCHO_RPG = v_NU_ROTULOTOTALANCHO,
                   NU_ALINEAROTULO_RPG = v_NU_ALINEAROTULO,
                   NU_TAMFUENTE_RPG = v_TAMANO_FUENTE,
                   NU_ROTULOPERPEN_RPG = v_NU_ROTULOPERPEN,
                   NU_ROTULOVISIBLE_RPG = v_NU_ROTULOVISIBLE,
                   NU_NEGRILLA_RPG = v_NU_NEGRILLA,
                   NU_ALINEAROTULOVERTICAL_RPG = v_NU_ALINEAROTULOVERTICAL,
                   TX_COLORFONDO_RPG = v_TX_COLORFONDO
             WHERE  NU_NUME_PLHI_RPG = v_NU_NUME_PLHI
              AND NU_NUME_GRHI_RPG = v_NU_NUME_GRHI;
         
         END;
         ELSE
         
         BEGIN
            INSERT INTO R_PLAN_GRUP
              ( NU_NUME_PLHI_RPG, NU_NUME_GRHI_RPG, NU_INDI_RPG, NU_INGR_RPG, NU_NUGR_RPG, NU_TOP_RPG, NU_LEFT_RPG, NU_HEIGHT_RPG, NU_WIDTH_RPG, NU_INDIDEP_RPC_RPG, NU_INVACTASO_RPG, TX_BORDES_RPG, TX_hxCOLORROTULO_RPG, TX_hxCOLORLETRA_RPG, NU_ROTULOTOTALANCHO_RPG, NU_ALINEAROTULO_RPG, NU_TAMFUENTE_RPG, NU_ROTULOPERPEN_RPG, NU_ROTULOVISIBLE_RPG, NU_NEGRILLA_RPG, NU_ALINEAROTULOVERTICAL_RPG, TX_COLORFONDO_RPG )
              VALUES ( v_NU_NUME_PLHI, v_NU_NUME_GRHI, v_NU_INDI_ORDEN, v_NU_INGR_PADRE, v_NU_NUGR_RPG, v_NU_TOP, v_NU_LEFT, v_NU_ALTO, v_NU_ANCHO, v_NU_INDIDEP, v_NU_INVACTASO, v_TX_BORDES, v_C0LOR_FONDO, v_COLOR_LETRA, v_NU_ROTULOTOTALANCHO, v_NU_ALINEAROTULO, v_TAMANO_FUENTE, v_NU_ROTULOPERPEN, v_NU_ROTULOVISIBLE, v_NU_NEGRILLA, v_NU_ALINEAROTULOVERTICAL, v_TX_COLORFONDO );
         
         END;
         END IF;
      
      END;
      ELSE
      DECLARE
         v_temp NUMBER(1, 0) := 0;
      
      BEGIN
         BEGIN
            SELECT 1 INTO v_temp
              FROM DUAL
             WHERE ( EXISTS ( SELECT NU_NUME_PLHI_RPC ,
                                     NU_NUME_COHI_RPC ,
                                     NU_NUME_GRHI_RPC 
                              FROM R_PLAN_CONC 
                               WHERE  NU_NUME_PLHI_RPC = v_NU_NUME_PLHI
                                        AND NU_NUME_COHI_RPC = v_NU_NUME_COHI_RPC
                                        AND NU_NUME_GRHI_RPC = v_NU_NUME_GRHI ) );
         EXCEPTION
            WHEN OTHERS THEN
               NULL;
         END;
            
         IF v_temp = 1 THEN
          
         BEGIN
            UPDATE R_PLAN_CONC
               SET NU_INGR_RPC = v_NU_INGR_PADRE,
                   NU_INDI_RPC = v_NU_INDI_ORDEN,
                   NU_TOP_RPC = v_NU_TOP,
                   NU_LEFT_RPC = v_NU_LEFT,
                   NU_HEIGHT_RPC = v_NU_ALTO,
                   NU_WIDTH_RPC = v_NU_ANCHO,
                   NU_PATH_FILE = v_NU_PATH_FILE,
                   TX_NOMBRPT_RPC = NULL,
                   TX_FORMRPT_RPC = NULL,
                   NU_VISIBLE_RPC = 1,
                   NU_EDITA_RPC = 0,
                   NU_INDIDEP_RPC = v_NU_INDIDEP,
                   TX_CAMPOSASOCIA_RPC = v_TX_CAMPOSASOCIA_RPC,
                   TX_hxCOLORLETRA_RPC = v_COLOR_LETRA,
                   NU_ROTULOTOTALANCHO_RPC = v_NU_ROTULOTOTALANCHO,
                   NU_ALINEAROTULO_RPC = v_NU_ALINEAROTULO,
                   TX_IDGROP_RPC = v_TX_IDGROP_RPC,
                   TX_KEYESTILO_RPC = v_TX_KEYESTILO_RPC,
                   NU_TAMFUENTE_RPC = v_TAMANO_FUENTE,
                   NU_ROTULOPERPEN_RPC = v_NU_ROTULOPERPEN,
                   NU_ROTULOVISIBLE_RPC = v_NU_ROTULOVISIBLE,
                   NU_INVACTASO_RPC = v_NU_INVACTASO,
                   NU_NEGRILLA_RPC = v_NU_NEGRILLA,
                   NU_ALINEAROTULOVERTICAL_RPC = v_NU_ALINEAROTULOVERTICAL,
                   TX_COLORFONDO_RPC = v_TX_COLORFONDO,
                   TX_hxCOLORROTULO_RPC = v_C0LOR_FONDO,
                   ES_SEMA_RPC = v_ES_SEMA_RPC,
                   TX_VALOR_SEMA_RPC = v_TX_VALOR_SEMA_RPC,
                   TX_RELA_SEMA_RPC = v_TX_RELA_SEMA_RPC,
                   TX_DESC_SEMA_RPC = v_TX_DESC_SEMA_RPC,
                   TX_COLOR_SEMA_RPC = v_TX_COLOR_SEMA_RPC
             WHERE  NU_NUME_PLHI_RPC = v_NU_NUME_PLHI
              AND NU_NUME_COHI_RPC = v_NU_NUME_COHI_RPC
              AND NU_NUME_GRHI_RPC = v_NU_NUME_GRHI;
         
         END;
         ELSE
         
         BEGIN
            INSERT INTO R_PLAN_CONC
              ( NU_NUME_PLHI_RPC, NU_NUME_COHI_RPC, NU_NUME_GRHI_RPC, NU_INGR_RPC, NU_INDI_RPC, NU_TOP_RPC, NU_LEFT_RPC, NU_HEIGHT_RPC, NU_WIDTH_RPC, NU_PATH_FILE, TX_NOMBRPT_RPC, TX_FORMRPT_RPC, NU_VISIBLE_RPC, NU_EDITA_RPC, NU_INDIDEP_RPC, TX_CAMPOSASOCIA_RPC, TX_hxCOLORLETRA_RPC, NU_ROTULOTOTALANCHO_RPC, NU_ALINEAROTULO_RPC, TX_IDGROP_RPC, TX_KEYESTILO_RPC, NU_TAMFUENTE_RPC, NU_ROTULOPERPEN_RPC, NU_ROTULOVISIBLE_RPC, NU_INVACTASO_RPC, NU_NEGRILLA_RPC, NU_ALINEAROTULOVERTICAL_RPC, TX_COLORFONDO_RPC, TX_hxCOLORROTULO_RPC, ES_SEMA_RPC, TX_VALOR_SEMA_RPC, TX_RELA_SEMA_RPC, TX_DESC_SEMA_RPC, TX_COLOR_SEMA_RPC )
              VALUES ( v_NU_NUME_PLHI, v_NU_NUME_COHI_RPC, v_NU_NUME_GRHI, v_NU_INGR_PADRE, v_NU_INDI_ORDEN, v_NU_TOP, v_NU_LEFT, v_NU_ALTO, v_NU_ANCHO, v_NU_PATH_FILE, NULL, NULL, 1, 0, v_NU_INDIDEP, v_TX_CAMPOSASOCIA_RPC, v_COLOR_LETRA, v_NU_ROTULOTOTALANCHO, v_NU_ALINEAROTULO, v_TX_IDGROP_RPC, v_TX_KEYESTILO_RPC, v_TAMANO_FUENTE, v_NU_ROTULOPERPEN, v_NU_ROTULOVISIBLE, v_NU_INVACTASO, v_NU_NEGRILLA, v_NU_ALINEAROTULOVERTICAL, v_TX_COLORFONDO, v_C0LOR_FONDO, v_ES_SEMA_RPC, v_TX_VALOR_SEMA_RPC, v_TX_RELA_SEMA_RPC, v_TX_DESC_SEMA_RPC, v_TX_COLOR_SEMA_RPC );
         
         END;
         END IF;
      
      END;
      END IF;
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;