CREATE OR REPLACE PROCEDURE H3i_SP_REC_REG_ADSC_REMI_MODIF
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_MOVIMIENTO IN NUMBER,
 	CV_1 OUT SYS_REFCURSOR
 )
AS

BEGIN
	OPEN CV_1 FOR
		SELECT CD_IDEN_READ,
			  --,p.NU_HIST_PAC AS [NU_HIST_PAC_READ]--,p.NU_DOCU_PAC AS [NU_HIST_PAC_READ]
			  MOSTRARTIPODOCUMENTO(p.NU_TIPD_PAC) + p.NU_DOCU_PAC AS NU_HIST_PAC_READ,
			  p.NU_HIST_PAC AS NU_HIST_PAC_REAL,
			  TX_NOM_COMPLE,
			  NU_TIPO_DOC,
			  NU_EDAD_PAC,
			  TXT_GENERO_PAC,
			  TXT_TIPO_USR,
			  FE_AUTO_READ,
			  FE_VENCI_READ,
			  TXT_COD_BARRA_READ,
			  cc.NO_NOMB_CECO AS TXT_AREA_DEPEN_READ,
			  TXT_ASEGURADORA_READ,
			  NO_CANT_AUTORI_READ,
			  NU_RECEPCIONADO,
			  NU_AUTORIZADO,
			  NU_PRE_REGISTRO,
			  CD_CODI_MEDI_LABO,
			  e.NO_NOMB_ESP AS ESPECIALIDAD,
			  m.NO_NOMB_MED
		FROM REMISION_TRABAJO_ADSCRITO
		INNER JOIN PACIENTES p 
		  	ON (NU_HIST_PAC_RETRA = p.NU_HIST_PAC 
		  		OR NU_HIST_PAC_RETRA = MOSTRARTIPODOCUMENTO(p.NU_TIPD_PAC) + p.NU_DOCU_PAC)
		INNER JOIN REGISTRO_ADSCRITO ra 
		  	ON (NU_HIST_PAC_READ = p.NU_HIST_PAC  
		  		OR NU_HIST_PAC_READ = MOSTRARTIPODOCUMENTO(p.NU_TIPD_PAC) + p.NU_DOCU_PAC)
		INNER JOIN LABORATORIO 
		  	ON NU_NUME_MOVI_LABO = NU_NUME_MOVI_RETRA
		INNER JOIN MEDICOS m 
		  	ON m.CD_CODI_MED = CD_CODI_MEDI_LABO
		INNER JOIN ESPECIALIDADES e 
		  	ON CD_CODI_ESP_LABO = e.CD_CODI_ESP
		  
		  -- se pone en relacion al documento contra la historia de registro_autorizacion, por problema en codigo (NU_DOCU_PAC)
		INNER JOIN CENTRO_COSTO cc 
		  	ON cc.CD_CODI_CECO = TXT_AREA_DEPEN_READ
		WHERE NU_RECEP_RETRA = 0
		AND NU_NUME_MOVI_RETRA = V_MOVIMIENTO;


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

	