CREATE OR REPLACE PROCEDURE H3i_SP_ELIM_PROPIEDADESGRA_CyD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_PLHI_RPC_RGR IN NUMBER,
  v_NU_NUME_COHI_RPC_RGR IN NUMBER,
  v_NU_INDI_RPC_RGR IN NUMBER,
  v_NU_TIPOGR_RGR IN NUMBER,
  v_NU_SUBTIPO_RGR IN NUMBER
)
AS

BEGIN

   DELETE R_GRACyD_RPC

    WHERE  NU_NUME_PLHI_RPC_RGR = v_NU_NUME_PLHI_RPC_RGR
             AND NU_NUME_COHI_RPC_RGR = v_NU_NUME_COHI_RPC_RGR
             AND NU_INDI_RPC_RGR = v_NU_INDI_RPC_RGR
             AND NU_TIPOGR_RGR = v_NU_TIPOGR_RGR
             AND NU_SUBTIPO_RGR = v_NU_SUBTIPO_RGR;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;