CREATE OR REPLACE PROCEDURE H3i_SP_ACT_VALIDACION_2_HIST
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_COHI_VAHI2 IN NUMBER,
  v_NU_NUME_PLHI_VAHI2 IN NUMBER,
  v_NU_LONG_VAHI2 IN NUMBER,
  v_NU_VALI_VAHI2 IN NUMBER,
  v_DE_TMAX_VAHI2 IN VARCHAR2,
  v_DE_TMIN_VAHI2 IN VARCHAR2,
  v_DE_VDEF_VAHI2 IN VARCHAR2
)
AS
   v_CONT NUMBER(10,0);

BEGIN

   SELECT COUNT(NU_NUME_COHI_VAHI2)  

     INTO v_CONT
     FROM VALCONC_HIST2 
    WHERE  NU_NUME_COHI_VAHI2 = v_NU_NUME_COHI_VAHI2
             AND NU_NUME_PLHI_VAHI2 = v_NU_NUME_PLHI_VAHI2;
   IF v_CONT >= 1 THEN
    
   BEGIN
      UPDATE VALCONC_HIST2
         SET NU_LONG_VAHI2 = v_NU_LONG_VAHI2,
             NU_VALI_VAHI2 = v_NU_VALI_VAHI2,
             DE_TMAX_VAHI2 = v_DE_TMAX_VAHI2,
             DE_TMIN_VAHI2 = v_DE_TMIN_VAHI2,
             DE_VDEF_VAHI2 = v_DE_VDEF_VAHI2
       WHERE  NU_NUME_COHI_VAHI2 = v_NU_NUME_COHI_VAHI2
        AND NU_NUME_PLHI_VAHI2 = v_NU_NUME_PLHI_VAHI2;
   
   END;
   ELSE
   
   BEGIN
      INSERT INTO VALCONC_HIST2
        ( NU_NUME_COHI_VAHI2, NU_NUME_PLHI_VAHI2, NU_LONG_VAHI2, NU_VALI_VAHI2, DE_TMAX_VAHI2, DE_TMIN_VAHI2, DE_VDEF_VAHI2 )
        VALUES ( v_NU_NUME_COHI_VAHI2, v_NU_NUME_PLHI_VAHI2, v_NU_LONG_VAHI2, v_NU_VALI_VAHI2, v_DE_TMAX_VAHI2, v_DE_TMIN_VAHI2, v_DE_VDEF_VAHI2 );
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;