CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_DATA_FAVA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_IDVARINDI IN NUMBER,
  v_IDPLANTILLA IN NUMBER,
  v_ORDENCPTO IN NUMBER,
  v_VALMIN IN NUMBER,
  v_VALMAX IN NUMBER,
  v_PESO IN NUMBER,
  v_IDCONCEPTO IN VARCHAR2,
  v_IDCONCEPTOASOC IN VARCHAR2,
  v_BOOLFINAL IN NUMBER,
  v_IDPLANTILLAEXT IN NUMBER
)
AS

BEGIN

   INSERT INTO FACTOR_VAIN
     ( NU_AUTO_VAIN_FAVA, NU_NUME_PLHI_FAVA, NU_INDI_RPC_FAVA, NU_VALMIN_FAVA, NU_VALMAX_FAVA, NU_PESO_FAVA, NU_ID_CPTO_INDI_FAVA, NU_CPTO_ASOC_FAVA, BOOL_ES_FORMFIN_FAVA, NU_PLANT_EXT_FAVA )
     VALUES ( v_IDVARINDI, v_IDPLANTILLA, v_ORDENCPTO, v_VALMIN, v_VALMAX, v_PESO, v_IDCONCEPTO, v_IDCONCEPTOASOC, v_BOOLFINAL, v_IDPLANTILLAEXT );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;