CREATE OR REPLACE PROCEDURE H3i_SP_ACTUALIZAR_CONF_CLAP /*PROCEDIMIENTO ALMACENADO QUE PERMITE ACTUALIZAR UNA CONFIGURACION DE CLAP SEGUN ID*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_COD_CONF_CLAP IN NUMBER,
  v_NU_NUME_PLHI_CLAP IN NUMBER,
  v_NU_INGRE_PLHI_CLAP IN NUMBER,
  v_NU_SEGUI_PLHI_CLAP IN NUMBER,
  v_NU_EDADMIN_CLAP IN NUMBER,
  v_NU_EDADMAX_CLAP IN NUMBER
)
AS

BEGIN

   UPDATE CONFIGURA_CLAP
      SET NU_NUME_PLHI_CLAP = v_NU_NUME_PLHI_CLAP,
          NU_INGRE_PLHI_CLAP = v_NU_INGRE_PLHI_CLAP,
          NU_SEGUI_PLHI_CLAP = v_NU_SEGUI_PLHI_CLAP,
          NU_EDADMIN_CLAP = v_NU_EDADMIN_CLAP,
          NU_EDADMAX_CLAP = v_NU_EDADMAX_CLAP
    WHERE  COD_CONF_CLAP = v_COD_CONF_CLAP;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;