CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_ACTIVIDADS_PyP	
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================				
(
	V_CODIGO IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)		
AS
BEGIN
	OPEN CV_1 FOR
		SELECT CD_CODI_ACTI
	      ,NO_NOMB_ACTI
	      ,CD_CODI_FICO_ACTI
	      ,TX_CODI_RFF_ACTI
		  ,NU_AUTO_PYPACTPARAM_ACTI
		FROM ACTIVIDAD_PYP
		WHERE NO_NOMB_ACTI LIKE '%' + V_CODIGO + '%'
		ORDER BY NO_NOMB_ACTI;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

	
