CREATE OR REPLACE PROCEDURE H3i_SP_GUARD_PREPA_MEDIC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_HMED IN NUMBER,
  v_CD_CODI_ARTI IN VARCHAR2,
  v_NOMBRE_MEDICAMENTO IN VARCHAR2,
  v_CONCENTRACION IN NUMBER,
  v_VOLUMEN IN NUMBER,
  v_NUM_LOTE_MEDICAMENTO IN VARCHAR2,
  v_NUM_LOTE_PREPARADO IN VARCHAR2,
  v_PREPARADO_EN IN VARCHAR2
)
AS

BEGIN

   INSERT INTO PREPARADO_MEDICAMENTO
     ( NU_NUME_HICL_HMED, CD_CODI_ARTI, NOMBRE_MEDICAMENTO, CONCENTRACION, VOLUMEN, NUM_LOTE_MEDICAMENTO, NUM_LOTE_PREPARADO, PREPARADO_EN )
     VALUES ( v_NU_NUME_HICL_HMED, v_CD_CODI_ARTI, v_NOMBRE_MEDICAMENTO, v_CONCENTRACION, v_VOLUMEN, v_NUM_LOTE_MEDICAMENTO, v_NUM_LOTE_PREPARADO, v_PREPARADO_EN );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;