CREATE OR REPLACE PROCEDURE H3I_SP_OBTENER_REL_PLAN_PLAN
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT PH1.NU_NUME_PLHI COD_PRINCIPAL  ,
             F1.CD_NOMB_FIN NOM_PRINCIPAL  ,
             PH2.NU_NUME_PLHI COD_SECUNDARIO  ,
             F2.CD_NOMB_FIN NOM_SECUNDARIO  ,
             NU_VAL_ORDEN_RPP VALIDA_ORDEN  
        FROM R_PLAN_PLAN 
              INNER JOIN PLANTILLA_HIST PH1   ON NU_NUME_PLHI_RPP = PH1.NU_NUME_PLHI
              INNER JOIN R_PLANTILLA_HIST RP1   ON PH1.NU_NUME_PLHI = RP1.NU_NUME_PLHI_R
              INNER JOIN FINALIDAD_HIST F1   ON RP1.NU_FINA_PLHI = F1.CD_CODI_FIN
              INNER JOIN PLANTILLA_HIST PH2   ON NU_NUME_PLHISEC_RPP = PH2.NU_NUME_PLHI
              INNER JOIN R_PLANTILLA_HIST RP2   ON PH2.NU_NUME_PLHI = RP2.NU_NUME_PLHI_R
              INNER JOIN FINALIDAD_HIST F2   ON RP2.NU_FINA_PLHI = F2.CD_CODI_FIN ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;