CREATE OR REPLACE PROCEDURE H3i_SP_ACTUALIZAR_CONF_FORM_CI /*PROCEDIMIENTO ALMACENADO QUE PERMITE ACTUALIZAR LA RELACION ENTRE FORMATOS Y CIRUGIAS*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_COD_CONF_FORM_CIR IN NUMBER,
  v_NU_PLHI_ANTES IN NUMBER,
  v_NU_PLHI_DURANTE IN NUMBER,
  v_NU_PLHI_DESPUES IN NUMBER
)
AS

BEGIN

   UPDATE CONFIGURA_FORM_CIR
      SET NU_PLHI_ANTES = v_NU_PLHI_ANTES,
          NU_PLHI_DURANTE = v_NU_PLHI_DURANTE,
          NU_PLHI_DESPUES = v_NU_PLHI_DESPUES
    WHERE  COD_CONF_FORM_CIR = v_COD_CONF_FORM_CIR;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;