DECLARE 
 TYPE ARR_CIUDADES IS TABLE OF VARCHAR2(50) INDEX BY BINARY_INTEGER;
 misCiudades ARR_CIUDADES;
 V_CODIGO_RESTAURANTE CHAR(13);
 V_COUNT NUMBER;
 
 TOTAL NUMBER := 0;
BEGIN
     misCiudades(1) := 'CHUR-0001';
     misCiudades(2) := 'SALAD-TOROCAESAR';
     misCiudades(3) := 'ESPECIAL-LACUBANA';
     
     FOR i IN misCiudades.FIRST..misCiudades.LAST
     LOOP
        SELECT COUNT(VENEMPC)
        INTO V_COUNT
        FROM VEN0001
        WHERE PROCOD = CAST(misCiudades(I) AS CHAR(20));	
        
        TOTAL := TOTAL + V_COUNT;
     END LOOP;
     
     
     
     DBMS_OUTPUT.PUT_LINE(TOTAL);
END;



CREATE GLOBAL TEMPORARY TABLE TT_COD_RES(
	COD_RES CHAR(13) NOT NULL
) ON COMMIT DELETE ROWS;


        SELECT VENEMPC
        --INTO V_CODIGO_RESTAURANTE
        FROM USUCED
        WHERE PROCOD = CAST( 'CHUR-0001' AS CHAR(13));
        
        
        
        SELECT VEN00012.PROPRE
        --INTO V_PRECIO_ITEM
        FROM VEN00012
        WHERE VENEMPC = '901.023.461-1'
            AND LIPCOD = '01'
            AND PROCOD = 'CHUR-0001'
            
            
    SELECT MAX(VEN0004.PEDLIN) + 1
	--INTO V_CONTADOR_ITEMS_PEDIDO
	FROM VEN0004 
	WHERE VEN0004.PEDNRO = 5;
	
	
	SELECT CNT0014.DEDPOR
	--INTO V_VALOR_IVA
	FROM VEN0001 
	LEFT JOIN CNT0014  
	    ON VEN0001.FDEDCOD = CNT0014.DEDCOD 
	    AND VEN0001.FDEDSC = CNT0014.DEDSUBCOD
	    AND VEN0001.FDEDANO = CNT0014.DEDANO 
	WHERE VEN0001.VENEMPPAI = '169' 
	    AND VEN0001.VENEMPC = '901.023.461-1' 
	    AND VEN0001.PROCOD = 'ESPECIAL-LACUBANA';