CREATE OR REPLACE FUNCTION FN_IDENTIF_ROL_ESPECIAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CEDULA_EPL EMPLEADOS_BASIC.CEDULA%TYPE
)
RETURN VARCHAR2
AS 
	CONTADOR_ROL_ESPC NUMBER; -- CONTADOR PARA IDENTIFICAR SI TIENE ASIGNADO UN ROL ESPECIAL
BEGIN
	SELECT COUNT(*)
	INTO CONTADOR_ROL_ESPC
	FROM T_USUARIO_ROL_ESPECIAL
	WHERE COD_USUARIO_ESPECIAL = V_CEDULA_EPL;

	IF(CONTADOR_ROL_ESPC > 0) THEN
		RETURN 'ESPECIAL';
	ELSE 
		RETURN 'SIN_ROL';
	END IF;
END;