CREATE OR REPLACE FUNCTION FN_IDENTIF_ROL_PREDETERMINADO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CEDULA_EPL EMPLEADOS_BASIC.CEDULA%TYPE
)
RETURN VARCHAR2
AS
	-- VARIABLES PARA FILTRAR LA BUSQUEDA EN LOS ROLES DE TIPO SENA 
	GRU1 VARCHAR2(50) := 't_gru_sena';         -- GRUPO DE APRENDICES DEL SENA
	GRU2 VARCHAR2(50) := 't_gru_sena_prod';    -- GRUPO DE SENA EN ETAPA DE PRODUCCION
	GRU3 VARCHAR2(50) := 't_gru_sena_aut_ind'; -- GRUPO DE SENA NUEVOS

	SENTENCIA_SQL VARCHAR2(1000);			   -- SENTENCIA DE CADA ROL QUE SE EJECUTARA	
	CONTADOR_ROL NUMBER;					   -- CONTADOR PARA IDENTIFICAR EN QUE GRUPO DE ROL SE ENCUENTRA
BEGIN
	-- ====================================================
	-- BLOQUE DEL ROL ADMINISTRADOR
	BEGIN
		SELECT SENTENCIA
		INTO SENTENCIA_SQL
		FROM T_ROLES
		WHERE COD_ROL = 4;

		SENTENCIA_SQL := 'SELECT COUNT(*) FROM DUAL WHERE :CEDULA IN ('||SENTENCIA_SQL||')';
		EXECUTE IMMEDIATE SENTENCIA_SQL INTO CONTADOR_ROL USING V_CEDULA_EPL;

		-- SI HAY RESULTADOS  EN LA BUSQUEDA RETORNA INDICANDO QUE PERTENECE AL ADMIN
		IF(CONTADOR_ROL > 0) THEN
			RETURN 'ADMIN';
		END IF;
	EXCEPTION
		WHEN NO_DATA_FOUND
			THEN CONTADOR_ROL:= 0;
	END;

	-- ====================================================
	-- BLOQUE DEL ROL JEFE
	BEGIN
		SELECT SENTENCIA
		INTO SENTENCIA_SQL
		FROM T_ROLES
		WHERE COD_ROL = 3;

		SENTENCIA_SQL := 'SELECT COUNT(*) FROM DUAL WHERE :CEDULA IN ('||SENTENCIA_SQL||')';

		EXECUTE IMMEDIATE SENTENCIA_SQL INTO CONTADOR_ROL USING V_CEDULA_EPL;

		-- SI HAY RESULTADO EN LA BUSQUEDA RETORNA INDICANDO QUE PERTENECE AL SENA
		IF(CONTADOR_ROL > 0) THEN
			RETURN 'JEFE';
		END IF;
	EXCEPTION
		WHEN NO_DATA_FOUND
			THEN CONTADOR_ROL:= 0;
	END;

	-- ===================================================
	-- BLOQUE DEL ROL RASO
	BEGIN
		SELECT SENTENCIA
		INTO SENTENCIA_SQL
		FROM T_ROLES
		WHERE COD_ROL = 2;

		SENTENCIA_SQL := 'SELECT COUNT(*) FROM DUAL WHERE :CEDULA IN ('||SENTENCIA_SQL||')';

		EXECUTE IMMEDIATE SENTENCIA_SQL INTO CONTADOR_ROL USING V_CEDULA_EPL;

		-- SI HAY RESULTADO EN LA BUSQUEDA RETORNA INDICANDO QUE PERTENECE AL SENA
		IF(CONTADOR_ROL > 0) THEN
			RETURN 'RASO';
		END IF;
	EXCEPTION
		WHEN NO_DATA_FOUND
			THEN CONTADOR_ROL:= 0;
	END;

	-- ====================================================
	-- BLOQUE DEL ROL SENA
	BEGIN
		-- CONSULTA EL QUERY QUE TRAE TODAS LAS CEDULAS DE LOS EMPLEADOS CON ROL SENA
		SELECT SENTENCIA 
		INTO SENTENCIA_SQL
		FROM T_ROLES
		WHERE COD_ROL = 1;
		
		SENTENCIA_SQL := 'SELECT COUNT(*) FROM DUAL WHERE :CEDULA IN ('||SENTENCIA_SQL||')';
		EXECUTE IMMEDIATE SENTENCIA_SQL INTO CONTADOR_ROL USING V_CEDULA_EPL, GRU1, GRU2, GRU3;

		-- SI HAY RESULTADO EN LA BUSQUEDA RETORNA INDICANDO QUE PERTENECE AL SENA
		IF(CONTADOR_ROL > 0) THEN
			RETURN 'SENA';
		ELSE
			RETURN 'SIN_ROL';
		END IF;
	EXCEPTION
		WHEN NO_DATA_FOUND
			THEN CONTADOR_ROL:= 0;
	END;	
END;
