CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_CONS_PERIODONTO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_INS_UP_CONS_PAC OUT NUMBER,
  v_CD_PACIENTE IN NUMBER,
  v_FECHA_CONS IN DATE,
  v_CD_SESION IN VARCHAR2,
  v_NU_LABO IN NUMBER,
  v_BOOL_REEV IN NUMBER
)
AS

BEGIN

    INSERT INTO HIST_PERIODONTO_CONSULTAS( 
        CD_PAC_PERIOD, FE_CONS_PERIOD, 
        CD_SES_ACT, CD_NUM_LABO, 
        BOOL_REEVAL )
    VALUES ( 
        v_CD_PACIENTE, v_FECHA_CONS, 
        v_CD_SESION, v_NU_LABO, 
        v_BOOL_REEV);

    SELECT CD_CONS_PER 
    INTO v_CD_INS_UP_CONS_PAC 
    FROM HIST_PERIODONTO_CONSULTAS
    WHERE CD_CONS_PER = (SELECT MAX(CD_CONS_PER) FROM HIST_PERIODONTO_CONSULTAS);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;