CREATE OR REPLACE PROCEDURE H3i_SP_LISTAR_HC_AUDIT
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_FECHAINI IN DATE DEFAULT NULL ,
  v_FECHAFIN IN DATE DEFAULT NULL ,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT HISTORIACLINICA.NU_NUME_LABO_HICL ,
             HISTORIACLINICA.NU_NUME_HICL ,
             HISTORIACLINICA.FE_FECH_HICL ,
             PACIENTES.NU_TIPD_PAC ,
             PACIENTES.NU_DOCU_PAC ,
             PACIENTES.TX_NOMBRECOMPLETO_PAC ,
             SERVICIOS.CD_CODI_SER ,
             SERVICIOS.NO_NOMB_SER ,
             FINALIDAD_HIST.CD_NOMB_FIN ,
             ESPECIALIDADES.NO_NOMB_ESP ,
             MEDICOS.NO_NOMB_MED ,
             MEDICOS.NU_TIPO_MEDI ,
             AUDITORIA_HC.TX_Observacion_AUCH ,
             AUDITORIA_HC.NU_AUTO_VAAU_AUHC ,
             AUDITORIA_HC.FE_FechaCreacion_AUHC ,
             AUDITORIA_HC.NU_VALORACION_AUHC ,
             AUDITORIA_HC.TX_NOMPROFESI_AUHC ,
             VALORACION_AUDITORIA_HC.TX_Descripcion_VAHC ,
             M.NO_NOMB_MED MEDAPRUEBA  
        FROM HISTORIACLINICA 
               INNER JOIN LABORATORIO    ON NU_NUME_LABO = NU_NUME_LABO_HICL
               INNER JOIN MOVI_CARGOS    ON NU_NUME_MOVI_LABO = NU_NUME_MOVI
               INNER JOIN PACIENTES    ON PACIENTES.NU_HIST_PAC = MOVI_CARGOS.NU_HIST_PAC_MOVI
               INNER JOIN SERVICIOS    ON SERVICIOS.CD_CODI_SER = LABORATORIO.CD_CODI_SER_LABO
               INNER JOIN R_PLANTILLA_HIST    ON R_PLANTILLA_HIST.NU_NUME_PLHI_R = HISTORIACLINICA.NU_NUME_PLHI_HICL
               INNER JOIN FINALIDAD_HIST    ON FINALIDAD_HIST.CD_CODI_FIN = R_PLANTILLA_HIST.NU_FINA_PLHI
               INNER JOIN ESPECIALIDADES    ON LABORATORIO.CD_CODI_ESP_LABO = ESPECIALIDADES.CD_CODI_ESP
               INNER JOIN MEDICOS    ON MEDICOS.CD_CODI_MED = HISTORIACLINICA.CD_MED_REAL_HICL
               INNER JOIN AUDITORIA_HC    ON AUDITORIA_HC.ID_HistoriaClinica_AUHC = HISTORIACLINICA.NU_NUME_HICL
               INNER JOIN VALORACION_AUDITORIA_HC    ON VALORACION_AUDITORIA_HC.NU_AUTO_VAAU_VAHC = AUDITORIA_HC.NU_AUTO_VAAU_AUHC
               LEFT JOIN HIST_ADENDUM AD   ON AD.NU_NUME_HICL = HISTORIACLINICA.NU_NUME_HICL
               LEFT JOIN MEDICOS M   ON AD.CD_DOCENTE_APRUEBA = M.CD_CODI_MED
       WHERE  LABORATORIO.NU_ESTA_LABO <> 2
                AND MOVI_CARGOS.NU_ESTA_MOVI <> 2
                AND FE_FECH_HICL >= NVL(v_FECHAINI, FE_FECH_HICL)
                AND FE_FECH_HICL <= NVL(v_FECHAFIN, FE_FECH_HICL) ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;