CREATE OR REPLACE PROCEDURE H3i_SP_PERSONAS_ATENDIDAS_SALUD_OCUPA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	@INI DATE,
	@FIN DATE
 )
				
AS
BEGIN



EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

	SELECT	TX_TITULO_COHI PROCESO, COUNT(NU_NUME_HICL) CANTIDAD
	FROM	CONCEPTO_HIST 
			INNER JOIN R_PLAN_CONC RPC ON NU_NUME_COHI = NU_NUME_COHI_RPC AND NU_NUME_PLHI_RPC = 1342
			INNER JOIN HISTORIACLINICA HC ON HC.NU_NUME_PLHI_HICL = RPC.NU_NUME_PLHI_RPC
			INNER JOIN HIST_NUME HN ON HC.NU_NUME_HICL = HN.NU_NUME_HICL_HINU AND RPC.NU_INDI_RPC= HN.NU_INDI_HINU
	WHERE	NU_NUME_COHI IN (6331, 6332, 6333)
			AND		FE_FECINI_HICL BETWEEN @INI AND @FIN
			
	GROUP BY TX_TITULO_COHI
	
	/*************************************************/
	
	SELECT EDAD = (DBO.CalcularEdad (FE_NACI_PAC,GETDATE(), 0)) 
	INTO	#TMPEDADES
	FROM   PACIENTES       INNER JOIN  (
										SELECT	DISTINCT NU_HIST_PAC_MOVI
										FROM	HISTORIACLINICA INNER JOIN LABORATORIO ON NU_NUME_LABO_HICL = NU_NUME_LABO
												INNER JOIN MOVI_CARGOS ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
										WHERE	NU_ESTA_MOVI <> 2
										AND		FE_FECINI_HICL BETWEEN @INI AND @FIN
										AND     NU_NUME_PLHI_HICL = 1342) MC ON NU_HIST_PAC = MC.NU_HIST_PAC_MOVI									
										
	SELECT	AVG(EDAD) AS PROMEDIO
	FROM	#TMPEDADES