CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTAASIGCITA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_MEDICO IN VARCHAR2,
  v_CARGO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT A.TX_CODIGO_ASIG ASIGNATURA  ,
             PA.NU_AUTO_PEAC PERIODO  ,
             G.CD_CODI_GRUP GRUPO  ,
             HG.NU_AUTO_HOGR HORARIO  
        FROM CITAS_MEDICAS CM
               INNER JOIN MOVI_CARGOS MV   ON CM.NU_NUME_MOVI_CIT = MV.NU_NUME_MOVI
               INNER JOIN HORARIO_GRUPO HG   ON CM.NU_AUTO_HOGR_CIME = HG.NU_AUTO_HOGR
               INNER JOIN GRUPO_ASIGNATURA_PERIODO ASP   ON HG.NU_AUTO_GRAP_HOGR = ASP.NU_AUTO_GRAP
               INNER JOIN ASIGNATURA A   ON ASP.TX_CODIGO_ASIG_GRAP = A.TX_CODIGO_ASIG
               INNER JOIN PERIODO_ACADEMICO PA   ON ASP.NU_AUTO_PEAC_GRAP = PA.NU_AUTO_PEAC
               INNER JOIN GRUPO G   ON ASP.NU_CODIGO_GRAP = G.CD_CODI_GRUP
       WHERE  CM.CD_CODI_MED_CIT = v_MEDICO
                AND CM.NU_NUME_MOVI_CIT = v_CARGO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;