
CREATE OR REPLACE PROCEDURE H3i_SP_RPT_FICHA_NOTIF
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_INFORME IN NUMBER,
	V_FECHAINICIAL IN DATE,
	V_FECHAFINAL IN DATE,
	CV_1 OUT SYS_REFCURSOR
 )
AS
BEGIN
	OPEN CV_1 FOR
		SELECT	DISTINCT 
				NU_HIST_PAC,
				TO_NUMBER(NU_AUTO_FINA) NU_AUTO_FINA,
				TX_TITULO_FINA,
				TX_CODIGO_FINA,
				CALCULAREDAD(FE_NACI_PAC, FE_FECH_MOVI, 0) EDAD,
				CALCULAREDAD(FE_NACI_PAC, FE_FECH_MOVI, 1) UME,
				TO_NUMBER(NU_SEXO_PAC) NU_SEXO_PAC
		FROM	R_LABO_DIAG RLD 
		INNER JOIN LABORATORIO L 
			ON (RLD.NU_NUME_LABO_RLAD = NU_NUME_LABO 
			AND ID_TIPO_RLAD=1)
		INNER JOIN MOVI_CARGOS M 
			ON L.NU_NUME_MOVI_LABO = M.NU_NUME_MOVI
		INNER JOIN PACIENTES P 
			ON P.NU_HIST_PAC = M.NU_HIST_PAC_MOVI
		INNER JOIN R_FINA_DIAG RFD 
			ON RFD.CD_CODI_DIAG_RFD = RLD.CD_CODI_DIAG_RLAD
		INNER JOIN FICHA_NOTIFICACION FN 
			ON FN.NU_AUTO_FINA = RFD.NU_AUTO_FINA_RFD
		WHERE	NU_ESTA_LABO <> 2
		AND		NU_ESTA_MOVI <> 2
		AND		NU_AUTO_FINA = V_INFORME
		AND		FE_FECH_MOVI BETWEEN V_FECHAINICIAL AND V_FECHAFINAL;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
	