CREATE OR REPLACE PROCEDURE H3i_SP_INFORME_MORBILIDAD_DETA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_INI IN DATE,
	V_FIN IN DATE,
	CV_1 OUT SYS_REFCURSOR
 )
				
AS
BEGIN
	OPEN CV_1 FOR 
		SELECT	CASE NU_TIPD_PAC 
					WHEN 0 THEN 'CC'
					WHEN 1 THEN 'TI'
					WHEN 2 THEN 'RC'
					WHEN 3 THEN 'CE'
					WHEN 4 THEN 'PA'
					WHEN 5 THEN 'AS'
					WHEN 6 THEN 'MS'
					WHEN 7 THEN 'NU'
				END NU_TIPD_PAC,
			NU_DOCU_PAC,
			TX_NOMBRECOMPLETO_PAC,
			TX_JORNADA_PAC JORNADA,
			DE_DESC_DEPE PROGRAMA_ACADEMICO,
			MA.DE_DESC_HITE MODALIDAD_ACADEMICA,	
			DX.DE_DESC_HITE DX_PRINCIPAL
		
		FROM PACIENTES INNER JOIN  (
					SELECT	NU_HIST_PAC_MOVI, NU_NUME_HICL, FE_FECH_HICL
					FROM	HISTORIACLINICA INNER JOIN LABORATORIO ON NU_NUME_LABO_HICL = NU_NUME_LABO
							INNER JOIN MOVI_CARGOS ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
					WHERE	NU_ESTA_MOVI <> 2
					AND		FE_FECINI_HICL BETWEEN V_INI AND V_FIN) MC ON NU_HIST_PAC = MC.NU_HIST_PAC_MOVI
				 LEFT JOIN PACIENTES_ANEXO_UNAL ON NU_HIST_PAC_PAU = NU_HIST_PAC
				 LEFT JOIN DEPENDENCIA ON CD_CODI_DEPE = CD_CODI_DEPE_PAU
				 LEFT JOIN HIST_TEXT DX ON DX.NU_NUME_HICL_HITE = MC.NU_NUME_HICL AND DX.NU_INDI_HITE = 258
				 LEFT JOIN HIST_TEXT MA ON MA.NU_NUME_HICL_HITE = MC.NU_NUME_HICL AND MA.NU_INDI_HITE = 5
		ORDER BY 7,3;
	
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;