CREATE OR REPLACE PROCEDURE H3i_SP_OBT_REGSCONS_ORTODONC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CD_CONSULTA IN NUMBER,
	CV_1 OUT SYS_REFCURSOR
)
	
AS
BEGIN
	OPEN CV_1 FOR
		SELECT CD_REGISTRO_CONS,
		CD_CONSULTA,
		NU_DIENTE,
		POS_DIENTE,
		ESTADO_DIENTE,
		VAL_POSANTERIOR,
		VAL_POSNUEVA,
		VAL_ROTACION,
		BOOL_BRACKET,
		VAL_POSBRACKET,
		BOOL_DIASTEMA,
		VAL_POSDIASTEMA
		FROM HIST_ORTODONCIA_REG_CONS
		WHERE CD_CONSULTA = V_CD_CONSULTA
		ORDER BY CD_REGISTRO_CONS ASC;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
