CREATE OR REPLACE PROCEDURE H3i_SP_CONSENT_INFOR_TOTALIZAD
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_INI IN DATE,
	V_FIN IN DATE,
	CV_1 OUT SYS_REFCURSOR	
)

AS
BEGIN
	OPEN CV_1 FOR
		SELECT	CANTIDAD,
				FC.DE_NOMB_FOCO TIPO_CONSENTIMIENTO,
				DE_DESC_DEPE PROCESO_O_PROGRAMA_ACADEMICO,
				MA.DE_DESC_HITE MODALIDAD_ACADEMICA,	
				ME.NO_NOMB_MED	MEDICO_QUE_REALIZA
		FROM	PACIENTES	INNER JOIN  (
									SELECT	NU_HIST_PAC_MOVI, NU_NUME_HICL, CD_MED_REAL_HICL
									FROM	HISTORIACLINICA INNER JOIN LABORATORIO ON NU_NUME_LABO_HICL = NU_NUME_LABO
											INNER JOIN MOVI_CARGOS ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
									WHERE	NU_ESTA_MOVI <> 2
									AND		FE_FECINI_HICL BETWEEN V_INI AND V_FIN
									GROUP	BY NU_HIST_PAC_MOVI, NU_NUME_HICL, CD_MED_REAL_HICL
									HAVING COUNT(NU_NUME_HICL) >=1) MC ON NU_HIST_PAC = MC.NU_HIST_PAC_MOVI
							INNER JOIN DEPENDENCIA ON NU_DEPENDENCIA_PAC = CD_CODI_DEPE
							INNER JOIN (    SELECT DISTINCT NU_NUME_FOCO_HCONSENT,COUNT (NU_NUME_FOCO_HCONSENT) CANTIDAD, NU_NUME_HICL_HCONSENT 
											FROM HIST_CONSENT 
											WHERE NU_NUME_FOCO_HCONSENT NOT IN (1,4) 
											GROUP BY NU_NUME_FOCO_HCONSENT,NU_NUME_HICL_HCONSENT) NUCO
										ON MC.NU_NUME_HICL = NU_NUME_HICL_HCONSENT
							INNER JOIN FORMATOS_CONSENTIMIENTO FC ON NU_NUME_FOCO_HCONSENT = FC.NU_NUME_FOCO
							INNER JOIN MEDICOS ME ON MC.CD_MED_REAL_HICL = ME.CD_CODI_MED
							LEFT JOIN HIST_TEXT MA ON MA.NU_NUME_HICL_HITE = MC.NU_NUME_HICL AND MA.NU_INDI_HITE = 5;
							
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
