CREATE OR REPLACE PROCEDURE H3I_SP_RPT_HC_SEGUI_DEPORTIVO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FechaIni DATE,
	V_FechaFin DATE,
	CV_1 OUT SYS_REFCURSOR
)
AS

BEGIN

	OPEN CV_1 FOR
		SELECT	P.TX_NOMBRECOMPLETO_PAC Nombre,
				MOSTRARTIPODOCUMENTO(P.NU_TIPD_PAC) TipoDocumento,
				P.NU_HIST_PAC NumeroDocumento,
				NVL((SELECT HTM.DE_DESC_HITE
				FROM	HIST_TEXT HTM
				WHERE NU_NUME_HICL_HITE= HC.NU_NUME_HICL
				AND	NU_INDI_HITE= 4),'') Proceso	,
				NVL((SELECT HTM.DE_DESC_HITE
				FROM	HIST_TEXT HTM
				WHERE NU_NUME_HICL_HITE= HC.NU_NUME_HICL
				AND	NU_INDI_HITE= 5),'') Modalidad,
				NVL(P.TX_JORNADA_PAC,'') Jornada,
				D.DE_DESC_DIAG Diagnostico,
				p.NU_ESTA_PAC Estado
		FROM	HISTORIACLINICA HC 
				INNER JOIN HIST_EVOLUCION HE ON HC.NU_NUME_HICL = HE.NU_NUME_HICL_HEVO
				INNER JOIN LABORATORIO L ON HC.NU_NUME_LABO_HICL = L.NU_NUME_LABO
				INNER JOIN MOVI_CARGOS M ON L.NU_NUME_MOVI_LABO = M.NU_NUME_MOVI
				INNER JOIN PACIENTES P ON M.NU_HIST_PAC_MOVI = P.NU_HIST_PAC
				LEFT JOIN R_LABO_DIAG RLD ON L.NU_NUME_LABO = RLD.NU_NUME_LABO_RLAD
				LEFT JOIN DIAGNOSTICO D ON RLD.CD_CODI_DIAG_RLAD = D.CD_CODI_DIAG  AND RLD.ID_TIPO_DIAG_RLAD = 'PR'		
		WHERE	HC.NU_NUME_PLHI_HICL= 1346
		and		hc.FE_FECH_HICL between V_FechaIni and (V_FechaFin+1);


EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;

