CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_CONS_ORTODONCIA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_INS_UP_CONS_PAC OUT NUMBER,
  v_CD_PACIENTE IN NUMBER,
  v_FECHA_CONS IN DATE,
  v_CD_SESION IN VARCHAR2,
  v_NU_LABO IN NUMBER,
  v_VAL_TIPOBRACKET IN VARCHAR2,
  v_VAL_MORDIDASUP IN VARCHAR2,
  v_VAL_MORDIDAINF IN VARCHAR2,
  v_VAL_POS_MORDIDASUP IN VARCHAR2,
  v_VAL_POS_MORDIDAINF IN VARCHAR2
)
AS

BEGIN

    INSERT INTO HIST_ORTODONCIA_CONSULTAS( 
        CD_PAC_ORTODONCIA, FE_CONS_ORTODONCIA, 
        CD_SES_ACT, CD_NUM_LABO, 
        VAL_TIPOBRACKET, VAL_MORD_SUP, 
        VAL_MORD_INF, VAL_POSMORD_SUP, 
        VAL_POSMORD_INF)
    VALUES ( 
        v_CD_PACIENTE, v_FECHA_CONS, 
        v_CD_SESION, v_NU_LABO, 
        v_VAL_TIPOBRACKET, v_VAL_MORDIDASUP, 
        v_VAL_MORDIDAINF, v_VAL_POS_MORDIDASUP, 
        v_VAL_POS_MORDIDAINF );

    SELECT CD_CONS_ORTOD 
    INTO v_CD_INS_UP_CONS_PAC 
    FROM HIST_ORTODONCIA_CONSULTAS
    WHERE CD_CONS_ORTOD = (SELECT MAX(CD_CONS_ORTOD) FROM HIST_ORTODONCIA_CONSULTAS);

 EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;