CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAANEXO3 --PROCEDIMIENTO ALMACENADO QUE GRABA LA JUSTIFICACIÓN DEL ANEXO3
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_ANEX IN NUMBER,
  v_NU_NUME_HEVO_ANEX IN NUMBER,
  v_NU_NUME_CONV_ANEX IN NUMBER,
  v_CD_CODI_MEDI_ANEX IN VARCHAR2,
  v_DE_DESC_ANEX IN VARCHAR2,
  v_NU_AUTO_ANEX OUT NUMBER
)
AS

BEGIN

    INSERT INTO ANEXO3( 
      FE_FECH_ANEX, NU_NUME_HICL_ANEX, 
      NU_NUME_HEVO_ANEX, NU_NUME_CONV_ANEX, 
      CD_CODI_MEDI_ANEX, DE_DESC_ANEX)
     VALUES( 
      SYSDATE, v_NU_NUME_HICL_ANEX, 
      v_NU_NUME_HEVO_ANEX, v_NU_NUME_CONV_ANEX, 
      v_CD_CODI_MEDI_ANEX, v_DE_DESC_ANEX);

  
    SELECT NU_AUTO_ANEX 
    INTO v_NU_AUTO_ANEX 
    FROM ANEXO3
    WHERE NU_AUTO_ANEX = (SELECT MAX(NU_AUTO_ANEX) FROM ANEXO3);

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;