CREATE OR REPLACE PROCEDURE H3i_SP_GUARDAR_NOTAS_SEG_PAC
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NU_NUME_HICL_HNSSPYP IN NUMBER,
  v_NU_NUME_HPSSPYP_HNSSPYP IN NUMBER,
  v_TXT_DESCRIPCION_HNSSPYP IN VARCHAR2
)
AS

BEGIN

   	INSERT INTO HIST_NOTA_SEG_SER_PYP( 
   		NU_NUME_HICL_HNSSPYP, NU_NUME_HPSSPYP_HNSSPYP, 
   		FECHA_REG_HNSSPYP, TXT_DESCRIPCION_HNSSPYP )
    VALUES ( 
     	v_NU_NUME_HICL_HNSSPYP, v_NU_NUME_HPSSPYP_HNSSPYP, 
     	SYSDATE, v_TXT_DESCRIPCION_HNSSPYP );

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;