CREATE OR REPLACE PROCEDURE H3i_SP_CREA_ASIG_DOCE_ESTU
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_NUME_CIT_ACDE IN NUMBER,
  v_FECHA IN DATE,
  v_CODI_DOCENTE IN VARCHAR2,
  v_CODI_ESTUDIANTE IN VARCHAR2
)
AS
   v_temp NUMBER(1, 0) := 0;

BEGIN

   BEGIN
      SELECT 1 INTO v_temp
        FROM DUAL
       WHERE ( SELECT COUNT(*)  
               FROM ASIG_CITA_DOCENTE_ESTUDIANTE 
                WHERE  NU_NUME_CIT_ACDE = v_NUME_CIT_ACDE ) = 1;
   EXCEPTION
      WHEN OTHERS THEN
         NULL;
   END;
      
   IF v_temp = 1 THEN
    
   BEGIN
      UPDATE ASIG_CITA_DOCENTE_ESTUDIANTE
         SET FECH_ACDE = v_FECHA,
             CD_CODI_MEDI_EST_ACDE = v_CODI_ESTUDIANTE,
             CD_CODI_MEDI_AUT_ACDE = v_CODI_DOCENTE
       WHERE  NU_NUME_CIT_ACDE = v_NUME_CIT_ACDE;
   
   END;
   ELSE
      INSERT INTO ASIG_CITA_DOCENTE_ESTUDIANTE
        ( NU_NUME_CIT_ACDE, FECH_ACDE, CD_CODI_MEDI_EST_ACDE, CD_CODI_MEDI_AUT_ACDE )
        VALUES ( v_NUME_CIT_ACDE, v_FECHA, v_CODI_ESTUDIANTE, v_CODI_DOCENTE );
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;