CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_CONTACTOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_FECHAINI IN DATE,
  v_FECHAFIN IN DATE,
  v_TIPOCONTACTO IN NUMBER,
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   OPEN  cv_1 FOR
      SELECT CONT.CD_CODI_CONT ID  ,
             LUA.NO_NOMB_LUAT LUGAR_ATENCION  ,
             EPS.NO_NOMB_EPS EPS  ,
             ESPE.NO_NOMB_ESP ESPECIALIDAD  ,
             MED.NO_NOMB_MED PROFESIONAL  ,
             CONT.FE_CITA_CONT FECHACITA  ,
             PAC.NU_TIPD_PAC TIPODOC  ,
             PAC.TX_NOMBRECOMPLETO_PAC NOMBREPAC  ,
             PAC.NU_DOCU_PAC DOCUPAC  ,
             PAC.DE_DIRE_PAC DIRECCIONPAC  ,
             PAC.DE_TELE_PAC TELEFONOPAC  ,
             CONT.TX_MOTI_INAS MOTIVO  ,
             CONT.FE_HORA_CONT FECHACONTACTO  ,
             CONT.NOM_PERSO_CONT PERSORECIBE  ,
             ( SELECT CASE 
                           WHEN CONT.ES_ASIGNA_CITA = 1 THEN 'SI'
                           WHEN CONT.ES_ASIGNA_CITA = 0 THEN 'NO'   END col  
                 FROM DUAL  ) ASIGNOCITA  
        FROM CONTACTO_INASISTENCIA CONT
               INNER JOIN LUGAR_ATENCION LUA   ON LUA.CD_CODI_LUAT = CONT.CD_CODI_LUAT
               INNER JOIN EPS EPS   ON EPS.CD_NIT_EPS = CONT.CD_CODI_EPS
               INNER JOIN ESPECIALIDADES ESPE   ON ESPE.CD_CODI_ESP = CONT.CD_CODI_ESPE
               INNER JOIN MEDICOS MED   ON MED.CD_CODI_MED = CONT.CD_CODI_PROF_CONT
               INNER JOIN PACIENTES PAC   ON PAC.NU_DOCU_PAC = CONT.CD_DOCU_PACIENTE
       WHERE  CONT.FE_HORA_CONT BETWEEN v_FECHAINI AND v_FECHAFIN
                AND CONT.ES_TIPO_CONT = v_TIPOCONTACTO ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;