CREATE OR REPLACE PROCEDURE H3i_SP_RECU_CITAS_DISPONIBLES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_FECHA IN DATE,
	V_FECHA_INICIO IN DATE,
	V_CD_MED VARCHAR2,
	V_NUM_TUR NUMBER,
	V_ES_GRUPAL NUMBER,
	CV_1 OUT SYS_REFCURSOR
)

AS	
BEGIN

	IF V_ES_GRUPAL = 1 THEN
		BEGIN
			OPEN CV_1 FOR
				SELECT NU_TUME_CIDI,
				  	CD_MED_CIDI,
				  	FE_FECH_CIDI,
				  	FE_HOIN_CIDI,
				  	FE_HOFI_CIDI,
				  	NU_DURA_CIDI,
				  	NU_AUTO_CIDI
				FROM CITAS_DISPONIBLES
				WHERE FE_HOIN_CIDI <= V_FECHA_INICIO AND
					FE_HOFI_CIDI > V_FECHA_INICIO AND
					TO_CHAR(FE_FECH_CIDI,'YYYY') = TO_CHAR(V_FECHA,'YYYY') AND
					TO_CHAR(FE_FECH_CIDI,'MM') = TO_CHAR(V_FECHA,'MM') AND
					TO_CHAR(FE_FECH_CIDI,'DD') = TO_CHAR(V_FECHA,'DD') AND
					CD_MED_CIDI = V_CD_MED AND 
					NU_TUME_CIDI = V_NUM_TUR
					
			 UNION ALL
			  
				SELECT distinct NU_NUME_TUME AS NU_TUME_CIDI,
					CD_CODI_MED_CIT AS CD_MED_CID,
					TO_DATE(FE_FECH_CIT) AS FE_FECH_CIDI,
					TO_DATE(FE_FECH_CIT) AS FE_HOFI_CIDI,
					TO_DATE(FE_FECH_CIT + NU_DURA_CIT / 1440) AS FE_HOFI_CIDI,
					NU_DURA_CIT AS NU_DURA_CIDI,
					0 AS NU_AUTO_CIDI
				FROM CITAS_MEDICAS 
				INNER JOIN TURNOS_MEDICOS 
					ON TO_DATE(FE_FECH_TUME) = TO_DATE(FE_FECH_CIT)
				WHERE CD_CODI_MED_CIT = V_CD_MED AND
					NU_NUME_TUME = V_NUM_TUR AND
					TO_DATE(FE_FECH_CIT) = V_FECHA AND
					TO_DATE(FE_FECH_CIT) <= V_FECHA_INICIO AND
					TO_DATE(FE_FECH_CIT + NU_DURA_CIT / 1440) > V_FECHA_INICIO;
		END;
	ELSE
		BEGIN
			OPEN CV_1 FOR
				SELECT NU_TUME_CIDI,
					CD_MED_CIDI,
				  	FE_FECH_CIDI,
				  	FE_HOIN_CIDI,
				  	FE_HOFI_CIDI,
				  	NU_DURA_CIDI,
				  	NU_AUTO_CIDI
				FROM CITAS_DISPONIBLES
				where FE_HOIN_CIDI <= V_FECHA_INICIO AND
					FE_HOFI_CIDI > V_FECHA_INICIO AND
					TO_CHAR(FE_FECH_CIDI,'YYYY') = TO_CHAR(V_FECHA,'YYYY') AND
					TO_CHAR(FE_FECH_CIDI,'MM') = TO_CHAR(V_FECHA,'MM') AND
					TO_CHAR(FE_FECH_CIDI,'DD') = TO_CHAR(V_FECHA,'DD') AND
					CD_MED_CIDI = V_CD_MED AND 
					NU_TUME_CIDI = V_NUM_TUR;
		END;
	END IF;
END;