CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_PACTOTALPYP
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  cv_1 OUT SYS_REFCURSOR
)
AS

BEGIN

   --calcula todos los pacientes que no estan en ninguna actividad de pyp y los agrupa por servicio
   DELETE FROM tt_TOTAL_PAC_NOPYP;
   UTILS.IDENTITY_RESET('tt_TOTAL_PAC_NOPYP');
   
   INSERT INTO tt_TOTAL_PAC_NOPYP ( 
   	SELECT CD_CODI_SER_RSA ,
           COUNT(P.NU_HIST_PAC)  CANT_NOPYP  
   	  FROM PACIENTES P,
           R_SER_ACTI RSA
             JOIN ACTIVIDAD_PYP AP   ON AP.CD_CODI_ACTI = RSA.CD_CODI_ACTI_RSA
             JOIN FREC_SER_POBLA FSP   ON RSA.NU_CONS_RSA = FSP.NU_CONS_RSA_FREC
             JOIN GRUPO_POBLA GP   ON FSP.CD_CODI_GP_FREC = GP.CD_CODI_GP
             JOIN CONDICION_POBLA CP   ON GP.CD_CODI_GP = CP.CD_CODI_GP_CP
   	 WHERE  CalcularEdad(P.FE_NACI_PAC, SYSDATE, 0) BETWEEN CP.NU_EDAD_INI_CP AND CP.NU_EDAD_FIN_CP
              AND CalcularEdad(FE_NACI_PAC, SYSDATE, 1) = CP.NU_MED_EDAD_CP
   	  GROUP BY CD_CODI_SER_RSA );
   --calcula todos los pacientes que estan en actividad de pyp y los agrupa por servicio
   DELETE FROM tt_TOTAL_PAC_PYP;
   UTILS.IDENTITY_RESET('tt_TOTAL_PAC_PYP');
   
   INSERT INTO tt_TOTAL_PAC_PYP ( 
   	SELECT CD_CODI_SER_RSA ,
           COUNT(P.NU_HIST_PAC)  CANT_PYP  
   	  FROM MOVI_CARGOS C
             JOIN PACIENTES P   ON P.NU_HIST_PAC = C.NU_HIST_PAC_MOVI
             JOIN LABORATORIO LAB   ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
             JOIN HISTORIACLINICA HC   ON NU_NUME_LABO_HICL = NU_NUME_LABO
             JOIN SERVICIOS S   ON LAB.CD_CODI_SER_LABO = S.CD_CODI_SER
             JOIN R_SER_ACTI RSA   ON RSA.CD_CODI_SER_RSA = S.CD_CODI_SER
             JOIN ACTIVIDAD_PYP AP   ON AP.CD_CODI_ACTI = RSA.CD_CODI_ACTI_RSA
             JOIN FREC_SER_POBLA FSP   ON RSA.NU_CONS_RSA = FSP.NU_CONS_RSA_FREC
             JOIN GRUPO_POBLA GP   ON FSP.CD_CODI_GP_FREC = GP.CD_CODI_GP
             JOIN CONDICION_POBLA CP   ON GP.CD_CODI_GP = CP.CD_CODI_GP_CP
   	 WHERE  CalcularEdad(FE_NACI_PAC, SYSDATE, 0) BETWEEN CP.NU_EDAD_INI_CP AND CP.NU_EDAD_FIN_CP
              AND CalcularEdad(FE_NACI_PAC, SYSDATE, 1) = CP.NU_MED_EDAD_CP
   	  GROUP BY CD_CODI_SER_RSA );
   ---- se unen las tablas para saber cuales estan en pyp y cuales no
   OPEN  cv_1 FOR
      SELECT CD_CODI_ACTI ,
             NO_NOMB_ACTI ,
             CD_CODI_SER ,
             NO_NOMB_SER ,
             CANT_PYP ,
             ABS(UTILS.CONVERT_TO_NUMBER(CANT_PYP / UTILS.CONVERT_TO_NUMBER(CANT_NOPYP,20,4) * 100,20,4)) POR_PYP  ,
             CANT_NOPYP ,
             ABS(UTILS.CONVERT_TO_NUMBER(CANT_PYP / UTILS.CONVERT_TO_NUMBER(CANT_NOPYP,20,4) * 100 - 100,20,4)) POR_NOPYP  ,
             (CANT_PYP + CANT_NOPYP) TOTAL  
        FROM tt_TOTAL_PAC_PYP TPP
               JOIN tt_TOTAL_PAC_NOPYP TPN   ON TPP.CD_CODI_SER_RSA = TPN.CD_CODI_SER_RSA
               JOIN SERVICIOS S   ON S.CD_CODI_SER = TPN.CD_CODI_SER_RSA
               JOIN R_SER_ACTI RSA   ON RSA.CD_CODI_SER_RSA = S.CD_CODI_SER
               JOIN ACTIVIDAD_PYP AP   ON AP.CD_CODI_ACTI = RSA.CD_CODI_ACTI_RSA ;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;