CREATE OR REPLACE PROCEDURE H3i_SP_PYP_CONS_ALRT_PARM_ACTI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_NUM_HIST_PAC IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
	
AS
	V_EDAD_PAC NUMBER;
	V_SEXO NUMBER;
	V_TIPO_EDAD NUMBER;
	V_GESTANTE NUMBER;
BEGIN
	
	SELECT TO_NUMBER(NU_SEXO_PAC),
		CalcularEdad(FE_NACI_PAC, SYSDATE, 0),
		CalcularEdad(FE_NACI_PAC, SYSDATE, 1),
		NVL(NU_GEST_PAC, 0)
	INTO V_SEXO, V_EDAD_PAC, V_TIPO_EDAD, V_GESTANTE
	FROM PACIENTES
	WHERE NU_HIST_PAC = V_NUM_HIST_PAC;


	OPEN CV_1 FOR 
		SELECT CD_CODI_ACTI_RSA AS CD_CODI_ACTI_PYPPAC,
			NO_NOMB_ACTI AS NOMBRE_ACTIVIDAD,
			CD_CODI_SER_LABO AS COD_SERVICIO,
			FE_FECH_HICL,
			'EnActividad' AS ESTADO_PYP,
			'' AS NOMBRE_CONCEPTO,
			'' AS VALOR_PYPPAC
		FROM HISTORIACLINICA 
		INNER JOIN LABORATORIO 
			ON NU_NUME_LABO = NU_NUME_LABO_HICL
		INNER JOIN MOVI_CARGOS 
			ON NU_NUME_MOVI = NU_NUME_MOVI_LABO
		INNER JOIN R_SER_ACTI 
			ON CD_CODI_SER_RSA = CD_CODI_SER_LABO 
			AND CD_CODI_PLANTILLA = NU_NUME_PLHI_HICL
		INNER JOIN ACTIVIDAD_PYP 
			ON CD_CODI_ACTI = CD_CODI_ACTI_RSA
		WHERE NU_HIST_PAC_MOVI = V_NUM_HIST_PAC

	UNION ALL

		SELECT AP.CD_CODI_ACTI AS CD_CODI_ACTI_PYPPAC,
			AP.NO_NOMB_ACTI AS NOMBRE_ACTIVIDAD,
			RAS.CD_CODI_SER_RSA AS COD_SERVICIO,
			SYSDATE AS FE_FECH_HICL,
			'AlertaAtencion' AS ESTADO_PYP,
			'' AS NOMBRE_CONCEPTO,
			'' AS VALOR_PYPPAC
		FROM ACTIVIDAD_PYP AP 
		INNER JOIN R_SER_ACTI RAS 
			ON AP.CD_CODI_ACTI = RAS.CD_CODI_ACTI_RSA 
		INNER JOIN FREC_SER_POBLA SER 
			ON RAS.NU_CONS_RSA = SER.NU_CONS_RSA_FREC
		INNER JOIN GRUPO_POBLA GP 
			ON SER.CD_CODI_GP_FREC = GP.CD_CODI_GP
		INNER JOIN CONDICION_POBLA CP 
			ON GP.CD_CODI_GP = CP.CD_CODI_GP_CP
		WHERE CP.NU_MED_EDAD_CP = V_TIPO_EDAD
				AND V_EDAD_PAC >= CP.NU_EDAD_INI_CP
				AND V_EDAD_PAC <= CP.NU_EDAD_FIN_CP
				AND (CP.NU_SEXO_CP = V_SEXO OR CP.NU_SEXO_CP = 2)
				AND CP.NU_GEST_CP = V_GESTANTE;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;