CREATE OR REPLACE PROCEDURE H3i_SP_ACTUAL_FREC_ELEM
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_GP_RAG IN VARCHAR2,
  v_COD_ELEMENTO_REL IN NUMBER,
  v_FRECUENCIA IN FLOAT
)
AS

BEGIN

   UPDATE R_ARTI_GRPOB
      SET NU_VALOR_RAG = v_FRECUENCIA
    WHERE  NU_AUTO_RARA_RAG = v_COD_ELEMENTO_REL
     AND CD_CODI_GP_RAG = v_CD_CODI_GP_RAG;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;