CREATE OR REPLACE PROCEDURE H3i_SP_UPDATE_ESTRATEGIA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_CD_CODI_EST IN VARCHAR2,
  v_NO_NOMB_EST IN VARCHAR2,
  v_DE_DESCRIP_EST IN VARCHAR2,
  v_NU_NUME_ESTADO_EST IN NUMBER
)
AS

BEGIN

   UPDATE ESTRATEGIA
      SET NO_NOMB_EST = v_NO_NOMB_EST,
          DE_DESCRIP_EST = v_DE_DESCRIP_EST,
          NU_NUME_ESTADO_EST = v_NU_NUME_ESTADO_EST
    WHERE  CD_CODI_EST = v_CD_CODI_EST;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;