CREATE OR REPLACE PROCEDURE H3i_SP_BUSCaCT_PYPSUB_PROGUNAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_NU_CODI_PRSA OUT NUMBER,
 	CV_1 OUT SYS_REFCURSOR
 )
					
AS
BEGIN
	OPEN CV_1 FOR
		SELECT CD_CODI_ACTI,
	      	NO_NOMB_ACTI
	 	FROM R_SUB_PROG_ACT_PYP 
	 	INNER JOIN ACTIVIDAD_PYP 
	 		ON CD_CODI_ACTI = CD_CODI_ACTI_RSPAPYP
	  	WHERE NU_CODI_SUBP_RSPAPYP = V_NU_CODI_PRSA;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);

END;
	