CREATE OR REPLACE PROCEDURE H3i_SP_OBTNR_ELEMT_X_ACTIVI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_COD_ACTIVIDAD VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
)
		
AS
BEGIN
	OPEN CV_1 FOR 
		SELECT ART.CD_CODI_ARTI CODIGO,
			ART.NO_NOMB_ARTI NOMBRE,
			RAC.NU_AUTO_RARA CODRELACION
		FROM ARTICULO ART
		INNER JOIN R_ARTI_ACTI RAC
		ON ART.CD_CODI_ARTI = RAC.CD_CODI_ARTI_RARA
		WHERE CD_CODI_ACTI_RARA	= V_COD_ACTIVIDAD;
		
EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;