CREATE OR REPLACE PROCEDURE SP_AUTOGES_ASIGNAR_ROLESPACIAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_CEDULA_EMPLEADO IN EMPLEADOS_BASIC.CEDULA%TYPE,         -- 
	V_IN_COD_ROLESPECIAL IN T_ROL_ESPECIAL.COD_ROL_ESPECIAL%TYPE,
	V_OUT_MENSAJE OUT VARCHAR2
)
AS 
	EXISTE_ASIG NUMBER; -- IDENTIFICAR SI YA TIENE ASIGNADO UN ROL 
BEGIN
	-- SI EXISTE EL EMPLEADO
	SELECT COUNT(*)	
	INTO EXISTE_ASIG
	FROM EMPLEADOS_BASIC
	WHERE CEDULA = V_IN_CEDULA_EMPLEADO;

	IF(EXISTE_ASIG >= 1) THEN
		BEGIN
			SELECT COUNT(*)
			INTO EXISTE_ASIG
			FROM T_USUARIO_ROL_ESPECIAL
			WHERE COD_USUARIO_ESPECIAL = V_IN_CEDULA_EMPLEADO;

			--SI EXISTE UN REGISTRO CON EL CODIGO SE ACTUALIZA SU ROL, DE LO CONTRARIO SE INSERTA SU NUEVO ROL
			IF(EXISTE_ASIG = 1) THEN
				BEGIN
					UPDATE T_USUARIO_ROL_ESPECIAL
					SET COD_ROL_ESPECIAL = V_IN_COD_ROLESPECIAL
					WHERE COD_USUARIO_ESPECIAL = V_IN_CEDULA_EMPLEADO;

					V_OUT_MENSAJE := 'El rol del usuario '||V_IN_CEDULA_EMPLEADO||' ha sido actualizado.';
				END;
			ELSE
				BEGIN
					INSERT INTO T_USUARIO_ROL_ESPECIAL
					VALUES (V_IN_CEDULA_EMPLEADO, V_IN_COD_ROLESPECIAL);

					V_OUT_MENSAJE := 'El rol ha sido asignado al usuario '||V_IN_CEDULA_EMPLEADO||'.';
				END;
			END IF;
		END;
	ELSE
		BEGIN
			V_OUT_MENSAJE := 'La usuario con cedula '||V_IN_CEDULA_EMPLEADO||' no se encuentra registrado en nomina.';
		END;
	END IF;
END;