CREATE OR REPLACE PROCEDURE SP_AUTOGES_CREAR_ROLESPECIAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_NOMBRE_ROL IN VARCHAR2,  -- NOMBRE DEL ROL ESPECIAL A CREAR
	V_IN_DESCRIPCION IN VARCHAR2, -- DESCRIPCION DEL ROL
	V_IN_SUBMENUS IN VARCHAR2, 	  -- SUBMENUS ASIGANADAS AL ROL QUE SE CREA
	V_OUT_MENSAJE OUT VARCHAR2	  -- MENSAJE DE LA ACCION OCURRIDA
)
AS
	CODIGO_ROL_CREADO NUMBER;         --CODIGO ASIGNADO AL ROL QUE SE CREA 
	ARRAY_DATOS ARRAY_DE_DATOS_TYPE;  -- CODIGOS DE LOS SUBMENUS ASIGNADOS AL ROL 
	CANTIDAD_DATOS NUMBER;			  -- CANTIDAD DE DATOS EN ARRAY
	EXISTE_SUBMENUS NUMBER;			  -- CANTIDAD DE SUBMENUS CORRECTOS A LS INGRESADOS
	SENTENCIA_SQL VARCHAR(1000);      -- SENTENCIA SQL PARA VALIDAR CODIGOS
BEGIN
	-- SEPARAMOS LOS DATOS Y SE ALMACENAN EN UN ARRAY
	SP_AUTOGES_SUBMENUS_ASIGNADOS(V_IN_SUBMENUS,ARRAY_DATOS,CANTIDAD_DATOS);

	-- SE COMPRUEBA QUE LOS CODIGOS INGRESADOS SON VALIDOS
	SENTENCIA_SQL := 'SELECT COUNT(*) FROM T_SUB_MENU WHERE COD_SUB_MENU IN ('||V_IN_SUBMENUS||')';
	EXECUTE IMMEDIATE SENTENCIA_SQL INTO EXISTE_SUBMENUS;

	IF(EXISTE_SUBMENUS <> CANTIDAD_DATOS) THEN
		BEGIN
			V_OUT_MENSAJE := 'Algun(os) codigo(s) no coincide(n) con los submenus existentes';
		END;
	ELSE
		BEGIN			
			-- CREAR EL ROL
			INSERT INTO T_ROL_ESPECIAL (
				NOM_ROL_ESPECIAL, DESCRIPCION)
			VALUES (
				V_IN_NOMBRE_ROL, V_IN_DESCRIPCION);
			-- CODIGO ASIGNADO AL ROL CREADO
			SELECT MAX(COD_ROL_ESPECIAL) 
			INTO CODIGO_ROL_CREADO 
			FROM T_ROL_ESPECIAL;
			-- INSERTAMS LOS SUBMENUS ASIGNADOS AL ROL CREADO
			FOR I IN 1..CANTIDAD_DATOS
			LOOP
				INSERT INTO T_REL_SUBMENU_ESPECIAL
				VALUES(CODIGO_ROL_CREADO,ARRAY_DATOS(I));
			END LOOP;

			V_OUT_MENSAJE := 'Rol especial creado correctamente';
		END;
	END IF;
END;