CREATE OR REPLACE PROCEDURE SP_AUTOGES_SUBMENUITEM_SPECIAL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_CEDULA_EPL IN EMPLEADOS_BASIC.COD_EPL%TYPE,
	V_OUT_SUBMENU OUT SYS_REFCURSOR
)
AS
	ITEM_MENU NUMBER;				 -- DATOS DEVUELTOS EN EL CURSOR
	CURSOR CURSOR_SUBMENU_COD IS 		 -- CODIGOS DE TODOS LOS MENUS EXISTENTES
		SELECT COD_SUB_MENU 
		FROM T_SUB_MENU;   
	CURSOR CURSOR_SUBMENU IS		 -- CURSOR CONSULTA ITEM DE SUBMENU ASIGNADOS AL ROL ESPECIAL
		SELECT TRSE.T_SUB_MENU
		FROM T_REL_SUBMENU_ESPECIAL TRSE 	
		INNER JOIN T_ROL_ESPECIAL TRE
		    ON TRE.COD_ROL_ESPECIAL = TRSE.COD_ROL_ESPECIAL
		INNER JOIN T_USUARIO_ROL_ESPECIAL TURE
		    ON TURE.COD_ROL_ESPECIAL = TRE.COD_ROL_ESPECIAL
		    AND TURE.COD_USUARIO_ESPECIAL = V_IN_CEDULA_EPL;
BEGIN
	DELETE FROM TT_SUBMENU;
	-- INSERTO TODOS LOS MENUS EN FALSO
	OPEN CURSOR_SUBMENU_COD;
	
	LOOP
		FETCH CURSOR_SUBMENU_COD INTO ITEM_MENU;
		EXIT WHEN CURSOR_SUBMENU_COD%NOTFOUND;		

		INSERT INTO TT_SUBMENU VALUES(ITEM_MENU,'FALSE');
	END LOOP;

	CLOSE CURSOR_SUBMENU_COD;

	-- ACTUALIZO LOS SUBMENUS QUE ESTAN ASIGNADOS AL ROL EN VERDADERO
	OPEN CURSOR_SUBMENU;	

	LOOP
		FETCH CURSOR_SUBMENU INTO ITEM_MENU;
		EXIT WHEN CURSOR_SUBMENU%NOTFOUND;

		UPDATE TT_SUBMENU 
		SET VALOR = 'TRUE'
		WHERE SUBMENU = ITEM_MENU;		
	END LOOP;

	CLOSE CURSOR_SUBMENU;

	OPEN V_OUT_SUBMENU FOR
		SELECT TTS.SUBMENU,TSM.NOM_SUB_MENU,TTS.VALOR
		FROM T_SUB_MENU TSM
		INNER JOIN TT_SUBMENU TTS
			ON TTS.SUBMENU = TSM.COD_SUB_MENU;	
END;