CREATE OR REPLACE PROCEDURE SP_AUTOGES_SUBMENUS_ASIGNADOS
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_IN_DATOS IN VARCHAR2,		    	-- VARIABLE QUE CONTIENE TODOS LOS DATOS INSERTADOS SEPARADOS POR COMAS
	ARRAY_DATOS OUT ARRAY_DE_DATOS_TYPE,
	V_OUT_NUM_DATOS  OUT NUMBER
)
AS
	POSICION NUMBER := 1;				    -- POSICION DONDE ARRANCA A LEER LOS DATOS
    DATOS_ING VARCHAR2(1000) := V_IN_DATOS; -- CADENA DE DATOS SEPARADOS POR COMAS (,)
    DATOS_CON VARCHAR2(1000) := V_IN_DATOS; -- CADENA PARA CALCULAR TAMANO
    CONTADOR NUMBER := 1;				    -- POSICION DEL ARRAY PARA GRABAR LOS DATOS
    TAMANO_ARRAY NUMBER;					-- TAMANO DEL ARRAY DE DATOS A RETORNAR
BEGIN
	-- CALCULAMOS EL TAMAñO QUE VA A TENER EL ARRAY 
	TAMANO_ARRAY := LENGTH(DATOS_CON) - LENGTH(REPLACE(DATOS_CON,',')) + 1;
	V_OUT_NUM_DATOS := TAMANO_ARRAY;
	-- DECLARAMOS EL TAMAñO DEL ARRAY 
	ARRAY_DATOS := ARRAY_DE_DATOS_TYPE();
    ARRAY_DATOS.EXTEND(TAMANO_ARRAY);

    -- CICLO DE LLENADO DEL ARRAY 
	LOOP
		IF(INSTR(DATOS_ING,',') = 0) THEN
			BEGIN
				ARRAY_DATOS(CONTADOR) := SUBSTR(DATOS_ING,1);
				EXIT;
			END;
		ELSE
			BEGIN
				POSICION := INSTR (DATOS_ING, ',') - 1;
			END;
		END IF;
		ARRAY_DATOS(CONTADOR) := SUBSTR (DATOS_ING, 1, POSICION);
		DATOS_ING := SUBSTR(DATOS_ING,POSICION+2);
		CONTADOR:= CONTADOR +1;
	END LOOP;
END;