CREATE OR REPLACE PACKAGE PKG_ACOMER_PROCEDURES
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
AS
-- =============================================
-- ARRAY DE LOS PEDIDOS REALIZADOS
	TYPE TYPE_PEDIDOS_ARRAY IS TABLE OF VARCHAR(100) INDEX BY BINARY_INTEGER;  	

-- =============================================
-- ARRAY CON LA CAPACIDAD QUE TIENE CADA COCINA DE CADA CONTENEDOS EN PREPARAR UN PLATO
	TYPE TYPE_CAPACIDAD_CONTAINER IS TABLE OF NUMBER INDEX BY VARCHAR2(64);	

-- =============================================
-- CODIGOS DE LOS RESTAURANTES (CONTAINERS)
	PKG_CONTAINER1 GEN0006.EMPCOD%TYPE := '901.023.461-1';
	PKG_CONTAINER2 GEN0006.EMPCOD%TYPE := '901.023.461-2';
	PKG_CONTAINER3 GEN0006.EMPCOD%TYPE := '901.023.461-3';
	PKG_CONTAINER4 GEN0006.EMPCOD%TYPE := '901.023.461-4';

-- =============================================
-- CAPACIDAD DE CADA CONTAINER EN PREPARAR PLATOS AL MISMO TIEMPO
	PKG_CAPACIDAD_CONTAINER1 NUMBER := 10;
	PKG_CAPACIDAD_CONTAINER2 NUMBER := 10;
	PKG_CAPACIDAD_CONTAINER3 NUMBER := 10;
	PKG_CAPACIDAD_CONTAINER4 NUMBER := 10;

-- =============================================
-- MUESTRA LOS PEDIDOS EN COCINA
	PROCEDURE SP_ACOMER_PEDIDOS_COCINA
	(
		IN_CODIGO_COCINERO IN SEG0001.USUCED%TYPE,	-- CODIGO DEL COCINERO
		OUT_CONJUNTOS OUT SYS_REFCURSOR,			-- CONJUNTOS DE LOS PEDIDOS 
		OUT_MESA OUT SYS_REFCURSOR,					-- MESAS CON PEDIDOS
		OUT_PEDIDOS OUT SYS_REFCURSOR				-- PEDIDOS DETALLADOS DE LAS MESAS
	);

-- =============================================
-- INDICAR QUE EL PEDIDOS YA ESTA LISTO PARA ENTREGAR
	PROCEDURE SP_ACOMER_ENTREGA_PEDIDO
	(
		IN_CODIGO_EMPRESA VEN0004.PEDEMPC%TYPE, -- CODIGO DE LA EMPRESA A LA QUE PERTENECE EL PLATO
		IN_CODIGO_PEDIDO VEN0004.PEDNRO%TYPE,	-- CODIGO DE PEDIDO QUE SE LE ASIGNA AL PLATO
		IN_NOMBRE_PLATO VEN0004.PEDPROCOD%TYPE	-- CODIGO DEL PLATO QUE SE ESTA ENTREGANDO	
	);

-- =============================================
-- CATEGORIAS Y PLATOS QUE TIENE LOS 4 CONTAINERS
	PROCEDURE SP_ACOMER_MENU
	(
		CURSOR_CATEGORIAS OUT SYS_REFCURSOR,    -- CURSOR QUE TENDRA LOS DATOS DE  LAS CATEGORIAS DE COMIDAS
		CURSOR_SUBCATEGORIAS OUT SYS_REFCURSOR, -- CURSOR QUE TENDRA LOS DATOS DE LAS SUBCATEGORIAS DE COMIDAS
		CURSOR_TERMINOS OUT SYS_REFCURSOR,      -- CURSOR QUE TENDRA LOS DATOS DE LOS TERMINOS DE LA COMIDA EN CASO DE TENERLOS
		CURSOR_COMIDA OUT SYS_REFCURSOR			-- CRUSRO QUE TENDRA LOS DATOS DE CADA UNO DE LAS COMIDAD OFRECIDAS
	);

-- =============================================
-- PUESTOS QUE HAY POR FACTURAR EN LA NES
	PROCEDURE SP_aCOMER_FACTURA_PUESTOS
	(
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA
		OUT_CURSOR_PUESTOS OUT SYS_REFCURSOR   -- CURSOR CON LOS PUESTOS QUE FALTAN POR FACTURAR
	);

-- =============================================
-- FACTURACION DE UNA MESA
	PROCEDURE SP_ACOMER_FACTURACION
	(
		IN_CEDULA_CLIENTE IN VEN0104.PCLICOD%TYPE,  -- CEDULA DEL CLINETE QUE VA A FACTURAR
		IN_NOMBRE_COMPLETO IN VEN0104.PCLINOM%TYPE, -- NOMBRE COMPLETO DEL CLIENTE
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, 		-- CODIGO DE LA MESA DEL PEDIDO 
		IN_CELULA_MESERO IN SEG0001.USUCED%TYPE,    -- CEDULA DEL MESERIO
		IN_FORMA_PAGO VEN0104.PFPGCOD%TYPE,      	-- FORMA DE PAGO
		IN_PUESTOS_ARRAY IN TYPE_PEDIDOS_ARRAY,		-- PUESTOS QUE SE VAN A FACTURAR
		OUT_CURSOR_FACTURA OUT SYS_REFCURSOR,		-- CURSOR CON LOS DATOS DE LA CABECERA DE FACTURA
		OUR_CURSOR_FACTURA_C OUT SYS_REFCURSOR,     -- CURSOR PARA EL DETALLE DE LA FACTURA
		OUT_TOTAL_PAGAR OUT NUMBER 					-- TOTAL A PAGAR 
	);

-- =============================================
-- ACTUALIZACION DE LOS DATOS DEL PEDIDO
	PROCEDURE SP_ACOMER_FACTURACION_ACT
	(
		IN_TIPO_PRECIO IN GEN0024.LIPCOD%TYPE, -- PRECIO QUE SE LE DEBE AJUSTAR AL PEDUDO
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA DEL PEDIDO 
		IN_PUESTOS_ARRAY IN TYPE_PEDIDOS_ARRAY -- PUESTOS QUE SE VAN A FACTURAR
	);

-- =============================================
-- ACTUALIZA LOS DATOS DEL CLIENTE EN EL PEDIDO
	PROCEDURE SP_ACOMER_ACT_PEDIDO_CLI
	(
		IN_REGISTRADO_BD NUMBER, -- SABER SI YA ESTA REGISTRADO O NO
		IN_CEDULA_CLIENTE VEN0104.PCLICOD%TYPE, -- CEDULA DEL CLIENTE
		IN_NOMBRE_CLINETE VEN0104.PCLINOM%TYPE, -- NOMBRE DEL CLIENTE
		IN_FORMA_PAGO VEN0104.PFPGCOD%TYPE,      -- FORMA DE PAGO
		IN_CODIGO_EMPRESA GEN0006.EMPCOD%TYPE,	-- CODIGO DE LA EMPRESA
		IN_NUMERO_DOCUMENTO CNT00071.MOVDOCNRO%TYPE  -- CODIGO DEL PEDIDO 
	);

-- =============================================
-- INSERCION DE LA CABECERA Y EL DETALLE DE LA FACTURA
	PROCEDURE SP_ACOMER_FACTURACION_CAB_DET
	(
		IN_DOC_PEDIDO IN GEN0012.DOCCOD%TYPE,   		-- DOCUMENTO PEDIDO PD
		IN_CODIGO_PAIS IN GEN0006.EMPPAIC%TYPE, 		-- CODIGO DEL PAIS
		IN_CODIGO_EMPRESA IN GEN0006.EMPCOD%TYPE, 		-- CODIGO DE LA EMPRESA
		IN_NUMERO_DOCUMENTO IN CNT00071.MOVDOCNRO%TYPE, -- CODIGO DEL PEDIDO 
		IN_CODIGO_USUARIO IN SEG0001.USUID%TYPE,		-- CODIGO DEL USUARIO
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE,			-- CODIGO DE LA MESA
		OUT_NUMERO_FACTURA OUT VEN0008.FACNRO%TYPE 		-- NUMERO DE FACTURA QUE SE LE ASUGNA A LOS PEDIDOS 
	);

-- =============================================
-- LIBERAR LA MESA DESPUES DE UNA FACTURACION FINAL
	PROCEDURE SP_ACOMER_FACTURA_MESA_FIN
	(
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, 	-- CODIGO DE LA MESA DEL PEDIDO 	
		IN_PUESTOS IN NUMBER					-- SABER SI LA FACTURACION ES POR PUESTOS
	);

-- =============================================
-- ESTADO DE UNA MESA ESPECIFICADA
	PROCEDURE SP_ACOMER_ESTADO_MESA_FAC
	(
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE,  -- CODIGO DE LA MESA DEL PEDIDO 	
		OUT_ESTADO OUT NUMBER					 -- ESTADO DE LA MESA 
	);

-- =============================================
-- FACTURA QUE SE LE ENTREGA AL CLIENTE
	PROCEDURE SP_ACOMER_FACTURA_CLIENTE
	(
		IN_FECHA_FACTURA IN CAB_FACTURA_GRAL.FACFECHA%TYPE,	-- FECHA QUE SE FACTURA
		IN_HORA_FACTURA IN CAB_FACTURA_GRAL.FACHORA%TYPE,	-- HORA EN LA QUE SE FACTURA
		IN_FACTURA_GENERAL IN TYPE_PEDIDOS_ARRAY,	        -- NUMERO DE LA FACTURA GENERAL
		IN_CODIGO_MESERO IN INV00018.MESUSUREQ%TYPE,		-- CODIGO DEL MESERO
		IN_PORCENTAJE_PROPINA IN NUMBER,					-- PORCENTAJE DE LA PROPINA VOLUNTARIA 
		OUT_FACTURA_CLIENTE OUT SYS_REFCURSOR				-- DATOS DE LA FACTURA 
	);

-- =============================================
-- RESPALDO DE LOS DATOS DESPUES DE FACTURAR PARA REVERSAR LO HECHO
	PROCEDURE SP_ACOMER_FACTURA_RESPALDO
	(
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE, -- CODIGO DE LA MESA QUE SE SACARA RESPALDO DEL PEDIDO
		OUT_CODIGO_REVER OUT NUMBER				-- NUMERO DE REVER QUE SE LE ASIGNA
	);

-- =============================================
-- REVERSAR LA FACTURACION YA HECHA 
	PROCEDURE SP_ACOMER_FACTURACION_REVER
	(
		IN_NUMERO_FACTURA IN TAB_FACTURA_CLIENTE.FACNROCLI%TYPE, -- NUMERO DE LA FACTURA DEL CLIENTE
		IN_NUMERO_REVER IN NUMBER								 -- NUMERO DE REVER PARA LOS DATOS ALMACENADOS ANTES DEL CAMBIO
	);

-- =============================================
-- SABER QUE PEDIDOS DE QUE MESA ESTAN LISTO PARA ENTREGAR
	PROCEDURE SP_ACOMER_PEDIDOS_ENTREGAR
	(
		CURSOR_PEDIDOS OUT SYS_REFCURSOR  -- CURSOR QUE TRAE LOS PEDIDOS QUE YA ESTAN LISTOS PARA ENTREGAR
	);

-- =============================================
--	REALIZAR PEDIDOS DE UNA MESA 
	PROCEDURE SP_ACOMER_PEDIDOS
	(
		IN_PUESTOS_ARRAY IN OUT TYPE_PEDIDOS_ARRAY, 	 -- LOS PUESTOS DE DONDE FUERON SOLICITADOS LOS PEDIDOS
		IN_PRODUCTOS_ARRAY IN  OUT TYPE_PEDIDOS_ARRAY,   -- LOS CODIGOS DE LOS PRODUCTOS QUE SE ESTA PIDIENDO 
		IN_CANTIDAD_ARRAR IN OUT TYPE_PEDIDOS_ARRAY,	 -- LA CANTIDAD PEDIDA POR PRODDUCTO
		IN_TERMINO_ARRAY IN OUT TYPE_PEDIDOS_ARRAY,		 -- TERMINO DE LA COMIDA SI HA DE TENERLA 
		IN_CODIGO_MESERO IN SEG0001.USUCED%TYPE,		 -- CODIGO DEL MESERO 
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE      	 -- CODIGO DE LA MESA DONDE SE ESTA REALIZANDO DEL PEDIDO 	
	);

-- =============================================
-- SABER CUAL ES LA MESA PRINCIPAL  CUALES ESGAN UNIDAS A ELLA
	PROCEDURE SP_ACOMER_MESAS_UNIDAS
	(
		IN_CODIGO_MESA IN DETMESA.MESCOD%TYPE, -- CODIGO DE LA MESA QUE SE VA A BUSCAR SUS UNIONES
		OUT_MESAS_UNIDAS OUT SYS_REFCURSOR,    -- CURSOR QUE CONTIENE LAS MESAS QUE VAN UNIDAD EN LA MESA CLICKEADA
		OUT_MESA_PRINCIPAL OUT DETMESA.MESCOD%TYPE  -- CODIGO DE LA MESA PRINCIPAL
	);

-- =============================================
-- ADICIONAR PEDIDOS A UNA MESA
	PROCEDURE SP_ACOMER_PEDIDOS_ADD
	(	
		IN_PUESTOS_ARRAY IN OUT TYPE_PEDIDOS_ARRAY, 	 -- LOS PUESTOS DE DONDE FUERON SOLICITADOS LOS PEDIDOS
		IN_PRODUCTOS_ARRAY IN  OUT TYPE_PEDIDOS_ARRAY,   -- LOS CODIGOS DE LOS PRODUCTOS QUE SE ESTA PIDIENDO 
		IN_CANTIDAD_ARRAR IN OUT TYPE_PEDIDOS_ARRAY,	 -- LA CANTIDAD PEDIDA POR PRODDUCTO
		IN_TERMINO_ARRAY IN OUT TYPE_PEDIDOS_ARRAY,		 -- TERMINO DE LA COMIDA SI HA DE TENERLA 
		IN_CODIGO_MESERO IN SEG0001.USUCED%TYPE,		 -- CODIGO DEL MESERO 
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE      	 -- CODIGO DE LA MESA DONDE SE ESTA REALIZANDO DEL PEDIDO 	
	);

-- =============================================
-- UNIR MESAS CON LA RESPECTIVA CANTIDAD DE PUESTOS NECESARIOS
	PROCEDURE SP_ACOMER_UNION_MESAS
	(
		IN_MESA IN DETMESA.MESCOD%TYPE,			  -- CODIGO DE LA MESA
		IN_PUESTOS IN DETMESA.PUESTOS%TYPE, 	  -- CANTIDAD DE PUESTOS QUE SE VAN A USA 	
		IN_MESAS_ARRAY IN OUT TYPE_PEDIDOS_ARRAY  -- MESAS QUE SE UNEN
	);

-- =============================================
-- DETALLE DEL PEDIDO DE LA MESA
	PROCEDURE SP_ACOMER_DETALLE_PEDIDO
	(
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA QUE HA HECHO PEDIDO
		OUT_CURSOR OUT SYS_REFCURSOR
	);

-- =============================================
-- NOMBRE DEL PLATO QUE ES INGRESADO
	PROCEDURE SP_ACOMER_NOMBRE_PLATOS
	(
		IN_CODIGO_PLATO IN VEN0001.PROCOD%TYPE, -- CODIGO DEL PLATO QUE SE CONSULTA
		OUT_NOMBRE_PLATO OUT VEN0001.PRODES%TYPE, -- NOMBRE DEL PLATO
		OUT_NOMBRE_IMAGEN OUT INV0013.CATIMG%TYPE
	);

-- =============================================
-- CANCELAR PEDIDOS QUE YA ESTAN CONFIRMADOS
	PROCEDURE SP_ACOMER_PEDIDOS_CANCEL
	(
		IN_TIPO_CANCELAR IN NUMBER,			 		  -- MODO QUE SE CANCELA EL PEIDO
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE, 	  -- CODIGO DE LA MESA DONDE SE VA A CANCELAR EL PEDIDO
		IN_PLATOS_CANCELAR IN OUT TYPE_PEDIDOS_ARRAY, -- CODIGO DE LOS PLATOS QUE SE CANCELAN
		IN_CANTIDAD IN OUT TYPE_PEDIDOS_ARRAY,        -- CANTIDAD POR PLATO QUE SE CANCELAN 
		IN_PUESTO IN OUT TYPE_PEDIDOS_ARRAY, 		  -- PUESTO DONDE CANCELAN EL PEDIDO
		OUT_CODIGO_MENSAJE OUT NUMBER -- CODIGO DE MENSAJE
	);

-- =============================================
-- LOS DATOS DE LA FACTURA PARA PREVISUALIZARLA ANTES DE GENERARLA
	PROCEDURE SP_ACOMER_VISUALIZA_FAC
	(
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE,  -- CODIGO DE LA MESA DEL PEDIDO 	
		IN_PUESTOS_ARRAY IN TYPE_PEDIDOS_ARRAY,	-- PUESTOS QUE SE VAN A FACTURAR
		OUT_CURSOR_VISUALIZA OUT SYS_REFCURSOR,   -- CURSOR CON LOS DATOS DE LA CABECERA DE FACTURA
		OUT_FECHA OUT VARCHAR2
	);

-- =============================================
-- CONSULTA LAS MESAS QUE DEBEN ESTAR UNIDAS A ELLA
	PROCEDURE SP_ACOMER_MESA_PRINC_HIJOS
	(
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE, -- CODIGO DE LA MESA QUE HA HECHO PEDIDO
		OUT_MESAS OUT VARCHAR2				   -- MESAS QUE ESTAN UNIDAS EN EL PEDIDO
	);

-- =============================================
-- CARGA LAS MESAS EN LA PLAZA
	PROCEDURE SP_ACOMER_MESAS
	(
		CURSOR_MESAS OUT SYS_REFCURSOR --CURSOR QUE TENDRA LOS DATOS DE LA MESA (EMP, IDENTIFICADOR, PUESTOS, COORDENADAS)
	);

-- =============================================
-- LIBERAR LAS MESAS QUE SE ENCUENTREN UNIDAS ENTRE SI
	PROCEDURE SP_ACOMER_LIBERAR_MESA_UNIDA
	(
		IN_CODIGO_MESA IN VEN0104.MESCOD%TYPE 	-- CODIGO DE LA MESA DEL PEDIDO 	
	);

-- =============================================
-- ACTUALIZA EL PEDIDO DE UN PUESTO ESPECIFICO
	PROCEDURE SP_ACOMER_PEDIDOS_ACT
	(
		IN_CODIGO_PRODUCTO IN VEN0001.PROCOD%TYPE, -- CODIGO DEL ITEM QUE SE ADICIONARA
		IN_CODIGO_PEDIDO IN VEN0104.PEDNRO%TYPE,   -- CODIGO DEL PEDIDO QUE YA TIENE EN LA MESA
		IN_CODIGO_PUESTO IN VEN0004.CCOCOD%TYPE,   -- PUESTO DESDE DONDE SE ESTA PIDIENDO
		IN_CANTIDAD IN VEN0004.PEDUNI%TYPE		   -- CANTIDD DEL PRODUCTO QUE SE ESTA PIDIENDO 
	);

-- =============================================
-- INSERTA LA CABECERA DEL PEDIDO 
	PROCEDURE SP_ACOMER_PEDIDOS_CAB
	(
		IN_CODIGO_RESTAURANTE IN  GEN0006.EMPCOD%TYPE,	   -- RESTAURANTE AL CUAL SE LE HACE EL PEDIDO
		IN_CODIGO_DOCUMENTO_PEDIDO IN GEN0012.DOCCOD%TYPE, -- VDOCUMENTO DE PEDIDO PARA SABER EL NUMERO DE PEDIDO DEPENDIENDO EL RESTAURANTE 
		IN_CODIGO_MESERO IN SEG0001.USUID%TYPE,        	   -- CEDULA DEL MESERO QUE ESTA TOMANDO EL PEDIDO 
		IN_CODIGO_MESA_USADA IN INV00018.MESCOD%TYPE,	   -- CODIGO DE LA MESA
		OUT_NUMERO_PEDIDO OUT VEN0104.PEDNRO%TYPE		   -- CODIGO DEL PEDIDO
	);

-- =============================================
-- INSERTA EL DETALLE DEL PEDIDO
	PROCEDURE SP_ACOMER_PEDIDOS_DET
	(
		IN_CODIGO_RESTAURANTE IN  GEN0006.EMPCOD%TYPE,	   -- RESTAURANTE AL CUAL SE LE HACE EL PEDIDO
		IN_CODIGO_DOCUMENTO_PEDIDO IN GEN0012.DOCCOD%TYPE, -- VDOCUMENTO DE PEDIDO PARA SABER EL NUMERO DE PEDIDO DEPENDIENDO EL RESTAURANTE 
		IN_CODIGO_PEDIDO IN VEN0004.PEDNRO%TYPE,		   -- NUMERO DE PEDIDO
		IN_CODIGO_ITME IN VEN0001.PROCOD%TYPE,			   -- CODIGO DEL ALIMENTO O ITEM QUE SE ESTA PIDIENDO 
		IN_CODIGO_TERMINO IN VEN0004.PEDBODL%TYPE,		   -- CODIGO DEL TERMINO DE LA COMIDAS
		IN_PUESTO_MESA IN VEN0004.CCOCOD%TYPE,			   -- PUESTO DE MESA DEL CUAL SE ESTA SOLICITANDO
		IN_CANTIDAD IN VEN0004.PEDUNI%TYPE,				   -- CANTIDAD DEL PRODUCTO
		IN_CODIGO_MESERO IN SEG0001.USUID%TYPE        	   -- CEDULA DEL MESERO QUE ESTA TOMANDO EL PEDIDO 
	);

-- =============================================
-- CALCULAR LOS TIEMPOS QUE DEMORAN LOS PEDIDOS
	PROCEDURE SP_ACOMER_TIEMPO_PEDIDO;

-- =============================================
-- FUNCION PARA CALCULAR EL TIEMPO TRASCURRIDO DEL PEDIDO
	FUNCTION FN_TIEMPO_TRASCURRIDO_PEDIDO
	(
		IN_MESA NUMBER,			  -- CODIGO DE LA MESA
		IN_HORA_PEDIDO VARCHAR2,  -- HORA EN LA QUE EL PEDIDO FUE REALIZADO
	 	IN_TIEMPO_DEMORA NUMBER   -- NUMERO DE MINUTOS QUE DEMORA EL PEDIDO EN SER ENTREGADO A LA MESA
	)
	RETURN VARCHAR2;

-- =============================================
-- REGISTRO DE CLIENTES
	PROCEDURE SP_ACOMER_REGISTRO_CLIENTE
	(
		IN_CODIGO_CLIENTE IN GEN0024.CLICOD%TYPE, 	-- CODIGO DEL CLIENTE QUE VA HACER REGISTRADO
		IN_NOMBRE_CLINETE IN GEN0024.CLINOM1%TYPE,	-- NOMBRE DLE CLIENTE QUE SE VA A REGISTRAR
		IN_DIRECCION_CLIENTE IN GEN0024.SUCTERDIR%TYPE, -- DIRECCION DEL CLIENTE QUE SE VA A REGISTRAR
		IN_CORREO_CLIENTE IN GEN0024.CLICNT%TYPE,		-- CORREO DEL CLIENTE QUE SE VA A REGISTRAR
		IN_TELEFONO_CLIENTE IN GEN0024.SUCTERTEL%TYPE,  -- TELEFONO DEL CLIENTE QUE SE VA A REGISTRAR
		IN_CIUDAD_CLIENTE IN GEN0024.CLIDIRENT%TYPE,		-- CIUDAD DE DIRECCION DEL CLIENTE
		OUT_CODIGO_MENSAJE OUT NUMBER					-- CODIGO DE MENSAJE	
	);

-- =============================================
-- CONSULTA EL NOMBRE DEL CLIENTE PARA LA FACTURA
	PROCEDURE SP_ACOMER_DATOS_CLIENTE
	( 
		IN_CEDULA_CLIENTE IN GEN0024.CLICOD%TYPE, -- CODIGO DEL CLIENTE
		OUT_NOMBRE_CLIENTE OUT VARCHAR2 -- NOMBRE DEL CLIENTE
	);

-- =============================================
-- CODIGOS DE LOS RESTAURANTES
	PROCEDURE SP_ACOMER_CODIGO_CONTAINERS
	(
		OUT_CONTAINER1 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 1
		OUT_CONTAINER2 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 2
		OUT_CONTAINER3 OUT GEN0006.EMPCOD%TYPE,  -- CODIGO DEL CONTAINER 3
		OUT_CONTAINER4 OUT GEN0006.EMPCOD%TYPE   -- CODIGO DEL CONTAINER 4
	);

-- =============================================
-- CANCELAR LO RESTANTE POR ENTREGAR
	PROCEDURE SP_ACOMER_PEDIDOS_CANCEL_REST
	(
		IN_CODIGO_MESA IN INV00018.MESCOD%TYPE  -- CODIGO DE LA MESA QU SE CANCELA
	);

-- =============================================
-- SABER SI LAS MESAS UNIDAS (ENTRE TODAS) TIENEN YA ENTREGADO UN PEDIDO
	PROCEDURE SP_ACOMER_PED_ENTREG_MESUNIDA
	(
	    IN_MESA_PRINCIPAL IN NUMBER,
	    OUT_CODIGO_MENSAJE OUT NUMBER
	);

-- =============================================
-- PONER EL ESTADO DEL PEDIDO COMO ENTREGAGO
	PROCEDURE SP_ACOMER_ENTREGAR_PEDIDO_MESA
	(
		IN_PUESTOS IN TYPE_PEDIDOS_ARRAY, 				-- 
        IN_PLATOS IN TYPE_PEDIDOS_ARRAY,				--
		IN_NUMERO_DOCUMENTO IN VEN0104.PEDNUMDOC%TYPE,  -- NUMERO DE DOCUMENTO
		IN_CODIGO_EMPRESA IN VEN0004.PEDEMPC%TYPE 		-- CODIGO DE LA EMPRESA
	);

-- =============================================
-- HISTORIAL DE PEDIDOS EN COCINA YA HECHOS
	PROCEDURE SP_ACOMER_HISTORIAL_COCINA	 
	(
		IN_CODIGO_COCINERO IN GEN0011.TERCOD%TYPE, -- CODIGO DEL COCINERO QUE TERMINA EL PEDIDO
		IN_PLATO IN VEN0001.PRODES%TYPE,		   -- CODIGO DEL PLATO QUE TERMINA
		IN_CANTIDAD	IN VEN0004.PEDUNI%TYPE		   -- CANTIDAD DEL PLATO QUE HA TERMINADO 
	);

-- =============================================
-- CONSULTA EL HISTORIAL EN COCINA
	PROCEDURE SP_ACOMER_CONSULTA_HISTCOCINA
	(
		IN_CODIGO_COCINERO IN GEN0011.TERCOD%TYPE,
		OUT_CURSOR OUT SYS_REFCURSOR -- CRUSR CON LOS DATOS DEL HISTORIAL 
	);

-- =============================================
-- CONSULTA EL ROL 
	PROCEDURE SP_ACOMER_CONSULTA_ROL	 
	(
		IN_CEDULA IN TAB_REL_ROL.TERCOD%TYPE, -- CODIGO DE QUIEN INICIA SESION
		OUT_PERFIL OUT VARCHAR2				  -- PERFIL QUE POSEE QUIEN INICIA SESION
	);

-- =============================================
-- NOMBRE DE LA COCINA
	PROCEDURE SP_ACOMER_NOMBRE_COCINAS
	(
		IN_CEDULA IN TAB_REL_ROL.TERCOD%TYPE,			-- CEDULA DE QUIEN INCIIA
		OUT_NOMBRE_REST OUT GEN0006.EMPNOM%TYPE  		-- NOMBRE DE LA EMPRESA A LA QUE PERTENECE
	);
END;