CREATE OR REPLACE TRIGGER HIMS.ABONO_RECIBO_CAJA_CD_CODI_AB_1 BEFORE INSERT ON HIMS.ABONO_RECIBO_CAJA
FOR EACH ROW
DECLARE

BEGIN
    SELECT ABONO_RECIBO_CAJA_CD_CODI_ABRC.NEXTVAL
    INTO :NEW.CD_CODI_ABRC
    FROM DUAL;
END;
