CREATE OR REPLACE TRIGGER HIMS.ABONOS_GASTADOS_NU_NUME_ABGA_T BEFORE INSERT ON HIMS.ABONOS_GASTADOS
FOR EACH ROW
DECLARE

BEGIN
    SELECT ABONOS_GASTADOS_NU_NUME_ABGA_S.NEXTVAL
    INTO :NEW.NU_NUME_ABGA
    FROM DUAL;
END;
