CREATE OR REPLACE TRIGGER HIMS.ALT_NPOSM_NU_AUTO_ALTN_TRG BEFORE INSERT ON HIMS.ALT_NPOSM
FOR EACH ROW
DECLARE

BEGIN
    SELECT ALT_NPOSM_NU_AUTO_ALTN_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_ALTN
    FROM DUAL;
END;
/