CREATE OR REPLACE TRIGGER HIMS.AUDITAR_LOG_SINCRO_ERROR_AUT_1 BEFORE INSERT ON HIMS.AUDITAR_LOG_SINCRO_ERROR
FOR EACH ROW
DECLARE

BEGIN
    SELECT AUDITAR_LOG_SINCRO_ERROR_AUTO_.NEXTVAL
    INTO :NEW.AUTO_LOG_SINCR_ERR_ALSE
    FROM DUAL;
END;
/