CREATE OR REPLACE TRIGGER HIMS.AUDITAR_ESTA_FECHA_CAT_PROFE_2 BEFORE INSERT ON HIMS.AUDITAR_ESTA_FECHA_CAT_PROFE_S
FOR EACH ROW
DECLARE

BEGIN
    SELECT AUDITAR_ESTA_FECHA_CAT_PROFE_1.NEXTVAL
    INTO :NEW.COD_NUM_ESTA_AEFCPS
    FROM DUAL;
END;
