CREATE OR REPLACE TRIGGER HIMS.AUDITAR_GLOSADO_SEGUIM_ITEMS_1 BEFORE INSERT ON HIMS.AUDITAR_GLOSADO_SEGUIM_ITEMS
FOR EACH ROW
DECLARE

BEGIN
  SELECT AUDITAR_GLOSADO_SEGUIM_ITEMS_A.NEXTVAL
  INTO :NEW.AUTO_SEGU_DOC_ITEM
  FROM DUAL;
END;
