CREATE OR REPLACE TRIGGER HIMS.AUDITAR_LOG_SINCRO_DOCU_AUTO_1 BEFORE INSERT ON HIMS.AUDITAR_LOG_SINCRO_DOCU
FOR EACH ROW
DECLARE

BEGIN
    SELECT AUDITAR_LOG_SINCRO_DOCU_AUTO_L.NEXTVAL
    INTO :NEW.AUTO_LOG_SINCR_ALSD
    FROM DUAL;
END;
/