CREATE OR REPLACE TRIGGER HIMS.AUDITAR_PRECIO_ANIO_MEDICAM__1 BEFORE INSERT ON HIMS.AUDITAR_PRECIO_ANIO_MEDICAM
FOR EACH ROW
DECLARE

BEGIN
    SELECT AUDITAR_PRECIO_ANIO_MEDICAM_AU.NEXTVAL
    INTO :NEW.AUTO_CAT_PRECIO_MEDIC
    FROM DUAL;
END;
/