CREATE OR REPLACE TRIGGER HIMS.BITACORA_REGISTRO_NU_AUTO_BI_1 BEFORE INSERT ON HIMS.BITACORA_REGISTRO
FOR EACH ROW
DECLARE

BEGIN
    SELECT BITACORA_REGISTRO_NU_AUTO_BIRE.NEXTVAL
    INTO :NEW.NU_AUTO_BIREG
    FROM DUAL;
END;
/