CREATE OR REPLACE TRIGGER HIMS.CATEGORIA_ODONTO_NU_AUTO_CAO_1 BEFORE INSERT ON HIMS.CATEGORIA_ODONTO FOR EACH ROW
DECLARE

BEGIN
    SELECT CATEGORIA_ODONTO_NU_AUTO_CAOD_.NEXTVAL
    INTO :NEW.NU_AUTO_CAOD
    FROM DUAL;
END;
