CREATE OR REPLACE TRIGGER HIMS.COMPROBANTE_CTAADS_ID_COMPRO_1 BEFORE INSERT ON HIMS.COMPROBANTE_CTAADS FOR EACH ROW
DECLARE

BEGIN
    SELECT COMPROBANTE_CTAADS_ID_COMPROBA.NEXTVAL
    INTO :NEW.ID_COMPROBANTE_CTAADS
    FROM DUAL;
END;
