CREATE OR REPLACE TRIGGER HIMS.CONCEPTO_HIST_NU_NUME_COHI_TRG BEFORE INSERT ON HIMS.CONCEPTO_HIST FOR EACH ROW
DECLARE

BEGIN
    SELECT CONCEPTO_HIST_NU_NUME_COHI_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_COHI
    FROM DUAL;
END;
/