CREATE OR REPLACE TRIGGER HIMS.CONSIGNACIONES_CD_CODI_CONSI_1 BEFORE INSERT ON HIMS.CONSIGNACIONES FOR EACH ROW
DECLARE

BEGIN
    SELECT CONSIGNACIONES_CD_CODI_CONSIG_.NEXTVAL
    INTO :NEW.CD_CODI_CONSIG
    FROM DUAL;
END;