CREATE OR REPLACE TRIGGER HIMS.CONTACTO_INASISTENCIA_CD_COD_1 BEFORE INSERT ON HIMS.CONTACTO_INASISTENCIA FOR EACH ROW
DECLARE

BEGIN
    SELECT CONTACTO_INASISTENCIA_CD_CODI_.NEXTVAL
    INTO :NEW.CD_CODI_CONT
    FROM DUAL;
END;
/