CREATE OR REPLACE TRIGGER HIMS.CONVOCATORIAS_HIST_CD_CONVOC_1 BEFORE INSERT ON HIMS.CONVOCATORIAS_HIST FOR EACH ROW
DECLARE

BEGIN
    SELECT  CONVOCATORIAS_HIST_CD_CONVOC_H.NEXTVAL 
    INTO :NEW.CD_CONVOC_HC
    FROM DUAL;
END;
/