CREATE OR REPLACE TRIGGER HIMS.COTIZ_SERVICIOS_NU_NUME_CSER_T BEFORE INSERT ON HIMS.COTIZ_SERVICIOS FOR EACH ROW
DECLARE

BEGIN
    SELECT COTIZ_SERVICIOS_NU_NUME_CSER_S.NEXTVAL
    INTO :NEW.NU_NUME_CSER
    FROM DUAL;
END;
/