CREATE OR REPLACE TRIGGER HIMS.DEPORTES_NU_AUTO_NUME_DEP_TRG BEFORE INSERT ON HIMS.DEPORTES FOR EACH ROW
DECLARE

BEGIN
    SELECT DEPORTES_NU_AUTO_NUME_DEP_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_NUME_DEP
    FROM DUAL;
END;
/