CREATE OR REPLACE TRIGGER HIMS.DIAGNOSTICOS_NU_NUME_DIAG_TRG BEFORE INSERT ON HIMS.DIAGNOSTICOS FOR EACH ROW
DECLARE

BEGIN
    SELECT DIAGNOSTICOS_NU_NUME_DIAG_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_DIAG
    FROM DUAL;
END;
/