CREATE OR REPLACE TRIGGER HIMS.DISCAPACIDAD_NU_AUTO_DISC_TRG BEFORE INSERT ON HIMS.DISCAPACIDAD FOR EACH ROW
DECLARE

BEGIN
    SELECT DISCAPACIDAD_NU_AUTO_DISC_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_DISC
    FROM DUAL;
END;
/