CREATE OR REPLACE TRIGGER HIMS.ERROR_PROCEDTO_CONSECUTIVO_TRG BEFORE INSERT ON HIMS.ERROR_PROCEDTO FOR EACH ROW
DECLARE

BEGIN
    SELECT ERROR_PROCEDTO_CONSECUTIVO_SEQ.NEXTVAL
    INTO :NEW.CONSECUTIVO
    FROM DUAL;
END;
/