CREATE OR REPLACE TRIGGER HIMS.ERROR_SERVICIO_CONSECUTIVO_TRG BEFORE INSERT ON HIMS.ERROR_SERVICIO FOR EACH ROW
DECLARE

BEGIN
    SELECT ERROR_SERVICIO_CONSECUTIVO_SEQ.NEXTVAL
    INTO :NEW.CONSECUTIVO
    FROM DUAL;
END;
/