CREATE OR REPLACE TRIGGER HIMS.ERROR_URGENCIA_CONSECUTIVO_TRG BEFORE INSERT ON HIMS.ERROR_URGENCIA FOR EACH ROW
DECLARE

BEGIN
    SELECT ERROR_URGENCIA_CONSECUTIVO_SEQ.NEXTVAL
    INTO :NEW.CONSECUTIVO
    FROM DUAL;
END;
/