CREATE OR REPLACE TRIGGER HIMS.ERROR_MEDICA_CONSECUTIVO_TRG BEFORE INSERT ON HIMS.ERROR_MEDICA FOR EACH ROW
DECLARE

BEGIN
    SELECT ERROR_MEDICA_CONSECUTIVO_SEQ.NEXTVAL
    INTO :NEW.CONSECUTIVO
    FROM DUAL;
END;
/