CREATE OR REPLACE TRIGGER HIMS.ERROR_NACIDO_CONSECUTIVO_TRG BEFORE INSERT ON HIMS.ERROR_NACIDO FOR EACH ROW
DECLARE

BEGIN
    SELECT ERROR_NACIDO_CONSECUTIVO_SEQ.NEXTVAL
    INTO :NEW.CONSECUTIVO
    FROM DUAL;
END;
/