CREATE OR REPLACE TRIGGER HIMS.EVENTO_ENFERMERIA_NU_AUTO_EV_1 BEFORE INSERT ON HIMS.EVENTO_ENFERMERIA FOR EACH ROW
DECLARE

BEGIN
    SELECT EVENTO_ENFERMERIA_NU_AUTO_EVEN.NEXTVAL
    INTO :NEW.NU_AUTO_EVEN
    FROM DUAL;
END;
/