CREATE OR REPLACE TRIGGER HIMS.EVENTO_LUGAR_OCURRENCIA_CD_E_1 BEFORE INSERT ON HIMS.EVENTO_LUGAR_OCURRENCIA FOR EACH ROW
DECLARE

BEGIN
    SELECT EVENTO_LUGAR_OCURRENCIA_CD_EVT.NEXTVAL
    INTO :NEW.CD_EVT_LUGAR_OCURR
    FROM DUAL;
END;
/