CREATE OR REPLACE TRIGGER HIMS.EVENTO_ADVERSO_CD_EVENTO_ADV_1 BEFORE INSERT ON HIMS.EVENTO_ADVERSO FOR EACH ROW
DECLARE
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
    SELECT EVENTO_ADVERSO_CD_EVENTO_ADVER.NEXTVAL
    INTO :NEW.CD_EVENTO_ADVERSO
    FROM DUAL;
END;
/