CREATE OR REPLACE TRIGGER HIMS.EVENTO_ADVERSO_MEJORA_NU_NUM_1 BEFORE INSERT ON HIMS.EVENTO_ADVERSO_MEJORA FOR EACH ROW
DECLARE

BEGIN
    SELECT EVENTO_ADVERSO_MEJORA_NU_NUME_.NEXTVAL
    INTO :NEW.NU_NUME_EAM
    FROM DUAL;
END;
/