CREATE OR REPLACE TRIGGER HIMS.EVENTO_ADVERSO_SEGUIMIENTO_N_1 BEFORE INSERT ON HIMS.EVENTO_ADVERSO_SEGUIMIENTO FOR EACH ROW
DECLARE

BEGIN
    SELECT EVENTO_ADVERSO_SEGUIMIENTO_NU_.NEXTVAL
    INTO :NEW.NU_NUME_EAS
    FROM DUAL;
END;
/