CREATE OR REPLACE TRIGGER HIMS.GESTION_SALUD_NU_NUME_GESA_TRG BEFORE INSERT ON HIMS.GESTION_SALUD FOR EACH ROW
DECLARE

BEGIN
    SELECT GESTION_SALUD_NU_NUME_GESA_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_GESA
    FROM DUAL;
END;
/