CREATE OR REPLACE TRIGGER HIMS.GESTION_GLOSA_NU_NUME_GEGL_TRG BEFORE INSERT ON HIMS.GESTION_GLOSA FOR EACH ROW
DECLARE

BEGIN
    SELECT GESTION_GLOSA_NU_NUME_GEGL_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_GEGL
    FROM DUAL;
END;
/