CREATE OR REPLACE TRIGGER HIMS.GLOSA3I_NU_AUTO_GLOS_TRG BEFORE INSERT ON HIMS.GLOSA3I
FOR EACH ROW
DECLARE

BEGIN
    SELECT GLOSA3i_NU_AUTO_GLOS_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_GLOS
    FROM DUAL;
END;
/