CREATE OR REPLACE TRIGGER HIMS.GLOSA_NU_NUME_GLOS_TRG BEFORE INSERT ON HIMS.GLOSA FOR EACH ROW
DECLARE

BEGIN
    SELECT GLOSA_NU_NUME_GLOS_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_GLOS
    FROM DUAL;
END;
/