CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONS_PRESUPUESTO_ADSC
-- =============================================      
-- Author:  Carlos Castro Agudelo
-- =============================================  
(v_FECH_INICIO IN DATE, v_FECH_FIN IN DATE, cv_1 OUT SYS_REFCURSOR)
IS
BEGIN
   DELETE FROM tt_temmovpads;
   
    INSERT INTO tt_temmovpads
    (SELECT aa.CD_CODI_ADSC_AUAD, aa.CD_CODI_COAD_AUAD, aa.CD_CODI_AUTORIZA_AUAD, aa.VAL_PAGCONV_AUAD, aa.FE_AUTORIZA_AUAD, 1 FROM AUTORIZACION_ADSCRITOS aa);
    
    INSERT INTO tt_temmovpads
    (SELECT aua.CD_CODI_ADSC_AUAD, aua.CD_CODI_COAD_AUAD, aaa.CD_CODI_AUTORIZA_AUAD_ANUL, aaa.VL_DESCONTADO_PRE_AUAD_UNAL, aaa.FECH_ANUL, 0 
     FROM ANULACION_AUTORIZACION_ADS aaa
     JOIN AUTORIZACION_ADSCRITOS aua   ON aua.CD_CODI_AUTORIZA_AUAD = aaa.CD_CODI_AUTORIZA_AUAD_ANUL);
   
    OPEN  cv_1 FOR
    SELECT DISTINCT A.CD_CODI_ADSC, A.NU_CONSE_ADSC, A.DE_NOMB_ADSC, A.NU_ESTA_ADSC, A.NU_TIPCONT_ADSC, A.NU_LABO_DENTAL, NVL(C.CD_CODI_COAD, 'ND') CD_CODI_COAD, NVL(C.DE_NOMB_COAD, 'ND') DE_NOMB_COAD,
    aa.CD_CODI_AUTORIZA, aa.VL_MONTO, aa.AUTORIZACION, NVL(C.VL_CUPO_COAD, 0) MONT_CONS, NVL(C.VL_CUPO_COAD, 0) - NVL(C.VL_SALD_COAD, 0) MONT_EJEC, NVL(C.VL_CUIN_COAD, 0) MONT_INDV, NVL(C.VL_SALD_COAD, 0) MONT_SALD,
    CASE A.NU_LABO_DENTAL
        WHEN 0 THEN 'NORMAL'
        WHEN 1 THEN 'DENTAL'
    END TIPO, aa.FE_FECHA 
    FROM ADSCRITOS A
    LEFT JOIN CONVENIO_ADSC C   ON A.NU_CONSE_ADSC = C.NU_CONSE_ADSC_COAD
    JOIN tt_temmovpads aa   ON C.CD_CODI_COAD = aa.CD_CODI_COAD AND A.CD_CODIGO_ADSC = aa.CD_CODI_ADS 
    WHERE  aa.FE_FECHA >= v_FECH_INICIO AND aa.FE_FECHA <= v_FECH_FIN
    ORDER BY A.CD_CODI_ADSC ;
   
   EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_temmovpads ';
Exception
    When Others Then
    RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/