CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_REP_TRAB_AUDI_FECH
-- =============================================      
-- Author:  Nelson Galeano
-- =============================================
(
    v_FECHA_INICIO IN DATE,
    v_FECHA_FIN IN DATE,
    cv_1 OUT SYS_REFCURSOR
)
IS
    v_FECHA_INICIO_N DATE;
    v_FECHA_FIN_N DATE;

BEGIN

    v_FECHA_INICIO_N := v_FECHA_INICIO ;
    v_FECHA_FIN_N := v_FECHA_FIN ;
    --seleccionamos los ultimos documentos con operaciones 
    DELETE FROM tt_DOCUMENTOS_GLOSADOS_3;
    --UTILS.IDENTITY_RESET('tt_DOCUMENTOS_GLOSADOS_3');
       
    INSERT INTO tt_DOCUMENTOS_GLOSADOS_3 ( 
    SELECT COD_AUDI_DOCUM , FECHA_ASIG_AAD , IDEN_USUARIO_AAD , DOCUMENTO_VALOR_TOTAL , ESTADO_ARG 
    FROM AUDITAR_REGISTRO_GLOSADO ARG
    JOIN AUDITAR_DOCUMENTO    ON ARG.COD_AUDI_DOCUM_ARG = COD_AUDI_DOCUM
    JOIN AUDITAR_ASIGNACION_DOCUM    ON COD_AUDI_DOCUM_AAD = COD_AUDI_DOCUM
    WHERE  ( FECHA_ASIG_AAD BETWEEN v_FECHA_INICIO_N AND v_FECHA_FIN_N ) );

    OPEN  cv_1 FOR
    SELECT U.ID_IDEN_USUA , U.NO_NOMB_USUA , U.NU_TRABAJO_AUDI , ( SELECT COUNT(COD_AUDI_DOCUM_AAD) FROM AUDITAR_ASIGNACION_DOCUM 
    WHERE  ( FECHA_ASIG_AAD BETWEEN v_FECHA_INICIO_N AND v_FECHA_FIN_N )
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_TOTAL  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0)  FROM AUDITAR_DOCUMENTO 
    JOIN AUDITAR_ASIGNACION_DOCUM    ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
    WHERE  ( FECHA_ASIG_AAD BETWEEN v_FECHA_INICIO_N AND v_FECHA_FIN_N )
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_TOTAL  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM)  FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_AUDITADOS  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_AUDITADOS  ,
    ( SELECT COUNT(AD.COD_AUDI_DOCUM) FROM AUDITAR_DOCUMENTO AD
    JOIN AUDITAR_ASIGNACION_DOCUM AAD   ON AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
    LEFT JOIN tt_DOCUMENTOS_GLOSADOS_3 DG   ON DG.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
    WHERE  ( AAD.FECHA_ASIG_AAD BETWEEN v_FECHA_INICIO_N AND v_FECHA_FIN_N )
    AND AAD.IDEN_USUARIO_AAD = U.ID_IDEN_USUA
    AND DG.COD_AUDI_DOCUM IS NULL ) CANTIDAD_SIN_AUDITAR  ,
    ( SELECT NVL(SUM(AD.DOCUMENTO_VALOR_TOTAL) , 0) 
    FROM AUDITAR_DOCUMENTO AD
    JOIN AUDITAR_ASIGNACION_DOCUM AAD   ON AD.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
    LEFT JOIN tt_DOCUMENTOS_GLOSADOS_3 DG   ON DG.COD_AUDI_DOCUM = AAD.COD_AUDI_DOCUM_AAD
    WHERE  ( AAD.FECHA_ASIG_AAD BETWEEN v_FECHA_INICIO_N AND v_FECHA_FIN_N )
    AND AAD.IDEN_USUARIO_AAD = U.ID_IDEN_USUA
    AND DG.COD_AUDI_DOCUM IS NULL ) VALOR_SIN_AUDITAR  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 0
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_GLOSADOS  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 0
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_GLOSADOS  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 1
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_CERRADOS  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 1
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_CERRADOS  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 2
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_CON_RESPUESTA  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 2
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_CON_RESPUESTA  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 3
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) CANTIDAD_CONCILIADOS  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM tt_DOCUMENTOS_GLOSADOS_3 DG
    WHERE ESTADO_ARG = 3
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) VALOR_CONCILIADOS  
    FROM USUARIOS U
    JOIN USUARIO_PERFIL UP   ON U.ID_IDEN_USUA = UP.ID_IDEN_USUA
    WHERE  UP.CD_CODI_PERF = 33
    ORDER BY U.ID_IDEN_USUA ;
            
    EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_DOCUMENTOS_GLOSADOS_3 ';

EXCEPTION 
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/