CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONS_HISTORICREPOSAMA
-- =============================================      
-- Author:  Carlos Castro Agudelo
-- ============================================= 
(V_FECHAINI IN DATE, V_FECHAFIN IN DATE, CV_1 OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN CV_1 FOR
    SELECT CD_CODI_REPO CODIGO, FE_FECH_REPO FECHA, U.NO_NOMB_USUA USUARIO, CD_CODI_TIPO_REPO TIPOREPORTE
    FROM REPORTESAMA_HIST
    INNER JOIN USUARIOS U ON U.ID_IDEN_USUA = TX_USER_REPO
    WHERE FE_FECH_REPO BETWEEN V_FECHAINI AND V_FECHAFIN;
Exception
    When Others Then
    RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;