CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONS_COTIZ_X_HIST
-- =============================================      
-- Author:  Nelson Galeano
-- =============================================
(
  v_CD_CODI_HC_MCOT IN NUMBER,
  v_HC_PACIENTE IN VARCHAR2,
  cv_1 OUT SYS_REFCURSOR,
  cv_2 OUT SYS_REFCURSOR
)
IS

BEGIN

    DELETE FROM tt_CARGOS_COT;
       
    INSERT INTO tt_CARGOS_COT (SELECT MCOT.*, C.CD_NOMB_CONV , EPS.NO_NOMB_EPS 
    FROM MOVI_CARGOS_COT MCOT
    JOIN CONVENIOS C   ON MCOT.NU_NUME_CONV_MCOT = C.NU_NUME_CONV
    JOIN EPS    ON MCOT.ID_ADMINISTRADORA_NIT = EPS.CD_NIT_EPS
    WHERE  CD_CODI_HC_MCOT = v_CD_CODI_HC_MCOT
    AND NU_HIST_PAC_MCOT = v_HC_PACIENTE );

    DELETE FROM tt_LABORATORIO_COT;
       
    INSERT INTO tt_LABORATORIO_COT ( SELECT LAB.ID_CODI_TIDI_LCOT , LAB.TX_CODI_RFF_LCOT , LAB.TX_CODI_RRTT_LCOT , LAB.ID_CODI_CAEX_LCOT , LAB.CD_CODI_SER_LCOT ,
    SER.NO_NOMB_SER , LAB.CT_CANT_LCOT, LAB.VL_UNID_LCOT, LAB.VL_COPA_LCOT , LAB.CD_CODI_MEDI_LCOT , LAB.NU_AUTO_LCOT , LAB.NU_NUME_LCOT , LAB.NU_NUME_MOVI_LCOT , ESP.NO_NOMB_ESP 
    FROM LABORATORIO_COT LAB
    JOIN tt_CARGOS_COT CAR   ON LAB.NU_NUME_MOVI_LCOT = CAR.NU_NUME_MCOT
    JOIN SERVICIOS SER   ON SER.CD_CODI_SER = LAB.CD_CODI_SER_LCOT
    JOIN ESPECIALIDADES ESP   ON LAB.CD_CODI_ESP_LCOT = ESP.CD_CODI_ESP );

    OPEN  cv_1 FOR
    SELECT * FROM tt_CARGOS_COT  ;

    OPEN  cv_2 FOR 
    SELECT * FROM tt_LABORATORIO_COT  ;

EXCEPTION 
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/