CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CREA_REPORTESAMAESM
-- =============================================      
-- Author:  Carlos Castro Agudelo
-- ============================================= 
(V_ANALISIS IN VARCHAR2, V_CODIGOESM IN NUMBER, V_FUERZA IN VARCHAR2, V_NUMEROFORMULAAUDITADA IN VARCHAR2, V_VALORCONCILIADO IN VARCHAR2, V_VALORCONCILIAR IN VARCHAR2, V_VALORFACTURADO IN VARCHAR2,
V_VALORFIRMEPAGAR IN VARCHAR2, V_VALORGLOSADO IN VARCHAR2, V_VALORMEDACU IN VARCHAR2, V_VALORMEDCTC IN VARCHAR2, V_VALORMEDTUTELA IN VARCHAR2, V_VALORRATIFICADO IN VARCHAR2, V_NUMHISTORICO IN NUMBER)
IS
BEGIN
    INSERT INTO ESM_REPORTESAMA(TX_ANAL_ESM, CD_CODI_ESM, 
    NO_NOMB_FUER, NU_NUME_FORMU_AUDI, VL_VLR_GLOSA,
     VL_VLR_RATI, VL_VLR_FIRM_PAG, VL_VLR_CONCILIAR, 
     VL_VLR_CONCILIADO, VL_VLR_FACTU, VL_VLR_MED_ACU,
    VL_VLR_MED_CTC, VL_VLR_MED_TUTE, NU_AUTO_ESM_HIST)
    VALUES (V_ANALISIS, V_CODIGOESM, V_FUERZA, V_NUMEROFORMULAAUDITADA, V_VALORGLOSADO, V_VALORRATIFICADO, V_VALORFIRMEPAGAR, V_VALORCONCILIAR,
     V_VALORCONCILIADO, V_VALORFACTURADO, V_VALORMEDACU, V_VALORMEDCTC,
    V_VALORMEDTUTELA, V_NUMHISTORICO);
Exception
    When Others Then
    RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/