CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONS_EVEN_SALUD_PUBLICA
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
 (
 	V_TIPO IN VARCHAR2,
    V_FECHAINICIAL IN DATE,
	V_FECHAFINAL IN DATE,
	V_FILTRO IN VARCHAR2,
	CV_1 OUT SYS_REFCURSOR
 )

AS
BEGIN
	IF(V_FILTRO = 'Todos') THEN
		BEGIN
			OPEN CV_1 FOR
				SELECT DISTINCT VS.COD_DIA_VISA AS CD_CODI_ALERT,
					D.DE_DESC_DIAG AS NOMBRE_ALERT,
					VS.NOM__DIA_VISA AS EVENTO,
					NU_DOCU_PAC AS CD_DOCUMENTO,
					TX_NOMBRECOMPLETO_PAC AS NO_NOMB_PACIENTE,
					CalcularEdad (P.FE_NACI_PAC, SYSDATE, 0) AS NU_EDAD_PAC,
					CASE P.NU_SEXO_PAC
						WHEN 1 THEN 'Masculino'
						WHEN 0 THEN 'Femenino'
					END NU_SEXO_PAC,
					V.FE_FECH_HICL AS FE_FECHA_CONSULTA,
					S.CD_CODI_SER,
					S.NO_NOMB_SER		
				FROM V_DATOS_HISTCLINICA V
				INNER JOIN DIAGNOSTICO D 
					ON V.TX_VALOR_CONC = DE_DESC_DIAG
				INNER JOIN VIGILANCIA_SALUD VS 
					ON D.CD_CODI_DIAG = COD_DIA_VISA
				INNER JOIN LABORATORIO L 
					ON V.NU_NUME_LABO_HICL = L.NU_NUME_LABO
				INNER JOIN MOVI_CARGOS MC 
					ON L.NU_NUME_MOVI_LABO = MC.NU_NUME_MOVI
				INNER JOIN SERVICIOS S 
					ON S.CD_CODI_SER = L.CD_CODI_SER_LABO
				INNER JOIN PACIENTES P 
					ON P.NU_HIST_PAC = MC.NU_HIST_PAC_MOVI
					AND NU_NUME_COHI in (6794, 6791,6792,6793)
					AND VS.NOTIFICACION_VISA = V_TIPO
					AND (V.FE_FECH_HICL BETWEEN V_FECHAINICIAL AND V_FECHAFINAL)
				GROUP BY VS.COD_DIA_VISA,
					D.DE_DESC_DIAG,
					VS.NOM__DIA_VISA,
					NU_DOCU_PAC,
					TX_NOMBRECOMPLETO_PAC,
					P.FE_NACI_PAC,
					P.NU_SEXO_PAC,
					V.FE_FECH_HICL,
					S.CD_CODI_SER,
					S.NO_NOMB_SER
					ORDER BY EVENTO ASC;
		END;
	ELSE
		BEGIN
			OPEN CV_1 FOR
				SELECT DISTINCT VS.COD_DIA_VISA AS CD_CODI_ALERT,
					D.DE_DESC_DIAG AS NOMBRE_ALERT,
					VS.NOM__DIA_VISA AS EVENTO,
					NU_DOCU_PAC AS CD_DOCUMENTO,
					TX_NOMBRECOMPLETO_PAC AS NO_NOMB_PACIENTE,
					CalcularEdad (P.FE_NACI_PAC, SYSDATE, 0) AS NU_EDAD_PAC,
					CASE P.NU_SEXO_PAC
						WHEN 1 THEN 'Masculino'
						WHEN 0 THEN 'Femenino'
					END NU_SEXO_PAC,
					V.FE_FECH_HICL AS FE_FECHA_CONSULTA,
					S.CD_CODI_SER,
					S.NO_NOMB_SER	
					FROM V_DATOS_HISTCLINICA V
					INNER JOIN DIAGNOSTICO D ON V.TX_VALOR_CONC = DE_DESC_DIAG
					INNER JOIN VIGILANCIA_SALUD VS ON D.CD_CODI_DIAG = COD_DIA_VISA
					INNER JOIN LABORATORIO L ON V.NU_NUME_LABO_HICL = L.NU_NUME_LABO
					INNER JOIN MOVI_CARGOS MC ON L.NU_NUME_MOVI_LABO = MC.NU_NUME_MOVI
					INNER JOIN SERVICIOS S ON S.CD_CODI_SER = L.CD_CODI_SER_LABO
					INNER JOIN PACIENTES P ON P.NU_HIST_PAC = MC.NU_HIST_PAC_MOVI
					AND NU_NUME_COHI in (6794, 6791,6792,6793)
					AND VS.NOTIFICACION_VISA = V_TIPO
					AND (V.FE_FECH_HICL BETWEEN V_FECHAINICIAL AND V_FECHAFINAL)
					WHERE VS.NOM__DIA_VISA = V_FILTRO
					GROUP BY VS.COD_DIA_VISA,
					D.DE_DESC_DIAG,
					VS.NOM__DIA_VISA,
					NU_DOCU_PAC,
					TX_NOMBRECOMPLETO_PAC,
					P.FE_NACI_PAC,
					P.NU_SEXO_PAC,
					V.FE_FECH_HICL,
					S.CD_CODI_SER,
					S.NO_NOMB_SER
					ORDER BY EVENTO ASC;
		END;
	END IF;
END;
