CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_REP_ESTAD_CONC_AUD
-- =============================================      
-- Author:  Nelson Galeano
-- =============================================
(
  v_FECHAINI IN DATE DEFAULT NULL ,
  v_FECHAFIN IN DATE DEFAULT NULL ,
  v_ESTADO IN NUMBER DEFAULT NULL ,
  v_ID_IDEN_USUA IN VARCHAR2 DEFAULT NULL ,
  v_BODEGA_CODIGO IN NUMBER DEFAULT NULL ,
  v_FUERZA_CODIGO IN VARCHAR2 DEFAULT NULL ,
  cv_1 OUT SYS_REFCURSOR
)
IS
   v_FECHAINI_N DATE;
   v_FECHAFIN_N DATE;
   v_ESTADO_N NUMBER(10,0);
   v_ID_IDEN_USUA_N VARCHAR2(30);
   v_BODEGA_CODIGO_N NUMBER(18,2);
   v_FUERZA_CODIGO_N VARCHAR2(100);

BEGIN

    v_FECHAINI_N := v_FECHAINI ;
    v_FECHAFIN_N := v_FECHAFIN ;
    v_ESTADO_N := v_ESTADO ;
    v_ID_IDEN_USUA_N := v_ID_IDEN_USUA ;
    v_BODEGA_CODIGO_N := v_BODEGA_CODIGO ;
    v_FUERZA_CODIGO_N := v_FUERZA_CODIGO ;
    --seleccionamos los ultimos documentos con operaciones 
    DELETE FROM tt_DOCUMENTOS_GLOSADOS_2;
    -- UTILS.IDENTITY_RESET('tt_DOCUMENTOS_GLOSADOS_2');
       
    INSERT INTO tt_DOCUMENTOS_GLOSADOS_2 ( 
    SELECT COD_AUDI_DOCUM ,
    FUERZA_CODIGO ,
    BODEGA_CODIGO ,
    ESTADO_ARG ,
    IDEN_USUARIO_AAD ,
    DOCUMENTO_FECHA_TRANSACCION ,
    DOCUMENTO_VALOR_TOTAL 
    FROM AUDITAR_REGISTRO_GLOSADO ARG
    JOIN AUDITAR_DOCUMENTO    ON ARG.COD_AUDI_DOCUM_ARG = COD_AUDI_DOCUM
    JOIN AUDITAR_ASIGNACION_DOCUM    ON COD_AUDI_DOCUM_AAD = COD_AUDI_DOCUM
    WHERE  ( DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(v_FECHAINI_N,'DD-MM-YYYY') AND TO_DATE(v_FECHAFIN_N,'DD-MM-YYYY') ) );
    --AUTO_REG_GLOSA = (SELECT MAX(AUTO_REG_GLOSA) FROM AUDITAR_REGISTRO_GLOSADO ARG_AUX WHERE ARG_AUX.COD_AUDI_DOCUM_ARG = ARG.COD_AUDI_DOCUM_ARG)
    --  AND FE_FECHA_ARG BETWEEN @FECHA_INI AND @FECHA_FIN
    --ORDER BY COD_AUDI_DOCUM_ARG
    --@CRITERIO = 'GENERAL',  CONSULTAR TODOS LOS AUDITORES
--============================================================================================================================
    OPEN  cv_1 FOR
    SELECT U.ID_IDEN_USUA , U.NO_NOMB_USUA , U.NU_TRABAJO_AUDI ,
    ( SELECT COUNT(COD_AUDI_DOCUM) FROM AUDITAR_DOCUMENTO JOIN AUDITAR_ASIGNACION_DOCUM    ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
    WHERE  FUERZA_CODIGO = NVL(v_FUERZA_CODIGO_N, FUERZA_CODIGO)
    AND BODEGA_CODIGO = NVL(v_BODEGA_CODIGO_N, BODEGA_CODIGO)
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
    AND ( DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(v_FECHAINI_N,'DD-MM-YYYY') AND TO_DATE(v_FECHAFIN_N,'DD-MM-YYYY') ) ) CANTI_DOCU_ASIG  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) FROM AUDITAR_DOCUMENTO 
    JOIN AUDITAR_ASIGNACION_DOCUM    ON COD_AUDI_DOCUM = COD_AUDI_DOCUM_AAD
    WHERE  FUERZA_CODIGO = NVL(v_FUERZA_CODIGO_N, FUERZA_CODIGO)
    AND BODEGA_CODIGO = TO_NUMBER(NVL(v_BODEGA_CODIGO_N, BODEGA_CODIGO),18)
    AND IDEN_USUARIO_AAD = U.ID_IDEN_USUA
    AND ( DOCUMENTO_FECHA_TRANSACCION BETWEEN TO_DATE(v_FECHAINI_N,'DD-MM-YYYY') AND TO_DATE(v_FECHAFIN_N,'DD-MM-YYYY') ) ) VALOR_TOTAL_DOCUMENTOS_ASIG  ,
    ( SELECT COUNT(DG.COD_AUDI_DOCUM) FROM tt_DOCUMENTOS_GLOSADOS_2 DG
    WHERE  DG.FUERZA_CODIGO = NVL(v_FUERZA_CODIGO_N, DG.FUERZA_CODIGO)
    AND DG.BODEGA_CODIGO = TO_NUMBER(NVL(v_BODEGA_CODIGO_N, DG.BODEGA_CODIGO),18)
    AND DG.ESTADO_ARG = NVL(v_ESTADO_N, DG.ESTADO_ARG)
    AND DG.IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) 
    -- AND (DG.DOCUMENTO_FECHA_TRANSACCION BETWEEN CONVERT(DATETIME,@FECHAINI_N,120) AND CONVERT(DATETIME,@FECHAFIN_N,120))
    CANTI_DOCU_AUDIT  ,
    ( SELECT NVL(SUM(DOCUMENTO_VALOR_TOTAL) , 0) 
    FROM tt_DOCUMENTOS_GLOSADOS_2 DG
    WHERE  DG.FUERZA_CODIGO = NVL(v_FUERZA_CODIGO_N, DG.FUERZA_CODIGO)
    AND DG.BODEGA_CODIGO = TO_NUMBER(NVL(v_BODEGA_CODIGO_N, DG.BODEGA_CODIGO),18)
    AND DG.ESTADO_ARG = NVL(v_ESTADO_N, DG.ESTADO_ARG)
    AND DG.IDEN_USUARIO_AAD = U.ID_IDEN_USUA ) 
    --AND (DG.DOCUMENTO_FECHA_TRANSACCION BETWEEN CONVERT(DATETIME,@FECHAINI_N,120) AND CONVERT(DATETIME,@FECHAFIN_N,120))
    VALOR_TOTAL_DOCUMENTOS_AUDIT_T  
    FROM USUARIOS U
    JOIN USUARIO_PERFIL UP   ON U.ID_IDEN_USUA = UP.ID_IDEN_USUA
    WHERE  UP.CD_CODI_PERF = 33
    AND U.ID_IDEN_USUA = NVL(v_ID_IDEN_USUA_N, U.ID_IDEN_USUA) ;

EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_DOCUMENTOS_GLOSADOS_2 ';

EXCEPTION 
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/