CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONSULTA_TURNOS_HA 
-- =============================================      
-- Author:  Carlos Castro Agudelo
-- =============================================  
/*PROCEDIMIENTO ALMACENADO DE CONSULTA DE TURNOS MEDICOS ISOCIADOS A UN HORAIO ACADEMICO */
(v_IDHORARIO_ACADEMICO IN VARCHAR2, cv_1 OUT SYS_REFCURSOR, cv_2 OUT SYS_REFCURSOR)
IS
   v_FECHA_MINIMA DATE;
BEGIN
    v_FECHA_MINIMA := SYSDATE;
    v_FECHA_MINIMA := v_FECHA_MINIMA - 1;
   
   DELETE FROM tt_TMP_TUR_HA;
   
   INSERT INTO tt_TMP_TUR_HA 
   (SELECT FE_FECH_TUME, FE_HOIN_TUME, FE_HOFI_TUME, NU_TIEMCIT_TUME, ID_DISP_TUME, CD_CODI_CONS_TUME, NU_NUME_TUME, TX_MOTINHA_TUME, TX_CODI_EQUI_TUME, NU_AUTO_TIPO_TUME_TUME,
   CD_MED_TUME, TX_DESC_TIPO_TUME, NU_AUTO_HOGR_TUME 
    FROM TURNOS_MEDICOS 
    JOIN MEDICOS ON CD_MED_TUME = CD_CODI_MED
    LEFT JOIN TIPO_TURNO_MED ON ( NU_AUTO_TIPO_TUME_TUME = NU_AUTO_TIPO_TUME )
    WHERE  FE_FECH_TUME >= v_FECHA_MINIMA AND NU_AUTO_HOGR_TUME IN (SELECT TO_CHAR(item,10) FROM TABLE(fnSplit(v_IDHORARIO_ACADEMICO, ','))));
    
    OPEN  cv_1 FOR
    SELECT * FROM tt_TMP_TUR_HA;
        
    OPEN  cv_2 FOR
    SELECT NU_NUME_TUME_RTE, CD_CODI_MED_RTE, CD_CODI_CONS_RTE FROM R_TUR_ESC WHERE  NU_NUME_TUME_RTE IN ( SELECT NU_NUME_TUME FROM tt_TMP_TUR_HA);
    
   EXECUTE IMMEDIATE ' TRUNCATE TABLE tt_TMP_TUR_HA ';
Exception
    When Others Then
    RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/