CREATE OR REPLACE PROCEDURE HIMS.H3i_SP_CONS_FACT_LAB_ADMIN
-- =============================================      
-- Author:  Carlos Castro Agudelo
-- =============================================  
(v_NU_NUME_CONV IN VARCHAR2, v_FECHA_INI IN DATE, v_FECHA_FIN IN DATE, cv_1 OUT SYS_REFCURSOR, cv_2 OUT SYS_REFCURSOR)
IS
    v_VALRIAFAC NUMBER(1,0);
BEGIN
    SELECT CASE TO_CHAR(CON.VL_VALO_CONT,30) WHEN '1' THEN 1 ELSE 0 END  INTO v_VALRIAFAC FROM CONTROL CON WHERE CON.CD_CONC_CONT = 'VALRIAFAC';
    DELETE FROM tt_CARGOS_4;
   
    INSERT INTO tt_CARGOS_4 
    (SELECT MOV.NU_NUME_MOVI, MOV.NU_TIPO_MOVI, MOV.VL_UNID_MOVI, MOV.VL_COPA_MOVI, MOV.FE_FECH_MOVI, MOV.NU_NUME_REG_MOVI, MOV.NU_NUME_CONV_MOVI, MED.NO_NOMB_MED, PAC.NU_DOCU_PAC, PAC.TX_NOMBRECOMPLETO_PAC,
    ESP.NO_NOMB_ESP 
    FROM MOVI_CARGOS MOV
    JOIN MEDICOS MED ON MED.CD_CODI_MED = MOV.CD_MEDI_ORDE_MOVI
    JOIN PACIENTES PAC ON PAC.NU_HIST_PAC = MOV.NU_HIST_PAC_MOVI
    JOIN CONVENIOS CON ON MOV.NU_NUME_CONV_MOVI = CON.NU_NUME_CONV
    JOIN EPS EPS ON CON.CD_NIT_EPS_CONV = EPS.CD_NIT_EPS
    JOIN LABORATORIO LAB ON LAB.NU_NUME_MOVI_LABO = MOV.NU_NUME_MOVI
    JOIN ESPECIALIDADES ESP ON ESP.CD_CODI_ESP = LAB.CD_CODI_ESP_LABO
    WHERE CON.NU_NUME_CONV = v_NU_NUME_CONV AND v_FECHA_INI <= MOV.FE_FECH_MOVI AND MOV.FE_FECH_MOVI <= v_FECHA_FIN AND MOV.NU_ESTA_MOVI <> 2 AND ( MOV.NU_NUME_FAC_MOVI = 0 OR MOV.NU_NUME_FAC_MOVI IS NULL)
    GROUP BY MOV.NU_NUME_MOVI, MOV.NU_TIPO_MOVI, MOV.VL_UNID_MOVI, MOV.VL_COPA_MOVI, MOV.FE_FECH_MOVI, MOV.NU_NUME_REG_MOVI, MOV.NU_NUME_CONV_MOVI, MED.NO_NOMB_MED, PAC.NU_DOCU_PAC, PAC.TX_NOMBRECOMPLETO_PAC,
    ESP.NO_NOMB_ESP);

    DELETE FROM tt_LABORATORIOS_2;
   
    INSERT INTO tt_LABORATORIOS_2 
   (SELECT LAB.NU_NUME_LABO, LAB.NU_NUME_MOVI_LABO, LAB.CD_CODI_SER_LABO, LAB.CT_CANT_LABO, LAB.VL_UNID_LABO, LAB.VL_COPA_LABO, LAB.ID_ESTA_ASIS_LABO, SER.NO_NOMB_SER, MED.NO_NOMB_MED
    FROM LABORATORIO LAB
    JOIN tt_CARGOS_4 CAR ON LAB.NU_NUME_MOVI_LABO = CAR.NU_NUME_MOVI AND LAB.NU_ESTA_LABO <> 2
    JOIN SERVICIOS SER ON SER.CD_CODI_SER = LAB.CD_CODI_SER_LABO
    JOIN MEDICOS MED ON LAB.CD_CODI_MEDI_LABO = MED.CD_CODI_MED);

    IF v_VALRIAFAC = 0 THEN
        BEGIN
            OPEN  cv_1 FOR
            SELECT * FROM tt_LABORATORIOS_2;
        END;
    END IF;
    
    IF v_VALRIAFAC = 1 THEN
        BEGIN
            OPEN  cv_2 FOR
            SELECT LAB.* 
            FROM tt_CARGOS_4 MOV
            JOIN tt_LABORATORIOS_2 LAB ON LAB.NU_NUME_MOVI_LABO = MOV.NU_NUME_MOVI
            WHERE  LAB.ID_ESTA_ASIS_LABO = '1';
        END;
    END IF;
Exception
    When Others Then
    RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;
/