CREATE OR REPLACE TRIGGER HIMS.HIST_GRAXY_VARIABLE_NU_AUTO__1 BEFORE INSERT ON HIMS.HIST_GRAXY_VARIABLE FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_GRAXY_VARIABLE_NU_AUTO_HG.NEXTVAL
    INTO :NEW.NU_AUTO_HGXY_VAR
    FROM DUAL;
END;
/