CREATE OR REPLACE TRIGGER HIMS.HIST_GRAXY_PERCENTIL_NU_AUTO_1 BEFORE INSERT ON HIMS.HIST_GRAXY_PERCENTIL FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_GRAXY_PERCENTIL_NU_AUTO_H.NEXTVAL
    INTO :NEW.NU_AUTO_HGXY_PERC
    FROM DUAL;
END;
/