CREATE OR REPLACE TRIGGER HIMS.HIST_SCOP_OBS_NU_NUME_HSO_TRG BEFORE INSERT ON HIMS.HIST_SCOP_OBS FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_SCOP_OBS_NU_NUME_HSO_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_HSO
    FROM DUAL;
END;
/