CREATE OR REPLACE TRIGGER HIMS.HIST_GRAXY_NU_AUTO_HGXY_TRG BEFORE INSERT ON HIMS.HIST_GRAXY FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_GRAXY_NU_AUTO_HGXY_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_HGXY
    FROM DUAL;
END;
/