CREATE OR REPLACE TRIGGER HIMS.HIST_ODONTO_LOG_CONS_CD_CONS_1 BEFORE INSERT ON HIMS.HIST_ODONTO_LOG_CONS FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_ODONTO_LOG_CONS_CD_CONSUL.NEXTVAL
    INTO :NEW.CD_CONSULTA
    FROM DUAL;
END;
/