CREATE OR REPLACE TRIGGER HIMS.HISTORIACLINICA_NU_NUME_HICL_T BEFORE INSERT ON HIMS.HISTORIACLINICA FOR EACH ROW
DECLARE

BEGIN
    SELECT HISTORIACLINICA_NU_NUME_HICL_S.NEXTVAL
    INTO :NEW.NU_NUME_HICL
    FROM DUAL;
END;
/