CREATE OR REPLACE TRIGGER HIMS.HIST_ODONTO_ICDAS_NU_ICDAS_TRG BEFORE INSERT ON HIMS.HIST_ODONTO_ICDAS FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_ODONTO_ICDAS_NU_ICDAS_SEQ.NEXTVAL
    INTO :NEW.NU_ICDAS
    FROM DUAL;
END;
/