CREATE OR REPLACE TRIGGER HIMS.HIST_GENO_UBICA_FAM_NU_NUME__1 BEFORE INSERT ON HIMS.HIST_GENO_UBICA_FAM FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_GENO_UBICA_FAM_NU_NUME_UB.NEXTVAL
    INTO :NEW.NU_NUME_UBICA
    FROM DUAL;
END;
/