CREATE OR REPLACE TRIGGER HIMS.HIST_INCA_NUM_CONSEC_HINC_TRG BEFORE INSERT ON HIMS.HIST_INCA FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_INCA_NUM_CONSEC_HINC_SEQ.NEXTVAL
    INTO :NEW.NUM_CONSEC_HINC
    FROM DUAL;
END;
/