CREATE OR REPLACE TRIGGER HIMS.HIST_APOD_NU_AUTO_HIAP_TRG BEFORE INSERT ON HIMS.HIST_APOD FOR EACH ROW
DECLARE

BEGIN
    SELECT HIST_APOD_NU_AUTO_HIAP_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_HIAP
    FROM DUAL;
END;
/