CREATE OR REPLACE TRIGGER HIMS.IMAGEN_CONV_NU_NUME_IMAGEN_TRG BEFORE INSERT ON HIMS.IMAGEN_CONV FOR EACH ROW
DECLARE

BEGIN
    SELECT IMAGEN_CONV_NU_NUME_IMAGEN_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_IMAGEN
    FROM DUAL;
END;
/