CREATE OR REPLACE TRIGGER HIMS.INCONSISTENCIA_BASE_NU_AUTO__1 BEFORE INSERT ON HIMS.INCONSISTENCIA_BASE FOR EACH ROW
DECLARE

BEGIN
    SELECT INCONSISTENCIA_BASE_NU_AUTO_IN.NEXTVAL
    INTO :NEW.NU_AUTO_INCO
    FROM DUAL;
END;
/