CREATE OR REPLACE TRIGGER HIMS.ITEM_TISS_NU_AUTO_ITTI_TRG BEFORE INSERT ON HIMS.ITEM_TISS FOR EACH ROW
DECLARE

BEGIN
    SELECT ITEM_TISS_NU_AUTO_ITTI_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_ITTI
    FROM DUAL;
END;
/