CREATE OR REPLACE TRIGGER HIMS.ITEMSRESULTADO_MOTRICIDAD_NU_1 BEFORE INSERT ON HIMS.ITEMSRESULTADO_MOTRICIDAD FOR EACH ROW
DECLARE

BEGIN
    SELECT ITEMSRESULTADO_MOTRICIDAD_NU_A.NEXTVAL
    INTO :NEW.NU_AUTO_IRMO
    FROM DUAL;
END;
/