CREATE OR REPLACE TRIGGER HIMS.ITEM_RESPUESTA_GLOSA3I_NU_AU_1 BEFORE INSERT ON HIMS.ITEM_RESPUESTA_GLOSA3I
FOR EACH ROW
DECLARE

BEGIN
    SELECT ITEM_RESPUESTA_GLOSA3i_NU_AUTO.NEXTVAL
    INTO :NEW.NU_AUTO_RIGL
    FROM DUAL;
END;
/