CREATE OR REPLACE TRIGGER HIMS.LABORATORIO_NU_NUME_LABO_TRG BEFORE INSERT ON HIMS.LABORATORIO FOR EACH ROW
DECLARE

BEGIN
    SELECT LABORATORIO_NU_NUME_LABO_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_LABO
    FROM DUAL;
END;
/