CREATE OR REPLACE TRIGGER HIMS.MENSAJES_MIHIMS_AUTO_MSG_MIH_1 BEFORE INSERT ON HIMS.MENSAJES_MIHIMS FOR EACH ROW
DECLARE

BEGIN
    SELECT MENSAJES_MIHIMS_AUTO_MSG_MIHIM.NEXTVAL
    INTO :NEW.AUTO_MSG_MIHIMS
    FROM DUAL;
END;
/