CREATE OR REPLACE TRIGGER HIMS.MOTIVOS_ARCHIVO_FISICO_NU_AU_1 BEFORE INSERT ON HIMS.MOTIVOS_ARCHIVO_FISICO FOR EACH ROW
DECLARE

BEGIN
    SELECT MOTIVOS_ARCHIVO_FISICO_NU_AUTO.NEXTVAL
    INTO :NEW.NU_AUTO_MOAR
    FROM DUAL;
END;
/