CREATE OR REPLACE TRIGGER HIMS.MULTA_NU_NUME_MULT_TRG BEFORE INSERT ON HIMS.MULTA FOR EACH ROW
DECLARE

BEGIN
    SELECT MULTA_NU_NUME_MULT_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_MULT
    FROM DUAL;
END;
/