CREATE OR REPLACE TRIGGER HIMS.NO_AFILIADO_EPS_COD_NO_EPS_TRG BEFORE INSERT ON HIMS.NO_AFILIADO_EPS FOR EACH ROW
DECLARE

BEGIN
    SELECT NO_AFILIADO_EPS_COD_NO_EPS_SEQ.NEXTVAL
    INTO :NEW.COD_NO_EPS
    FROM DUAL;
END;
/