CREATE OR REPLACE TRIGGER HIMS.PAC_ANTE_FAMI_NU_NUME_PAF_TRG BEFORE INSERT ON HIMS.PAC_ANTE_FAMI FOR EACH ROW
DECLARE

BEGIN
    SELECT PAC_ANTE_FAMI_NU_NUME_PAF_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_PAF
    FROM DUAL;
END;
/