CREATE OR REPLACE TRIGGER HIMS.PLAN_PAGOS_CD_CODI_PLP_TRG BEFORE INSERT ON HIMS.PLAN_PAGOS FOR EACH ROW
DECLARE

BEGIN
    SELECT PLAN_PAGOS_CD_CODI_PLP_SEQ.NEXTVAL
    INTO :NEW.CD_CODI_PLP
    FROM DUAL;
END;
/