CREATE OR REPLACE TRIGGER HIMS.PREPARADO_MEDICAMENTO_CD_PRE_1 BEFORE INSERT ON HIMS.PREPARADO_MEDICAMENTO FOR EACH ROW
DECLARE

BEGIN
    SELECT PREPARADO_MEDICAMENTO_CD_PREP_.NEXTVAL
    INTO :NEW.CD_PREP_MEDI
    FROM DUAL;
END;
/