CREATE OR REPLACE TRIGGER HIMS.PROGRAMACION_QX_NU_AUTO_PRQX_T BEFORE INSERT ON HIMS.PROGRAMACION_QX FOR EACH ROW
DECLARE

BEGIN
    SELECT PROGRAMACION_QX_NU_AUTO_PRQX_S.NEXTVAL
    INTO :NEW.NU_AUTO_PRQX
    FROM DUAL;
END;
/