CREATE OR REPLACE TRIGGER HIMS.PROGRAMACION_ELEMENTO_NU_NUM_1 BEFORE INSERT ON HIMS.PROGRAMACION_ELEMENTO
FOR EACH ROW
DECLARE

BEGIN
    SELECT programacion_elemento_nu_nume_.NEXTVAL
    INTO :NEW.nu_nume_prel
    FROM DUAL;
END;
/