CREATE OR REPLACE TRIGGER HIMS.PROP_EXTEND_CD_CODI_PREX_TRG BEFORE INSERT ON HIMS.PROP_EXTEND FOR EACH ROW
DECLARE

BEGIN
    SELECT PROP_EXTEND_CD_CODI_PREX_SEQ.NEXTVAL
    INTO :NEW.CD_CODI_PREX
    FROM DUAL;
END;
/