CREATE OR REPLACE TRIGGER HIMS.PROPIETARIO_COD_PROPIETARIO_TR BEFORE INSERT ON HIMS.PROPIETARIO FOR EACH ROW
DECLARE

BEGIN
    SELECT PROPIETARIO_COD_PROPIETARIO_SE.NEXTVAL
    INTO :NEW.COD_PROPIETARIO
    FROM DUAL;
END;
/