CREATE OR REPLACE TRIGGER HIMS.PRUEBA_VITALIDAD_ODO_NU_AUTO_1 BEFORE INSERT ON HIMS.PRUEBA_VITALIDAD_ODO FOR EACH ROW
DECLARE

BEGIN
    SELECT PRUEBA_VITALIDAD_ODO_NU_AUTO_P.NEXTVAL
    INTO :NEW.NU_AUTO_PRVI
    FROM DUAL;
END;
/