CREATE OR REPLACE TRIGGER HIMS.PYP_INFO_OBLIG_NU_AUTO_PYPIN_1 BEFORE INSERT ON HIMS.PYP_INFO_OBLIG FOR EACH ROW
DECLARE

BEGIN
    SELECT PYP_INFO_OBLIG_NU_AUTO_PYPINFO.NEXTVAL
    INTO :NEW.NU_AUTO_PYPINFOBLI
    FROM DUAL;
END;
/