CREATE OR REPLACE TRIGGER HIMS.PYP_DETECT_PAC_HIST_NU_AUTO__1 BEFORE INSERT ON HIMS.PYP_DETECT_PAC_HIST FOR EACH ROW
DECLARE

BEGIN
    SELECT PYP_DETECT_PAC_HIST_NU_AUTO_PY.NEXTVAL
    INTO :NEW.NU_AUTO_PYPPAC
    FROM DUAL;
END;
/