CREATE OR REPLACE TRIGGER HIMS.PYP_ACTIV_INFO_OBLIG_NU_AUTO_1 BEFORE INSERT ON HIMS.PYP_ACTIV_INFO_OBLIG FOR EACH ROW
DECLARE

BEGIN
    SELECT PYP_ACTIV_INFO_OBLIG_NU_AUTO_P.NEXTVAL
    INTO :NEW.NU_AUTO_PYPACTPARAM
    FROM DUAL;
END;
/