CREATE OR REPLACE TRIGGER HIMS.QYR_TIPO_SOLICITUD_ID_TP_SOL_1 BEFORE INSERT ON HIMS.QYR_TIPO_SOLICITUD FOR EACH ROW
DECLARE

BEGIN
    SELECT QYR_TIPO_SOLICITUD_ID_TP_SOLIC.NEXTVAL
    INTO :NEW.ID_TP_SOLICITUD
    FROM DUAL;
END;
/