CREATE OR REPLACE TRIGGER HIMS.R_DEAR_LTAR_NU_AUTO_RDAL_TRG BEFORE INSERT ON HIMS.R_DEAR_LTAR FOR EACH ROW
DECLARE

BEGIN
    SELECT R_DEAR_LTAR_NU_AUTO_RDAL_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_RDAL
    FROM DUAL;
END;