CREATE OR REPLACE TRIGGER HIMS.R_ESPE_PLHI_R_ESPE_NU_TRG BEFORE INSERT ON HIMS.R_ESPE_PLHI FOR EACH ROW
DECLARE

BEGIN
    SELECT R_ESPE_PLHI_R_ESPE_NU_SEQ.NEXTVAL
    INTO :NEW.R_ESPE_NU
    FROM DUAL;
END;