CREATE OR REPLACE TRIGGER HIMS.R_GRID_PLHI_R_GRID_HICLI_TRG BEFORE INSERT ON HIMS.R_GRID_PLHI FOR EACH ROW
DECLARE

BEGIN
    SELECT R_GRID_PLHI_R_GRID_HICLI_SEQ.NEXTVAL
    INTO :NEW.R_GRID_HICLI
    FROM DUAL;
END;