CREATE OR REPLACE TRIGGER HIMS.R_HIST_IMAGEN_CONV_NU_NUME_C_1 BEFORE INSERT ON HIMS.R_HIST_IMAGEN_CONV FOR EACH ROW
DECLARE

BEGIN
    SELECT R_HIST_IMAGEN_CONV_NU_NUME_CON.NEXTVAL
    INTO :NEW.NU_NUME_CONVEN
    FROM DUAL;
END;
/