CREATE OR REPLACE TRIGGER HIMS.R_KARD_LTAR_NU_AUTO_RKART_TRG BEFORE INSERT ON HIMS.R_KARD_LTAR FOR EACH ROW
DECLARE

BEGIN
      SELECT R_KARD_LTAR_NU_AUTO_RKART_SEQ.NEXTVAL
      INTO :NEW.NU_AUTO_RKART
      FROM DUAL;
END;