CREATE OR REPLACE TRIGGER HIMS.R_LUAT_DEPE_NU_AUTO_RLD_TRG BEFORE INSERT ON HIMS.R_LUAT_DEPE FOR EACH ROW
DECLARE

BEGIN
    SELECT R_LUAT_DEPE_NU_AUTO_RLD_SEQ.NEXTVAL 
    INTO :NEW.NU_AUTO_RLD
    FROM DUAL;
END;