CREATE OR REPLACE TRIGGER HIMS.R_PLANTILLA_HIST_NU_PLANTLLA_1 BEFORE INSERT ON HIMS.R_PLANTILLA_HIST FOR EACH ROW
DECLARE

BEGIN
    SELECT R_PLANTILLA_HIST_NU_PLANTLLA_R.NEXTVAL
    INTO :NEW.NU_PLANTLLA_R
    FROM DUAL;
END;