CREATE OR REPLACE TRIGGER HIMS.R_REGIS_ADSCR_SERV_CD_COD_RA_1 BEFORE INSERT ON HIMS.R_REGIS_ADSCR_SERV FOR EACH ROW
DECLARE

BEGIN
    SELECT R_REGIS_ADSCR_SERV_CD_COD_RAS_.NEXTVAL
    INTO :NEW.CD_COD_RAS
    FROM DUAL;
END;