CREATE OR REPLACE TRIGGER HIMS.R_TUR_ESC_NU_AUTO_RTE_TRG BEFORE INSERT ON HIMS.R_TUR_ESC FOR EACH ROW
DECLARE

BEGIN
    SELECT R_TUR_ESC_NU_AUTO_RTE_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_RTE
    FROM DUAL;
END;