CREATE OR REPLACE TRIGGER HIMS.RADICARCHIVO_NU_CONSE_ARCH_TRG BEFORE INSERT ON HIMS.RADICARCHIVO FOR EACH ROW
DECLARE

BEGIN
    SELECT RADICARCHIVO_NU_CONSE_ARCH_SEQ.NEXTVAL
    INTO :NEW.NU_CONSE_ARCH
    FROM DUAL;
END;