CREATE OR REPLACE TRIGGER HIMS.RADICACION_NU_CONSE_RADI_TRG BEFORE INSERT ON HIMS.RADICACION FOR EACH ROW
DECLARE

BEGIN
		SELECT RADICACION_NU_CONSE_RADI_SEQ.NEXTVAL
		INTO :NEW.NU_CONSE_RADI
		FROM DUAL;
END;
/