CREATE OR REPLACE TRIGGER HIMS.RADICAFACTURA_RIPS_NU_CONSE__1 BEFORE INSERT ON HIMS.RADICAFACTURA_RIPS FOR EACH ROW
DECLARE

BEGIN
    SELECT RADICAFACTURA_RIPS_NU_CONSE_RA.NEXTVAL
    INTO :NEW.NU_CONSE_RAFA
    FROM DUAL;
END;
/