CREATE OR REPLACE TRIGGER HIMS.REPORTESAMA_HIST_CD_CODI_REP_1 BEFORE INSERT ON HIMS.REPORTESAMA_HIST FOR EACH ROW
DECLARE

BEGIN
    SELECT REPORTESAMA_HIST_CD_CODI_REPO_.NEXTVAL
    INTO :NEW.CD_CODI_REPO
    FROM DUAL;
END;