CREATE OR REPLACE TRIGGER HIMS.REQUISICION_MED_CD_CODI_REQU_1 BEFORE INSERT ON HIMS.REQUISICION_MED FOR EACH ROW
DECLARE

BEGIN
    SELECT REQUISICION_MED_CD_CODI_REQU_R.NEXTVAL
    INTO :NEW.CD_CODI_REQU_RMED
    FROM DUAL;
END;