CREATE OR REPLACE TRIGGER HIMS.REQUISITOS_ID_IDEN_REQ_TRG BEFORE INSERT ON HIMS.REQUISITOS FOR EACH ROW
DECLARE

BEGIN
    SELECT REQUISITOS_ID_IDEN_REQ_SEQ.NEXTVAL
    INTO :NEW.ID_IDEN_REQ
    FROM DUAL;
END;