CREATE OR REPLACE TRIGGER HIMS.RESERVA_LAB_NU_AUTO_RELAB_TRG BEFORE INSERT ON HIMS.RESERVA_LAB FOR EACH ROW
DECLARE

BEGIN
    SELECT RESERVA_LAB_NU_AUTO_RELAB_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_RELAB
    FROM DUAL;
END;