CREATE OR REPLACE TRIGGER HIMS.RESERV_CIT_PREPAR_COLDEP_NU__1 BEFORE INSERT ON HIMS.RESERV_CIT_PREPAR_COLDEP FOR EACH ROW
DECLARE

BEGIN
    SELECT RESERV_CIT_PREPAR_COLDEP_NU_NU.NEXTVAL
    INTO :NEW.NU_NUME_RCPC
    FROM DUAL;
END;