CREATE OR REPLACE TRIGGER HIMS.RESERVA_LAB_AUD_ELIM_NU_AUTO_1 BEFORE INSERT ON HIMS.RESERVA_LAB_AUD_ELIM FOR EACH ROW
DECLARE

BEGIN
    SELECT RESERVA_LAB_AUD_ELIM_NU_AUTO_R.NEXTVAL
    INTO :NEW.NU_AUTO_RELABAE
    FROM DUAL;
END;