CREATE OR REPLACE TRIGGER HIMS.SEGUIMIENTO_EVENTO_ID_SEGUIM_1 BEFORE INSERT ON HIMS.SEGUIMIENTO_EVENTO FOR EACH ROW
DECLARE

BEGIN
    SELECT SEGUIMIENTO_EVENTO_ID_SEGUIMIE.NEXTVAL
    INTO :NEW.ID_SEGUIMIENTO
    FROM DUAL;
END;