CREATE OR REPLACE TRIGGER HIMS.SERVICIOS_OBSERVA_PREDE_CD_C_1 BEFORE INSERT ON HIMS.SERVICIOS_OBSERVA_PREDE FOR EACH ROW
DECLARE

BEGIN
    SELECT SERVICIOS_OBSERVA_PREDE_CD_COD.NEXTVAL
    INTO :NEW.CD_CODI_OBSER
    FROM DUAL;
END;