CREATE OR REPLACE TRIGGER HIMS.SERVICIOS_PREPARACIONES_CITA_1 BEFORE INSERT ON HIMS.SERVICIOS_PREPARACIONES_CITA FOR EACH ROW
DECLARE

BEGIN
    SELECT SERVICIOS_PREPARACIONES_CITA_C.NEXTVAL
    INTO :NEW.CD_PREP_SER_CIT
    FROM DUAL;
END;