CREATE OR REPLACE TRIGGER HIMS.SERVICIOS_PREPARACION_CD_COD_1 BEFORE INSERT ON HIMS.SERVICIOS_PREPARACION FOR EACH ROW
DECLARE

BEGIN
    SELECT SERVICIOS_PREPARACION_CD_CODI_.NEXTVAL
    INTO :NEW.CD_CODI_PREP_SER
    FROM DUAL;
END;
/