CREATE OR REPLACE TRIGGER HIMS.SOLICITUD_SERVICIOS_NU_AUTO__1 BEFORE INSERT ON HIMS.SOLICITUD_SERVICIOS FOR EACH ROW
DECLARE

BEGIN
    SELECT SOLICITUD_SERVICIOS_NU_AUTO_SO.NEXTVAL
    INTO :NEW.NU_AUTO_SOSE
    FROM DUAL;
END;