CREATE OR REPLACE TRIGGER HIMS.TIPO_EVENTO_ADVERSO_CD_TIPO__1 BEFORE INSERT ON HIMS.TIPO_EVENTO_ADVERSO FOR EACH ROW
DECLARE

BEGIN
    SELECT TIPO_EVENTO_ADVERSO_CD_TIPO_EV.NEXTVAL
    INTO :NEW.CD_TIPO_EVENTO
    FROM DUAL;
END;
/
