CREATE OR REPLACE TRIGGER HIMS.TIPO_GESTION_NU_NUME_TIGE_TRG BEFORE INSERT ON HIMS.TIPO_GESTION FOR EACH ROW
DECLARE

BEGIN
    SELECT TIPO_GESTION_NU_NUME_TIGE_SEQ.NEXTVAL
    INTO :NEW.NU_NUME_TIGE
    FROM DUAL;
END;