CREATE OR REPLACE TRIGGER HIMS.TIPORH_NU_AUTO_TIRH_TRG BEFORE INSERT ON HIMS.TIPORH FOR EACH ROW
DECLARE

BEGIN
    SELECT TIPORH_NU_AUTO_TIRH_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_TIRH
    FROM DUAL;
END;