CREATE OR REPLACE TRIGGER HIMS.URGENCIAS_RIPS_NU_CONSE_URGE_T BEFORE INSERT ON HIMS.URGENCIAS_RIPS FOR EACH ROW
DECLARE

BEGIN
    SELECT URGENCIAS_RIPS_NU_CONSE_URGE_S.NEXTVAL
    INTO :NEW.NU_CONSE_URGE
    FROM DUAL;
END;