CREATE OR REPLACE TRIGGER HIMS.USUARIO_AUDIT_AUTO_USR_AUDIT_T BEFORE INSERT ON HIMS.USUARIO_AUDIT FOR EACH ROW
DECLARE

BEGIN
    SELECT USUARIO_AUDIT_AUTO_USR_AUDIT_S.NEXTVAL
    INTO :NEW.AUTO_USR_AUDIT
    FROM DUAL;
END;