CREATE OR REPLACE TRIGGER HIMS.VACUNACION_NU_AUTO_VACU_TRG BEFORE INSERT ON HIMS.VACUNACION FOR EACH ROW
DECLARE

BEGIN
    SELECT VACUNACION_NU_AUTO_VACU_SEQ.NEXTVAL
    INTO :NEW.NU_AUTO_VACU
    FROM DUAL;
END;