CREATE OR REPLACE TRIGGER HIMS.VALORACION_AUDITORIA_HC_NU_A_1 BEFORE INSERT ON HIMS.VALORACION_AUDITORIA_HC FOR EACH ROW
DECLARE

BEGIN
    SELECT VALORACION_AUDITORIA_HC_NU_AUT.NEXTVAL
    INTO :NEW.NU_AUTO_VAAU_VAHC
    FROM DUAL;
END;