CREATE OR REPLACE PROCEDURE H3i_SP_CONSULTA_PERF_AUDI_CTRL
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_CONTROL_VALO_CONT OUT CONTROL.VL_VALO_CONT%TYPE
)
AS
BEGIN

	SELECT CONTROL.VL_VALO_CONT
	INTO V_CONTROL_VALO_CONT
	FROM CONTROL
	WHERE  CONTROL.CD_CONC_CONT = 'PERFIL_AUDITOR';

EXCEPTION
  WHEN OTHERS 
      THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CONSULTA_PERF_AUDI_CTRL;
