CREATE OR REPLACE PROCEDURE H3i_SP_CREA_PERFIL_CORREO
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_TX_HOST_PECO IN VARCHAR2,
  v_ID_SSLHABIL_PECO IN NUMBER,
  v_TX_USUARIO_PECO IN VARCHAR2,
  v_TX_CONTRASENA_PECO IN VARCHAR2,
  v_TX_CORREOORIGEN_PECO IN VARCHAR2,
  v_NU_PUERTO_PECO IN NUMBER,
  v_TX_NOMBRE_PECO IN VARCHAR2,
  v_TX_DESTINO IN VARCHAR2
)
AS

BEGIN

   INSERT INTO PERFILES_CORREO
     ( TX_HOST_PECO, ID_SSLHABIL_PECO, TX_USUARIO_PECO, TX_CONTRASENA_PECO, TX_CORREOORIGEN_PECO, NU_PUERTO_PECO, TX_NOMBRE_PECO, TX_DESTINO )
     VALUES ( v_TX_HOST_PECO, v_ID_SSLHABIL_PECO, v_TX_USUARIO_PECO, v_TX_CONTRASENA_PECO, v_TX_CORREOORIGEN_PECO, v_NU_PUERTO_PECO, v_TX_NOMBRE_PECO, v_TX_DESTINO );

EXCEPTION
  WHEN OTHERS 
      THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_CREA_PERFIL_CORREO;