CREATE OR REPLACE PROCEDURE H3i_SP_USER_AUDITA 
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
	V_TABLENAME IN VARCHAR2 DEFAULT NULL,
	CV_1 OUT SYS_REFCURSOR
)
AS

BEGIN
   	OPEN  CV_1 FOR
    	SELECT USUARIO 
    	FROM AUDIT3I
        INNER JOIN CONEXIONES 
        ON NU_NUME_CONE = NOCONEXION
       	WHERE  NOCONEXION <> 0
        AND TABLENAME = NVL(V_TABLENAME, TABLENAME)
        ORDER BY 1;

EXCEPTION 
	WHEN OTHERS 
		THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_USER_AUDITA;