CREATE OR REPLACE PROCEDURE H3i_SP_BLOQUEAUSUARIO /*PROCEDIMIENTO ALMACENADO QUE PERMITE BLOQUEAR UNA CUENTA DE USUARIO*/
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_LOGIN IN VARCHAR2
)
AS

BEGIN

   UPDATE USUARIOS
      SET NU_ESTADO_USUA = 0
    WHERE  ID_IDEN_USUA = v_LOGIN;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END;