CREATE OR REPLACE PROCEDURE       H3i_SP_ACTUALIZA_PARAMAUDITORI
 -- =============================================      
 -- Author:  FELIPE SATIZABAL
 -- =============================================
(
  v_DE_NOMTABLA_PAAU IN VARCHAR2,
  v_DE_NOMCOL_PAAU IN VARCHAR2,
  v_TIPO IN NUMBER,--1:Inserta, 2:Actualiza, 3:Elimina
  v_VALOR IN NUMBER
)
AS
   v_EXISTE NUMBER(10,0);

BEGIN

   SELECT COUNT(1)  

     INTO v_EXISTE
     FROM PARAMETRIZACION_AUDITORIA 
    WHERE  DE_NOMTABLA_PAAU = v_DE_NOMTABLA_PAAU
             AND DE_NOMCOL_PAAU = v_DE_NOMCOL_PAAU;
   IF ( v_EXISTE = 0 ) THEN
    
   BEGIN
      INSERT INTO PARAMETRIZACION_AUDITORIA
        ( DE_NOMTABLA_PAAU, DE_NOMCOL_PAAU, NU_INSERT_PAAU, NU_ACTUA_PAAU, NU_ELIMI_PAAU, NU_ESTA_PAAU )
        VALUES ( v_DE_NOMTABLA_PAAU, v_DE_NOMCOL_PAAU, 0, 0, 0, 1 );
   
   END;
   END IF;
   IF ( v_TIPO = 1 ) THEN
    
   BEGIN
      UPDATE PARAMETRIZACION_AUDITORIA
         SET NU_INSERT_PAAU = v_VALOR
       WHERE  DE_NOMTABLA_PAAU = v_DE_NOMTABLA_PAAU
        AND DE_NOMCOL_PAAU = v_DE_NOMCOL_PAAU;
   
   END;
   END IF;
   IF ( v_TIPO = 2 ) THEN
    
   BEGIN
      UPDATE PARAMETRIZACION_AUDITORIA
         SET NU_ACTUA_PAAU = v_VALOR
       WHERE  DE_NOMTABLA_PAAU = v_DE_NOMTABLA_PAAU
        AND DE_NOMCOL_PAAU = v_DE_NOMCOL_PAAU;
   
   END;
   END IF;
   IF ( v_TIPO = 3 ) THEN
    
   BEGIN
      UPDATE PARAMETRIZACION_AUDITORIA
         SET NU_ELIMI_PAAU = v_VALOR
       WHERE  DE_NOMTABLA_PAAU = v_DE_NOMTABLA_PAAU
        AND DE_NOMCOL_PAAU = v_DE_NOMCOL_PAAU;
   
   END;
   END IF;

EXCEPTION 
    WHEN OTHERS 
        THEN RAISE_APPLICATION_ERROR(SQLCODE,SQLERRM);
END H3i_SP_ACTUALIZA_PARAMAUDITORI;